# coding: utf-8

"""
    test-timeout-bug API

    A simple API based for testing test-timeout-bug.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from test_timeout_bug.paths.simple_endpoint.get import Fetch
from test_timeout_bug.apis.tags.test_api_raw import TestApiRaw


class TestApi(
    Fetch,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TestApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TestApiRaw(api_client)
