openapi: 3.0.3
info:
  title: java-merge-anyof-object-schemas API
  description: A simple API based for testing java-merge-anyof-object-schemas.
  version: 1.0.0
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Live API server
    url: https://java-merge-anyof-object-schemas.konfigthis.com
tags:
  - name: Test
paths:
  /merge-different:
    get:
      tags:
        - Test
      summary: merge different
      operationId: Test_mergeDifferent
      description: merge different
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeDifferent'
  /merge-same:
    get:
      tags:
        - Test
      summary: merge same
      operationId: Test_mergeSame
      description: merge same
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeSame'
  /simple-endpoint:
    get:
      tags:
        - Test
      summary: Fetches a JSON value based on input parameter
      operationId: Test_fetch
      description: Provide an input parameter to receive a JSON value with properties.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestFetchResponse'
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    TestFetchResponse:
      anyOf:
        - $ref: '#/components/schemas/A'
        - $ref: '#/components/schemas/B'
        - $ref: '#/components/schemas/C'
    MergeDifferent:
      anyOf:
        - $ref: '#/components/schemas/A'
        - $ref: '#/components/schemas/AA'
    MergeSame:
      anyOf:
        - $ref: '#/components/schemas/B'
        - $ref: '#/components/schemas/BB'
    A:
      type: object
      properties:
        a:
          type: string
    AA:
      type: object
      properties:
        a:
          type: number
    B:
      type: object
      properties:
        b:
          type: string
      required:
        - b
    BB:
      type: object
      properties:
        b:
          type: string
    C:
      type: object
      properties:
        c:
          type: string
security:
  - ApiKey: []
