name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: konfig-dev/automation/.github/workflows/release.yaml@main
    secrets:
      TEST_ENV: ${{ secrets.TEST_ENV }}
      KONFIG_API_KEY: ${{ secrets.KONFIG_API_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PYPI_TOKEN_1: ${{ secrets.PYPI_TOKEN_1 }}
      SUBMODULE_DEPLOY_KEY_PYTHON: ${{ secrets.SUBMODULE_DEPLOY_KEY_PYTHON }}
      SUBMODULE_DEPLOY_KEY_TYPESCRIPT: ${{ secrets.SUBMODULE_DEPLOY_KEY_TYPESCRIPT }}