/*
 * java-merge-anyof-object-schemas API
 * A simple API based for testing java-merge-anyof-object-schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.javamergeanyofobjectschemas.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AOrAA
 */
public class AOrAATest {
    private final AOrAA model = new AOrAA();

    /**
     * Model tests for AOrAA
     */
    @Test
    public void testAOrAA() {
        // TODO: test AOrAA
    }

    /**
     * Test the property 'a'
     */
    @Test
    public void aTest() {
        // TODO: test a
    }

}
