/*
 * java-merge-anyof-object-schemas API
 * A simple API based for testing java-merge-anyof-object-schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.javamergeanyofobjectschemas.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BOrBB
 */
public class BOrBBTest {
    private final BOrBB model = new BOrBB();

    /**
     * Model tests for BOrBB
     */
    @Test
    public void testBOrBB() {
        // TODO: test BOrBB
    }

    /**
     * Test the property 'b'
     */
    @Test
    public void bTest() {
        // TODO: test b
    }

}
