# coding: utf-8

"""
    Python Pydantic Responses API

    A simple API based on python pydantic responses.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from python_pydantic.paths.free_form_object.get import FreeFormObject
from python_pydantic.apis.tags.test_response_api_raw import TestResponseApiRaw


class TestResponseApi(
    FreeFormObject,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TestResponseApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TestResponseApiRaw(api_client)
