name: SafehealthPush
targets:
  SafehealthPush:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [SafehealthPush]
    info:
      path: ./Info.plist
      version: 0.1.5
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable