openapi: 3.0.3
info:
  title: typescript-oauth-token API
  description: A simple API based for testing typescript-oauth-token.
  version: 1.0.0
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Live API server
    url: https://typescript-oauth-token.konfigthis.com
tags:
  - name: Test
paths:
  /test:
    get:
      tags:
        - Test
      summary: Fetches a JSON value based on input parameter
      operationId: Test_fetch
      security:
        - oauth: [ "api.v3" ]
      description: Provide an input parameter to receive a JSON value with properties.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestFetchResponse'
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "http://127.0.0.1:4048/token"
          scopes:
            api.v3: ""
  schemas:
    TestFetchResponse:
      type: object