/*
 * csharp-body-with-object-field API
 *
 * A simple API based for testing csharp-body-with-object-field.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://konfigthis.com
 */


using RestSharp;

namespace CsharpBodyWithObjectField.Net.Client
{
    public partial class ApiClient
    {
        partial void InterceptRequest(RestRequest request) { }
    }
}
