/*
 * csharp-body-with-object-field API
 *
 * A simple API based for testing csharp-body-with-object-field.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://konfigthis.com
 */


using CsharpBodyWithObjectField.Net.Api;

namespace CsharpBodyWithObjectField.Net.Client
{
    /// <summary>
    ///  SDK client
    /// </summary>
    public class CsharpBodyWithObjectFieldClient
    {
        /// <summary>
        /// API instance
        /// </summary>
        public TestApi Test { get; private set; }

        /// <summary>
        /// Configuration instance
        /// </summary>
        public readonly Configuration Configuration;

        /// <summary>
        /// Constructor
        /// </summary>
        public CsharpBodyWithObjectFieldClient()
        {
            Configuration = new Configuration();
            init();
        }

        private void init()
        {
            Test = new TestApi(Configuration);
        }

        /// <summary>
        /// Setter for base path
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetBasePath(string basePath)
        {
            Configuration.BasePath = basePath;
            init();
            return this;
        }

        /// <summary>
        /// Setter for verify SSL configuration. Set to false when you want to disable SSL verification.
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetVerifySsl(bool verifySsl)
        {
            Configuration.VerifySsl = verifySsl;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Username
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetUsername(string username)
        {
            Configuration.Username = username;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Password
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetPassword(string password)
        {
            Configuration.Password = password;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Access Token
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetAccessToken(string accessToken)
        {
            Configuration.AccessToken = accessToken;
            init();
            return this;
        }

        /// <summary>
        /// Setter for API Key
        /// </summary>
        public CsharpBodyWithObjectFieldClient SetApiKey(string apiKey)
        {
            Configuration.ApiKey["X-API-KEY"] = apiKey;
            init();
            return this;
        }
    }
}
