/*
 * csharp-body-with-object-field API
 *
 * A simple API based for testing csharp-body-with-object-field.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://konfigthis.com
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CsharpBodyWithObjectField.Net.Client;
using CsharpBodyWithObjectField.Net.Api;
using CsharpBodyWithObjectField.Net.Model;

namespace CsharpBodyWithObjectField.Net.Test.Api
{
    /// <summary>
    ///  Class for testing TestApi
    /// </summary>
    public class TestApiTests : IDisposable
    {
        private CsharpBodyWithObjectFieldClient client;

        public TestApiTests()
        {
            client = new CsharpBodyWithObjectFieldClient();
            client.SetBasePath("http://127.0.0.1:4006");
            // Configure API key authorization: ApiKeyAuth
            client.SetApiKey("YOUR_API_KEY");

        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test Fetch
        /// </summary>
        [Fact]
        public void FetchTest()
        {
            
            try
            {
                // Fetches a JSON value based on input parameter
                Object result = client.Test.Fetch();
                Console.WriteLine(result);
            }
            catch (ApiException e)
            {
                Console.WriteLine("Exception when calling TestApi.Fetch: " + e.Message);
                Console.WriteLine("Status Code: "+ e.ErrorCode);
                Console.WriteLine(e.StackTrace);
            }
            catch (ClientException e)
            {
                Console.WriteLine(e.Response.StatusCode);
                Console.WriteLine(e.Response.RawContent);
                Console.WriteLine(e.InnerException);
            }
        }
    }
}
