processed:
  securitySchemes:
    CookieAuth:
      type: apiKey
      name: VisierASIDToken
      in: cookie
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: header
    BearerAuth:
      type: http
      scheme: bearer
    OAuth2Auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /v1/auth/oauth2/authorize
          tokenUrl: /v1/auth/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
        password:
          tokenUrl: /v1/auth/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
  apiBaseUrl: https://{vanity-name}.api.visier.io
  apiVersion: 22222222.99201.1256
  apiDescription: Visier APIs for managing objects in studio experience
  apiTitle: Visier Object Configuration APIs
  endpoints: 6
  sdkMethods: 6
  schemas: 16
  parameters: 6
  originalCustomRequest:
    type: GET
    url: >-
      https://raw.githubusercontent.com/visier/openapi-clients/main/res/object-configuration-apis.yaml
    servers:
      - url: https://{vanity-name}.api.visier.io
        variables:
          vanity-name:
            default: vanity
  customRequestSpecFilename: visier.com_ObjectConfiguration.yaml
  difficultyScore: 15.5
