publishJson:
  company: Brex
  serviceName: Budgets
  sdkName: brex-budgets-{language}-sdk
  clientName: BrexBudgets
  metaDescription: >-
    Brex is the AI-powered spend platform. We transform finance teams from
    reactive no-sayers to proactive growth drivers. With Brex, companies spend
    with confidence by empowering employees to make smarter financial decisions
    from anywhere. Brex provides corporate cards, business accounts, and global
    payments, plus intuitive software for travel and expenses, that make it easy
    to plan and track all company spend in one place, in real time. Over 20,000
    companies from startups to global enterprises — including DoorDash,
    Flexport, and Compass — use Brex to proactively control spend, reduce costs,
    and increase efficiency on a global scale.
  apiStatusUrls: inherit
  homepage: brex.com
  developerDocumentation: developer.brex.com/openapi/budgets_api/
  categories:
    - finance
    - payments
    - online_payments
    - fintech
    - automation
    - global_payments
    - travel_expenses
    - banking
    - business_accounts
    - corporate_cards
rawSpecString: |
  openapi: 3.0.1
  info:
    title: Budgets API
    description: |

      The budgets API lets you manage your Brex budgets.
    contact:
      name: Admin
      url: https://brex.com
      email: developer-access@brex.com
    version: '1.0'
  servers:
    - url: https://platform.brexapis.com
      description: Production
    - url: https://platform.staging.brexapps.com
      description: >-
        Staging (Note: This is not a sandbox. It will not work with customer
        tokens.)
  security:
    - OAuth2: []
  tags:
    - name: Budgets
      description: Endpoints for budgets data.
    - name: Budget Programs
      description: Endpoints for budgets programs data.
  paths:
    /v1/budget_programs:
      get:
        tags:
          - Budget Programs
        summary: |

          List Budget Programs
        description: |

          Lists Budget Programs belonging to this account
        operationId: listBudgetPrograms
        security:
          - OAuth2:
              - budgets.readonly
              - budgets
      post:
        tags:
          - Budget Programs
        summary: |

          Create Budget Program
        description: >

          Creates a Budget Program.

          If your account does not have access to budget program features, a 403
          response status will be returned.

          If this is the case and you want to gain access to this endpoint, please
          contact Brex support.
        operationId: createBudgetProgram
        security:
          - OAuth2:
              - budgets
    /v1/budget_programs/{id}:
      get:
        tags:
          - Budget Programs
        summary: |

          Get Budget Program
        description: |

          Retrieves a Budget Program by ID
        operationId: getBudgetProgramById
        security:
          - OAuth2:
              - budgets.readonly
              - budgets
      put:
        tags:
          - Budget Programs
        summary: |

          Update Budget Program
        description: >

          Updates a Budget Program.

          This endpoint requires budget management. If your account does not have
          access to budget management features, a 403 response status will be
          returned. 

          If this is the case and you want to gain access to this endpoint, please
          contact Brex support.
        operationId: updateBudgetProgram
        security:
          - OAuth2:
              - budgets
      delete:
        tags:
          - Budget Programs
        summary: |

          Delete Budget Program
        description: >

          Delete a Budget Program by ID.

          This endpoint requires budget management. If your account does not have
          access to budget management features, a 403 response status will be
          returned. 

          If this is the case and you want to gain access to this endpoint, please
          contact Brex support.
        operationId: deleteBudgetProgram
        security:
          - OAuth2:
              - budgets
    /v1/budgets:
      get:
        tags:
          - Budgets
        summary: |

          List Budgets
        description: |

          Lists Budgets belonging to this account
        operationId: listBudgets
        security:
          - OAuth2:
              - budgets.readonly
              - budgets
      post:
        tags:
          - Budgets
        summary: |

          Create Budget
        description: >

          Creates a Budget.

          This endpoint requires budget management. If your account does not have
          access to budget management features, a 403 response status will be
          returned. 

          If this is the case and you want to gain access to this endpoint, please
          contact Brex support.
        operationId: createBudget
        security:
          - OAuth2:
              - budgets
    /v1/budgets/{id}:
      get:
        tags:
          - Budgets
        summary: |

          Get Budget
        description: |

          Retrieves a Budget by ID
        operationId: getBudgetById
        security:
          - OAuth2:
              - budgets.readonly
              - budgets
      put:
        tags:
          - Budgets
        summary: |

          Update Budget
        description: >

          Updates a Budget.

          This endpoint requires budget management. If your account does not have
          access to budget management features, a 403 response status will be
          returned. 

          If this is the case and you want to gain access to this endpoint, please
          contact Brex support.
        operationId: updateBudget
        security:
          - OAuth2:
              - budgets
    /v1/budgets/{id}/archive:
      post:
        tags:
          - Budgets
        summary: |

          Archive a budget
        description: >

          Archives a budget, making it unusable for future expenses and removing
          it from the UI
        operationId: archiveBudget
        security:
          - OAuth2:
              - budgets
  components:
    securitySchemes:
      OAuth2:
        type: oauth2
        description: OAuth2 security scheme
        flows:
          authorizationCode:
            authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
            tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
            scopes:
              openid: openid
              offline_access: offline access
              budgets: View and manage budgets data
              budgets.readonly: View budgets data
  x-explorer-enabled: false
konfigCliVersion: 1.38.37
