publishJson:
  company: ChatKitty
  serviceName: false
  sdkName: chat-kitty-{language}-sdk
  clientName: ChatKitty
  metaDescription: >-
    ChatKitty gives you the tools to build real-time chat for web and mobile
    apps, complete with advanced features like moderation, offline messaging and
    analytics.
  apiStatusUrls: inherit
  homepage: chatkitty.com
  developerDocumentation: chatkitty.com/docs/api/reference
  categories:
    - communications_software
    - messaging
    - chat_platforms
    - chat_sdks
rawSpecString: |
  openapi: 3.0.1
  info:
    title: ChatKitty Platform API
    description: |-
      OpenAPI specification (OAS) for the ChatKitty Platform API.
      See the Interactive Docs to try ChatKitty API methods without writing code,
      and get the complete schema of resources exposed by the API.
    termsOfService: https://chatkitty.com/terms-of-service
    contact:
      name: Support
      url: mailto:support@chatkitty.com
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
    version: 2.58.3
  servers:
    - url: https://api.chatkitty.com
  tags:
    - name: analytics
      description: Export analytics data from your ChatKitty application
      x-displayName: Analytics
    - name: application
      description: Configure and manage your ChatKitty application
      x-displayName: Application
    - name: channels
      description: Operations to create, retrieve, update and delete channels
      x-displayName: Channels
    - name: chat-sessions
      description: Chat session operations
      x-displayName: Chat Sessions
    - name: function-versions
      description: Chat function version operations
      x-displayName: Chat Function Versions
    - name: functions
      description: Chat function operations
      x-displayName: Chat Functions
    - name: imports
      description: Import user, channel, message data into your ChatKitty application
      x-displayName: Imports
    - name: jobs
      description: >-
        Retrieve information about long running scheduled jobs like imports and
        exports
      x-displayName: Jobs
    - name: messages
      description: Operations to retrieve, update and delete messages
      x-displayName: Messages
    - name: runtime
      description: Chat runtime operations
      x-displayName: Chat Runtime
    - name: threads
      description: Message thread operations
      x-displayName: Threads
    - name: user-sessions
      description: User session operations
      x-displayName: User Sessions
    - name: users
      description: User operations
      x-displayName: Users
  paths:
    /v1/analytics/messages:
      post:
        tags:
          - analytics
        summary: Export message analytics
        description: Batch export message analytics data
        operationId: export-message-analytics
        security:
          - application_authorization:
              - read:message
    /v1/analytics/users:
      post:
        tags:
          - analytics
        summary: Export user analytics
        description: Batch export user analytics data
        operationId: export-user-analytics
        security:
          - application_authorization:
              - read:user
    /v1/application:
      get:
        tags:
          - application
        summary: Retrieve the authenticated application
        description: >-
          Returns the ChatKitty application associated with the authentication
          credentials used.


          You must use an **OAuth V2 Bearer token** to access this endpoint.
        operationId: retrieve-authenticated-application
        security:
          - application_authorization:
              - read:application
    /v1/application/settings:
      get:
        tags:
          - application
        summary: Retrieve the authenticated application settings
        description: Returns the current settings configuring this application
        operationId: retrieve-authenticated-application-settings
        security:
          - application_authorization:
              - read:application
      put:
        tags:
          - application
        summary: Update the authenticated application settings
        description: Update the settings configuring this application
        operationId: update-authenticated-application-settings
        security:
          - application_authorization:
              - update:application
    /v1/channels:
      get:
        tags:
          - channels
        summary: List channels
        description: Returns a page of channels belonging to this application
        operationId: list-channels
        security:
          - application_authorization:
              - read:channel
      post:
        tags:
          - channels
        summary: Create a channel
        description: Creates a new channel or returns an equivalent existing channel
        operationId: create-channel
        security:
          - application_authorization:
              - create:channel
    /v1/channels/{id}:
      get:
        tags:
          - channels
        summary: Retrieve a channel
        description: Returns a channel by ID
        operationId: retrieve-channel
        security:
          - application_authorization:
              - read:channel
      delete:
        tags:
          - channels
        summary: Delete a channel
        description: Deletes a channel by ID
        operationId: delete-channel
        security:
          - application_authorization:
              - read:channel
              - delete:channel
      patch:
        tags:
          - channels
        summary: Update a channel
        description: Updates a channel properties
        operationId: update-channel
        security:
          - application_authorization:
              - read:channel
              - update:channel
    /v1/channels/{id}/events:
      post:
        tags:
          - channels
        summary: Send a channel event
        description: Sends a custom channel event
        operationId: send-channel-event
        security:
          - application_authorization:
              - read:channel
              - create:channel_event
    /v1/channels/{id}/invites:
      get:
        tags:
          - channels
        summary: List channel invites
        description: Returns a page of invites sent to join this channel
        operationId: list-channel-invites
        security:
          - application_authorization:
              - read:channel_invite
      post:
        tags:
          - channels
        summary: Send a channel invite
        description: Sends a channel invite to user
        operationId: send-channel-invite
        security:
          - application_authorization:
              - read:channel
              - read:user
              - create:channel_invite
    /v1/channels/{id}/keystrokes:
      post:
        tags:
          - channels
        summary: Send channel keystrokes
        description: Sends keystrokes in this channel on behalf of a user
        operationId: send-channel-keystrokes
        security:
          - application_authorization:
              - read:channel
              - read:user
              - create:keystrokes
    /v1/channels/{id}/members:
      get:
        tags:
          - channels
        summary: List a channel's members
        description: Returns a page of channel members
        operationId: list-channel-members
        security:
          - application_authorization:
              - read:channel
              - read:channel_membership
      post:
        tags:
          - channels
        summary: Add a channel member
        description: Makes a user a group channel member
        operationId: add-channel-member
        security:
          - application_authorization:
              - read:channel
              - read:user
              - create:channel_membership
    /v1/channels/{id}/members/{user_id}:
      delete:
        tags:
          - channels
        summary: Remove a channel member
        description: Removes a member from a group channel
        operationId: remove-channel-member
        security:
          - application_authorization:
              - read:channel
              - read:user
              - delete:channel_membership
    /v1/channels/{id}/memberships:
      get:
        tags:
          - channels
        summary: List channel memberships
        description: Returns a page of channel membership info for this channel
        operationId: list-channel-memberships
        security:
          - application_authorization:
              - read:channel
              - read:channel_membership
    /v1/channels/{id}/messages:
      get:
        tags:
          - channels
        summary: List channel messages
        description: Returns a page of messages sent in this channel
        operationId: list-channel-messages
        security:
          - application_authorization:
              - read:channel
              - read:message
      post:
        tags:
          - channels
        summary: Send a channel message
        description: Sends a message in this channel as the system or on behalf of a user
        operationId: send-channel-message
        security:
          - application_authorization:
              - read:channel
              - read:user
              - create:message
    /v1/channels/{id}/moderators:
      get:
        tags:
          - channels
        summary: Lists a channel's moderators
        description: Returns a page of channel moderators
        operationId: list-channel-moderators
        security:
          - application_authorization:
              - read:channel
              - read:channel_moderator
      post:
        tags:
          - channels
        summary: Add a channel moderator
        description: Makes a user a group channel moderator
        operationId: add-channel-moderator
        security:
          - application_authorization:
              - read:channel
              - read:user
              - read:channel_membership
              - create:channel_moderator
    /v1/channels/{id}/moderators/{user_id}:
      delete:
        tags:
          - channels
        summary: Remove a channel moderator
        description: Removes a moderator from a group channel
        operationId: remove-channel-moderator
        security:
          - application_authorization:
              - read:channel
              - read:user
              - delete:channel_moderator
    /v1/channels/{id}/participants:
      get:
        tags:
          - channels
        summary: List channel participants
        description: >-
          Returns a page of channel active participants: members that currently
          online
        operationId: list-channel-participants
        security:
          - application_authorization:
              - read:channel
              - read:chat_session
    /v1/channels/{id}/reported-messages:
      get:
        tags:
          - channels
        summary: List channel reported messages
        description: Returns a page of reported messages in this channel
        operationId: list-channel-reported-messages
        security:
          - application_authorization:
              - read:channel
              - read:message_report
    /v1/chat-sessions:
      get:
        tags:
          - chat-sessions
        summary: List chat sessions
        description: Returns a page of chat sessions belonging to this application
        operationId: list-chat-sessions
        security:
          - application_authorization:
              - read:chat_session
    /v1/function-versions/{id}:
      get:
        tags:
          - function-versions
        summary: Retrieve a chat function version
        description: Returns a chat function version by ID
        operationId: retrieve-function-version
        security:
          - application_authorization:
              - read:function_version
    /v1/functions/{id}:
      get:
        tags:
          - functions
        summary: Retrieve a chat function
        description: Returns a chat function by ID
        operationId: retrieve-function
        security:
          - application_authorization:
              - read:function
    /v1/functions/{id}/current-version:
      get:
        tags:
          - functions
        summary: Retrieve chat function current version
        description: Returns the version of this chat function currently deployed
        operationId: retrieve-function-current-version
        security:
          - application_authorization:
              - read:function
              - read:function_version
    /v1/functions/{id}/invocations:
      get:
        tags:
          - functions
        summary: List chat function invocations
        description: >-
          Returns a page of invocations of this chat function. A log of previous
          runs of the function
        operationId: list-function-invocations
        security:
          - application_authorization:
              - read:function
              - read:function_invocation
    /v1/functions/{id}/versions:
      get:
        tags:
          - functions
        summary: List chat function versions
        description: Returns a page of versions of this chat function
        operationId: list-function-versions
        security:
          - application_authorization:
              - read:function
              - read:function_version
      post:
        tags:
          - functions
        summary: Create a chat function version
        description: Creates a new version of this chat function
        operationId: create-function-version
        security:
          - application_authorization:
              - read:function
              - create:function_version
    /v1/imports/channels:
      post:
        tags:
          - imports
        summary: Import channels
        description: Batch imports channels from a JSON array file
        operationId: import-channels
        security:
          - application_authorization:
              - create:channel
    /v1/imports/channels/{id}/members:
      post:
        tags:
          - imports
        summary: Import channel members
        description: Batch imports channel members from a JSON array file
        operationId: import-channel-members
        security:
          - application_authorization:
              - create:channel_membership
    /v1/imports/messages:
      post:
        tags:
          - imports
        summary: Import messages
        description: Batch imports messages from a JSON array file
        operationId: import-messages
        security:
          - application_authorization:
              - create:message
    /v1/imports/users:
      post:
        tags:
          - imports
        summary: Import users
        description: Batch imports users from a JSON array file
        operationId: import-users
        security:
          - application_authorization:
              - create:user
    /v1/jobs:
      get:
        tags:
          - jobs
        summary: List jobs
        description: Returns a page of jobs created for this application
        operationId: list-jobs
        security:
          - application_authorization:
              - read:job
    /v1/jobs/{id}:
      get:
        tags:
          - jobs
        summary: Retrieve a job
        description: Returns a job by ID
        operationId: retrieve-job
        security:
          - application_authorization:
              - read:job
    /v1/messages:
      get:
        tags:
          - messages
        summary: List messages
        description: Returns a page of messages belonging to this application
        operationId: list-messages
        security:
          - application_authorization:
              - read:message
      delete:
        tags:
          - messages
        summary: Delete messages
        description: Deletes all messages belonging to this application
        operationId: delete-messages
        security:
          - application_authorization:
              - read:message
              - delete:message
    /v1/messages/{id}:
      get:
        tags:
          - messages
        summary: Retrieve a message
        description: Returns a message by ID
        operationId: retrieve-message
        security:
          - application_authorization:
              - read:message
      delete:
        tags:
          - messages
        summary: Delete a message
        description: Deletes a message by ID
        operationId: delete-message
        security:
          - application_authorization:
              - read:message
              - delete:message
      patch:
        tags:
          - messages
        summary: Update a message
        description: Updates a message properties
        operationId: update-message
        security:
          - application_authorization:
              - read:message
              - update:message
    /v1/messages/{id}/read-receipts:
      get:
        tags:
          - messages
        summary: List message read receipts
        description: Returns a page of read receipts for this message
        operationId: list-message-read-receipts
        security:
          - application_authorization:
              - read:message
              - read:read_receipt
    /v1/runtimes/nodejs:
      get:
        tags:
          - runtime
        summary: Retrieve NodeJS chat runtime
        description: Return this application's NodeJS chat runtime
        operationId: retrieve-nodejs-runtime
        security:
          - application_authorization:
              - read:runtime
              - update:runtime
    /v1/runtimes/nodejs/dependencies:
      put:
        tags:
          - runtime
        summary: Update NodeJS chat runtime NPM dependencies
        description: Updates the NPM dependencies for this application's NodeJS chat runtime
        operationId: update-nodejs-runtime-dependencies
        security:
          - application_authorization:
              - read:runtime
              - update:runtime
    /v1/runtimes/nodejs/environment-variables:
      put:
        tags:
          - runtime
        summary: Update NodeJS chat runtime environment variables
        description: >-
          Updates the runtime environment variables of this application's NodeJS
          chat runtime
        operationId: update-nodejs-runtime-environment-variables
        security:
          - application_authorization:
              - read:runtime
              - update:runtime
    /v1/runtimes/nodejs/functions:
      get:
        tags:
          - runtime
        summary: List NodeJS chat runtime functions
        description: Returns a page of functions for this application's NodeJS chat runtime
        operationId: list-nodejs-runtime-functions
        security:
          - application_authorization:
              - read:runtime
              - read:function
      post:
        tags:
          - runtime
        summary: Create a NodeJS chat runtime function
        description: Creates a NodeJS chat function for this runtime
        operationId: create-nodejs-runtime-function
        security:
          - application_authorization:
              - read:runtime
              - read:function
    /v1/runtimes/nodejs/initialization-script:
      put:
        tags:
          - runtime
        summary: Update NodeJS chat runtime initialization script
        description: >-
          Updates the initialization script for this application's NodeJS chat
          runtime
        operationId: update-nodejs-runtime-initialization-script
        security:
          - application_authorization:
              - read:runtime
              - update:runtime
    /v1/threads/{id}:
      get:
        tags:
          - threads
        summary: Retrieve a thread
        description: Returns a thread by ID
        operationId: retrieve-thread
        security:
          - application_authorization:
              - read:thread
    /v1/threads/{id}/keystrokes:
      post:
        tags:
          - threads
        summary: Send thread keystrokes
        description: Sends keystrokes in this thread on behalf of a user
        operationId: send-thread-keystrokes
        security:
          - application_authorization:
              - read:thread
              - read:user
              - create:keystrokes
    /v1/threads/{id}/messages:
      get:
        tags:
          - threads
        summary: List reply thread messages
        description: Returns a page of replies sent in this thread
        operationId: list-thread-messages
        security:
          - application_authorization:
              - read:thread
              - read:message
      post:
        tags:
          - threads
        summary: Send a reply thread message
        description: >-
          Sends a reply message in this thread as the system or on behalf of a
          user
        operationId: send-thread-message
        security:
          - application_authorization:
              - read:thread
              - read:user
              - create:message
    /v1/user-sessions:
      get:
        tags:
          - user-sessions
        summary: List user sessions
        description: Returns a page of user sessions belonging to this application
        operationId: list-user-sessions
        security:
          - application_authorization:
              - read:user_session
    /v1/users:
      get:
        tags:
          - users
        summary: List users
        description: Returns a page of users belonging to this application
        operationId: list-users
        security:
          - application_authorization:
              - read:user
      post:
        tags:
          - users
        summary: Create a user
        description: Creates a new user
        operationId: create-user
        security:
          - application_authorization:
              - create:user
      head:
        tags:
          - users
        summary: Check a user exists
        description: Checks if a user exists
        operationId: check-user-exists
        security:
          - application_authorization:
              - read:user
    /v1/users/{id}:
      get:
        tags:
          - users
        summary: Retrieve a user
        description: Returns a user by ID
        operationId: retrieve-user
        security:
          - application_authorization:
              - read:user
      delete:
        tags:
          - users
        summary: Delete a user
        description: Delets a user
        operationId: delete-user
        security:
          - application_authorization:
              - read:user
              - delete:user
      patch:
        tags:
          - users
        summary: Update a user
        description: Updates a user
        operationId: update-user
        security:
          - application_authorization:
              - read:user
              - update:user
    /v1/users/{id}/channels:
      get:
        tags:
          - users
        summary: List a user's channels
        description: Returns a page of channels for this user created or joined
        operationId: list-user-channels
        security:
          - application_authorization:
              - read:user
              - read:channels
    /v1/users/{id}/display-picture:
      post:
        tags:
          - users
        summary: Update a user's display picture
        description: Updates a user's display picture
        operationId: update-user-display-picture
        security:
          - application_authorization:
              - read:user
              - update:user
    /v1/users/{id}/messages:
      get:
        tags:
          - users
        summary: List a user's messages
        description: Returns a page of messages sent by this user
        operationId: list-user-messages
        security:
          - application_authorization:
              - read:user
              - read:channels
    /v1/users/{id}/notifications:
      get:
        tags:
          - users
        summary: List a user's notifications
        description: Returns a page of notifications received by this user
        operationId: list-user-notifications
        security:
          - application_authorization:
              - read:user
              - read:notifications
    /v1/users/{id}/secrets/{name}:
      get:
        tags:
          - users
        summary: Retrieve a user secret
        description: Returns a user secret
        operationId: retrieve-user-secret
        security:
          - application_authorization:
              - read:user_secret
      put:
        tags:
          - users
        summary: Set a user secret
        description: Sets a user secret's value
        operationId: set-user-secret
        security:
          - application_authorization:
              - read:user
              - update:user_secret
      delete:
        tags:
          - users
        summary: Remove a user secret
        description: Removes a user secret's value
        operationId: remove-user-secret
        security:
          - application_authorization:
              - read:user
              - delete:user_secret
  components:
    securitySchemes:
      password_reset_token_authorization:
        type: apiKey
        name: X-Token
        in: header
      application_authorization:
        type: oauth2
        flows:
          clientCredentials:
            tokenUrl: https://authorization.chatkitty.com/oauth/token
            refreshUrl: https://authorization.chatkitty.com/oauth/token
            scopes:
              create:*: Create application resources
              read:*: Read application resources
              update:*: Update application resources
              delete:*: Delete application resources
konfigCliVersion: 1.38.37
