publishJson:
  company: HubSpot
  serviceName: CRM
  sdkName: hub-spot-crm-{language}-sdk
  clientName: HubSpotCrm
  metaDescription: >-
    HubSpot is a Massachusetts-based CRM platform that provides solutions such
    as marketing automation, meeting scheduling and data quality automation for
    businesses.
  apiStatusUrls: inherit
  homepage: hubspot.com
  developerDocumentation: developers.hubspot.com/docs/api/overview
  categories:
    - crm
rawSpecString: |
  openapi: 3.0.1
  info:
    title: Line Items
    description: ''
    version: v3
    x-hubspot-product-tier-requirements:
      marketing: FREE
      sales: FREE
      service: FREE
      cms: FREE
    x-hubspot-documentation-banner: NONE
    x-hubspot-api-use-case: >-
      When creating a set of quotes for sales reps to send to potential buyers,
      use this API to add goods and services to the quotes.
    x-hubspot-related-documentation:
      - name: Products Guide
        url: https://hubspot.dev/guides/api/crm/products
      - name: Pipelines Guide
        url: https://hubspot.dev/guides/api/crm/pipelines
      - name: Companies Guide
        url: https://hubspot.dev/guides/api/crm/companies
      - name: Call SDK Guide
        url: https://hubspot.dev/guides/api/crm/extensions/calling-sdk
      - name: Quotes guide
        url: https://hubspot.dev/guides/api/crm/quotes
      - name: Deals Guide
        url: https://hubspot.dev/guides/api/crm/deals
      - name: Import CRM Guide
        url: https://hubspot.dev/guides/api/crm/imports
      - name: Custom Object Guide
        url: https://hubspot.dev/guides/api/crm/objects/crm-custom-objects
      - name: Properties Guide
        url: https://hubspot.dev/guides/api/crm/properties
      - name: Owners Guide
        url: https://hubspot.dev/guides/api/crm/owners
      - name: Timeline Events Guide
        url: https://hubspot.dev/guides/api/crm/extensions/timeline
      - name: Contacts Guide
        url: https://hubspot.dev/guides/api/crm/contacts
      - name: Feedback Submissions Guide
        url: https://hubspot.dev/guides/api/crm/feedback-submissions
      - name: Video Conference Guide
        url: https://hubspot.dev/guides/api/crm/extensions/video-conferencing
      - name: Tickets Guide
        url: https://hubspot.dev/guides/api/crm/tickets
      - name: Line Items Guide
        url: https://hubspot.dev/guides/api/crm/line-items
    x-hubspot-introduction: >-
      Use the line items API to add instances of products to deals and quotes. You
      can create line items from existing products or create them as custom line
      items with no product attached.
  servers:
    - url: https://api.hubapi.com
  tags:
    - name: Pipeline Stage Audits
      description: ''
      x-hubspot-tag-name-english-source: Pipeline Stage Audits
    - name: Pipelines
      description: ''
      x-hubspot-tag-name-english-source: Pipelines
    - name: Pipeline Audits
      description: ''
      x-hubspot-tag-name-english-source: Pipeline Audits
    - name: Pipeline Stages
      description: ''
      x-hubspot-tag-name-english-source: Pipeline Stages
    - name: Recording_Settings
      description: ''
      x-hubspot-tag-name-english-source: Recording_Settings
    - name: Public_Imports
      description: ''
      x-hubspot-tag-name-english-source: Public_Imports
    - name: Core
    - name: Public_Object_Schemas
    - name: Batch
      description: ''
      x-hubspot-tag-name-english-source: Batch
    - name: Groups
      description: ''
      x-hubspot-tag-name-english-source: Groups
    - name: Core
      description: ''
      x-hubspot-tag-name-english-source: Core
    - name: Owners
      description: ''
      x-hubspot-tag-name-english-source: Owners
    - name: Events
    - name: Templates
    - name: Tokens
    - name: Settings
      description: ''
      x-hubspot-tag-name-english-source: Settings
    - name: Batch
    - name: Basic
    - name: Public_Object
    - name: GDPR
    - name: Search
  paths:
    /crm/v3/objects/products/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of products by internal ID, or unique property values
        operationId: post-/crm/v3/objects/products/batch/read_read
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/{productId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{productId}`. `{productId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/products/{productId}_getById
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{productId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/products/{productId}_archive
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{productId}`.
          `{productId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/products/{productId}_update
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two products with same type
        operationId: post-/crm/v3/objects/products/merge_merge
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of products by ID
        operationId: post-/crm/v3/objects/products/batch/archive_archive
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of products
        operationId: post-/crm/v3/objects/products/batch/create_create
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of products
        operationId: post-/crm/v3/objects/products/batch/update_update
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/products/gdpr-delete_purge
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of products. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/products_getPage
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a product with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard products is provided.
        operationId: post-/crm/v3/objects/products_create
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
    /crm/v3/objects/products/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/products/search_doSearch
        security:
          - oauth2_legacy:
              - e-commerce
          - oauth2: []
          - private_apps_legacy:
              - e-commerce
          - private_apps: []
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit:
      get:
        tags:
          - Pipeline Stage Audits
        summary: Return an audit of all changes to the pipeline stage
        description: >-
          Return a reverse chronological list of all mutations that have occurred
          on the pipeline stage identified by `{stageId}`.
        operationId: >-
          get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/pipelines/{objectType}/{pipelineId}:
      get:
        tags:
          - Pipelines
        summary: Return a pipeline by ID
        description: Return a single pipeline object identified by its unique `{pipelineId}`.
        operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      put:
        tags:
          - Pipelines
        summary: Replace a pipeline
        description: >-
          Replace all the properties of an existing pipeline with the values
          provided. This will overwrite any existing pipeline stages. The updated
          pipeline will be returned in the response.
        operationId: put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      delete:
        tags:
          - Pipelines
        summary: Delete a pipeline
        description: Delete the pipeline identified by `{pipelineId}`.
        operationId: delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      patch:
        tags:
          - Pipelines
        summary: Update a pipeline
        description: >-
          Perform a partial update of the pipeline identified by `{pipelineId}`.
          The updated pipeline will be returned in the response.
        operationId: patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/pipelines/{objectType}/{pipelineId}/audit:
      get:
        tags:
          - Pipeline Audits
        summary: Return an audit of all changes to the pipeline
        description: >-
          Return a reverse chronological list of all mutations that have occurred
          on the pipeline identified by `{pipelineId}`.
        operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
      get:
        tags:
          - Pipeline Stages
        summary: Return all stages of a pipeline
        description: >-
          Return all the stages associated with the pipeline identified by
          `{pipelineId}`.
        operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Pipeline Stages
        summary: Create a pipeline stage
        description: >-
          Create a new stage associated with the pipeline identified by
          `{pipelineId}`. The entire stage object, including its unique ID, will
          be returned in the response.
        operationId: post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/pipelines/{objectType}:
      get:
        tags:
          - Pipelines
        summary: Retrieve all pipelines
        description: Return all pipelines for the object type specified by `{objectType}`.
        operationId: get-/crm/v3/pipelines/{objectType}_getAll
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Pipelines
        summary: Create a pipeline
        description: >-
          Create a new pipeline with the provided property values. The entire
          pipeline object, including its unique ID, will be returned in the
          response.
        operationId: post-/crm/v3/pipelines/{objectType}_create
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
      get:
        tags:
          - Pipeline Stages
        summary: Return a pipeline stage by ID
        description: >-
          Return the stage identified by `{stageId}` associated with the pipeline
          identified by `{pipelineId}`.
        operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.contacts.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      put:
        tags:
          - Pipeline Stages
        summary: Replace a pipeline stage
        description: >-
          Replace all the properties of an existing pipeline stage with the values
          provided. The updated stage will be returned in the response.
        operationId: put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      delete:
        tags:
          - Pipeline Stages
        summary: Delete a pipeline stage
        description: >-
          Delete the pipeline stage identified by `{stageId}` associated with the
          pipeline identified by `{pipelineId}`.
        operationId: >-
          delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      patch:
        tags:
          - Pipeline Stages
        summary: Update a pipeline stage
        description: >-
          Perform a partial update of the pipeline stage identified by `{stageId}`
          associated with the pipeline identified by `{pipelineId}`. Any
          properties not included in this update will keep their existing values.
          The updated stage will be returned in the response.
        operationId: >-
          patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/objects/companies/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of companies by internal ID, or unique property values
        operationId: post-/crm/v3/objects/companies/batch/read_read
        security:
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.read
    /crm/v3/objects/companies/{companyId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{companyId}`. `{companyId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/companies/{companyId}_getById
        security:
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{companyId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/companies/{companyId}_archive
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{companyId}`.
          `{companyId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/companies/{companyId}_update
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two companies with same type
        operationId: post-/crm/v3/objects/companies/merge_merge
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of companies by ID
        operationId: post-/crm/v3/objects/companies/batch/archive_archive
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of companies
        operationId: post-/crm/v3/objects/companies/batch/create_create
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of companies
        operationId: post-/crm/v3/objects/companies/batch/update_update
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/companies/gdpr-delete_purge
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of companies. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/companies_getPage
        security:
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a company with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard companies is provided.
        operationId: post-/crm/v3/objects/companies_create
        security:
          - oauth2:
              - crm.objects.companies.write
          - private_apps:
              - crm.objects.companies.write
    /crm/v3/objects/companies/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/companies/search_doSearch
        security:
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/extensions/calling/{appId}/settings:
      get:
        tags:
          - Settings
        summary: Get calling settings
        description: Returns the calling extension settings configured for your app.
        operationId: get-/crm/v3/extensions/calling/{appId}/settings_getById
        security:
          - developer_hapikey: []
      post:
        tags:
          - Settings
        summary: Configure a calling extension
        description: >-
          Used to set the menu label, target iframe URL, and dimensions for your
          calling extension.
        operationId: post-/crm/v3/extensions/calling/{appId}/settings_create
        security:
          - developer_hapikey: []
      delete:
        tags:
          - Settings
        summary: Delete calling settings
        description: >-
          Deletes this calling extension. This will remove your service as an
          option for all connected accounts.
        operationId: delete-/crm/v3/extensions/calling/{appId}/settings_archive
        security:
          - developer_hapikey: []
      patch:
        tags:
          - Settings
        summary: Update settings
        description: Updates existing calling extension settings.
        operationId: patch-/crm/v3/extensions/calling/{appId}/settings_update
        security:
          - developer_hapikey: []
    /crm/v3/extensions/calling/{appId}/settings/recording:
      get:
        tags:
          - Recording_Settings
        operationId: get-/crm/v3/extensions/calling/{appId}/settings/recording_getUrlFormat
        security:
          - developer_hapikey: []
      post:
        tags:
          - Recording_Settings
        operationId: >-
          post-/crm/v3/extensions/calling/{appId}/settings/recording_registerUrlFormat
        security:
          - developer_hapikey: []
      patch:
        tags:
          - Recording_Settings
        operationId: >-
          patch-/crm/v3/extensions/calling/{appId}/settings/recording_updateUrlFormat
        security:
          - developer_hapikey: []
    /crm/v3/objects/quotes/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of quotes by internal ID, or unique property values
        operationId: post-/crm/v3/objects/quotes/batch/read_read
        security:
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/quotes/{quoteId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{quoteId}`. `{quoteId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/quotes/{quoteId}_getById
        security:
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{quoteId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/quotes/{quoteId}_archive
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{quoteId}`.
          `{quoteId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/quotes/{quoteId}_update
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two quotes with same type
        operationId: post-/crm/v3/objects/quotes/merge_merge
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of quotes by ID
        operationId: post-/crm/v3/objects/quotes/batch/archive_archive
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of quotes
        operationId: post-/crm/v3/objects/quotes/batch/create_create
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of quotes
        operationId: post-/crm/v3/objects/quotes/batch/update_update
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/quotes/gdpr-delete_purge
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of quotes. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/quotes_getPage
        security:
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a quote with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard quotes is provided.
        operationId: post-/crm/v3/objects/quotes_create
        security:
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
    /crm/v3/objects/quotes/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/quotes/search_doSearch
        security:
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/objects/deals/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of deals by internal ID, or unique property values
        operationId: post-/crm/v3/objects/deals/batch/read_read
        security:
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.deals.read
    /crm/v3/objects/deals/{dealId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{dealId}`. `{dealId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/deals/{dealId}_getById
        security:
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.deals.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{dealId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/deals/{dealId}_archive
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{dealId}`.
          `{dealId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/deals/{dealId}_update
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two deals with same type
        operationId: post-/crm/v3/objects/deals/merge_merge
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of deals by ID
        operationId: post-/crm/v3/objects/deals/batch/archive_archive
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of deals
        operationId: post-/crm/v3/objects/deals/batch/create_create
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of deals
        operationId: post-/crm/v3/objects/deals/batch/update_update
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/deals/gdpr-delete_purge
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of deals. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/deals_getPage
        security:
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.deals.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a deal with the given properties and return a copy of the object,
          including the ID. Documentation and examples for creating standard deals
          is provided.
        operationId: post-/crm/v3/objects/deals_create
        security:
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.write
    /crm/v3/objects/deals/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/deals/search_doSearch
        security:
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.deals.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/imports/{importId}/cancel:
      post:
        tags:
          - Core
        summary: Cancel an active import
        description: This allows a developer to cancel an active import.
        operationId: post-/crm/v3/imports/{importId}/cancel_cancel
        security:
          - oauth2_legacy:
              - crm.import
          - private_apps_legacy:
              - crm.import
    /crm/v3/imports/{importId}:
      get:
        tags:
          - Core
        summary: Get the information on any import
        description: A complete summary of an import record, including any updates.
        operationId: get-/crm/v3/imports/{importId}_getById
        security:
          - oauth2_legacy:
              - crm.import
          - private_apps_legacy:
              - crm.import
    /crm/v3/imports/{importId}/errors:
      get:
        tags:
          - Public_Imports
        operationId: get-/crm/v3/imports/{importId}/errors_getErrors
        security:
          - oauth2_legacy:
              - crm.import
          - private_apps_legacy:
              - crm.import
    /crm/v3/imports/:
      get:
        tags:
          - Core
        summary: Get active imports
        description: Returns a paged list of active imports for this account.
        operationId: get-/crm/v3/imports/_getPage
        security:
          - oauth2_legacy:
              - crm.import
          - private_apps_legacy:
              - crm.import
      post:
        tags:
          - Core
        summary: Start a new import
        description: >-
          Begins importing data from the specified file resources. This uploads
          the corresponding file and uses the import request object to convert
          rows in the files to objects.
        operationId: post-/crm/v3/imports/_create
        security:
          - oauth2_legacy:
              - crm.import
          - private_apps_legacy:
              - crm.import
    /crm/v3/schemas/{objectType}:
      get:
        tags:
          - Core
        summary: Get an existing schema
        description: Returns an existing object schema.
        operationId: get-/crm/v3/schemas/{objectType}_getById
        security:
          - private_apps_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2_legacy:
              - crm.schemas.custom.read
      delete:
        tags:
          - Core
        summary: Delete a schema
        description: >-
          Deletes a schema. Any existing records of this schema must be deleted
          **first**. Otherwise this call will fail.
        operationId: delete-/crm/v3/schemas/{objectType}_archive
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
      patch:
        tags:
          - Core
        summary: Update a schema
        description: Update the details for an existing object schema.
        operationId: patch-/crm/v3/schemas/{objectType}_update
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
    /crm/v3/schemas/{objectType}/associations:
      post:
        tags:
          - Core
        summary: Create an association
        description: >-
          Defines a new association between the primary schema's object type and
          other object types.
        operationId: post-/crm/v3/schemas/{objectType}/associations_createAssociation
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
    /crm/v3/schemas/{objectType}/purge:
      delete:
        tags:
          - Public_Object_Schemas
        operationId: delete-/crm/v3/schemas/{objectType}/purge_purge
        deprecated: true
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
    /crm/v3/schemas/{objectType}/associations/{associationIdentifier}:
      delete:
        tags:
          - Core
        summary: Remove an association
        description: Removes an existing association from a schema.
        operationId: >-
          delete-/crm/v3/schemas/{objectType}/associations/{associationIdentifier}_archiveAssociation
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
    /crm/v3/schemas:
      get:
        tags:
          - Core
        summary: Get all schemas
        description: Returns all object schemas that have been defined for your account.
        operationId: get-/crm/v3/schemas_getAll
        security:
          - private_apps_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2_legacy:
              - crm.schemas.custom.read
      post:
        tags:
          - Core
        summary: Create a new schema
        description: >-
          Define a new object schema, along with custom properties and
          associations. The entire object schema, including its object type ID,
          properties, and associations will be returned in the response.
        operationId: post-/crm/v3/schemas_create
        security:
          - private_apps_legacy:
              - crm.schemas.custom.write
    /crm/v3/properties/{objectType}/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of properties
        description: >-
          Archive a provided list of properties. This method will return a 204 No
          Content response on success regardless of the initial state of the
          property (e.g. active, already archived, non-existent).
        operationId: post-/crm/v3/properties/{objectType}/batch/archive_archive
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/properties/{objectType}/groups/{groupName}:
      get:
        tags:
          - Groups
        summary: Read a property group
        description: Read a property group identified by {groupName}.
        operationId: get-/crm/v3/properties/{objectType}/groups/{groupName}_getByName
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.objects.quotes.write
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps:
              - crm.schemas.invoices.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      delete:
        tags:
          - Groups
        summary: Archive a property group
        description: Move a property group identified by {groupName} to the recycling bin.
        operationId: delete-/crm/v3/properties/{objectType}/groups/{groupName}_archive
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      patch:
        tags:
          - Groups
        summary: Update a property group
        description: >-
          Perform a partial update of a property group identified by {groupName}.
          Provided fields will be overwritten.
        operationId: patch-/crm/v3/properties/{objectType}/groups/{groupName}_update
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/properties/{objectType}/{propertyName}:
      get:
        tags:
          - Core
        summary: Read a property
        description: Read a property identified by {propertyName}.
        operationId: get-/crm/v3/properties/{objectType}/{propertyName}_getByName
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.objects.quotes.write
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps:
              - crm.schemas.invoices.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      delete:
        tags:
          - Core
        summary: Archive a property
        description: Move a property identified by {propertyName} to the recycling bin.
        operationId: delete-/crm/v3/properties/{objectType}/{propertyName}_archive
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
      patch:
        tags:
          - Core
        summary: Update a property
        description: >-
          Perform a partial update of a property identified by {propertyName}.
          Provided fields will be overwritten.
        operationId: patch-/crm/v3/properties/{objectType}/{propertyName}_update
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/properties/{objectType}/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of properties
        description: Read a provided list of properties.
        operationId: post-/crm/v3/properties/{objectType}/batch/read_read
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.objects.quotes.write
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps:
              - crm.schemas.invoices.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/properties/{objectType}/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of properties
        description: >-
          Create a batch of properties using the same rules as when creating an
          individual property.
        operationId: post-/crm/v3/properties/{objectType}/batch/create_create
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/properties/{objectType}:
      get:
        tags:
          - Core
        summary: Read all properties
        description: >-
          Read all existing properties for the specified object type and HubSpot
          account.
        operationId: get-/crm/v3/properties/{objectType}_getAll
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.objects.quotes.write
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps:
              - crm.schemas.invoices.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Core
        summary: Create a property
        description: >-
          Create and return a copy of a new property for the specified object
          type.
        operationId: post-/crm/v3/properties/{objectType}_create
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/properties/{objectType}/groups:
      get:
        tags:
          - Groups
        summary: Read all property groups
        description: >-
          Read all existing property groups for the specified object type and
          HubSpot account.
        operationId: get-/crm/v3/properties/{objectType}/groups_getAll
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - private_apps:
              - crm.objects.subscriptions.read
          - private_apps_legacy:
              - crm.objects.marketing_events.read
          - oauth2_legacy:
              - crm.objects.marketing_events.write
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
          - oauth2_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.schemas.quotes.read
          - private_apps:
              - crm.schemas.quotes.read
          - oauth2:
              - crm.objects.companies.read
          - oauth2_legacy:
              - crm.objects.marketing_events.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps_legacy:
              - crm.objects.marketing_events.write
          - private_apps_legacy:
              - crm.schemas.custom.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - timeline
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.subscriptions.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - crm.objects.feedback_submissions.read
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.schemas.line_items.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.schemas.line_items.read
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.schemas.deals.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2:
              - crm.objects.quotes.write
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - private_apps:
              - crm.schemas.commercepayments.read
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.schemas.commercepayments.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - oauth2:
              - crm.schemas.invoices.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps:
              - crm.schemas.invoices.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Groups
        summary: Create a property group
        description: Create and return a copy of a new property group.
        operationId: post-/crm/v3/properties/{objectType}/groups_create
        security:
          - oauth2_legacy:
              - tickets
          - private_apps_legacy:
              - tickets.sensitive
          - oauth2:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - crm.schemas.custom.write
          - private_apps:
              - crm.schemas.deals.write
    /crm/v3/owners/:
      get:
        tags:
          - Owners
        summary: Get a page of owners
        operationId: get-/crm/v3/owners/_getPage
        security:
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
    /crm/v3/owners/{ownerId}:
      get:
        tags:
          - Owners
        summary: Read an owner by given `id` or `userId`
        operationId: get-/crm/v3/owners/{ownerId}_getById
        security:
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.objects.owners.read
          - oauth2:
              - crm.objects.owners.read
    /crm/v3/timeline/events/batch/create:
      post:
        tags:
          - Events
        summary: Creates multiple events
        description: >-
          Creates multiple instances of timeline events based on an event
          template. Once created, these event are immutable on the object timeline
          and cannot be modified. If the event template was configured to update
          object properties via `objectPropertyName`, this call will also attempt
          to updates those properties, or add them if they don't exist.
        operationId: post-/crm/v3/timeline/events/batch/create_createBatch
        security:
          - oauth2_legacy:
              - tickets
          - oauth2:
              - crm.schemas.deals.write
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps_legacy:
              - timeline
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - timeline
          - private_apps:
              - crm.objects.companies.write
          - private_apps:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.companies.write
    /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}:
      get:
        tags:
          - Templates
        summary: Gets a specific event template for your app
        description: View the current state of a specific template and its tokens.
        operationId: get-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}_getById
        security:
          - developer_hapikey: []
      put:
        tags:
          - Templates
        summary: Update an existing event template
        description: >-
          Updates an existing template and its tokens. This is primarily used to
          update the headerTemplate/detailTemplate, and those changes will take
          effect for existing events.


          You can also update or replace all the tokens in the template here
          instead of doing individual API calls on the `/tokens` endpoint.
        operationId: put-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}_update
        security:
          - developer_hapikey: []
      delete:
        tags:
          - Templates
        summary: Deletes an event template for the app
        description: >-
          This will delete the event template. All associated events will be
          removed from search results and the timeline UI.


          This action can't be undone, so it's highly recommended that you stop
          using any associated events before deleting a template.
        operationId: >-
          delete-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}_archive
        security:
          - developer_hapikey: []
    /crm/v3/timeline/events:
      post:
        tags:
          - Events
        summary: Create a single event
        description: >-
          Creates an instance of a timeline event based on an event template. Once
          created, this event is immutable on the object timeline and cannot be
          modified. If the event template was configured to update object
          properties via `objectPropertyName`, this call will also attempt to
          updates those properties, or add them if they don't exist.
        operationId: post-/crm/v3/timeline/events_create
        security:
          - oauth2_legacy:
              - tickets
          - oauth2:
              - crm.schemas.deals.write
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps_legacy:
              - timeline
          - oauth2:
              - crm.schemas.contacts.write
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.schemas.companies.write
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.schemas.contacts.write
          - private_apps:
              - crm.schemas.companies.write
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - timeline
          - private_apps:
              - crm.objects.companies.write
          - private_apps:
              - crm.schemas.deals.write
          - oauth2:
              - crm.objects.companies.write
    /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens:
      post:
        tags:
          - Tokens
        summary: Adds a token to an existing event template
        description: >-
          Once you've defined an event template, it's likely that you'll want to
          define tokens for it as well. You can do this on the event template
          itself or update individual tokens here.


          Event type tokens allow you to attach custom data to events displayed in
          a timeline or used for list segmentation.


          You can also use `objectPropertyName` to associate any CRM object
          properties. This will allow you to fully build out CRM objects.


          Token names should be unique across the template.
        operationId: >-
          post-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens_create
        security:
          - developer_hapikey: []
    /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}:
      put:
        tags:
          - Tokens
        summary: Updates an existing token on an event template
        description: >-
          This will update the existing token on an event template. Name and type
          can't be changed on existing tokens.
        operationId: >-
          put-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_update
        security:
          - developer_hapikey: []
      delete:
        tags:
          - Tokens
        summary: Removes a token from the event template
        description: >-
          This will remove the token from an existing template. Existing events
          and CRM objects will still retain the token and its mapped object
          properties, but new ones will not.


          The timeline will still display this property for older CRM objects if
          it's still referenced in the template `Markdown`. New events will not.


          Any lists or reports referencing deleted tokens will no longer return
          new contacts, but old ones will still exist in the lists.
        operationId: >-
          delete-/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_archive
        security:
          - developer_hapikey: []
    /crm/v3/timeline/events/{eventTemplateId}/{eventId}/detail:
      get:
        tags:
          - Events
        summary: Gets the detailTemplate as rendered
        description: >-
          This will take the `detailTemplate` from the event template and return
          an object rendering the specified event. If the template references
          `extraData` that isn't found in the event, it will be ignored and we'll
          render without it.
        operationId: >-
          get-/crm/v3/timeline/events/{eventTemplateId}/{eventId}/detail_getDetailById
        security:
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.schemas.contacts.read
          - oauth2_legacy:
              - tickets
          - oauth2:
              - crm.objects.contacts.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - oauth2:
              - crm.objects.deals.read
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2_legacy:
              - timeline
    /crm/v3/timeline/events/{eventTemplateId}/{eventId}:
      get:
        tags:
          - Events
        summary: Gets the event
        description: >-
          This returns the previously created event. It contains all existing info
          for the event, but not necessarily the CRM object.
        operationId: get-/crm/v3/timeline/events/{eventTemplateId}/{eventId}_getById
        security:
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.schemas.contacts.read
          - oauth2_legacy:
              - tickets
          - oauth2:
              - crm.objects.contacts.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - oauth2:
              - crm.objects.deals.read
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2_legacy:
              - timeline
    /crm/v3/timeline/{appId}/event-templates:
      get:
        tags:
          - Templates
        summary: List all event templates for your app
        description: Use this to list all event templates owned by your app.
        operationId: get-/crm/v3/timeline/{appId}/event-templates_getAll
        security:
          - developer_hapikey: []
      post:
        tags:
          - Templates
        summary: Create an event template for your app
        description: >-
          Event templates define the general structure for a custom timeline
          event. This includes formatted copy for its heading and details, as well
          as any custom property definitions. The event could be something like
          viewing a video, registering for a webinar, or filling out a survey. A
          single app can define multiple event templates.


          Event templates will be created for contacts by default, but they can be
          created for companies, tickets, and deals as well.


          Each event template contains its own set of tokens and `Markdown`
          templates. These tokens can be associated with any CRM object properties
          via the `objectPropertyName` field to fully build out CRM objects.


          You must create an event template before you can create events.
        operationId: post-/crm/v3/timeline/{appId}/event-templates_create
        security:
          - developer_hapikey: []
    /crm/v3/timeline/events/{eventTemplateId}/{eventId}/render:
      get:
        tags:
          - Events
        summary: Renders the header or detail as HTML
        description: >-
          This will take either the `headerTemplate` or `detailTemplate` from the
          event template and render for the specified event as HTML. If the
          template references `extraData` that isn't found in the event, it will
          be ignored and we'll render without it.
        operationId: >-
          get-/crm/v3/timeline/events/{eventTemplateId}/{eventId}/render_getRenderById
        security:
          - oauth2:
              - crm.schemas.contacts.read
          - private_apps:
              - crm.schemas.contacts.read
          - oauth2_legacy:
              - tickets
          - oauth2:
              - crm.objects.contacts.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps_legacy:
              - timeline
          - oauth2:
              - crm.objects.deals.read
          - private_apps_legacy:
              - contacts
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.schemas.companies.read
          - oauth2:
              - crm.schemas.companies.read
          - private_apps:
              - crm.objects.deals.sensitive.read
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - private_apps_legacy:
              - tickets
          - private_apps:
              - crm.schemas.deals.read
          - oauth2:
              - crm.schemas.deals.read
          - oauth2_legacy:
              - timeline
    /crm/v3/objects/contacts/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of contacts by internal ID, or unique property values
        operationId: post-/crm/v3/objects/contacts/batch/read_read
        security:
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
    /crm/v3/objects/contacts/{contactId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{contactId}`. `{contactId}` refers to the
          internal object ID.  Control what is returned via the `properties` query
          param.
        operationId: get-/crm/v3/objects/contacts/{contactId}_getById
        security:
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{contactId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/contacts/{contactId}_archive
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{contactId}`.
          `{contactId}` refers to the internal object ID. Provided property values
          will be overwritten. Read-only and non-existent properties will be
          ignored. Properties values can be cleared by passing an empty string.
        operationId: patch-/crm/v3/objects/contacts/{contactId}_update
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two contacts with same type
        operationId: post-/crm/v3/objects/contacts/merge_merge
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of contacts by ID
        operationId: post-/crm/v3/objects/contacts/batch/archive_archive
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of contacts
        operationId: post-/crm/v3/objects/contacts/batch/create_create
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of contacts
        operationId: post-/crm/v3/objects/contacts/batch/update_update
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/contacts/gdpr-delete_purge
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of contacts. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/contacts_getPage
        security:
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a contact with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard contacts is provided.
        operationId: post-/crm/v3/objects/contacts_create
        security:
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
    /crm/v3/objects/contacts/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/contacts/search_doSearch
        security:
          - oauth2:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.contacts.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/objects/feedback_submissions/batch/read:
      post:
        tags:
          - Batch
        summary: >-
          Read a batch of feedback submissions by internal ID, or unique property
          values
        operationId: post-/crm/v3/objects/feedback_submissions/batch/read_read
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/{feedbackSubmissionId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{feedbackSubmissionId}`.
          `{feedbackSubmissionId}` refers to the internal object ID by default, or
          optionally any unique property value as specified by the `idProperty`
          query param.  Control what is returned via the `properties` query param.
        operationId: get-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_getById
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
      delete:
        tags:
          - Basic
        summary: Archive
        description: >-
          Move an Object identified by `{feedbackSubmissionId}` to the recycling
          bin.
        operationId: >-
          delete-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_archive
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by
          `{feedbackSubmissionId}`. `{feedbackSubmissionId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param. Provided property values
          will be overwritten. Read-only and non-existent properties will be
          ignored. Properties values can be cleared by passing an empty string.
        operationId: patch-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_update
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two feedback submissions with same type
        operationId: post-/crm/v3/objects/feedback_submissions/merge_merge
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of feedback submissions by ID
        operationId: post-/crm/v3/objects/feedback_submissions/batch/archive_archive
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of feedback submissions
        operationId: post-/crm/v3/objects/feedback_submissions/batch/create_create
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of feedback submissions
        operationId: post-/crm/v3/objects/feedback_submissions/batch/update_update
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/feedback_submissions/gdpr-delete_purge
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of feedback submissions. Control what is returned via the
          `properties` query param.
        operationId: get-/crm/v3/objects/feedback_submissions_getPage
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a feedback submission with the given properties and return a copy
          of the object, including the ID. Documentation and examples for creating
          standard feedback submissions is provided.
        operationId: post-/crm/v3/objects/feedback_submissions_create
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
    /crm/v3/objects/feedback_submissions/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/feedback_submissions/search_doSearch
        security:
          - oauth2_legacy: []
          - private_apps_legacy: []
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/objects/{objectType}/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of objects by internal ID, or unique property values
        operationId: post-/crm/v3/objects/{objectType}/batch/read_read
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/{objectId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{objectId}`. `{objectId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/{objectType}/{objectId}_getById
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{objectId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/{objectType}/{objectId}_archive
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{objectId}`.
          `{objectId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/{objectType}/{objectId}_update
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two objects with same type
        operationId: post-/crm/v3/objects/{objectType}/merge_merge
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of objects by ID
        operationId: post-/crm/v3/objects/{objectType}/batch/archive_archive
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of objects
        operationId: post-/crm/v3/objects/{objectType}/batch/create_create
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of objects by internal ID, or unique property values
        operationId: post-/crm/v3/objects/{objectType}/batch/update_update
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of objects. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/{objectType}_getPage
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a CRM object with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard objects is provided.
        operationId: post-/crm/v3/objects/{objectType}_create
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
    /crm/v3/objects/{objectType}/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/{objectType}/search_doSearch
        security:
          - oauth2_legacy:
              - media_bridge.read
          - private_apps_legacy:
              - tickets.sensitive
          - private_apps:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.subscriptions.read
          - oauth2:
              - crm.objects.deals.read
          - private_apps:
              - crm.objects.contacts.sensitive.write
          - private_apps_legacy:
              - contacts
          - oauth2:
              - crm.objects.subscriptions.read
          - private_apps:
              - crm.objects.companies.read
          - oauth2:
              - crm.objects.companies.read
          - private_apps:
              - crm.objects.companies.sensitive.read
          - private_apps:
              - crm.objects.deals.sensitive.write
          - private_apps_legacy:
              - crm.objects.goals.read
          - private_apps:
              - crm.objects.users.write
          - private_apps_legacy:
              - media_bridge.read
          - private_apps:
              - crm.objects.companies.write
          - oauth2:
              - crm.objects.companies.write
          - oauth2_legacy:
              - tickets
          - private_apps:
              - crm.objects.users.read
          - private_apps_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.users.read
          - oauth2:
              - crm.objects.users.write
          - private_apps_legacy:
              - e-commerce
          - private_apps:
              - crm.objects.deals.sensitive.read
          - oauth2_legacy:
              - e-commerce
          - private_apps_legacy:
              - tickets
          - oauth2_legacy:
              - crm.objects.goals.read
          - oauth2_legacy:
              - crm.objects.custom.write
          - oauth2:
              - crm.objects.contacts.read
          - oauth2:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.commercepayments.read
          - private_apps:
              - crm.objects.companies.sensitive.write
          - private_apps:
              - crm.objects.contacts.read
          - private_apps:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.deals.write
          - oauth2:
              - crm.objects.invoices.read
          - private_apps:
              - crm.objects.invoices.read
          - oauth2:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.quotes.write
          - private_apps:
              - crm.objects.line_items.read
          - oauth2:
              - crm.objects.contacts.write
          - private_apps:
              - crm.objects.contacts.write
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.custom.sensitive.read
          - oauth2_legacy:
              - crm.objects.custom.read
          - private_apps_legacy:
              - crm.objects.custom.read
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.custom.sensitive.write
          - private_apps:
              - crm.objects.contacts.sensitive.read
          - oauth2:
              - crm.objects.quotes.read
          - private_apps:
              - crm.objects.quotes.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/extensions/videoconferencing/settings/{appId}:
      get:
        tags:
          - Settings
        summary: Get settings
        description: >-
          Return the settings for a video conference application with the
          specified ID.
        operationId: get-/crm/v3/extensions/videoconferencing/settings/{appId}_getById
        security:
          - developer_hapikey: []
      put:
        tags:
          - Settings
        summary: Update settings
        description: >-
          Updates the settings for a video conference application with the
          specified ID.
        operationId: put-/crm/v3/extensions/videoconferencing/settings/{appId}_replace
        security:
          - developer_hapikey: []
      delete:
        tags:
          - Settings
        summary: Delete settings
        description: >-
          Deletes the settings for a video conference application with the
          specified ID.
        operationId: delete-/crm/v3/extensions/videoconferencing/settings/{appId}_archive
        security:
          - developer_hapikey: []
    /crm/v3/objects/tickets/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of tickets by internal ID, or unique property values
        operationId: post-/crm/v3/objects/tickets/batch/read_read
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/{ticketId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{ticketId}`. `{ticketId}` refers to the
          internal object ID by default, or optionally any unique property value
          as specified by the `idProperty` query param.  Control what is returned
          via the `properties` query param.
        operationId: get-/crm/v3/objects/tickets/{ticketId}_getById
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{ticketId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/tickets/{ticketId}_archive
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{ticketId}`.
          `{ticketId}` refers to the internal object ID by default, or optionally
          any unique property value as specified by the `idProperty` query param.
          Provided property values will be overwritten. Read-only and non-existent
          properties will be ignored. Properties values can be cleared by passing
          an empty string.
        operationId: patch-/crm/v3/objects/tickets/{ticketId}_update
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two tickets with same type
        operationId: post-/crm/v3/objects/tickets/merge_merge
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of tickets by ID
        operationId: post-/crm/v3/objects/tickets/batch/archive_archive
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of tickets
        operationId: post-/crm/v3/objects/tickets/batch/create_create
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of tickets
        operationId: post-/crm/v3/objects/tickets/batch/update_update
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/tickets/gdpr-delete_purge
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of tickets. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/tickets_getPage
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a ticket with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard tickets is provided.
        operationId: post-/crm/v3/objects/tickets_create
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
    /crm/v3/objects/tickets/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/tickets/search_doSearch
        security:
          - oauth2_legacy:
              - tickets
          - oauth2: []
          - private_apps_legacy:
              - tickets
          - private_apps: []
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
    /crm/v3/objects/line_items/batch/read:
      post:
        tags:
          - Batch
        summary: Read a batch of line items by internal ID, or unique property values
        operationId: post-/crm/v3/objects/line_items/batch/read_read
        security:
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.line_items.read
    /crm/v3/objects/line_items/{lineItemId}:
      get:
        tags:
          - Basic
        summary: Read
        description: >-
          Read an Object identified by `{lineItemId}`. `{lineItemId}` refers to
          the internal object ID by default, or optionally any unique property
          value as specified by the `idProperty` query param.  Control what is
          returned via the `properties` query param.
        operationId: get-/crm/v3/objects/line_items/{lineItemId}_getById
        security:
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.line_items.read
      delete:
        tags:
          - Basic
        summary: Archive
        description: Move an Object identified by `{lineItemId}` to the recycling bin.
        operationId: delete-/crm/v3/objects/line_items/{lineItemId}_archive
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
      patch:
        tags:
          - Basic
        summary: Update
        description: >-
          Perform a partial update of an Object identified by `{lineItemId}`.
          `{lineItemId}` refers to the internal object ID by default, or
          optionally any unique property value as specified by the `idProperty`
          query param. Provided property values will be overwritten. Read-only and
          non-existent properties will be ignored. Properties values can be
          cleared by passing an empty string.
        operationId: patch-/crm/v3/objects/line_items/{lineItemId}_update
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/merge:
      post:
        tags:
          - Public_Object
        summary: Merge two line items with same type
        operationId: post-/crm/v3/objects/line_items/merge_merge
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/batch/archive:
      post:
        tags:
          - Batch
        summary: Archive a batch of line items by ID
        operationId: post-/crm/v3/objects/line_items/batch/archive_archive
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/batch/create:
      post:
        tags:
          - Batch
        summary: Create a batch of line items
        operationId: post-/crm/v3/objects/line_items/batch/create_create
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/batch/update:
      post:
        tags:
          - Batch
        summary: Update a batch of line items
        operationId: post-/crm/v3/objects/line_items/batch/update_update
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/gdpr-delete:
      post:
        tags:
          - GDPR
        summary: GDPR DELETE
        description: >-
          Permanently delete a contact and all associated content to follow GDPR.
          Use optional property 'idProperty' set to 'email' to identify contact by
          email address. If email address is not found, the email address will be
          added to a blocklist and prevent it from being used in the future.
        operationId: post-/crm/v3/objects/line_items/gdpr-delete_purge
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items:
      get:
        tags:
          - Basic
        summary: List
        description: >-
          Read a page of line items. Control what is returned via the `properties`
          query param.
        operationId: get-/crm/v3/objects/line_items_getPage
        security:
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.line_items.read
      post:
        tags:
          - Basic
        summary: Create
        description: >-
          Create a line item with the given properties and return a copy of the
          object, including the ID. Documentation and examples for creating
          standard line items is provided.
        operationId: post-/crm/v3/objects/line_items_create
        security:
          - oauth2:
              - crm.objects.line_items.write
          - private_apps:
              - crm.objects.line_items.write
    /crm/v3/objects/line_items/search:
      post:
        tags:
          - Search
        operationId: post-/crm/v3/objects/line_items/search_doSearch
        security:
          - oauth2:
              - crm.objects.line_items.read
          - private_apps:
              - crm.objects.line_items.read
        x-hubspot-rate-limit-exemptions:
          - ten-secondly
  components:
    securitySchemes:
      oauth2_legacy:
        type: oauth2
        flows:
          authorizationCode:
            authorizationUrl: https://app.hubspot.com/oauth/authorize
            tokenUrl: https://api.hubapi.com/oauth/v1/token
            scopes:
              media_bridge.read: Read media and media events
              crm.objects.goals.read: Read goals
              tickets: Read and write tickets
              crm.objects.custom.read: View custom object records
              e-commerce: e-commerce
              crm.objects.custom.write: Change custom object records
              crm.objects.feedback_submissions.read: View feedback survey submissions
              crm.objects.marketing_events.write: Write marketing events
              timeline: Create timeline events
              crm.schemas.custom.read: View custom object definitions
              crm.objects.marketing_events.read: Read marketing events
              crm.import: Create or modify all your CRM data through bulk imports
      oauth2:
        type: oauth2
        flows:
          authorizationCode:
            authorizationUrl: https://app.hubspot.com/oauth/authorize
            tokenUrl: https://api.hubapi.com/oauth/v1/token
            scopes:
              crm.objects.quotes.write: Quotes
              crm.objects.deals.read: ' '
              crm.objects.line_items.read: Line Items
              crm.objects.deals.write: ' '
              crm.objects.quotes.read: Quotes
              crm.objects.line_items.write: Line Items
              crm.objects.companies.read: ' '
              crm.objects.companies.write: ' '
              crm.objects.contacts.write: ' '
              crm.objects.contacts.read: ' '
              crm.schemas.quotes.read: Quotes schemas
              crm.schemas.subscriptions.read: Read subscriptions schema
              crm.objects.users.read: Read User CRM objects
              crm.objects.subscriptions.read: Read Commerce Subscriptions
              crm.schemas.deals.read: ' '
              crm.schemas.contacts.read: ' '
              crm.schemas.commercepayments.read: Read the COMMERCE_PAYMENT properties.
              crm.objects.invoices.read: Read invoices objects
              crm.schemas.invoices.read: Read invoices schema
              crm.schemas.companies.read: ' '
              crm.schemas.line_items.read: Line Items schemas
              crm.objects.owners.read: ' '
              crm.schemas.deals.write: ' '
              crm.schemas.companies.write: ' '
              crm.schemas.contacts.write: ' '
              crm.objects.users.write: Write User CRM objects
              crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
      private_apps_legacy:
        type: apiKey
        name: private-app-legacy
        in: header
      private_apps:
        type: apiKey
        name: private-app
        in: header
      developer_hapikey:
        type: apiKey
        name: hapikey
        in: query
  x-hubspot-available-client-libraries:
    - PHP
    - Node
    - Ruby
    - Python
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
konfigCliVersion: 1.38.37
