publishJson:
  company: Hypatos
  serviceName: false
  sdkName: hypatos-{language}-sdk
  clientName: Hypatos
  metaDescription: >-
    Balancing humans and machines to accelerate business.


    Hypatos adds value to critical business operations using third wave AI and
    advanced automation technologies for document processing. By replacing
    routine and complex tasks with intelligent solutions, we are unlocking human
    potential and reshaping the workplace. As AI agents manage administrative
    tasks efficiently, accurately and cost effectively, people focus on
    strategic decisions and designing innovative solutions to bring business to
    the next level.


    Data Protection Policy:

    https://www.hypatos.ai/privacy-policy
  apiStatusUrls: inherit
  homepage: hypatos.ai
  developerDocumentation: hypatos.redoc.ly/
  categories:
    - machine_learning
    - ai
    - document_processing
rawSpecString: |
  openapi: 3.0.3
  info:
    version: 2.15.0
    title: Hypatos REST API
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: >
      # Introduction


      The Hypatos API is organized around REST. The majority of the endpoints
      provide CRUD 

      functionality for resources. The API is also exposing Intent Resources which
      mimic user intents 

      or actions.


      The Hypatos API uses [OAuth 2.0 Client Credential
      Grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.4) 

      to authenticate requests. Before making any requests to any endpoint a
      client must authenticate 

      with the authorization server and requests an access token from the [token
      endpoint](https://hypatos.redoc.ly/). 


      ````sh
        POST /auth/token HTTP/1.1
        Host: api.cloud.hypatos.ai
        Content-Type: application/x-www-form-urlencoded
        Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=

        grant_type=client_credentials
      ````


      `Authorization` header contains `client_id:client_secret` encoded as
      explained in [RFC Client Password
      section](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1).
           
      If the authorization server authenticated the client successfully, an access
      token is issued. 

      Here is an example successful response:


      ````sh
        HTTP/1.1 200 OK
        Content-Type: application/json;charset=UTF-8
        Cache-Control: no-store
        Pragma: no-cache

        {
          "access_token": "mF_9.B5f-4.1JqM",
          "expires_in": 86400,
          "scope": "enrichment.write files.read",
          "token_type": "Bearer"
        }
      ````

      This token can be used to authenticate the requests to API endpoints by
      sending a Bearer token 

      in the `Authorization` HTTP header. The following example demonstrates how
      to use the access token 

      to retrieve a list of documents.


      ````sh
        GET /v2/documents HTTP/1.1
        Host: api.cloud.hypatos.ai
        Authorization: Bearer mF_9.B5f-4.1JqM
      ````


      # Versioning


      Changes to this API are released regularly. We use [Semantic Versioning
      2.0.0](https://semver.org/spec/v2.0.0.html) 

      scheme for versioning so that the clients can identify any
      backward-incompatible changes 

      easily. Briefly summarized one can say, if the MAJOR version of the new API
      version didn't 

      change you can expect the new version to be backward-compatible.


      # Rate limits


      In order to maximise the stability of our API, we institue rate limits for
      all of API 

      endpoints. Clients who send too many requests over a given period of time
      will see error 

      responses that show up as status code [429 Too Many
      Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). 


      When you see error responses with status code 429, it means you exhausted
      your current 

      quota and need to withhold from sending further requests until the quota is
      reset. We 

      encourage you not to wait until you get a 429 error but to monitor your
      quota in each 

      request. In each response you receive from the API, you will find HTTP
      headers providing 

      the details about your current quota. Here is the list of the HTTP headers:


      * `x-ratelimit-limit`: Indicates the quota associated to the client in the 

      current time-window followed by the description of the quota policy.

      * `x-ratelimit-remaining`: Indicates the number of remaining requests in the
      current 

      time-window

      * `x-ratelimit-reset`: Indicates the number of seconds until quota reset of
      the current 

      time-window


      Please note that IETF is currently in the process of publishing a standard
      for these 

      headers. Please explore the
      [draft](https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/) 

      for more details.


      A basic technique to gracefully handle rate limits is watch for your quota
      permanently 

      and increase the time between your request as the quota is decreasing. To
      recover from a 

      429 error you need a retry mechanism following an exponential backoff
      schedule.
  servers:
    - description: API EU
      url: https://api.cloud.hypatos.ai/v2
    - description: API US
      url: https://api.cloud.hypatos.com/v2
  tags:
    - name: Authorization
      description: >-
        Endpoints for handling the [OAuth 2.0 Client Credentials
        Grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.4) flow.
    - name: Files
      description: |
        Endpoints for management of files
    - name: Documents
      description: Endpoints for document management
    - name: Enrichment
      description: Endpoints for data enrichment
    - name: Companies
      description: Endpoints for company management
    - name: Projects
      description: Endpoints for project management
  paths:
    /auth/token:
      post:
        tags:
          - Authorization
        summary: Request an access token
        operationId: requestAccessToken
        description: Request an access token using your client credentials
        security:
          - Basic: []
    /files:
      post:
        summary: Upload a file
        operationId: uploadFile
        description: >
          This endpoint allows a client to upload a binary file. The ``id``
          returned in the reponse is representing the file in Hypatos systems. It
          can be used in other endpoints, for example to initiate a processing of
          the file to create document holding captured data.
        tags:
          - Files
        security:
          - OAuth2:
              - files.write
    /files/{id}:
      get:
        summary: Download a file by id
        operationId: retrieveFile
        description: |
          Download the content of a file with the given identifier.
        tags:
          - Files
        security:
          - OAuth2:
              - files.read
    /documents:
      get:
        summary: Retrieve a list of documents
        operationId: documentsList
        description: Retrieve a list of documents.
        security:
          - OAuth2:
              - documents.read
        tags:
          - Documents
    /documents/process-file:
      post:
        summary: Request processing of a file
        operationId: processFileIntoDocument
        description: >
          Request a processing of a file that was previously uploaded. 

          The `fileId` in the request body is representing the identifier of the
          file that was returned by the upload endpoint. 

          As a result of this request a document will be created and its
          identifier will be returned in the response.

          The `projectId` in the request body is an identifier of the project to
          create the document in.
        security:
          - OAuth2:
              - documents.write
        tags:
          - Documents
    /documents/{id}:
      get:
        summary: Retrieve a document by id
        operationId: documentsGetById
        description: Retrieve a document by id
        security:
          - OAuth2:
              - documents.read
        tags:
          - Documents
    /documents/{id}/transfer:
      post:
        summary: Provide information about a transfer of a document to the target system
        operationId: documentsUpdateTransfer
        description: Update information about the transfer for the given document
        security:
          - OAuth2:
              - documents.write
        tags:
          - Documents
    /documents/{id}/external-data:
      post:
        summary: Provide external data for a document with given id
        operationId: documentUpdateExternalData
        description: >
          Update the external data for a document with given identifier. The
          external data are provided as a flat JSON object. The payload of this
          requests completley overrides the existing external data of a document.
          To remove the data, justsend empty JSON object `{}` in the payload.


          Please note that the maximum lenght of an key is 50 characters. Any
          value with a longer key will be omitted. The maximum amount of key-value
          pairs is limited to 20.
        tags:
          - Documents
        security:
          - OAuth2:
              - documents.write
    /documents/{id}/external-id:
      post:
        summary: Provide an external identifier for a document with given id
        operationId: documentsUpdateExternalId
        description: Provide an external identifier for a document with given id
        security:
          - OAuth2:
              - documents.write
        tags:
          - Documents
    /documents/{id}/title:
      post:
        summary: Provide a title for a document with given id
        operationId: documentsUpdateTitle
        description: Provide a title for a document with given id.
        security:
          - OAuth2:
              - documents.write
        tags:
          - Documents
    /documents/{id}/states:
      get:
        summary: Retrieve a document states
        operationId: retrieveDocumentStates
        description: >-
          Provides a list of states the given document passed through. If the
          document is still in processing, the number of states returend must not
          be considered as final. Subsequent calls to this endpoint might get more
          states as the document is progressing the processing pipeline.
        security:
          - OAuth2:
              - documents.read
        tags:
          - Documents
    /enrichment/invoices:
      post:
        tags:
          - Enrichment
        summary: Insert invoice including invoice lines
        security:
          - OAuth2:
              - enrichment.write
        operationId: insertInvoice
    /enrichment/invoices/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark invoice as deleted
        operationId: deleteInvoice
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/companies:
      post:
        tags:
          - Enrichment
        summary: Insert company
        operationId: insertCompany
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/companies/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark company as deleted
        operationId: deleteCompany
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/suppliers:
      post:
        tags:
          - Enrichment
        summary: Insert supplier including related subsidiaries
        operationId: insertSupplier
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/suppliers/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark supplier as deleted
        operationId: deleteSupplier
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/purchase-orders:
      post:
        tags:
          - Enrichment
        summary: Insert purchase order including purchase order lines
        operationId: insertPurchaseOrder
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/purchase-orders/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark purchase Order as deleted
        operationId: deletePurchaseOrder
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/gl-accounts:
      post:
        tags:
          - Enrichment
        summary: Insert general ledger account
        operationId: insertGLAccount
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/gl-accounts/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark general ledger account as deleted
        operationId: deleteGlAccount
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/cost-centers:
      post:
        tags:
          - Enrichment
        summary: Insert cost center
        operationId: insertCostCenter
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/cost-centers/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark cost Center as deleted
        operationId: deleteCostCenter
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/approvers:
      post:
        tags:
          - Enrichment
        summary: Insert approver
        operationId: insertApprover
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/approvers/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark approver as deleted
        operationId: deleteApprover
        security:
          - OAuth2:
              - enrichment.delete
    /enrichment/customers:
      post:
        tags:
          - Enrichment
        summary: Insert customer
        operationId: insertCustomer
        security:
          - OAuth2:
              - enrichment.write
    /enrichment/customers/{externalId}:
      delete:
        tags:
          - Enrichment
        summary: Mark customer as deleted
        operationId: deleteCustomer
        security:
          - OAuth2:
              - enrichment.delete
    /companies/{id}:
      get:
        tags:
          - Companies
        summary: Retrieve a company by id
        operationId: companiesGetById
        security:
          - OAuth2:
              - companies.read
    /companies:
      get:
        tags:
          - Companies
        summary: Retrieve a list of companies
        description: 'Note: For now pagination is not implemented'
        operationId: companiesList
        security:
          - OAuth2:
              - companies.read
    /projects:
      post:
        summary: Create a project
        operationId: projectsCreate
        description: Creates a project based on the request
        security:
          - OAuth2:
              - projects.write
        tags:
          - Projects
      get:
        tags:
          - Projects
        summary: Retrieve a projects list for given search criteria
        operationId: projectsList
        security:
          - OAuth2:
              - projects.read
    /projects/{id}:
      get:
        summary: Retrieve a project by id
        operationId: projectsGetById
        description: Retrieve a project by id
        security:
          - OAuth2:
              - projects.read
        tags:
          - Projects
    /projects/{id}/schema:
      get:
        summary: Retrieve a schema by project id
        operationId: schemasGetByProjectId
        description: Retrieve a schema by project id
        security:
          - OAuth2:
              - projects.read
        tags:
          - Projects
    /emails/{id}/content:
      get:
        tags:
          - Emails
        summary: Retrieve an email merged content for given document ID
        operationId: emailsContentGetByDocumentId
        security:
          - OAuth2:
              - emails.read
  components:
    securitySchemes:
      OAuth2:
        type: oauth2
        flows:
          clientCredentials:
            tokenUrl: /auth/token
            scopes:
              companies.read: Read companies
              documents.read: Read documents
              documents.write: Edit your documents
              enrichment.read: Read enrichment training data
              enrichment.write: Create/edit enrichment training data
              enrichment.delete: Delete enrichment training data
              files.read: Uploading files for processing
              files.write: Downloading uploaded files
      Basic:
        type: http
        scheme: basic
konfigCliVersion: 1.38.37
