openapi: 3.0.0
info:
  title: Bitbucket API
  description: >-
    Code against the Bitbucket API to automate simple tasks, embed Bitbucket
    data into your own site, build mobile or desktop apps, or even add custom UI
    add-ons into Bitbucket itself using the Connect framework.
  version: '2.0'
  termsOfService: https://www.atlassian.com/legal/customer-agreement
  contact:
    name: Bitbucket Support
    url: https://support.atlassian.com/bitbucket-cloud/
    email: support@bitbucket.org
servers:
  - url: https://api.bitbucket.org/2.0
tags:
  - description: |
      Bitbucket Pipelines brings continuous delivery to Bitbucket
      Cloud, empowering teams with full branching to deployment
      visibility and faster feedback loops.
    name: Pipelines
  - description: |
      Pull requests are a feature that makes it easier for developers
      to collaborate using Bitbucket. They provide a user-friendly web
      interface for discussing proposed changes before integrating them
      into the official project.
    name: Pullrequests
  - description: >
      The issue resources provide functionality for getting information on

      issues in an issue tracker, creating new issues, updating them and
      deleting

      them.


      You can access public issues without authentication, but you can't gain
      access

      to private repositories' issues. By authenticating, you will get the
      ability

      to create issues, as well as access to updating data or deleting issues
      you

      have access to. Issue Tracker features are not supported for repositories
      in workspaces administered through admin.atlassian.com.
    name: Issue tracker
  - description: |
      A Git repository is a virtual storage of your project. It
      allows you to save versions of your code, which you can access
      when needed. The repo resource allows you to access public repos,
      or repos that belong to a specific workspace.
    name: Repositories
  - description: |
      These are the repository's commits. They are paginated and returned in
      reverse chronological order, similar to the output of git log.
    name: Commits
  - description: |
      Snippets allow you share code segments or files with yourself, members of
      your workspace, or the world.

      Like pull requests, repositories and workspaces, the full set of snippets
      is defined by what the current user has access to. This includes all
      snippets owned by any of the workspaces the user is a member of, or
      snippets by other users that the current user is either watching or has
       collaborated on (for instance by commenting on it).
    name: Snippets
  - description: |
      Teams are deploying code faster than ever, thanks to continuous
      delivery practices and tools like Bitbucket Pipelines. Bitbucket
      Deployments gives teams visibility into their deployment
      environments and helps teams to track how far changes have
      progressed in their deployment pipeline.
    name: Deployments
  - description: |
      Bitbucket Cloud projects make it easier for teams to focus on
      a goal, product, or process by organizing their repositories.
    name: Projects
  - description: |
      A workspace is where you create repositories, collaborate on
      your code, and organize different streams of work in your Bitbucket
      Cloud account. Workspaces replace the use of teams and users in API
      calls.
    name: Workspaces
  - description: >
      Webhooks provide a way to configure Bitbucket Cloud to make requests to

      your server (or another external service) whenever certain events occur in

      Bitbucket Cloud.


      A webhook consists of:


      * A subject -- The resource that generates the events. Currently, this
      resource

      is the repository, user account, or team where you create the webhook.

      * One or more event -- The default event is a repository push, but you can

      select multiple events that can trigger the webhook.

      * A URL -- The endpoint where you want Bitbucket to send the event
      payloads

      when a matching event happens.


      There are two parts to getting a webhook to work: creating the webhook and

      triggering the webhook. After you create a webhook for an event, every
      time

      that event occurs, Bitbucket sends a payload request that describes the
      event

      to the specified URL. Thus, you can think of webhooks as a kind of

      notification system.


      Use webhooks to integrate applications with Bitbucket Cloud. The following

      use cases provides examples of when you would want to use webhooks:


      * Every time a user pushes commits in a repository, you may want to notify

      your CI server to start a build.

      * Every time a user pushes commits or creates a pull request, you may want
      to

      display a notification in your application.
    name: Webhooks
  - name: properties
  - description: |
      The addon resource is intended to use used by Bitbucket Cloud Connect
      Apps, and only supports JWT authentication.
    name: Addon
  - description: |
      The refs resource allows you access branches and tags in a repository.
      By default, results will be in the order the underlying source control
      system returns them and identical to the ordering one sees when running
      "$ git show-ref". Note that this follows simple lexical ordering of the
       ref names.
    name: Refs
  - description: |
      Code insights provides reports, annotations, and metrics to help you
      and your team improve code quality in pull requests throughout the code
      review process. Some of the available code insights are static analysis
      reports, security scan results, artifact links, unit tests, and build
      status.
    name: Reports
  - description: |
      The branching model resource is used to modify the branching model
      for a repository.

      You can use the branching model to define a branch based workflow
      for your repositories. When you map your workflow to branch types,
      you can ensure that branches are named consistently by configuring
      which branch types to make available.
    name: Branching model
  - description: |
      Repository owners and administrators can set branch management
      rules on a repository that control what can be pushed by whom.
      Through these rules, you can enforce a project or team
      workflow. For example, owners or administrators can:

      * Limit push powers
      * Prevent branch deletion
      * Prevent history re-writes (Git only)
    name: Branch restrictions
  - description: |
      Commit statuses provide a way to tag commits with meta data,
      like automated build results.
    name: Commit statuses
  - description: |
      The SSH resource allows you to manage SSH keys.
    name: Ssh
  - description: Access the list of download links associated with the repository.
    name: Downloads
  - description: |-
      Browse the source code in the repository and
                                    create new commits by uploading.
    name: Source
  - description: |
      The users resource allows you to access public information
      associated with a user account. Most resources in the users
      endpoint have been deprecated in favor of workspaces.
    name: Users
  - name: Search
  - description: |
      The teams resource has been deprecated, and the workspaces
      endpoint should be used instead.

      The teams resource returns all the teams that the authenticated
      user is associated with.
    name: Teams
  - description: |
      The wiki is a simple place to keep documents. Some people use it
      as their project home page. The wiki is a Git repository, so you
      can clone it and edit it like any other source files.
    name: Wiki
paths:
  /addon:
    delete:
      tags:
        - Addon
      summary: Delete an app
      operationId: Addon_deleteUserApp
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Deletes the application for the user.

        This endpoint is intended to be used by Bitbucket Connect apps
        and only supports JWT authentication -- that is how Bitbucket
        identifies the particular installation of the app. Developers
        with applications registered in the "Develop Apps" section
        of Bitbucket Marketplace need not use this endpoint as
        updates for those applications can be sent out via the
        UI of that section.

        ```
        $ curl -X DELETE https://api.bitbucket.org/2.0/addon \
          -H "Authorization: JWT <JWT Token>"
        ```
    put:
      tags:
        - Addon
      summary: Update an installed app
      operationId: Addon_updateAppInstallation
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Updates the application installation for the user.

        This endpoint is intended to be used by Bitbucket Connect apps
        and only supports JWT authentication -- that is how Bitbucket
        identifies the particular installation of the app. Developers
        with applications registered in the "Develop Apps" section
        of Bitbucket need not use this endpoint as updates for those
        applications can be sent out via the UI of that section.

        Passing an empty body will update the installation using the
        existing descriptor URL.

        ```
        $ curl -X PUT https://api.bitbucket.org/2.0/addon \
          -H "Authorization: JWT <JWT Token>" \
          --header "Content-Type: application/json" \
          --data '{}'
        ```

        The new `descriptor` for the installation can be also provided
        in the body directly.

        ```
        $ curl -X PUT https://api.bitbucket.org/2.0/addon \
          -H "Authorization: JWT <JWT Token>" \
          --header "Content-Type: application/json" \
          --data '{"descriptor": $NEW_DESCRIPTOR}'
        ```

        In both these modes the URL of the descriptor cannot be changed. To
        change the descriptor location and upgrade an installation
        the request must be made exclusively with a `descriptor_url`.

         ```
        $ curl -X PUT https://api.bitbucket.org/2.0/addon \
          -H "Authorization: JWT <JWT Token>" \
          --header "Content-Type: application/json" \
          --data '{"descriptor_url": $NEW_URL}'
        ```

        The `descriptor_url` must exactly match the marketplace registration
        that Atlassian has for the application. Contact your Atlassian
        developer advocate to update this registration. Once the registration
        has been updated you may call this resource for each installation.

        Note that the scopes of the application cannot be increased
        in the new descriptor nor reduced to none.
  /addon/linkers:
    get:
      tags:
        - Addon
      summary: List linkers for an app
      operationId: Addon_listLinkers
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Gets a list of all [linkers](https://dac-static.atlassian.com)
        for the authenticated application.
  /addon/linkers/{linker_key}:
    get:
      tags:
        - Addon
      summary: Get a linker for an app
      operationId: Addon_getLinker
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Gets a [linker](https://dac-static.atlassian.com) specified by
        `linker_key`

        for the authenticated application.
  /addon/linkers/{linker_key}/values:
    delete:
      tags:
        - Addon
      summary: Delete all linker values
      operationId: Addon_deleteLinkerValues
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Delete all [linker](https://dac-static.atlassian.com) values for the
        specified linker of the authenticated application.
    get:
      tags:
        - Addon
      summary: List linker values for a linker
      operationId: Addon_listLinkerValues
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Gets a list of all [linker](https://dac-static.atlassian.com) values for
        the

        specified linker of the authenticated application.


        A linker value lets applications supply values to modify its regular
        expression.


        The base regular expression must use a Bitbucket-specific match group
        `(?K)`

        which will be translated to `([\w\-]+)`. A value must match this
        pattern.


        [Read more about linker
        values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)
    post:
      tags:
        - Addon
      summary: Create a linker value
      operationId: Addon_createLinkerValue
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Creates a [linker](https://dac-static.atlassian.com) value for the
        specified

        linker of authenticated application.


        A linker value lets applications supply values to modify its regular
        expression.


        The base regular expression must use a Bitbucket-specific match group
        `(?K)`

        which will be translated to `([\w\-]+)`. A value must match this
        pattern.


        [Read more about linker
        values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)
    put:
      tags:
        - Addon
      summary: Update a linker value
      operationId: Addon_updateLinkerValues
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Bulk update [linker](https://dac-static.atlassian.com) values for the
        specified

        linker of the authenticated application.


        A linker value lets applications supply values to modify its regular
        expression.


        The base regular expression must use a Bitbucket-specific match group
        `(?K)`

        which will be translated to `([\w\-]+)`. A value must match this
        pattern.


        [Read more about linker
        values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)
  /addon/linkers/{linker_key}/values/{value_id}:
    delete:
      tags:
        - Addon
      summary: Delete a linker value
      operationId: Addon_deleteLinkerValue
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Delete a single [linker](https://dac-static.atlassian.com) value
        of the authenticated application.
    get:
      tags:
        - Addon
      summary: Get a linker value
      operationId: Addon_getLinkerValue
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Get a single [linker](https://dac-static.atlassian.com) value
        of the authenticated application.
  /hook_events:
    get:
      tags:
        - Webhooks
      summary: Get a webhook resource
      operationId: Webhooks_getResourceEvents
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: |-
        Returns the webhook resource or subject types on which webhooks can
        be registered.

        Each resource/subject type contains an `events` link that returns the
        paginated list of specific events each individual subject type can
        emit.

        This endpoint is publicly accessible and does not require
        authentication or scopes.
  /hook_events/{subject_type}:
    get:
      tags:
        - Webhooks
      summary: List subscribable webhook types
      operationId: Webhooks_listSubscribableTypes
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of all valid webhook events for the

        specified entity.

        **The team and user webhooks are deprecated, and you should use
        workspace instead.

        For more information, see [the
        announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**


        This is public data that does not require any scopes or authentication.


        NOTE: The example response is a truncated response object for the
        `workspace` `subject_type`.

        We return the same structure for the other `subject_type` objects.
  /pullrequests/{selected_user}:
    get:
      tags:
        - Pullrequests
      summary: List pull requests for a user
      operationId: Pullrequests_listForUser
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns all pull requests authored by the specified user.


        By default only open pull requests are returned. This can be controlled

        using the `state` query parameter. To retrieve pull requests that are

        in one of multiple states, repeat the `state` parameter for each

        individual state.


        This endpoint also supports filtering and sorting of the results. See

        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
  /repositories:
    get:
      tags:
        - Repositories
      summary: List public repositories
      operationId: Repositories_listPublicRepositories
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of all public repositories.


        This endpoint also supports filtering and sorting of the results. See

        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
  /repositories/{workspace}:
    get:
      tags:
        - Repositories
      summary: List repositories in a workspace
      operationId: Repositories_listInWorkspace
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of all repositories owned by the specified

        workspace.


        The result can be narrowed down based on the authenticated user's role.


        E.g. with `?role=contributor`, only those repositories that the

        authenticated user has write access to are returned (this includes any

        repo the user is an admin on, as that implies write access).


        This endpoint also supports filtering and sorting of the results. See

        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}:
    delete:
      tags:
        - Repositories
      summary: Delete a repository
      operationId: Repositories_deleteRepository
      security:
        - oauth2:
            - repository:delete
        - basic: []
        - api_key: []
      description: |-
        Deletes the repository. This is an irreversible operation.

        This does not affect its forks.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - delete:repository:bitbucket
    get:
      tags:
        - Repositories
      summary: Get a repository
      operationId: Repositories_getRepositoryDetails
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns the object describing this repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Repositories
      summary: Create a repository
      operationId: Repositories_createRepo
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Creates a new repository.


        Note: In order to set the project for the newly created repository,

        pass in either the project key or the project UUID as part of the

        request body as shown in the examples below:


        ```

        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "MARS"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding

        ```


        or


        ```

        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "{ba516952-992a-4c2d-acbd-17d502922f96}"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding

        ```


        The project must be assigned for all repositories. If the project is not
        provided,

        the repository is automatically assigned to the oldest project in the
        workspace.


        Note: In the examples above, the workspace ID `teamsinspace`,

        and/or the repository name `hablanding` can be replaced by UUIDs.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    put:
      tags:
        - Repositories
      summary: Update a repository
      operationId: Repositories_createOrUpdate
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: |-
        Since this endpoint can be used to both update and to create a
        repository, the request body depends on the intent.

        #### Creation

        See the POST documentation for the repository endpoint for an example
        of the request body.

        #### Update

        Note: Changing the `name` of the repository will cause the location to
        be changed. This is because the URL of the repo is derived from the
        name (a process called slugification). In such a scenario, it is
        possible for the request to fail if the newly created slug conflicts
        with an existing repository's slug. But if there is no conflict,
        the new location will be returned in the `Location` header of the
        response.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/branch-restrictions:
    get:
      tags:
        - Branch restrictions
      summary: List branch restrictions
      operationId: BranchRestrictions_listBranchRestrictions
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: |-
        Returns a paginated list of all branch restrictions on the
        repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    post:
      tags:
        - Branch restrictions
      summary: Create a branch restriction rule
      operationId: BranchRestrictions_createRule
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Creates a new branch restriction rule for a repository.


        `kind` describes what will be restricted. Allowed values include:

        `push`, `force`, `delete`, `restrict_merges`,
        `require_tasks_to_be_completed`,

        `require_approvals_to_merge`,
        `require_default_reviewer_approvals_to_merge`,

        `require_no_changes_requested`, `require_passing_builds_to_merge`,
        `require_commits_behind`,

        `reset_pullrequest_approvals_on_change`,
        `smart_reset_pullrequest_approvals`,

        `reset_pullrequest_changes_requested_on_change`,
        `require_all_dependencies_merged`,

        `enforce_merge_checks`, and `allow_auto_merge_when_builds_pass`.


        Different kinds of branch restrictions have different requirements:


        * `push` and `restrict_merges` require `users` and `groups` to be
          specified. Empty lists are allowed, in which case permission is
          denied for everybody.

        The restriction applies to all branches that match. There are

        two ways to match a branch. It is configured in `branch_match_kind`:


        1. `glob`: Matches a branch against the `pattern`. A `'*'` in
           `pattern` will expand to match zero or more characters, and every
           other character matches itself. For example, `'foo*'` will match
           `'foo'` and `'foobar'`, but not `'barfoo'`. `'*'` will match all
           branches.
        2. `branching_model`: Matches a branch against the repository's
           branching model. The `branch_type` controls the type of branch
           to match. Allowed values include: `production`, `development`,
           `bugfix`, `release`, `feature` and `hotfix`.

        The combination of `kind` and match must be unique. This means that

        two `glob` restrictions in a repository cannot have the same `kind` and

        `pattern`. Additionally, two `branching_model` restrictions in a

        repository cannot have the same `kind` and `branch_type`.


        `users` and `groups` are lists of users and groups that are except from

        the restriction. They can only be configured in `push` and

        `restrict_merges` restrictions. The `push` restriction stops a user

        pushing to matching branches unless that user is in `users` or is a

        member of a group in `groups`. The `restrict_merges` stops a user

        merging pull requests to matching branches unless that user is in

        `users` or is a member of a group in `groups`. Adding new users or

        groups to an existing restriction should be done via `PUT`.


        Note that branch restrictions with overlapping matchers is allowed,

        but the resulting behavior may be surprising.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/branch-restrictions/{id}:
    delete:
      tags:
        - Branch restrictions
      summary: Delete a branch restriction rule
      operationId: BranchRestrictions_deleteRule
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: Deletes an existing branch restriction rule.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    get:
      tags:
        - Branch restrictions
      summary: Get a branch restriction rule
      operationId: BranchRestrictions_getRule
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: Returns a specific branch restriction rule.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    put:
      tags:
        - Branch restrictions
      summary: Update a branch restriction rule
      operationId: BranchRestrictions_updateRule
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Updates an existing branch restriction rule.


        Fields not present in the request body are ignored.


        See
        [`POST`](/cloud/bitbucket/rest/api-group-branch-restrictions/#api-repositories-workspace-repo-slug-branch-restrictions-post)
        for details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/branching-model:
    get:
      tags:
        - Branching model
      summary: Get the branching model for a repository
      operationId: BranchingModel_getBranchingModel
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Return the branching model as applied to the repository. This view is
        read-only. The branching model settings can be changed using the
        [settings](https://dac-static.atlassian.com) API.

        The returned object:

        1. Always has a `development` property. `development.branch` contains
           the actual repository branch object that is considered to be the
           `development` branch. `development.branch` will not be present
           if it does not exist.
        2. Might have a `production` property. `production` will not
           be present when `production` is disabled.
           `production.branch` contains the actual branch object that is
           considered to be the `production` branch. `production.branch` will
           not be present if it does not exist.
        3. Always has a `branch_types` array which contains all enabled branch
           types.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/branching-model/settings:
    get:
      tags:
        - Branching model
      summary: Get the branching model config for a repository
      operationId: BranchingModel_getRepositoryBranchingSettings
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Return the branching model configuration for a repository. The returned

        object:


        1. Always has a `development` property for the development branch.

        2. Always a `production` property for the production branch. The
           production branch can be disabled.
        3. The `branch_types` contains all the branch types.


        This is the raw configuration for the branching model. A client

        wishing to see the branching model with its actual current branches may

        find the [active model
        API](/cloud/bitbucket/rest/api-group-branching-model/#api-repositories-workspace-repo-slug-branching-model-get)
        more useful.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    put:
      tags:
        - Branching model
      summary: Update the branching model config for a repository
      operationId: BranchingModel_updateConfig
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: |-
        Update the branching model configuration for a repository.

        The `development` branch can be configured to a specific branch or to
        track the main branch. When set to a specific branch it must
        currently exist. Only the passed properties will be updated. The
        properties not passed will be left unchanged. A request without a
        `development` property will leave the development branch unchanged.

        It is possible for the `development` branch to be invalid. This
        happens when it points at a specific branch that has been
        deleted. This is indicated in the `is_valid` field for the branch. It is
        not possible to update the settings for `development` if that
        would leave the branch in an invalid state. Such a request will be
        rejected.

        The `production` branch can be a specific branch, the main
        branch or disabled. When set to a specific branch it must currently
        exist. The `enabled` property can be used to enable (`true`) or
        disable (`false`) it. Only the passed properties will be updated. The
        properties not passed will be left unchanged. A request without a
        `production` property will leave the production branch unchanged.

        It is possible for the `production` branch to be invalid. This
        happens when it points at a specific branch that has been
        deleted. This is indicated in the `is_valid` field for the branch. A
        request that would leave `production` enabled and invalid will be
        rejected. It is possible to update `production` and make it invalid if
        it would also be left disabled.

        The `branch_types` property contains the branch types to be updated.
        Only the branch types passed will be updated. All updates will be
        rejected if it would leave the branching model in an invalid state.
        For branch types this means that:

        1. The prefixes for all enabled branch types are valid. For example,
           it is not possible to use '*' inside a Git prefix.
        2. A prefix of an enabled branch type must not be a prefix of another
           enabled branch type. This is to ensure that a branch can be easily
           classified by its prefix unambiguously.

        It is possible to store an invalid prefix if that branch type would be
        left disabled. Only the passed properties will be updated. The
        properties not passed will be left unchanged. Each branch type must
        have a `kind` property to identify it.

        There is currently a side effect when using this API endpoint. If the
        repository is inheriting branching model settings from its project,
        updating the branching model for this repository will disable the
        project setting inheritance.


        We have deprecated this side effect and will remove it on 1 August 2022.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}:
    get:
      tags:
        - Commits
      summary: Get a commit
      operationId: Commits_getCommitDetails
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns the specified commit.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/approve:
    delete:
      tags:
        - Commits
      summary: Unapprove a commit
      operationId: Commits_unapproveCommit
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Redact the authenticated user's approval of the specified commit.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
    post:
      tags:
        - Commits
      summary: Approve a commit
      operationId: Commits_approveCommit
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Approve the specified commit as the authenticated user.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - write:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/comments:
    get:
      tags:
        - Commits
      summary: List a commit's comments
      operationId: Commits_listComments
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Returns the commit's comments.

        This includes both global and inline comments.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Commits
      summary: Create comment for a commit
      operationId: Commits_createComment
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Creates new comment on the specified commit.


        To post a reply to an existing comment, include the `parent.id` field:


        ```

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/db9ba1e031d07a02603eae0e559a7adc010257fc/comments/
        \
          -X POST -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "One more thing!"},
               "parent": {"id": 5728901}}'
        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/comments/{comment_id}:
    delete:
      tags:
        - Commits
      summary: Delete a commit comment
      operationId: Commits_deleteComment
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Deletes the specified commit comment.


        Note that deleting comments that have visible replies that point to

        them will not really delete the resource. This is to retain the
        integrity

        of the original comment tree. Instead, the `deleted` element is set to

        `true` and the content is blanked out. The comment will continue to be

        returned by the collections and self endpoints.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    get:
      tags:
        - Commits
      summary: Get a commit comment
      operationId: Commits_getCommitComment
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns the specified commit comment.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    put:
      tags:
        - Commits
      summary: Update a commit comment
      operationId: Commits_updateComment
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Used to update the contents of a comment. Only the content of the
        comment can be updated.


        ```

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/7f71b5/comments/5728901
        \
          -X PUT -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "One more thing!"}'
        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/properties/{app_key}/{property_name}:
    put:
      tags:
        - properties
      summary: Update a commit application property
      operationId: Properties_updateCommitApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Update an [application property](https://dac-static.atlassian.com) value
        stored against a commit.
    delete:
      tags:
        - properties
      summary: Delete a commit application property
      operationId: Properties_deleteCommitApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Delete an [application property](https://dac-static.atlassian.com) value
        stored against a commit.
    get:
      tags:
        - properties
      summary: Get a commit application property
      operationId: Properties_getValue
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Retrieve an [application property](https://dac-static.atlassian.com)
        value stored against a commit.
  /repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests:
    get:
      tags:
        - Pullrequests
      summary: List pull requests that contain a commit
      operationId: Pullrequests_listContainingCommit
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of all pull requests as part of which this
        commit was reviewed. Pull Request Commit Links app must be installed
        first before using this API; installation automatically occurs when 'Go
        to pull request' is clicked from the web interface for a commit's
        details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports:
    get:
      tags:
        - Reports
        - Commits
      summary: List reports
      operationId: Reports_listLinkedReports
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns a paginated list of Reports linked to this commit.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}:
    put:
      tags:
        - Reports
        - Commits
      summary: Create or update a report
      operationId: Reports_commitReportCreateOrUpdate
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: "Creates or updates a report for the specified commit.\nTo upload a report, make sure to generate an ID that is unique across all reports for that commit. If you want to use an existing id from your own system, we recommend prefixing it with your system's name to avoid collisions, for example, mySystem-001.\n\n### Sample cURL request:\n```\ncurl --request PUT 'https://api.bitbucket.org/2.0/repositories/<username>/<reposity-name>/commit/<commit-hash>/reports/mysystem-001' \\\n-[...]"
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    get:
      tags:
        - Reports
        - Commits
      summary: Get a report
      operationId: Reports_getSingleReport
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns a single Report matching the provided ID.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    delete:
      tags:
        - Reports
        - Commits
      summary: Delete a report
      operationId: Reports_deleteReport
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Deletes a single Report matching the provided ID.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations:
    get:
      tags:
        - Reports
        - Commits
      summary: List annotations
      operationId: Reports_listAnnotations
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns a paginated list of Annotations for a specified report.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Reports
        - Commits
      summary: Bulk create or update annotations
      operationId: Reports_bulkCreateOrUpdateAnnotations
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >
        Bulk upload of annotations.

        Annotations are individual findings that have been identified as part of
        a report, for example, a line of code that represents a vulnerability.
        These annotations can be attached to a specific file and even a specific
        line in that file, however, that is optional. Annotations are not
        mandatory and a report can contain up to 1000 annotations.


        Add the annotations you want to upload as objects in a JSON array and
        make sure each annotation has the external_id field set to a unique
        value. If you want to use an existing id from your own system, we
        recommend prefixing it with your system's name to avoid collisions, for
        example, mySystem-annotation001. The external id can later be used to
        identify the report as an alternative to the generated
        [UUID](https://developer.atlassian.com/bitbucket/api/2/reference/meta/uri-uuid#uuid).
        You can upload up to 100 annotations per POST request.


        ### Sample cURL request:

        ```

        curl --location
        'https://api.bitbucket.org/2.0/repositories/<username>/<reposity-name>/commit/<commit-hash>/reports/mysystem-001/annotations'
        \

        --header 'Content-Type: application/json' \

        --data-raw '[
          {
                "external_id": "mysystem-annotation001",
                "title": "Security scan report",
                "annotation_type": "VULNERABILITY",
                "summary": "This line represents a security threat.",
                "severity": "HIGH",
              "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Main.java",
                "line": 42
          },
          {
                "external_id": "mySystem-annotation002",
                "title": "Bug report",
                "annotation_type": "BUG",
                "result": "FAILED",
                "summary": "This line might introduce a bug.",
                "severity": "MEDIUM",
              "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Helper.java",
                "line": 13
          }
        ]'

        ```


        ### Possible field values:

        annotation_type: VULNERABILITY, CODE_SMELL, BUG

        result: PASSED, FAILED, IGNORED, SKIPPED

        severity: HIGH, MEDIUM, LOW, CRITICAL


        Please refer to the [Code Insights
        documentation](https://confluence.atlassian.com/bitbucket/code-insights-994316785.html)
        for more information.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations/{annotationId}:
    get:
      tags:
        - Reports
        - Commits
      summary: Get an annotation
      operationId: Reports_getAnnotation
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns a single Annotation matching the provided ID.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    put:
      tags:
        - Reports
        - Commits
      summary: Create or update an annotation
      operationId: Reports_commitAnnotations
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >
        Creates or updates an individual annotation for the specified report.

        Annotations are individual findings that have been identified as part of
        a report, for example, a line of code that represents a vulnerability.
        These annotations can be attached to a specific file and even a specific
        line in that file, however, that is optional. Annotations are not
        mandatory and a report can contain up to 1000 annotations.


        Just as reports, annotation needs to be uploaded with a unique ID that
        can later be used to identify the report as an alternative to the
        generated
        [UUID](https://developer.atlassian.com/bitbucket/api/2/reference/meta/uri-uuid#uuid).
        If you want to use an existing id from your own system, we recommend
        prefixing it with your system's name to avoid collisions, for example,
        mySystem-annotation001.


        ### Sample cURL request:

        ```

        curl --request PUT
        'https://api.bitbucket.org/2.0/repositories/<username>/<reposity-name>/commit/<commit-hash>/reports/mySystem-001/annotations/mysystem-annotation001'
        \

        --header 'Content-Type: application/json' \

        --data-raw '{
            "title": "Security scan report",
            "annotation_type": "VULNERABILITY",
            "summary": "This line represents a security thread.",
            "severity": "HIGH",
            "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Main.java",
            "line": 42
        }'

        ```


        ### Possible field values:

        annotation_type: VULNERABILITY, CODE_SMELL, BUG

        result: PASSED, FAILED, IGNORED, SKIPPED

        severity: HIGH, MEDIUM, LOW, CRITICAL


        Please refer to the [Code Insights
        documentation](https://confluence.atlassian.com/bitbucket/code-insights-994316785.html)
        for more information.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    delete:
      tags:
        - Reports
        - Commits
      summary: Delete an annotation
      operationId: Reports_deleteAnnotation
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Deletes a single Annotation matching the provided ID.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/statuses:
    get:
      tags:
        - Commit statuses
      summary: List commit statuses for a commit
      operationId: CommitStatuses_listForCommit
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns all statuses (e.g. build results) for a specific commit.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build:
    post:
      tags:
        - Commit statuses
      summary: Create a build status for a commit
      operationId: CommitStatuses_createBuildStatus
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Creates a new build status against the specified commit.


        If the specified key already exists, the existing status object will

        be overwritten.


        Example:


        ```

        curl
        https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo/commit/e10dae226959c2194f2b07b077c07762d93821cf/statuses/build/          
        -X POST -u jdoe -H 'Content-Type: application/json'           -d '{
            "key": "MY-BUILD",
            "state": "SUCCESSFUL",
            "description": "42 tests passed",
            "url": "https://www.example.org/my-build-result"
          }'
        ```


        When creating a new commit status, you can use a URI template for the
        URL.

        Templates are URLs that contain variable names that Bitbucket will

        evaluate at runtime whenever the URL is displayed anywhere similar to

        parameter substitution in

        [Bitbucket
        Connect](https://developer.atlassian.com/bitbucket/concepts/context-parameters.html).

        For example, one could use
        `https://foo.com/builds/{repository.full_name}`

        which Bitbucket will turn into `https://foo.com/builds/foo/bar` at
        render time.

        The context variables available are `repository` and `commit`.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build/{key}:
    get:
      tags:
        - Commit statuses
      summary: Get a build status for a commit
      operationId: CommitStatuses_getBuildStatus
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns the specified build status for a commit.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    put:
      tags:
        - Commit statuses
      summary: Update a build status for a commit
      operationId: CommitStatuses_updateBuildStatus
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Used to update the current status of a build status object on the
        specific commit.

        This operation can also be used to change other properties of the
        build status:

        * `state`
        * `name`
        * `description`
        * `url`
        * `refname`

        The `key` cannot be changed.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commits:
    get:
      tags:
        - Commits
      summary: List commits
      operationId: Commits_list
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        These are the repository's commits. They are paginated and returned

        in reverse chronological order, similar to the output of `git log`.

        Like these tools, the DAG can be filtered.


        #### GET /repositories/{workspace}/{repo_slug}/commits/


        Returns all commits in the repo in topological order (newest commit

        first). All branches and tags are included (similar to

        `git log --all`).


        #### GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master


        Returns all commits in the repo that are not on master

        (similar to `git log --all ^master`).


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar


        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or

        `fubar` (similar to `git log foo bar ^fu ^fubar`).


        An optional `path` parameter can be specified that will limit the

        results to commits that affect that path. `path` can either be a file

        or a directory. If a directory is specified, commits are returned that

        have modified any file in the directory tree rooted by `path`. It is

        important to note that if the `path` parameter is specified, the commits

        returned by this endpoint may no longer be a DAG, parent commits that

        do not modify the path will be omitted from the response.


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/?path=README.md&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `foo` or `bar`, but not on `master`

        that changed the file README.md.


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/?path=src/&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `foo` or `bar`, but not on `master`

        that changed to a file in any file in the directory src or its children.


        Because the response could include a very large number of commits, it

        is paginated. Follow the 'next' link in the response to navigate to the

        next page of commits. As with other paginated resources, do not

        construct your own links.


        When the include and exclude parameters are more than can fit in a

        query string, clients can use a `x-www-form-urlencoded` POST instead.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Commits
      summary: List commits with include/exclude
      operationId: Commits_listWithIncludeExclude
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,
        except that POST allows clients to place the include and exclude
        parameters in the request body to avoid URL length issues.

        **Note that this resource does NOT support new commit creation.**
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/commits/{revision}:
    get:
      tags:
        - Commits
      summary: List commits for revision
      operationId: Commits_listForRevision
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        These are the repository's commits. They are paginated and returned

        in reverse chronological order, similar to the output of `git log`.

        Like these tools, the DAG can be filtered.


        #### GET /repositories/{workspace}/{repo_slug}/commits/master


        Returns all commits on ref `master` (similar to `git log master`).


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/dev?include=foo&exclude=master


        Returns all commits on ref `dev` or `foo`, except those that are
        reachable on

        `master` (similar to `git log dev foo ^master`).


        An optional `path` parameter can be specified that will limit the

        results to commits that affect that path. `path` can either be a file

        or a directory. If a directory is specified, commits are returned that

        have modified any file in the directory tree rooted by `path`. It is

        important to note that if the `path` parameter is specified, the commits

        returned by this endpoint may no longer be a DAG, parent commits that

        do not modify the path will be omitted from the response.


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/dev?path=README.md&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `dev` or `foo` or `bar`, but not on
        `master`

        that changed the file README.md.


        #### GET
        /repositories/{workspace}/{repo_slug}/commits/dev?path=src/&include=foo&exclude=master


        Returns all commits that are on refs `dev` or `foo`, but not on `master`

        that changed to a file in any file in the directory src or its children.


        Because the response could include a very large number of commits, it

        is paginated. Follow the 'next' link in the response to navigate to the

        next page of commits. As with other paginated resources, do not

        construct your own links.


        When the include and exclude parameters are more than can fit in a

        query string, clients can use a `x-www-form-urlencoded` POST instead.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Commits
      summary: List commits for revision using include/exclude
      operationId: Commits_listForRevision
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Identical to `GET
        /repositories/{workspace}/{repo_slug}/commits/{revision}`,

        except that POST allows clients to place the include and exclude

        parameters in the request body to avoid URL length issues.


        **Note that this resource does NOT support new commit creation.**
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/components:
    get:
      tags:
        - Issue tracker
      summary: List components
      operationId: IssueTracker_listComponents
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: |-
        Returns the components that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
  /repositories/{workspace}/{repo_slug}/components/{component_id}:
    get:
      tags:
        - Issue tracker
      summary: Get a component for issues
      operationId: IssueTracker_getComponent
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: Returns the specified issue tracker component object.
  /repositories/{workspace}/{repo_slug}/default-reviewers:
    get:
      tags:
        - Pullrequests
      summary: List default reviewers
      operationId: Pullrequests_listDefaultReviewers
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns the repository's default reviewers.


        These are the users that are automatically added as reviewers on every

        new pull request that is created. To obtain the repository's default
        reviewers

        as well as the default reviewers inherited from the project, use the

        [effective-default-reveiwers](https://dac-static.atlassian.com)
        endpoint.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}:
    delete:
      tags:
        - Pullrequests
      summary: Remove a user from the default reviewers
      operationId: Pullrequests_removeDefaultReviewer
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: Removes a default reviewer from the repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    get:
      tags:
        - Pullrequests
      summary: Get a default reviewer
      operationId: Pullrequests_getDefaultReviewer
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: |-
        Returns the specified reviewer.

        This can be used to test whether a user is among the repository's
        default reviewers list. A 404 indicates that that specified user is not
        a default reviewer.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    put:
      tags:
        - Pullrequests
      summary: Add a user to the default reviewers
      operationId: Pullrequests_addUserToDefaultReviewers
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: |-
        Adds the specified user to the repository's list of default
        reviewers.

        This method is idempotent. Adding a user a second time has no effect.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/deploy-keys:
    get:
      tags:
        - Deployments
      summary: List repository deploy keys
      operationId: Deployments_listRepositoryDeployKeys
      security:
        - oauth2:
            - repository
            - repository:admin
        - basic: []
        - api_key: []
      description: Returns all deploy-keys belonging to a repository.
    post:
      tags:
        - Deployments
      summary: Add a repository deploy key
      operationId: Deployments_addRepositoryDeployKey
      security:
        - oauth2:
            - repository
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Create a new deploy key in a repository. Note: If authenticating a
        deploy key

        with an OAuth consumer, any changes to the OAuth consumer will
        subsequently

        invalidate the deploy key.



        Example:

        ```

        $ curl -X POST \

        -H "Authorization <auth header>" \

        -H "Content-type: application/json" \

        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys -d \

        '{
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5 mleu@C02W454JHTD8",
            "label": "mydeploykey"
        }'

        ```
  /repositories/{workspace}/{repo_slug}/deploy-keys/{key_id}:
    delete:
      tags:
        - Deployments
      summary: Delete a repository deploy key
      operationId: Deployments_repositoryKeyDelete
      security:
        - oauth2:
            - repository
            - repository:admin
        - basic: []
        - api_key: []
      description: This deletes a deploy key from a repository.
    get:
      tags:
        - Deployments
      summary: Get a repository deploy key
      operationId: Deployments_getDeployKey
      security:
        - oauth2:
            - repository
            - repository:admin
        - basic: []
        - api_key: []
      description: Returns the deploy key belonging to a specific key.
    put:
      tags:
        - Deployments
      summary: Update a repository deploy key
      operationId: Deployments_updateRepositoryDeployKey
      security:
        - oauth2:
            - repository
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Create a new deploy key in a repository.


        The same key needs to be passed in but the comment and label can change.


        Example:

        ```

        $ curl -X PUT \

        -H "Authorization <auth header>" \

        -H "Content-type: application/json" \

        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234 -d
        \

        '{
            "label": "newlabel",
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5 newcomment"
        }'

        ```
  /repositories/{workspace}/{repo_slug}/deployments:
    get:
      tags:
        - Deployments
      summary: List deployments
      operationId: Deployments_listDeployments
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find deployments
  /repositories/{workspace}/{repo_slug}/deployments/{deployment_uuid}:
    get:
      tags:
        - Deployments
      summary: Get a deployment
      operationId: Deployments_getSingleDeployment
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a deployment
  /repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables:
    get:
      tags:
        - Pipelines
      summary: List variables for an environment
      operationId: Pipelines_listEnvironmentVariables
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find deployment environment level variables.
    post:
      tags:
        - Pipelines
      summary: Create a variable for an environment
      operationId: Pipelines_createDeploymentEnvironmentVariable
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Create a deployment environment level variable.
  /repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables/{variable_uuid}:
    put:
      tags:
        - Pipelines
      summary: Update a variable for an environment
      operationId: Pipelines_updateEnvironmentVariable
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Update a deployment environment level variable.
    delete:
      tags:
        - Pipelines
      summary: Delete a variable for an environment
      operationId: Pipelines_deleteVariableForEnvironment
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Delete a deployment environment level variable.
  /repositories/{workspace}/{repo_slug}/diff/{spec}:
    get:
      tags:
        - Commits
      summary: Compare two commits
      operationId: Commits_compareTwoCommitsDiff
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Produces a raw git-style diff.


        #### Single commit spec


        If the `spec` argument to this API is a single commit, the diff is

        produced against the first parent of the specified commit.


        #### Two commit spec


        Two commits separated by `..` may be provided as the `spec`, e.g.,

        `3a8b42..9ff173`. When two commits are provided and the `topic` query

        parameter is true, this API produces a 2-way three dot diff.

        This is the diff between source commit and the merge base of the source

        commit and the destination commit. When the `topic` query param is
        false,

        a simple git-style diff is produced.


        The two commits are interpreted as follows:


        * First commit: the commit containing the changes we wish to preview

        * Second commit: the commit representing the state to which we want to
          compare the first commit
        * **Note**: This is the opposite of the order used in `git diff`.


        #### Comparison to patches


        While similar to patches, diffs:


        * Don't have a commit header (username, commit message, etc)

        * Support the optional `path=foo/bar.py` query param to filter
          the diff to just that one file diff

        #### Response


        The raw diff is returned as-is, in whatever encoding the files in the

        repository use. It is not decoded into unicode. As such, the

        content-type is `text/plain`.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/diffstat/{spec}:
    get:
      tags:
        - Commits
      summary: Compare two commit diff stats
      operationId: Commits_compareDiffStats
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Produces a response in JSON format with a record for every path

        modified, including information on the type of the change and the

        number of lines added and removed.


        #### Single commit spec


        If the `spec` argument to this API is a single commit, the diff is

        produced against the first parent of the specified commit.


        #### Two commit spec


        Two commits separated by `..` may be provided as the `spec`, e.g.,

        `3a8b42..9ff173`. When two commits are provided and the `topic` query

        parameter is true, this API produces a 2-way three dot diff.

        This is the diff between source commit and the merge base of the source

        commit and the destination commit. When the `topic` query param is
        false,

        a simple git-style diff is produced.


        The two commits are interpreted as follows:


        * First commit: the commit containing the changes we wish to preview

        * Second commit: the commit representing the state to which we want to
          compare the first commit
        * **Note**: This is the opposite of the order used in `git diff`.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/downloads:
    get:
      tags:
        - Downloads
      summary: List download artifacts
      operationId: Downloads_listArtifacts
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: Returns a list of download links associated with the repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Downloads
      summary: Upload a download artifact
      operationId: Downloads_uploadArtifact
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Upload new download artifacts.

        To upload files, perform a `multipart/form-data` POST containing one
        or more `files` fields:

            $ echo Hello World > hello.txt
            $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt

        When a file is uploaded with the same name as an existing artifact,
        then the existing file will be replaced.
  /repositories/{workspace}/{repo_slug}/downloads/{filename}:
    delete:
      tags:
        - Downloads
      summary: Delete a download artifact
      operationId: Downloads_deleteArtifact
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: Deletes the specified download artifact from the repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
    get:
      tags:
        - Downloads
      summary: Get a download artifact link
      operationId: Downloads_artifactLinkGet
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Return a redirect to the contents of a download artifact.

        This endpoint returns the actual file contents and not the artifact's
        metadata.

            $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt
            Hello World
  /repositories/{workspace}/{repo_slug}/effective-branching-model:
    get:
      tags:
        - Branching model
      summary: >-
        Get the effective, or currently applied, branching model for a
        repository
      operationId: BranchingModel_getEffectiveBranchingModel
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/effective-default-reviewers:
    get:
      tags:
        - Pullrequests
      summary: List effective default reviewers
      operationId: Pullrequests_listEffectiveDefaultReviewers
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns the repository's effective default reviewers. This includes both
        default

        reviewers defined at the repository level as well as those inherited
        from its project.


        These are the users that are automatically added as reviewers on every

        new pull request that is created.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/environments:
    get:
      tags:
        - Deployments
      summary: List environments
      operationId: Deployments_listEnvironments
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find environments
    post:
      tags:
        - Deployments
      summary: Create an environment
      operationId: Deployments_createEnvironment
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Create an environment.
  /repositories/{workspace}/{repo_slug}/environments/{environment_uuid}:
    get:
      tags:
        - Deployments
      summary: Get an environment
      operationId: Deployments_getEnvironment
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve an environment
    delete:
      tags:
        - Deployments
      summary: Delete an environment
      operationId: Deployments_deleteEnvironment
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Delete an environment
  /repositories/{workspace}/{repo_slug}/environments/{environment_uuid}/changes:
    post:
      tags:
        - Deployments
      summary: Update an environment
      operationId: Deployments_updateEnvironment
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Update an environment
  /repositories/{workspace}/{repo_slug}/filehistory/{commit}/{path}:
    get:
      tags:
        - Source
        - Repositories
      summary: List commits that modified a file
      operationId: Source_filehistoryListCommits
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of commits that modified the specified file.


        Commits are returned in reverse chronological order. This is roughly

        equivalent to the following commands:

            $ git log --follow --date-order <sha> <path>

        By default, Bitbucket will follow renames and the path name in the

        returned entries reflects that. This can be turned off using the

        `?renames=false` query parameter.


        Results are returned in descending chronological order by default, and

        like most endpoints you can

        [filter and sort](/cloud/bitbucket/rest/intro/#filtering) the response
        to

        only provide exactly the data you want.


        The example response returns commits made before 2011-05-18 against a
        file

        named `README.rst`. The results are filtered to only return the path and

        date. This request can be made using:


        ```

        $ curl
        'https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/filehistory/master/README.rst'\
          '?fields=values.next,values.path,values.commit.date&q=commit.date<=2011-05-18'
        ```


        In the response you can see that the file was renamed to `README.rst`

        by the commit made on 2011-05-16, and was previously named `README.txt`.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/forks:
    get:
      tags:
        - Repositories
      summary: List repository forks
      operationId: Repositories_listForks
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Returns a paginated list of all the forks of the specified
        repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Repositories
      summary: Fork a repository
      operationId: Repositories_forkRepository
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: >-
        Creates a new fork of the specified repository.


        #### Forking a repository


        To create a fork, specify the workspace explicitly as part of the

        request body:


        ```

        $ curl -X POST -u jdoe
        https://api.bitbucket.org/2.0/repositories/atlassian/bbql/forks \
          -H 'Content-Type: application/json' -d '{
            "name": "bbql_fork",
            "workspace": {
              "slug": "atlassian"
            }
        }'

        ```


        To fork a repository into the same workspace, also specify a new `name`.


        When you specify a value for `name`, it will also affect the `slug`.

        The `slug` is reflected in the repository URL of the new fork. It is

        derived from `name` by substituting non-ASCII characters, removes

        whitespace, and changes characters to lower case. For example,

        `My repo` would turn into `my_repo`.


        You need contributor access to create new forks within a workspace.



        #### Change the properties of a new fork


        By default the fork inherits most of its properties from the parent.

        However, since the optional POST body document follows the normal

        `repository` JSON schema and you can override the new fork's

        properties.


        Properties that can be overridden include:


        * description

        * fork_policy

        * language

        * mainbranch

        * is_private (note that a private repo's fork_policy might prohibit
          the creation of public forks, in which `is_private=False` would fail)
        * has_issues (to initialize or disable the new repo's issue tracker --
          note that the actual contents of the parent repository's issue
          tracker are not copied during forking)
        * has_wiki (to initialize or disable the new repo's wiki --
          note that the actual contents of the parent repository's wiki are not
          copied during forking)
        * project (when forking into a private project, the fork's `is_private`
          must be `true`)

        Properties that cannot be modified include:


        * scm

        * parent

        * full_name
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - write:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/hooks:
    get:
      tags:
        - Repositories
        - Webhooks
      summary: List webhooks for a repository
      operationId: Repositories_listWebhooks
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      description: Returns a paginated list of webhooks installed on this repository.
    post:
      tags:
        - Repositories
        - Webhooks
      summary: Create a webhook for a repository
      operationId: Repositories_createWebhook
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      description: >-
        Creates a new webhook on the specified repository.


        Example:


        ```

        $ curl -X POST -u credentials -H 'Content-Type: application/json'
          https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo-slug/hooks
          -d '
            {
              "description": "Webhook Description",
              "url": "https://example.com/",
              "active": true,
              "secret": "this is a really bad secret",
              "events": [
                "repo:push",
                "issue:created",
                "issue:updated"
              ]
            }'
        ```


        When the `secret` is provided it will be used as the key to generate a
        HMAC

        digest value sent in the `X-Hub-Signature` header at delivery time.
        Passing

        a `null` or empty `secret` or not passing a `secret` will leave the
        webhook's

        secret unset. Bitbucket only generates the `X-Hub-Signature` when the
        webhook's

        secret is set.


        Note that this call requires the webhook scope, as well as any scope

        that applies to the events that the webhook subscribes to. In the

        example above that means: `webhook`, `repository` and `issue`.


        Also note that the `url` must properly resolve and cannot be an

        internal, non-routed address.
  /repositories/{workspace}/{repo_slug}/hooks/{uid}:
    delete:
      tags:
        - Repositories
        - Webhooks
      summary: Delete a webhook for a repository
      operationId: Repositories_deleteWebhook
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      description: |-
        Deletes the specified webhook subscription from the given
        repository.
    get:
      tags:
        - Repositories
        - Webhooks
      summary: Get a webhook for a repository
      operationId: Repositories_getWebhookByUid
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      description: |-
        Returns the webhook with the specified id installed on the specified
        repository.
    put:
      tags:
        - Repositories
        - Webhooks
      summary: Update a webhook for a repository
      operationId: Repositories_updateWebhookSubscription
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      description: >-
        Updates the specified webhook subscription.


        The following properties can be mutated:


        * `description`

        * `url`

        * `secret`

        * `active`

        * `events`


        The hook's secret is used as a key to generate the HMAC hex digest sent
        in the

        `X-Hub-Signature` header at delivery time. This signature is only
        generated

        when the hook has a secret.


        Set the hook's secret by passing the new value in the `secret` field.
        Passing a

        `null` value in the `secret` field will remove the secret from the hook.
        The

        hook's secret can be left unchanged by not passing the `secret` field in
        the

        request.
  /repositories/{workspace}/{repo_slug}/issues:
    get:
      tags:
        - Issue tracker
      summary: List issues
      operationId: IssueTracker_listIssuesInWorkspace
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: Returns the issues in the issue tracker.
    post:
      tags:
        - Issue tracker
      summary: Create an issue
      operationId: IssueTracker_createNewIssue
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: |-
        Creates a new issue.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorization.

        The authenticated user is used for the issue's `reporter` field.
  /repositories/{workspace}/{repo_slug}/issues/export:
    post:
      tags:
        - Issue tracker
      summary: Export issues
      operationId: IssueTracker_initiateJob
      security:
        - oauth2:
            - issue
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        A POST request to this endpoint initiates a new background celery task
        that archives the repo's issues.


        When the job has been accepted, it will return a 202 (Accepted) along
        with a unique url to this job in the

        'Location' response header. This url is the endpoint for where the user
        can obtain their zip files."
  /repositories/{workspace}/{repo_slug}/issues/export/{repo_name}-issues-{task_id}.zip:
    get:
      tags:
        - Issue tracker
      summary: Check issue export status
      operationId: IssueTracker_checkExportStatus
      security:
        - oauth2:
            - issue
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        This endpoint is used to poll for the progress of an issue export

        job and return the zip file after the job is complete.

        As long as the job is running, this will return a 202 response

        with in the response body a description of the current status.


        After the job has been scheduled, but before it starts executing, the
        endpoint

        returns a 202 response with status `ACCEPTED`.


        Once it starts running, it is a 202 response with status `STARTED` and
        progress filled.


        After it is finished, it becomes a 200 response with status `SUCCESS` or
        `FAILURE`.
  /repositories/{workspace}/{repo_slug}/issues/import:
    get:
      tags:
        - Issue tracker
      summary: Check issue import status
      operationId: IssueTracker_checkImportStatus
      security:
        - oauth2:
            - issue:write
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        When using GET, this endpoint reports the status of the current import
        task.


        After the job has been scheduled, but before it starts executing, the
        endpoint

        returns a 202 response with status `ACCEPTED`.


        Once it starts running, it is a 202 response with status `STARTED` and
        progress filled.


        After it is finished, it becomes a 200 response with status `SUCCESS` or
        `FAILURE`.
    post:
      tags:
        - Issue tracker
      summary: Import issues
      operationId: IssueTracker_importIssuesFromZip
      security:
        - oauth2:
            - issue:write
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        A POST request to this endpoint will import the zip file given by the
        archive parameter into the repository. All

        existing issues will be deleted and replaced by the contents of the
        imported zip file.


        Imports are done through a multipart/form-data POST. There is one valid
        and required form field, with the name

        "archive," which needs to be a file field:


        ```

        $ curl -u <username> -X POST -F archive=@/path/to/file.zip
        https://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/issues/import

        ```
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}:
    delete:
      tags:
        - Issue tracker
      summary: Delete an issue
      operationId: IssueTracker_deleteIssue
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: |-
        Deletes the specified issue. This requires write access to the
        repository.
    get:
      tags:
        - Issue tracker
      summary: Get an issue
      operationId: IssueTracker_getIssueById
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: Returns the specified issue.
    put:
      tags:
        - Issue tracker
      summary: Update an issue
      operationId: IssueTracker_updateIssue
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: >-
        Modifies the issue.


        ```

        $ curl
        https://api.bitbucket.org/2.0/repostories/evzijst/dogslow/issues/123 \
          -u evzijst -s -X PUT -H 'Content-Type: application/json' \
          -d '{
          "title": "Updated title",
          "assignee": {
            "account_id": "5d5355e8c6b9320d9ea5b28d"
          },
          "priority": "minor",
          "version": {
            "name": "1.0"
          },
          "component": null
        }'

        ```


        This example changes the `title`, `assignee`, `priority` and the

        `version`. It also removes the value of the `component` from the issue

        by setting the field to `null`. Any field not present keeps its existing

        value.


        Each time an issue is edited in the UI or through the API, an immutable

        change record is created under the `/issues/123/changes` endpoint. It

        also has a comment associated with the change.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments:
    get:
      tags:
        - Issue tracker
      summary: List attachments for an issue
      operationId: IssueTracker_listAttachmentsForIssue
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: |-
        Returns all attachments for this issue.

        This returns the files' meta data. This does not return the files'
        actual contents.

        The files are always ordered by their upload date.
    post:
      tags:
        - Issue tracker
      summary: Upload an attachment to an issue
      operationId: IssueTracker_uploadAttachment
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: |-
        Upload new issue attachments.

        To upload files, perform a `multipart/form-data` POST containing one
        or more file fields.

        When a file is uploaded with the same name as an existing attachment,
        then the existing file will be replaced.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments/{path}:
    delete:
      tags:
        - Issue tracker
      summary: Delete an attachment for an issue
      operationId: IssueTracker_deleteAttachment
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: Deletes an attachment.
    get:
      tags:
        - Issue tracker
      summary: Get attachment for an issue
      operationId: IssueTracker_getAttachmentContents
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: |-
        Returns the contents of the specified file attachment.

        Note that this endpoint does not return a JSON response, but instead
        returns a redirect pointing to the actual file that in turn will return
        the raw contents.

        The redirect URL contains a one-time token that has a limited lifetime.
        As a result, the link should not be persisted, stored, or shared.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes:
    get:
      tags:
        - Issue tracker
      summary: List changes on an issue
      operationId: IssueTracker_listIssueChanges
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: >-
        Returns the list of all changes that have been made to the specified

        issue. Changes are returned in chronological order with the oldest

        change first.


        Each time an issue is edited in the UI or through the API, an immutable

        change record is created under the `/issues/123/changes` endpoint. It

        also has a comment associated with the change.


        Note that this operation is changing significantly, due to privacy
        changes.

        See the
        [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-the-issue-changes-api)

        for details.


        Changes support [filtering and
        sorting](/cloud/bitbucket/rest/intro/#filtering) that

        can be used to search for specific changes. For instance, to see

        when an issue transitioned to "resolved":


        ```

        $ curl -s
        https://api.bitbucket.org/2.0/repositories/site/master/issues/1/changes
        \
           -G --data-urlencode='q=changes.state.new = "resolved"'
        ```


        This resource is only available on repositories that have the issue

        tracker enabled.


        N.B.


        The `changes.assignee` and `changes.assignee_account_id` fields are not

        a `user` object. Instead, they contain the raw `username` and

        `account_id` of the user. This is to protect the integrity of the audit

        log even after a user account gets deleted.


        The `changes.assignee` field is deprecated will disappear in the

        future. Use `changes.assignee_account_id` instead.
    post:
      tags:
        - Issue tracker
      summary: Modify the state of an issue
      operationId: IssueTracker_modifyIssueState
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: |-
        Makes a change to the specified issue.

        For example, to change an issue's state and assignee, create a new
        change object that modifies these fields:

        ```
        curl https://api.bitbucket.org/2.0/site/master/issues/1234/changes \
          -s -u evzijst -X POST -H "Content-Type: application/json" \
          -d '{
            "changes": {
              "assignee_account_id": {
                "new": "557058:c0b72ad0-1cb5-4018-9cdc-0cde8492c443"
              },
              "state": {
                "new": 'resolved"
              }
            }
            "message": {
              "raw": "This is now resolved."
            }
          }'
        ```

        The above example also includes a custom comment to go alongside the
        change. This comment will also be visible on the issue page in the UI.

        The fields of the `changes` object are strings, not objects. This
        allows for immutable change log records, even after user accounts,
        milestones, or other objects recorded in a change entry, get renamed or
        deleted.

        The `assignee_account_id` field stores the account id. When POSTing a
        new change and changing the assignee, the client should therefore use
        the user's account_id in the `changes.assignee_account_id.new` field.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorization.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes/{change_id}:
    get:
      tags:
        - Issue tracker
      summary: Get issue change object
      operationId: IssueTracker_getIssueChange
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: |-
        Returns the specified issue change object.

        This resource is only available on repositories that have the issue
        tracker enabled.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments:
    get:
      tags:
        - Issue tracker
      summary: List comments on an issue
      operationId: IssueTracker_listCommentsOnIssue
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of all comments that were made on the

        specified issue.


        The default sorting is oldest to newest and can be overridden with

        the `sort` query parameter.


        This endpoint also supports filtering and sorting of the results. See

        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
    post:
      tags:
        - Issue tracker
      summary: Create a comment on an issue
      operationId: IssueTracker_createCommentOnIssue
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: >-
        Creates a new issue comment.


        ```

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/
        \
          -X POST -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}}'
        ```
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments/{comment_id}:
    delete:
      tags:
        - Issue tracker
      summary: Delete a comment on an issue
      operationId: IssueTracker_deleteComment
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: Deletes the specified comment.
    get:
      tags:
        - Issue tracker
      summary: Get a comment on an issue
      operationId: IssueTracker_getComment
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: Returns the specified issue comment object.
    put:
      tags:
        - Issue tracker
      summary: Update a comment on an issue
      operationId: IssueTracker_updateIssueCommentContent
      security:
        - oauth2:
            - issue:write
        - basic: []
        - api_key: []
      description: >-
        Updates the content of the specified issue comment. Note that only

        the `content.raw` field can be modified.


        ```

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/5728901
        \
          -X PUT -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}'
        ```
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/vote:
    delete:
      tags:
        - Issue tracker
      summary: Remove vote for an issue
      operationId: IssueTracker_removeVote
      security:
        - oauth2:
            - account:write
            - issue:write
        - basic: []
        - api_key: []
      description: Retract your vote.
    get:
      tags:
        - Issue tracker
      summary: Check if current user voted for an issue
      operationId: IssueTracker_checkUserVoted
      security:
        - oauth2:
            - account
            - issue
        - basic: []
        - api_key: []
      description: |-
        Check whether the authenticated user has voted for this issue.
        A 204 status code indicates that the user has voted, while a 404
        implies they haven't.
    put:
      tags:
        - Issue tracker
      summary: Vote for an issue
      operationId: IssueTracker_voteForIssue
      security:
        - oauth2:
            - account:write
            - issue
        - basic: []
        - api_key: []
      description: |-
        Vote for this issue.

        To cast your vote, do an empty PUT. The 204 status code indicates that
        the operation was successful.
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/watch:
    delete:
      tags:
        - Issue tracker
      summary: Stop watching an issue
      operationId: IssueTracker_stopWatchingIssue
      security:
        - oauth2:
            - account:write
            - issue:write
        - basic: []
        - api_key: []
      description: Stop watching this issue.
    get:
      tags:
        - Issue tracker
      summary: Check if current user is watching a issue
      operationId: IssueTracker_checkIfWatchingIssue
      security:
        - oauth2:
            - account
            - issue
        - basic: []
        - api_key: []
      description: |-
        Indicated whether or not the authenticated user is watching this
        issue.
    put:
      tags:
        - Issue tracker
      summary: Watch an issue
      operationId: IssueTracker_watchIssue
      security:
        - oauth2:
            - account:write
            - issue
        - basic: []
        - api_key: []
      description: |-
        Start watching this issue.

        To start watching this issue, do an empty PUT. The 204 status code
        indicates that the operation was successful.
  /repositories/{workspace}/{repo_slug}/merge-base/{revspec}:
    get:
      tags:
        - Commits
      summary: Get the common ancestor between two commits
      operationId: Commits_getMergeBase
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns the best common ancestor between two commits, specified in a
        revspec

        of 2 commits (e.g. 3a8b42..9ff173).


        If more than one best common ancestor exists, only one will be returned.
        It is

        unspecified which will be returned.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/milestones:
    get:
      tags:
        - Issue tracker
      summary: List milestones
      operationId: IssueTracker_listMilestones
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: |-
        Returns the milestones that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
  /repositories/{workspace}/{repo_slug}/milestones/{milestone_id}:
    get:
      tags:
        - Issue tracker
      summary: Get a milestone
      operationId: IssueTracker_getMilestone
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      description: Returns the specified issue tracker milestone object.
  /repositories/{workspace}/{repo_slug}/override-settings:
    get:
      tags:
        - Repositories
      summary: Retrieve the inheritance state for repository settings
      operationId: Repositories_inheritanceStateGet
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    put:
      tags:
        - Repositories
      summary: |-
        Set the inheritance state for repository settings
                        
      operationId: Repositories_setInheritanceState
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/patch/{spec}:
    get:
      tags:
        - Commits
      summary: Get a patch for two commits
      operationId: Commits_getPatchForCommits
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Produces a raw patch for a single commit (diffed against its first
        parent), or a patch-series for a revspec of 2 commits (e.g.
        `3a8b42..9ff173` where the first commit represents the source and the
        second commit the destination).

        In case of the latter (diffing a revspec), a patch series is returned
        for the commits on the source branch (`3a8b42` and its ancestors in
        our example).

        While similar to diffs, patches:

        * Have a commit header (username, commit message, etc)
        * Do not support the `path=foo/bar.py` query parameter

        The raw patch is returned as-is, in whatever encoding the files in the
        repository use. It is not decoded into unicode. As such, the
        content-type is `text/plain`.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/permissions-config/groups:
    get:
      tags:
        - Repositories
      summary: List explicit group permissions for a repository
      operationId: Repositories_listGroupPermissions
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of explicit group permissions for the given
        repository.

        This endpoint does not support BBQL features.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - read:user:bitbucket
  /repositories/{workspace}/{repo_slug}/permissions-config/groups/{group_slug}:
    delete:
      tags:
        - Repositories
      summary: Delete an explicit group permission for a repository
      operationId: Repositories_deleteGroupPermission
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Deletes the repository group permission between the requested repository
        and group, if one exists.


        Only users with admin permission for the repository may access this
        resource.
    get:
      tags:
        - Repositories
      summary: Get an explicit group permission for a repository
      operationId: Repositories_getGroupPermissions
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Returns the group permission for a given group slug and repository


        Only users with admin permission for the repository may access this
        resource.


        Permissions can be:


        * `admin`

        * `write`

        * `read`

        * `none`
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - read:user:bitbucket
    put:
      tags:
        - Repositories
      summary: Update an explicit group permission for a repository
      operationId: Repositories_updateGroupPermission
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Updates the group permission, or grants a new permission if one does not
        already exist.


        Only users with admin permission for the repository may access this
        resource.


        The only authentication method supported for this endpoint is via app
        passwords.


        Permissions can be:


        * `admin`

        * `write`

        * `read`
  /repositories/{workspace}/{repo_slug}/permissions-config/users:
    get:
      tags:
        - Repositories
      summary: List explicit user permissions for a repository
      operationId: Repositories_listUserPermissions
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of explicit user permissions for the given
        repository.

        This endpoint does not support BBQL features.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - read:user:bitbucket
  /repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}:
    delete:
      tags:
        - Repositories
      summary: Delete an explicit user permission for a repository
      operationId: Repositories_deleteUserPermission
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Deletes the repository user permission between the requested repository
        and user, if one exists.


        Only users with admin permission for the repository may access this
        resource.


        The only authentication method for this endpoint is via app passwords.
    get:
      tags:
        - Repositories
      summary: Get an explicit user permission for a repository
      operationId: Repositories_explicitUserPermission
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Returns the explicit user permission for a given user and repository.


        Only users with admin permission for the repository may access this
        resource.


        Permissions can be:


        * `admin`

        * `write`

        * `read`

        * `none`
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
            - read:user:bitbucket
    put:
      tags:
        - Repositories
      summary: Update an explicit user permission for a repository
      operationId: Repositories_updateUserPermission
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: >-
        Updates the explicit user permission for a given user and repository.
        The selected user must be a member of

        the workspace, and cannot be the workspace owner.

        Only users with admin permission for the repository may access this
        resource.


        The only authentication method for this endpoint is via app passwords.


        Permissions can be:


        * `admin`

        * `write`

        * `read`
  /repositories/{workspace}/{repo_slug}/pipelines:
    get:
      tags:
        - Pipelines
      summary: List pipelines
      operationId: Pipelines_list
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find pipelines
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    post:
      tags:
        - Pipelines
      summary: Run a pipeline
      operationId: Pipelines_createPipeline
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: >
        Endpoint to create and initiate a pipeline.

        There are a couple of different options to initiate a pipeline, where
        the payload of the request will determine which type of pipeline will be
        instantiated.

        # Trigger a Pipeline for a branch

        One way to trigger pipelines is by specifying the branch for which you
        want to trigger a pipeline.

        The specified branch will be used to determine which pipeline definition
        from the `bitbucket-pipelines.yml` file will be applied to initiate the
        pipeline. The pipeline will then do a clone of the repository and
        checkout the latest revision of the specified branch.


        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
          -d '
          {
            "target": {
              "ref_type": "branch",
              "type": "pipeline_ref_target",
              "ref_name": "master"
            }
          }'
        ```

        # Trigger a Pipeline for a commit on a branch or tag

        You can initiate a pipeline for a specific commit and in the context of
        a specified reference (e.g. a branch, tag or bookmark).

        The specified reference will be used to determine which pipeline
        definition from the bitbucket-pipelines.yml file will be applied to
        initiate the pipeline. The pipeline will clone the repository and then
        do a checkout the specified reference.


        The following reference types are supported:


        * `branch`

        * `named_branch`

        * `bookmark`
         * `tag`

        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
          https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
          -d '
          {
            "target": {
              "commit": {
                "type": "commit",
                "hash": "ce5b7431602f7cbba007062eeb55225c6e18e956"
              },
              "ref_type": "branch",
              "type": "pipeline_ref_target",
              "ref_name": "master"
            }
          }'
        ```

        # Trigger a specific pipeline definition for a commit

        You can trigger a specific pipeline that is defined in your
        `bitbucket-pipelines.yml` file for a specific commit.

        In addition to the commit revision, you specify the type and pattern of
        the selector that identifies the pipeline definition. The resulting
        pipeline will then clone the repository and checkout the specified
        revision.


        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
         -d '
          {
             "target": {
              "commit": {
                 "hash":"a3c4e02c9a3755eccdc3764e6ea13facdf30f923",
                 "type":"commit"
               },
                "selector": {
                   "type":"custom",
                      "pattern":"Deploy to production"
                  },
                "type":"pipeline_commit_target"
           }
          }'
        ```

        # Trigger a specific pipeline definition for a commit on a branch or tag

        You can trigger a specific pipeline that is defined in your
        `bitbucket-pipelines.yml` file for a specific commit in the context of a
        specified reference.

        In addition to the commit revision, you specify the type and pattern of
        the selector that identifies the pipeline definition, as well as the
        reference information. The resulting pipeline will then clone the
        repository a checkout the specified reference.


        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
         -d '
          {
             "target": {
              "commit": {
                 "hash":"a3c4e02c9a3755eccdc3764e6ea13facdf30f923",
                 "type":"commit"
               },
               "selector": {
                  "type": "custom",
                  "pattern": "Deploy to production"
               },
               "type": "pipeline_ref_target",
               "ref_name": "master",
               "ref_type": "branch"
             }
          }'
        ```



        # Trigger a custom pipeline with variables

        In addition to triggering a custom pipeline that is defined in your
        `bitbucket-pipelines.yml` file as shown in the examples above, you can
        specify variables that will be available for your build. In the request,
        provide a list of variables, specifying the following for each variable:
        key, value, and whether it should be secured or not (this field is
        optional and defaults to not secured).


        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/{workspace}/{repo_slug}/pipelines/ \
         -d '
          {
            "target": {
              "type": "pipeline_ref_target",
              "ref_type": "branch",
              "ref_name": "master",
              "selector": {
                "type": "custom",
                "pattern": "Deploy to production"
              }
            },
            "variables": [
              {
                "key": "var1key",
                "value": "var1value",
                "secured": true
              },
              {
                "key": "var2key",
                "value": "var2value"
              }
            ]
          }'
        ```


        # Trigger a pull request pipeline


        You can also initiate a pipeline for a specific pull request.


        ### Example


        ```

        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/{workspace}/{repo_slug}/pipelines/ \
         -d '
          {
            "target": {
              "type": "pipeline_pullrequest_target",
              "source": "pull-request-branch",
              "destination": "master",
              "destination_commit": {
                "hash": "9f848b7"
              },
              "commit": {
                "hash": "1a372fc"
              },
              "pullrequest": {
                "id": "3"
              },
              "selector": {
                "type": "pull-requests",
                "pattern": "**"
              }
            }
          }'
        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
            - write:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines-config/caches:
    get:
      tags:
        - Pipelines
      summary: List caches
      operationId: Pipelines_getCaches
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve the repository pipelines caches.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    delete:
      tags:
        - Pipelines
      summary: Delete caches
      operationId: Pipelines_deleteCacheVersionByName
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: Delete repository cache versions by name.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}:
    delete:
      tags:
        - Pipelines
      summary: Delete a cache
      operationId: Pipelines_deleteCacheById
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: Delete a repository cache.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}/content-uri:
    get:
      tags:
        - Pipelines
      summary: Get cache content URI
      operationId: Pipelines_getCacheContentUri
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve the URI of the content of the specified cache.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}:
    get:
      tags:
        - Pipelines
      summary: Get a pipeline
      operationId: Pipelines_getSpecifiedPipeline
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a specified pipeline
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps:
    get:
      tags:
        - Pipelines
      summary: List steps for a pipeline
      operationId: Pipelines_getPipelineSteps
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find steps for the given pipeline.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}:
    get:
      tags:
        - Pipelines
      summary: Get a step of a pipeline
      operationId: Pipelines_getStep
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a given step of a pipeline.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log:
    get:
      tags:
        - Pipelines
      summary: Get log file for a step
      operationId: Pipelines_getStepLog
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: >-
        Retrieve the log file for a given step of a pipeline.


        This endpoint supports (and encourages!) the use of [HTTP Range
        requests](https://tools.ietf.org/html/rfc7233) to deal with potentially
        very large log files.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/logs/{log_uuid}:
    get:
      tags:
        - Pipelines
      summary: >-
        Get the logs for the build container or a service container for a given
        step of a pipeline.
      operationId: Pipelines_getStepLogs
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: >-
        Retrieve the log file for a build container or service container.


        This endpoint supports (and encourages!) the use of [HTTP Range
        requests](https://tools.ietf.org/html/rfc7233) to deal with potentially
        very large log files.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports:
    get:
      tags:
        - Pipelines
      summary: Get a summary of test reports for a given step of a pipeline.
      operationId: Pipelines_getTestReportsForStep
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases:
    get:
      tags:
        - Pipelines
      summary: Get test cases for a given step of a pipeline.
      operationId: Pipelines_getTestCasesForStep
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases/{test_case_uuid}/test_case_reasons:
    get:
      tags:
        - Pipelines
      summary: >-
        Get test case reasons (output) for a given test case in a step of a
        pipeline.
      operationId: Pipelines_getTestCaseReasons
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline:
    post:
      tags:
        - Pipelines
      summary: Stop a pipeline
      operationId: Pipelines_stopPipeline
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: >-
        Signal the stop of a pipeline and all of its steps that not have
        completed yet.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config:
    get:
      tags:
        - Pipelines
      summary: Get configuration
      operationId: Pipelines_getConfiguration
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: Retrieve the repository pipelines configuration.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
    put:
      tags:
        - Pipelines
      summary: Update configuration
      operationId: Pipelines_updateConfiguration
      security:
        - oauth2:
            - repository:admin
        - basic: []
        - api_key: []
      description: Update the pipelines configuration for a repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/build_number:
    put:
      tags:
        - Pipelines
      summary: Update the next build number
      operationId: Pipelines_updateNextBuildNumber
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: >-
        Update the next build number that should be assigned to a pipeline. The
        next build number that will be configured has to be strictly higher than
        the current latest build number for this repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules:
    post:
      tags:
        - Pipelines
      summary: Create a schedule
      operationId: Pipelines_createSchedule
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: Create a schedule for the given repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
            - write:pipeline:bitbucket
    get:
      tags:
        - Pipelines
      summary: List schedules
      operationId: Pipelines_listSchedules
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve the configured schedules for the given repository.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}:
    get:
      tags:
        - Pipelines
      summary: Get a schedule
      operationId: Pipelines_getConfigSchedule
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a schedule by its UUID.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    put:
      tags:
        - Pipelines
      summary: Update a schedule
      operationId: Pipelines_updateSchedule
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: Update a schedule.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
            - write:pipeline:bitbucket
    delete:
      tags:
        - Pipelines
      summary: Delete a schedule
      operationId: Pipelines_deleteSchedule
      security:
        - oauth2:
            - pipeline:write
        - basic: []
        - api_key: []
      description: Delete a schedule.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}/executions:
    get:
      tags:
        - Pipelines
      summary: List executions of a schedule
      operationId: Pipelines_listScheduleExecutions
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve the executions of a given schedule.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/key_pair:
    get:
      tags:
        - Pipelines
      summary: Get SSH key pair
      operationId: Pipelines_getKeyPair
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: >-
        Retrieve the repository SSH key pair excluding the SSH private key. The
        private key is a write only field and will never be exposed in the logs
        or the REST API.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    put:
      tags:
        - Pipelines
      summary: Update SSH key pair
      operationId: Pipelines_updateSshKeyPair
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: >-
        Create or update the repository SSH key pair. The private key will be
        set as a default SSH identity in your build container.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
    delete:
      tags:
        - Pipelines
      summary: Delete SSH key pair
      operationId: Pipelines_deleteSshKeyPair
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Delete the repository SSH key pair.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts:
    get:
      tags:
        - Pipelines
      summary: List known hosts
      operationId: Pipelines_listKnownHosts
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find repository level known hosts.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    post:
      tags:
        - Pipelines
      summary: Create a known host
      operationId: Pipelines_createKnownHost
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Create a repository level known host.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}:
    get:
      tags:
        - Pipelines
      summary: Get a known host
      operationId: Pipelines_getKnownHost
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a repository level known host.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    put:
      tags:
        - Pipelines
      summary: Update a known host
      operationId: Pipelines_updateKnownHost
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Update a repository level known host.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
    delete:
      tags:
        - Pipelines
      summary: Delete a known host
      operationId: Pipelines_deleteKnownHost
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Delete a repository level known host.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/variables:
    get:
      tags:
        - Pipelines
      summary: List variables for a repository
      operationId: Pipelines_listRepositoryVariables
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Find repository level variables.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    post:
      tags:
        - Pipelines
      summary: Create a variable for a repository
      operationId: Pipelines_createVariable
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Create a repository level variable.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/pipelines_config/variables/{variable_uuid}:
    get:
      tags:
        - Pipelines
      summary: Get a variable for a repository
      operationId: Pipelines_getRepositoryVariable
      security:
        - oauth2:
            - pipeline
        - basic: []
        - api_key: []
      description: Retrieve a repository level variable.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pipeline:bitbucket
    put:
      tags:
        - Pipelines
      summary: Update a variable for a repository
      operationId: Pipelines_updateVariableForRepository
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Update a repository level variable.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
    delete:
      tags:
        - Pipelines
      summary: Delete a variable for a repository
      operationId: Pipelines_deleteVariable
      security:
        - oauth2:
            - pipeline:variable
        - basic: []
        - api_key: []
      description: Delete a repository level variable.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - admin:pipeline:bitbucket
  /repositories/{workspace}/{repo_slug}/properties/{app_key}/{property_name}:
    put:
      tags:
        - properties
      summary: Update a repository application property
      operationId: Properties_updateApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Update an [application property](https://dac-static.atlassian.com) value
        stored against a repository.
    delete:
      tags:
        - properties
      summary: Delete a repository application property
      operationId: Properties_deleteRepositoryApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Delete an [application property](https://dac-static.atlassian.com) value
        stored against a repository.
    get:
      tags:
        - properties
      summary: Get a repository application property
      operationId: Properties_getApplicationValue
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Retrieve an [application property](https://dac-static.atlassian.com)
        value stored against a repository.
  /repositories/{workspace}/{repo_slug}/pullrequests:
    get:
      tags:
        - Pullrequests
      summary: List pull requests
      operationId: Pullrequests_list
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns all pull requests on the specified repository.


        By default only open pull requests are returned. This can be controlled

        using the `state` query parameter. To retrieve pull requests that are

        in one of multiple states, repeat the `state` parameter for each

        individual state.


        This endpoint also supports filtering and sorting of the results. See

        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Create a pull request
      operationId: Pullrequests_create
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: >-
        Creates a new pull request where the destination repository is

        this repository and the author is the authenticated user.


        The minimum required fields to create a pull request are `title` and

        `source`, specified by a branch name.


        ```

        curl
        https://api.bitbucket.org/2.0/repositories/my-workspace/my-repository/pullrequests
        \
            -u my-username:my-password \
            --request POST \
            --header 'Content-Type: application/json' \
            --data '{
                "title": "My Title",
                "source": {
                    "branch": {
                        "name": "staging"
                    }
                }
            }'
        ```


        If the pull request's `destination` is not specified, it will default

        to the `repository.mainbranch`. To open a pull request to a

        different branch, say from a feature branch to a staging branch,

        specify a `destination` (same format as the `source`):


        ```

        {
            "title": "My Title",
            "source": {
                "branch": {
                    "name": "my-feature-branch"
                }
            },
            "destination": {
                "branch": {
                    "name": "staging"
                }
            }
        }

        ```


        Reviewers can be specified by adding an array of user objects as the

        `reviewers` property.


        ```

        {
            "title": "My Title",
            "source": {
                "branch": {
                    "name": "my-feature-branch"
                }
            },
            "reviewers": [
                {
                    "uuid": "{504c3b62-8120-4f0c-a7bc-87800b9d6f70}"
                }
            ]
        }

        ```


        Other fields:


        * `description` - a string

        * `close_source_branch` - boolean that specifies if the source branch
        should be closed upon merging
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/activity:
    get:
      tags:
        - Pullrequests
      summary: List a pull request activity log
      operationId: Pullrequests_listActivityLog
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of the pull request's activity log.


        This handler serves both a v20 and internal endpoint. The v20 endpoint

        returns reviewer comments, updates, approvals and request changes. The
        internal

        endpoint includes those plus tasks and attachments.


        Comments created on a file or a line of code have an inline property.


        Comment example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "comment": {
                        "deleted": false,
                        "pullrequest": {
                            "type": "pullrequest",
                            "id": 5695,
                            "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                        },
                        "content": {
                            "raw": "inline with to a dn from lines",
                            "markup": "markdown",
                            "html": "<p>inline with to a dn from lines</p>",
                            "type": "rendered"
                        },
                        "created_on": "2019-09-27T00:33:46.039178+00:00",
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "created_on": "2019-09-27T00:33:46.039178+00:00",
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "updated_on": "2019-09-27T00:33:46.055384+00:00",
                        "inline": {
                            "context_lines": "",
                            "to": null,
                            "path": "",
                            "outdated": false,
                            "from": 211
                        },
                        "type": "pullrequest_comment",
                        "id": 118571088
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```


        Updates include a state property of OPEN, MERGED, or DECLINED.


        Update example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "update": {
                        "description": "",
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it",
                        "destination": {
                            "commit": {
                                "type": "commit",
                                "hash": "6a2c16e4a152"
                            },
                            "branch": {
                                "name": "master"
                            },
                            "repository": {
                                "name": "Atlaskit-MK-2",
                                "type": "repository",
                                "full_name": "atlassian/atlaskit-mk-2",
                                "uuid": "{}"
                            }
                        },
                        "reason": "",
                        "source": {
                            "commit": {
                                "type": "commit",
                                "hash": "728c8bad1813"
                            },
                            "branch": {
                                "name": "username/NONE-add-onClick-prop-for-accessibility"
                            },
                            "repository": {
                                "name": "Atlaskit-MK-2",
                                "type": "repository",
                                "full_name": "atlassian/atlaskit-mk-2",
                                "uuid": "{}"
                            }
                        },
                        "state": "OPEN",
                        "author": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "date": "2019-05-10T06:48:25.305565+00:00"
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```


        Approval example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "approval": {
                        "date": "2019-09-27T00:37:19.849534+00:00",
                        "pullrequest": {
                            "type": "pullrequest",
                            "id": 5695,
                            "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                        },
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        }
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      tags:
        - Pullrequests
      summary: Get a pull request
      operationId: Pullrequests_getPullRequest
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Returns the specified pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    put:
      tags:
        - Pullrequests
      summary: Update a pull request
      operationId: Pullrequests_updatePullRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: |-
        Mutates the specified pull request.

        This can be used to change the pull request's branches or description.

        Only open pull requests can be mutated.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity:
    get:
      tags:
        - Pullrequests
      summary: List a pull request activity log
      operationId: Pullrequests_listActivityLog
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of the pull request's activity log.


        This handler serves both a v20 and internal endpoint. The v20 endpoint

        returns reviewer comments, updates, approvals and request changes. The
        internal

        endpoint includes those plus tasks and attachments.


        Comments created on a file or a line of code have an inline property.


        Comment example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "comment": {
                        "deleted": false,
                        "pullrequest": {
                            "type": "pullrequest",
                            "id": 5695,
                            "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                        },
                        "content": {
                            "raw": "inline with to a dn from lines",
                            "markup": "markdown",
                            "html": "<p>inline with to a dn from lines</p>",
                            "type": "rendered"
                        },
                        "created_on": "2019-09-27T00:33:46.039178+00:00",
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "created_on": "2019-09-27T00:33:46.039178+00:00",
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "updated_on": "2019-09-27T00:33:46.055384+00:00",
                        "inline": {
                            "context_lines": "",
                            "to": null,
                            "path": "",
                            "outdated": false,
                            "from": 211
                        },
                        "type": "pullrequest_comment",
                        "id": 118571088
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```


        Updates include a state property of OPEN, MERGED, or DECLINED.


        Update example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "update": {
                        "description": "",
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it",
                        "destination": {
                            "commit": {
                                "type": "commit",
                                "hash": "6a2c16e4a152"
                            },
                            "branch": {
                                "name": "master"
                            },
                            "repository": {
                                "name": "Atlaskit-MK-2",
                                "type": "repository",
                                "full_name": "atlassian/atlaskit-mk-2",
                                "uuid": "{}"
                            }
                        },
                        "reason": "",
                        "source": {
                            "commit": {
                                "type": "commit",
                                "hash": "728c8bad1813"
                            },
                            "branch": {
                                "name": "username/NONE-add-onClick-prop-for-accessibility"
                            },
                            "repository": {
                                "name": "Atlaskit-MK-2",
                                "type": "repository",
                                "full_name": "atlassian/atlaskit-mk-2",
                                "uuid": "{}"
                            }
                        },
                        "state": "OPEN",
                        "author": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        },
                        "date": "2019-05-10T06:48:25.305565+00:00"
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```


        Approval example:

        ```

        {
            "pagelen": 20,
            "values": [
                {
                    "approval": {
                        "date": "2019-09-27T00:37:19.849534+00:00",
                        "pullrequest": {
                            "type": "pullrequest",
                            "id": 5695,
                            "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                        },
                        "user": {
                            "display_name": "Name Lastname",
                            "uuid": "{}",
                            "type": "user",
                            "nickname": "Name",
                            "account_id": ""
                        }
                    },
                    "pull_request": {
                        "type": "pullrequest",
                        "id": 5695,
                        "title": "username/NONE: small change from onFocus to onClick to handle tabbing through the page and not expand the editor unless a click event triggers it"
                    }
                }
            ]
        }

        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve:
    delete:
      tags:
        - Pullrequests
      summary: Unapprove a pull request
      operationId: Pullrequests_unapprovePullRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: |-
        Redact the authenticated user's approval of the specified pull
        request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Approve a pull request
      operationId: Pullrequests_approveRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: Approve the specified pull request as the authenticated user.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments:
    get:
      tags:
        - Pullrequests
      summary: List comments on a pull request
      operationId: Pullrequests_listComments
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: |-
        Returns a paginated list of the pull request's comments.

        This includes both global, inline comments and replies.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more
        details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Create a comment on a pull request
      operationId: Pullrequests_createComment
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: |-
        Creates a new pull request comment.

        Returns the newly created pull request comment.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}:
    delete:
      tags:
        - Pullrequests
      summary: Delete a comment on a pull request
      operationId: Pullrequests_deleteComment
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Deletes a specific pull request comment.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    get:
      tags:
        - Pullrequests
      summary: Get a comment on a pull request
      operationId: Pullrequests_getComment
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Returns a specific pull request comment.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    put:
      tags:
        - Pullrequests
      summary: Update a comment on a pull request
      operationId: Pullrequests_updateComment
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Updates a specific pull request comment.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}/resolve:
    delete:
      tags:
        - Pullrequests
      summary: Reopen a comment thread
      operationId: Pullrequests_reopenCommentThread
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Resolve a comment thread
      operationId: Pullrequests_resolveCommentThread
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits:
    get:
      tags:
        - Pullrequests
      summary: List commits on a pull request
      operationId: Pullrequests_listCommits
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: |-
        Returns a paginated list of the pull request's commits.

        These are the commits that are being merged into the destination
        branch when the pull requests gets accepted.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline:
    post:
      tags:
        - Pullrequests
      summary: Decline a pull request
      operationId: Pullrequests_declinePullRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: Declines the pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff:
    get:
      tags:
        - Pullrequests
      summary: List changes in a pull request
      operationId: Pullrequests_listDiff
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Redirects to the [repository
        diff](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diff-spec-get)

        with the revspec that corresponds to the pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat:
    get:
      tags:
        - Pullrequests
      summary: Get the diff stat for a pull request
      operationId: Pullrequests_getDiffstat
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Redirects to the [repository
        diffstat](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diffstat-spec-get)

        with the revspec that corresponds to the pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge:
    post:
      tags:
        - Pullrequests
      summary: Merge a pull request
      operationId: Pullrequests_mergePullRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: Merges the pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge/task-status/{task_id}:
    get:
      tags:
        - Pullrequests
      summary: Get the merge task status for a pull request
      operationId: Pullrequests_mergeTaskStatus
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        When merging a pull request takes too long, the client receives a

        task ID along with a 202 status code. The task ID can be used in a call

        to this endpoint to check the status of a merge task.


        ```

        curl -X GET
        https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/<task_id>

        ```


        If the merge task is not yet finished, a PENDING status will be
        returned.


        ```

        HTTP/2 200

        {
            "task_status": "PENDING"
        }

        ```


        If the merge was successful, a SUCCESS status will be returned.


        ```

        HTTP/2 200

        {
            "task_status": "SUCCESS",
            "merge_result": <the merged pull request object>
        }

        ```


        If the merge task failed, an error will be returned.


        ```

        {
            "type": "error",
            "error": {
                "message": "<error message>"
            }
        }

        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch:
    get:
      tags:
        - Pullrequests
      summary: Get the patch for a pull request
      operationId: Pullrequests_getPatch
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Redirects to the [repository
        patch](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-patch-spec-get)

        with the revspec that corresponds to pull request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/request-changes:
    delete:
      tags:
        - Pullrequests
      summary: Remove change request for a pull request
      operationId: Pullrequests_removeChangeRequest
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Request changes for a pull request
      operationId: Pullrequests_requestChanges
      security:
        - oauth2:
            - pullrequest:write
        - basic: []
        - api_key: []
      description: ''
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
            - write:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/statuses:
    get:
      tags:
        - Pullrequests
        - Commit statuses
      summary: List commit statuses for a pull request
      operationId: Pullrequests_listCommitStatuses
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: |-
        Returns all statuses (e.g. build results) for the given pull
        request.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks:
    get:
      tags:
        - Pullrequests
      summary: List tasks on a pull request
      operationId: Pullrequests_listTasksOnPullRequest
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Returns a paginated list of the pull request's tasks.


        This endpoint supports filtering and sorting of the results by the
        'task' field.

        See [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for
        more details.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    post:
      tags:
        - Pullrequests
      summary: Create a task on a pull request
      operationId: Pullrequests_createTask
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: >-
        Creates a new pull request task.


        Returns the newly created pull request task.


        Tasks can optionally be created in relation to a comment specified by
        the comment's ID which

        will cause the task to appear below the comment on a pull request when
        viewed in Bitbucket.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks/{task_id}:
    delete:
      tags:
        - Pullrequests
      summary: Delete a task on a pull request
      operationId: Pullrequests_deleteTask
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Deletes a specific pull request task.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    get:
      tags:
        - Pullrequests
      summary: Get a task on a pull request
      operationId: Pullrequests_getTask
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Returns a specific pull request task.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
    put:
      tags:
        - Pullrequests
      summary: Update a task on a pull request
      operationId: Pullrequests_updateTask
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      description: Updates a specific pull request task.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:pullrequest:bitbucket
  /repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}:
    put:
      tags:
        - properties
      summary: Update a pull request application property
      operationId: Properties_updatePullRequestApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Update an [application property](https://dac-static.atlassian.com) value
        stored against a pull request.
    delete:
      tags:
        - properties
      summary: Delete a pull request application property
      operationId: Properties_deletePullRequestApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Delete an [application property](https://dac-static.atlassian.com) value
        stored against a pull request.
    get:
      tags:
        - properties
      summary: Get a pull request application property
      operationId: Properties_getPullRequestApplicationProperty
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      description: >-
        Retrieve an [application property](https://dac-static.atlassian.com)
        value stored against a pull request.
  /repositories/{workspace}/{repo_slug}/refs:
    get:
      tags:
        - Refs
      summary: List branches and tags
      operationId: Refs_listBranchesAndTags
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns the branches and tags in the repository.


        By default, results will be in the order the underlying source control
        system returns them and identical to

        the ordering one sees when running "$ git show-ref". Note that this
        follows simple

        lexical ordering of the ref names.


        This can be undesirable as it does apply any natural sorting semantics,
        meaning for instance that refs are

        sorted ["branch1", "branch10", "branch2", "v10", "v11", "v9"] instead of
        ["branch1", "branch2",

        "branch10", "v9", "v10", "v11"].


        Sorting can be changed using the ?sort= query parameter. When using
        ?sort=name to explicitly sort on ref name,

        Bitbucket will apply natural sorting and interpret numerical values as
        numbers instead of strings.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/refs/branches:
    get:
      tags:
        - Refs
      summary: List open branches
      operationId: Refs_listOpenBranches
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns a list of all open branches within the specified repository.

        Results will be in the order the source control manager returns them.


        Branches support [filtering and
        sorting](/cloud/bitbucket/rest/intro/#filtering)

        that can be used to search for specific branches. For instance, to find

        all branches that have "stab" in their name:


        ```

        curl -s
        https://api.bitbucket.org/2.0/repositories/atlassian/aui/refs/branches
        -G --data-urlencode 'q=name ~ "stab"'

        ```


        By default, results will be in the order the underlying source control
        system returns them and identical to

        the ordering one sees when running "$ git branch --list". Note that this
        follows simple

        lexical ordering of the ref names.


        This can be undesirable as it does apply any natural sorting semantics,
        meaning for instance that tags are

        sorted ["v10", "v11", "v9"] instead of ["v9", "v10", "v11"].


        Sorting can be changed using the ?q= query parameter. When using ?q=name
        to explicitly sort on ref name,

        Bitbucket will apply natural sorting and interpret numerical values as
        numbers instead of strings.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Refs
      summary: Create a branch
      operationId: Refs_createBranch
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: >-
        Creates a new branch in the specified repository.


        The payload of the POST should consist of a JSON document that

        contains the name of the tag and the target hash.


        ```

        curl
        https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/branches \

        -s -u seanfarley -X POST -H "Content-Type: application/json" \

        -d '{
            "name" : "smf/create-feature",
            "target" : {
                "hash" : "default"
            }
        }'

        ```


        This call requires authentication. Private repositories require the

        caller to authenticate with an account that has appropriate

        authorization.


        The branch name should not include any prefixes (e.g.

        refs/heads). This endpoint does support using short hash prefixes for

        the commit hash, but it may return a 400 response if the provided

        prefix is ambiguous. Using a full commit hash is the preferred

        approach.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/refs/branches/{name}:
    delete:
      tags:
        - Refs
      summary: Delete a branch
      operationId: Refs_deleteBranch
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Delete a branch in the specified repository.

        The main branch is not allowed to be deleted and will return a 400
        response.

        The branch name should not include any prefixes (e.g.
        refs/heads).
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
    get:
      tags:
        - Refs
      summary: Get a branch
      operationId: Refs_getBranch
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: |-
        Returns a branch object within the specified repository.

        This call requires authentication. Private repositories require the
        caller to authenticate with an account that has appropriate
        authorization.

        For Git, the branch name should not include any prefixes (e.g.
        refs/heads).
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/refs/tags:
    get:
      tags:
        - Refs
      summary: List tags
      operationId: Refs_listTags
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns the tags in the repository.


        By default, results will be in the order the underlying source control
        system returns them and identical to

        the ordering one sees when running "$ git tag --list". Note that this
        follows simple

        lexical ordering of the ref names.


        This can be undesirable as it does apply any natural sorting semantics,
        meaning for instance that tags are

        sorted ["v10", "v11", "v9"] instead of ["v9", "v10", "v11"].


        Sorting can be changed using the ?sort= query parameter. When using
        ?sort=name to explicitly sort on ref name,

        Bitbucket will apply natural sorting and interpret numerical values as
        numbers instead of strings.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Refs
      summary: Create a tag
      operationId: Refs_createTag
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Creates a new tag in the specified repository.

        The payload of the POST should consist of a JSON document that
        contains the name of the tag and the target hash.

        ```
        curl https://api.bitbucket.org/2.0/repositories/jdoe/myrepo/refs/tags \
        -s -u jdoe -X POST -H "Content-Type: application/json" \
        -d '{
            "name" : "new-tag-name",
            "target" : {
                "hash" : "a1b2c3d4e5f6"
            }
        }'
        ```

        This endpoint does support using short hash prefixes for the commit
        hash, but it may return a 400 response if the provided prefix is
        ambiguous. Using a full commit hash is the preferred approach.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/refs/tags/{name}:
    delete:
      tags:
        - Refs
      summary: Delete a tag
      operationId: Refs_deleteTag
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: |-
        Delete a tag in the specified repository.

        The tag name should not include any prefixes (e.g. refs/tags).
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
    get:
      tags:
        - Refs
      summary: Get a tag
      operationId: Refs_tagsByNameGet
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        Returns the specified tag.


        ```

        $ curl -s
        https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8
        -G | jq .

        {
          "name": "3.8",
          "tagger": {
            "raw": "Matt Mackall <mpm@selenic.com>",
            "type": "author",
            "user": {
              "username": "mpmselenic",
              "nickname": "mpmselenic",
              "display_name": "Matt Mackall",
              "type": "user",
              "uuid": "{a4934530-db4c-419c-a478-9ab4964c2ee7}"
            }
          },
          "date": "2016-05-01T18:52:25+00:00",
          "message": "Added tag 3.8 for changeset f85de28eae32",
          "type": "tag",
          "target": {
            "hash": "f85de28eae32e7d3064b1a1321309071bbaaa069",
            "repository": {
              "type": "repository",
              "name": "hg",
              "full_name": "seanfarley/hg",
              "uuid": "{c75687fb-e99d-4579-9087-190dbd406d30}"
            },
            "author": {
              "raw": "Sean Farley <sean@farley.io>",
              "type": "author",
              "user": {
                "username": "seanfarley",
                "nickname": "seanfarley",
                "display_name": "Sean Farley",
                "type": "user",
                "uuid": "{a295f8a8-5876-4d43-89b5-3ad8c6c3c51d}"
              }
            },
            "parents": [
              {
                "hash": "9a98d0e5b07fc60887f9d3d34d9ac7d536f470d2",
                "type": "commit"
              }
            ],
            "date": "2016-05-01T04:21:17+00:00",
            "message": "debian: alphabetize build deps",
            "type": "commit"
          }
        }

        ```
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/src:
    get:
      tags:
        - Source
        - Repositories
      summary: Get the root directory of the main branch
      operationId: Source_getRootDirectory
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        This endpoint redirects the client to the directory listing of the

        root directory on the main branch.


        This is equivalent to directly hitting

        [/2.0/repositories/{username}/{repo_slug}/src/{commit}/{path}](src/%7Bcommit%7D/%7Bpath%7D)

        without having to know the name or SHA1 of the repo's main branch.


        To create new commits, [POST to this
        endpoint](https://dac-static.atlassian.com)
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - read:repository:bitbucket
    post:
      tags:
        - Source
        - Repositories
      summary: Create a commit by uploading a file
      operationId: Source_createCommitByUploadingFile
      security:
        - oauth2:
            - repository:write
        - basic: []
        - api_key: []
      description: >-
        This endpoint is used to create new commits in the repository by

        uploading files.


        To add a new file to a repository:


        ```

        $ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \
          -F /repo/path/to/image.png=@image.png
        ```


        This will create a new commit on top of the main branch, inheriting the

        contents of the main branch, but adding (or overwriting) the

        `image.png` file to the repository in the `/repo/path/to` directory.


        To create a commit that deletes files, use the `files` parameter:


        ```

        $ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \
          -F files=/file/to/delete/1.txt \
          -F files=/file/to/delete/2.txt
        ```


        You can add/modify/delete multiple files in a request. Rename/move a

        file by deleting the old path and adding the content at the new path.


        This endpoint accepts `multipart/form-data` (as in the examples above),

        as well as `application/x-www-form-urlencoded`.


        Note: `multipart/form-data` is currently not supported by Forge apps

        for this API.


        #### multipart/form-data


        A `multipart/form-data` post contains a series of "form fields" that

        identify both the individual files that are being uploaded, as well as

        additional, optional meta data.


        Files are uploaded in file form fields (those that have a

        `Content-Disposition` parameter) whose field names point to the remote

        path in the repository where the file should be stored. Path field

        names are always interpreted to be absolute from the root of the

        repository, regardless whether the client uses a leading slash (as the

        above `curl` example did).


        File contents are treated as bytes and are not decoded as text.


        The commit message, as well as other non-file meta data for the

        request, is sent along as normal form field elements. Meta data fields

        share the same namespace as the file objects. For `multipart/form-data`

        bodies that should not lead to any ambiguity, as the

        `Content-Disposition` header will contain the `filename` parameter to

        distinguish between a file named "message" and the commit message field.


        #### application/x-www-form-urlencoded


        It is also possible to upload new files using a simple

        `application/x-www-form-urlencoded` POST. This can be convenient when

        uploading pure text files:


        ```

        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src \
          --data-urlencode "/path/to/me.txt=Lorem ipsum." \
          --data-urlencode "message=Initial commit" \
          --data-urlencode "author=Erik van Zijst <erik.van.zijst@gmail.com>"
        ```


        There could be a field name clash if a client were to upload a file

        named "message", as this filename clashes with the meta data property

        for the commit message. To avoid this and to upload files whose names

        clash with the meta data properties, use a leading slash for the files,

        e.g. `curl --data-urlencode "/message=file contents"`.


        When an explicit slash is omitted for a file whose path matches that of

        a meta data parameter, then it is interpreted as meta data, not as a

        file.


        #### Executables and links


        While this API aims to facilitate the most common use cases, it is

        possible to perform some more advanced operations like creating a new

        symlink in the repository, or creating an executable file.


        Files can be supplied with a `x-attributes` value in the

        `Content-Disposition` header. For example, to upload an executable

        file, as well as create a symlink from `README.txt` to `README`:


        ```

        --===============1438169132528273974==

        Content-Type: text/plain; charset="us-ascii"

        MIME-Version: 1.0

        Content-Transfer-Encoding: 7bit

        Content-ID: "bin/shutdown.sh"

        Content-Disposition: attachment; filename="shutdown.sh";
        x-attributes:"executable"


        #!/bin/sh

        halt


        --===============1438169132528273974==

        Content-Type: text/plain; charset="us-ascii"

        MIME-Version: 1.0

        Content-Transfer-Encoding: 7bit

        Content-ID: "/README.txt"

        Content-Disposition: attachment; filename="README.txt";
        x-attributes:"link"


        README

        --===============1438169132528273974==--

        ```


        Links are files that contain the target path and have

        `x-attributes:"link"` set.


        When overwriting links with files, or vice versa, the newly uploaded

        file determines both the new contents, as well as the attributes. That

        means uploading a file without specifying `x-attributes="link"` will

        create a regular file, even if the parent commit hosted a symlink at

        the same path.


        The same applies to executables. When modifying an existing executable

        file, the form-data file element must include

        `x-attributes="executable"` in order to preserve the executable status

        of the file.


        Note that this API does not support the creation or manipulation of

        subrepos / submodules.
      x-atlassian-oauth2-scopes:
        - state: Current
          scheme: oauth2
          scopes:
            - write:repository:bitbucket
  /repositories/{workspace}/{repo_slug}/src/{commit}/{path}:
    get:
      tags:
        - Source
        - Repositories
      summary: Get file or directory contents
      operationId: Source_getRepositorySrcContent
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      description: >-
        This endpoints is used to retrieve the contents of a single file,

        or the contents of a directory at a specified revision.


        #### Raw file contents


        When `path` points to a file, this endpoint returns the raw contents.

        The response's Content-Type is derived from the filename

        extension (not from the contents). The file contents are not processed

        and no character encoding/recoding is performed and as a result no

        character encoding is included as part of the Content-Type.


        The `Content-Disposition` header will be "attachment" to prevent

        browsers from running executable files.


        If the file is managed by LFS, then a 301 redirect pointing to

        Atlassian's media services platform is returned.


        The response includes an ETag that is based on the contents of the file

        and its attributes. This means that an empty `__init__.py` always

        returns the same ETag, regardless on the directory it lives in, or the

        commit it is on.


        #### File meta data


        When the request for a file path includes the query parameter

        `?format=meta`, instead of returning the file's raw contents, Bitbucket

        instead returns the JSON object describing the file's properties:


        ```javascript

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests/__init__.py?format=meta

        {
          "path": "tests/__init__.py",
          "commit": {
            "type": "commit",
            "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
          },
          "attributes": [],
          "type": "commit_file",
          "size": 0
        }

        ```


        File objects contain an `attributes` element that contains a list of

        possible modifiers. Currently defined values are:


        * `link` -- indicates that the entry is a symbolic link. The contents
            of the file represent the path the link points to.
        * `executable` -- indicates that the file has the executable bit set.

        * `subrepository` -- indicates that the entry points to a submodule or
            subrepo. The contents of the file is the SHA1 of the repository
            pointed to.
        * `binary` -- indicates whether Bitbucket thinks the file is binary.


        This endpoint can provide an alternative to how a HEAD request can be

        used to check for the existence of a file, or a file's size without

        incurring the overhead of receiving its full contents.



        #### Directory listings


        When `path` points to a directory instead of a file, the response is a

        paginated list of directory and file objects in the same order as the

        underlying SCM system would return them.


        For example:


        ```javascript

        $ curl
        https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests

        {
          "pagelen": 10,
          "values": [
            {
              "path": "tests/test_project",
              "type": "commit_directory",
              "commit": {
                "type": "commit",
                "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
              }
            },
            {
              "path": "tests/__init__.py",
              "commit": {
                "type": "commit",
                "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
              },
              "attributes": [],
              "type": "commit_file",
              "size": 0
            }
          ],
          "page": 1,
          "size": 2
        }

        ```


        When listing the contents of the repo's root directory, the use of a

        trailing slash at the end of the URL is required.


        The response by default is not recursive, meaning that only the direct
        contents of

        a path are returned. The response does not recurse down into

        subdirectories. In order to "walk" the entire directory tree, the

        client can either parse each response and follow the `self` links of
        each

        `commit_directory` object, or can specify a `max_depth` to recurse to.


        The max_depth parameter will do a breadth-first search to return the
        contents of the subdirectories

        up to the depth specified. Breadth-first search was chosen as it leads
        to the least amount of

        file system operations for git. If the `max_depth` parameter is
        specified to be too

        large, the call will time out and return a 555.


        Each returned object is either a `commit_file`, or a `commit_directory`,

        both of which contain a `path` element. This path is the absolute path

        from the root of the repository. Each object also contains a `commit`

        object which embeds the commit the file is on. Note that this is merely

        the commit that was used in the URL. It is *not* the commit that last

        modified the file.


        Directory objects have 2 representations. Their `self` link returns the

        paginated contents of the directory. The `meta` link on the other hand

        returns the actual `directory` object itself, e.g.:


        ```javascript

        {
          "path": "tests/test_project",
          "type": "commit_directory",
          "commit": { ... }
        }

        ```


        #### Querying, filtering and sorting


        Like most API endpoints, this API supports the Bitbucket

        querying/filtering syntax and so you could filter a directory listing

        to only include entries that match certain criteria. For instance, to

[...]
