openapi: 3.0.1
info:
  title: ChatKitty Platform API
  description: |-
    OpenAPI specification (OAS) for the ChatKitty Platform API.
    See the Interactive Docs to try ChatKitty API methods without writing code,
    and get the complete schema of resources exposed by the API.
  version: 2.58.3
  termsOfService: https://chatkitty.com/terms-of-service
  contact:
    name: Support
    url: mailto:support@chatkitty.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-konfig-ignore:
    object-with-no-properties: true
servers:
  - url: https://api.chatkitty.com
tags:
  - description: Operations to create, retrieve, update and delete channels
    name: channels
    x-displayName: Channels
  - description: User operations
    name: users
    x-displayName: Users
  - description: Operations to retrieve, update and delete messages
    name: messages
    x-displayName: Messages
  - description: Chat runtime operations
    name: runtime
    x-displayName: Chat Runtime
  - description: Chat function operations
    name: functions
    x-displayName: Chat Functions
  - description: Import user, channel, message data into your ChatKitty application
    name: imports
    x-displayName: Imports
  - description: Message thread operations
    name: threads
    x-displayName: Threads
  - description: Configure and manage your ChatKitty application
    name: application
    x-displayName: Application
  - description: Export analytics data from your ChatKitty application
    name: analytics
    x-displayName: Analytics
  - description: >-
      Retrieve information about long running scheduled jobs like imports and
      exports
    name: jobs
    x-displayName: Jobs
  - description: Chat session operations
    name: chat-sessions
    x-displayName: Chat Sessions
  - description: Chat function version operations
    name: function-versions
    x-displayName: Chat Function Versions
  - description: User session operations
    name: user-sessions
    x-displayName: User Sessions
paths:
  /v1/analytics/messages:
    post:
      tags:
        - analytics
      summary: Export message analytics
      operationId: Analytics_exportMessageAnalyticsData
      security:
        - application_authorization:
            - read:message
      description: Batch export message analytics data
  /v1/analytics/users:
    post:
      tags:
        - analytics
      summary: Export user analytics
      operationId: Analytics_exportUserAnalyticsData
      security:
        - application_authorization:
            - read:user
      description: Batch export user analytics data
  /v1/application:
    get:
      tags:
        - application
      summary: Retrieve the authenticated application
      operationId: Application_getAuthenticated
      security:
        - application_authorization:
            - read:application
      description: >-
        Returns the ChatKitty application associated with the authentication
        credentials used.


        You must use an **OAuth V2 Bearer token** to access this endpoint.
  /v1/application/settings:
    get:
      tags:
        - application
      summary: Retrieve the authenticated application settings
      operationId: Application_getSettings
      security:
        - application_authorization:
            - read:application
      description: Returns the current settings configuring this application
    put:
      tags:
        - application
      summary: Update the authenticated application settings
      operationId: Application_updateSettings
      security:
        - application_authorization:
            - update:application
      description: Update the settings configuring this application
  /v1/channels:
    get:
      tags:
        - channels
      summary: List channels
      operationId: Channels_list
      security:
        - application_authorization:
            - read:channel
      description: Returns a page of channels belonging to this application
    post:
      tags:
        - channels
      summary: Create a channel
      operationId: Channels_createChannel
      security:
        - application_authorization:
            - create:channel
      description: Creates a new channel or returns an equivalent existing channel
  /v1/channels/{id}:
    get:
      tags:
        - channels
      summary: Retrieve a channel
      operationId: Channels_getById
      security:
        - application_authorization:
            - read:channel
      description: Returns a channel by ID
    delete:
      tags:
        - channels
      summary: Delete a channel
      operationId: Channels_deleteById
      security:
        - application_authorization:
            - read:channel
            - delete:channel
      description: Deletes a channel by ID
    patch:
      tags:
        - channels
      summary: Update a channel
      operationId: Channels_updateProperties
      security:
        - application_authorization:
            - read:channel
            - update:channel
      description: Updates a channel properties
  /v1/channels/{id}/events:
    post:
      tags:
        - channels
      summary: Send a channel event
      operationId: Channels_sendEvent
      security:
        - application_authorization:
            - read:channel
            - create:channel_event
      description: Sends a custom channel event
  /v1/channels/{id}/invites:
    get:
      tags:
        - channels
      summary: List channel invites
      operationId: Channels_listInvites
      security:
        - application_authorization:
            - read:channel_invite
      description: Returns a page of invites sent to join this channel
    post:
      tags:
        - channels
      summary: Send a channel invite
      operationId: Channels_sendInvite
      security:
        - application_authorization:
            - read:channel
            - read:user
            - create:channel_invite
      description: Sends a channel invite to user
  /v1/channels/{id}/keystrokes:
    post:
      tags:
        - channels
      summary: Send channel keystrokes
      operationId: Channels_sendKeystrokes
      security:
        - application_authorization:
            - read:channel
            - read:user
            - create:keystrokes
      description: Sends keystrokes in this channel on behalf of a user
  /v1/channels/{id}/members:
    get:
      tags:
        - channels
      summary: List a channel's members
      operationId: Channels_listMembersPage
      security:
        - application_authorization:
            - read:channel
            - read:channel_membership
      description: Returns a page of channel members
    post:
      tags:
        - channels
      summary: Add a channel member
      operationId: Channels_addMember
      security:
        - application_authorization:
            - read:channel
            - read:user
            - create:channel_membership
      description: Makes a user a group channel member
  /v1/channels/{id}/members/{user_id}:
    delete:
      tags:
        - channels
      summary: Remove a channel member
      operationId: Channels_removeMember
      security:
        - application_authorization:
            - read:channel
            - read:user
            - delete:channel_membership
      description: Removes a member from a group channel
  /v1/channels/{id}/memberships:
    get:
      tags:
        - channels
      summary: List channel memberships
      operationId: Channels_listMembershipsPage
      security:
        - application_authorization:
            - read:channel
            - read:channel_membership
      description: Returns a page of channel membership info for this channel
  /v1/channels/{id}/messages:
    get:
      tags:
        - channels
      summary: List channel messages
      operationId: Channels_listMessagesPage
      security:
        - application_authorization:
            - read:channel
            - read:message
      description: Returns a page of messages sent in this channel
    post:
      tags:
        - channels
      summary: Send a channel message
      operationId: Channels_sendChannelMessage
      security:
        - application_authorization:
            - read:channel
            - read:user
            - create:message
      description: Sends a message in this channel as the system or on behalf of a user
  /v1/channels/{id}/moderators:
    get:
      tags:
        - channels
      summary: Lists a channel's moderators
      operationId: Channels_listModeratorsPage
      security:
        - application_authorization:
            - read:channel
            - read:channel_moderator
      description: Returns a page of channel moderators
    post:
      tags:
        - channels
      summary: Add a channel moderator
      operationId: Channels_addModerator
      security:
        - application_authorization:
            - read:channel
            - read:user
            - read:channel_membership
            - create:channel_moderator
      description: Makes a user a group channel moderator
  /v1/channels/{id}/moderators/{user_id}:
    delete:
      tags:
        - channels
      summary: Remove a channel moderator
      operationId: Channels_removeModerator
      security:
        - application_authorization:
            - read:channel
            - read:user
            - delete:channel_moderator
      description: Removes a moderator from a group channel
  /v1/channels/{id}/participants:
    get:
      tags:
        - channels
      summary: List channel participants
      operationId: Channels_listParticipantsPage
      security:
        - application_authorization:
            - read:channel
            - read:chat_session
      description: >-
        Returns a page of channel active participants: members that currently
        online
  /v1/channels/{id}/reported-messages:
    get:
      tags:
        - channels
      summary: List channel reported messages
      operationId: Channels_listReportedMessagesPage
      security:
        - application_authorization:
            - read:channel
            - read:message_report
      description: Returns a page of reported messages in this channel
  /v1/chat-sessions:
    get:
      tags:
        - chat-sessions
      summary: List chat sessions
      operationId: Chatsessions_listPage
      security:
        - application_authorization:
            - read:chat_session
      description: Returns a page of chat sessions belonging to this application
  /v1/function-versions/{id}:
    get:
      tags:
        - function-versions
      summary: Retrieve a chat function version
      operationId: Functionversions_getById
      security:
        - application_authorization:
            - read:function_version
      description: Returns a chat function version by ID
  /v1/functions/{id}:
    get:
      tags:
        - functions
      summary: Retrieve a chat function
      operationId: Functions_getById
      security:
        - application_authorization:
            - read:function
      description: Returns a chat function by ID
  /v1/functions/{id}/current-version:
    get:
      tags:
        - functions
      summary: Retrieve chat function current version
      operationId: Functions_getCurrentVersion
      security:
        - application_authorization:
            - read:function
            - read:function_version
      description: Returns the version of this chat function currently deployed
  /v1/functions/{id}/invocations:
    get:
      tags:
        - functions
      summary: List chat function invocations
      operationId: Functions_listInvocationsPage
      security:
        - application_authorization:
            - read:function
            - read:function_invocation
      description: >-
        Returns a page of invocations of this chat function. A log of previous
        runs of the function
  /v1/functions/{id}/versions:
    get:
      tags:
        - functions
      summary: List chat function versions
      operationId: Functions_listVersionsPage
      security:
        - application_authorization:
            - read:function
            - read:function_version
      description: Returns a page of versions of this chat function
    post:
      tags:
        - functions
      summary: Create a chat function version
      operationId: Functions_createFunctionVersion
      security:
        - application_authorization:
            - read:function
            - create:function_version
      description: Creates a new version of this chat function
  /v1/imports/channels:
    post:
      tags:
        - imports
      summary: Import channels
      operationId: Imports_batchChannels
      security:
        - application_authorization:
            - create:channel
      description: Batch imports channels from a JSON array file
  /v1/imports/channels/{id}/members:
    post:
      tags:
        - imports
      summary: Import channel members
      operationId: Imports_channelMembersBatch
      security:
        - application_authorization:
            - create:channel_membership
      description: Batch imports channel members from a JSON array file
  /v1/imports/messages:
    post:
      tags:
        - imports
      summary: Import messages
      operationId: Imports_batchMessagesFromJson
      security:
        - application_authorization:
            - create:message
      description: Batch imports messages from a JSON array file
  /v1/imports/users:
    post:
      tags:
        - imports
      summary: Import users
      operationId: Imports_jsonUsersBatch
      security:
        - application_authorization:
            - create:user
      description: Batch imports users from a JSON array file
  /v1/jobs:
    get:
      tags:
        - jobs
      summary: List jobs
      operationId: Jobs_listJobsPage
      security:
        - application_authorization:
            - read:job
      description: Returns a page of jobs created for this application
  /v1/jobs/{id}:
    get:
      tags:
        - jobs
      summary: Retrieve a job
      operationId: Jobs_getJobById
      security:
        - application_authorization:
            - read:job
      description: Returns a job by ID
  /v1/messages:
    get:
      tags:
        - messages
      summary: List messages
      operationId: Messages_listPage
      security:
        - application_authorization:
            - read:message
      description: Returns a page of messages belonging to this application
    delete:
      tags:
        - messages
      summary: Delete messages
      operationId: Messages_deleteAll
      security:
        - application_authorization:
            - read:message
            - delete:message
      description: Deletes all messages belonging to this application
  /v1/messages/{id}:
    get:
      tags:
        - messages
      summary: Retrieve a message
      operationId: Messages_getById
      security:
        - application_authorization:
            - read:message
      description: Returns a message by ID
    delete:
      tags:
        - messages
      summary: Delete a message
      operationId: Messages_removeById
      security:
        - application_authorization:
            - read:message
            - delete:message
      description: Deletes a message by ID
    patch:
      tags:
        - messages
      summary: Update a message
      operationId: Messages_updateProperties
      security:
        - application_authorization:
            - read:message
            - update:message
      description: Updates a message properties
  /v1/messages/{id}/read-receipts:
    get:
      tags:
        - messages
      summary: List message read receipts
      operationId: Messages_listReadReceipts
      security:
        - application_authorization:
            - read:message
            - read:read_receipt
      description: Returns a page of read receipts for this message
  /v1/runtimes/nodejs:
    get:
      tags:
        - runtime
      summary: Retrieve NodeJS chat runtime
      operationId: Runtime_getNodejsChatRuntime
      security:
        - application_authorization:
            - read:runtime
            - update:runtime
      description: Return this application's NodeJS chat runtime
  /v1/runtimes/nodejs/dependencies:
    put:
      tags:
        - runtime
      summary: Update NodeJS chat runtime NPM dependencies
      operationId: Runtime_updateNodejsChatDependencies
      security:
        - application_authorization:
            - read:runtime
            - update:runtime
      description: Updates the NPM dependencies for this application's NodeJS chat runtime
  /v1/runtimes/nodejs/environment-variables:
    put:
      tags:
        - runtime
      summary: Update NodeJS chat runtime environment variables
      operationId: Runtime_updateNodejsChatEnvironmentVariables
      security:
        - application_authorization:
            - read:runtime
            - update:runtime
      description: >-
        Updates the runtime environment variables of this application's NodeJS
        chat runtime
  /v1/runtimes/nodejs/functions:
    get:
      tags:
        - runtime
      summary: List NodeJS chat runtime functions
      operationId: Runtime_listNodejsChatFunctions
      security:
        - application_authorization:
            - read:runtime
            - read:function
      description: Returns a page of functions for this application's NodeJS chat runtime
    post:
      tags:
        - runtime
      summary: Create a NodeJS chat runtime function
      operationId: Runtime_createNodejsChatFunction
      security:
        - application_authorization:
            - read:runtime
            - read:function
      description: Creates a NodeJS chat function for this runtime
  /v1/runtimes/nodejs/initialization-script:
    put:
      tags:
        - runtime
      summary: Update NodeJS chat runtime initialization script
      operationId: Runtime_updateNodejsChatInitializationScript
      security:
        - application_authorization:
            - read:runtime
            - update:runtime
      description: >-
        Updates the initialization script for this application's NodeJS chat
        runtime
  /v1/threads/{id}:
    get:
      tags:
        - threads
      summary: Retrieve a thread
      operationId: Threads_getById
      security:
        - application_authorization:
            - read:thread
      description: Returns a thread by ID
  /v1/threads/{id}/keystrokes:
    post:
      tags:
        - threads
      summary: Send thread keystrokes
      operationId: Threads_sendKeystrokes
      security:
        - application_authorization:
            - read:thread
            - read:user
            - create:keystrokes
      description: Sends keystrokes in this thread on behalf of a user
  /v1/threads/{id}/messages:
    get:
      tags:
        - threads
      summary: List reply thread messages
      operationId: Threads_listThreadMessages
      security:
        - application_authorization:
            - read:thread
            - read:message
      description: Returns a page of replies sent in this thread
    post:
      tags:
        - threads
      summary: Send a reply thread message
      operationId: Threads_sendReplyMessage
      security:
        - application_authorization:
            - read:thread
            - read:user
            - create:message
      description: >-
        Sends a reply message in this thread as the system or on behalf of a
        user
  /v1/user-sessions:
    get:
      tags:
        - user-sessions
      summary: List user sessions
      operationId: Usersessions_listUserSessions
      security:
        - application_authorization:
            - read:user_session
      description: Returns a page of user sessions belonging to this application
  /v1/users:
    get:
      tags:
        - users
      summary: List users
      operationId: Users_getPage
      security:
        - application_authorization:
            - read:user
      description: Returns a page of users belonging to this application
    post:
      tags:
        - users
      summary: Create a user
      operationId: Users_createUser
      security:
        - application_authorization:
            - create:user
      description: Creates a new user
    head:
      tags:
        - users
      summary: Check a user exists
      operationId: Users_checkExists
      security:
        - application_authorization:
            - read:user
      description: Checks if a user exists
  /v1/users/{id}:
    get:
      tags:
        - users
      summary: Retrieve a user
      operationId: Users_getById
      security:
        - application_authorization:
            - read:user
      description: Returns a user by ID
    delete:
      tags:
        - users
      summary: Delete a user
      operationId: Users_removeUser
      security:
        - application_authorization:
            - read:user
            - delete:user
      description: Delets a user
    patch:
      tags:
        - users
      summary: Update a user
      operationId: Users_updateUserById
      security:
        - application_authorization:
            - read:user
            - update:user
      description: Updates a user
  /v1/users/{id}/channels:
    get:
      tags:
        - users
      summary: List a user's channels
      operationId: Users_listChannelsPage
      security:
        - application_authorization:
            - read:user
            - read:channels
      description: Returns a page of channels for this user created or joined
  /v1/users/{id}/display-picture:
    post:
      tags:
        - users
      summary: Update a user's display picture
      operationId: Users_updateDisplayPicture
      security:
        - application_authorization:
            - read:user
            - update:user
      description: Updates a user's display picture
  /v1/users/{id}/messages:
    get:
      tags:
        - users
      summary: List a user's messages
      operationId: Users_listMessagesPage
      security:
        - application_authorization:
            - read:user
            - read:channels
      description: Returns a page of messages sent by this user
  /v1/users/{id}/notifications:
    get:
      tags:
        - users
      summary: List a user's notifications
      operationId: Users_listNotificationsPage
      security:
        - application_authorization:
            - read:user
            - read:notifications
      description: Returns a page of notifications received by this user
  /v1/users/{id}/secrets/{name}:
    get:
      tags:
        - users
      summary: Retrieve a user secret
      operationId: Users_getSecret
      security:
        - application_authorization:
            - read:user_secret
      description: Returns a user secret
    put:
      tags:
        - users
      summary: Set a user secret
      operationId: Users_setUserSecret
      security:
        - application_authorization:
            - read:user
            - update:user_secret
      description: Sets a user secret's value
    delete:
      tags:
        - users
      summary: Remove a user secret
      operationId: Users_removeSecretValue
      security:
        - application_authorization:
            - read:user
            - delete:user_secret
      description: Removes a user secret's value
components:
  securitySchemes:
    password_reset_token_authorization:
      type: apiKey
      name: X-Token
      in: header
    application_authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://authorization.chatkitty.com/oauth/token
          refreshUrl: https://authorization.chatkitty.com/oauth/token
          scopes:
            create:*: Create application resources
            read:*: Read application resources
            update:*: Update application resources
            delete:*: Delete application resources