openapi: 3.0.1
info:
  title: Line Items
  description: ''
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: >-
    When creating a set of quotes for sales reps to send to potential buyers,
    use this API to add goods and services to the quotes.
  x-hubspot-related-documentation:
    - name: Products Guide
      url: https://hubspot.dev/guides/api/crm/products
    - name: Pipelines Guide
      url: https://hubspot.dev/guides/api/crm/pipelines
    - name: Companies Guide
      url: https://hubspot.dev/guides/api/crm/companies
    - name: Call SDK Guide
      url: https://hubspot.dev/guides/api/crm/extensions/calling-sdk
    - name: Quotes guide
      url: https://hubspot.dev/guides/api/crm/quotes
    - name: Deals Guide
      url: https://hubspot.dev/guides/api/crm/deals
    - name: Import CRM Guide
      url: https://hubspot.dev/guides/api/crm/imports
    - name: Custom Object Guide
      url: https://hubspot.dev/guides/api/crm/objects/crm-custom-objects
    - name: Properties Guide
      url: https://hubspot.dev/guides/api/crm/properties
    - name: Owners Guide
      url: https://hubspot.dev/guides/api/crm/owners
    - name: Timeline Events Guide
      url: https://hubspot.dev/guides/api/crm/extensions/timeline
    - name: Contacts Guide
      url: https://hubspot.dev/guides/api/crm/contacts
    - name: Feedback Submissions Guide
      url: https://hubspot.dev/guides/api/crm/feedback-submissions
    - name: Video Conference Guide
      url: https://hubspot.dev/guides/api/crm/extensions/video-conferencing
    - name: Tickets Guide
      url: https://hubspot.dev/guides/api/crm/tickets
    - name: Line Items Guide
      url: https://hubspot.dev/guides/api/crm/line-items
  x-hubspot-introduction: >-
    Use the line items API to add instances of products to deals and quotes. You
    can create line items from existing products or create them as custom line
    items with no product attached.
  x-konfig-ignore:
    potential-incorrect-type: true
servers:
  - url: https://api.hubapi.com
tags:
  - name: Basic
  - description: ''
    name: Batch
    x-hubspot-tag-name-english-source: Batch
  - name: Core
  - name: Public_Object
  - name: Search
  - name: GDPR
  - description: ''
    name: Settings
    x-hubspot-tag-name-english-source: Settings
  - description: ''
    name: Pipelines
    x-hubspot-tag-name-english-source: Pipelines
  - description: ''
    name: Pipeline Stages
    x-hubspot-tag-name-english-source: Pipeline Stages
  - description: ''
    name: Groups
    x-hubspot-tag-name-english-source: Groups
  - name: Events
  - name: Templates
  - description: ''
    name: Recording_Settings
    x-hubspot-tag-name-english-source: Recording_Settings
  - name: Tokens
  - description: ''
    name: Owners
    x-hubspot-tag-name-english-source: Owners
  - description: ''
    name: Pipeline Stage Audits
    x-hubspot-tag-name-english-source: Pipeline Stage Audits
  - description: ''
    name: Pipeline Audits
    x-hubspot-tag-name-english-source: Pipeline Audits
  - description: ''
    name: Public_Imports
    x-hubspot-tag-name-english-source: Public_Imports
  - name: Public_Object_Schemas
paths:
  /crm/v3/objects/products/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of products by internal ID, or unique property values
      operationId: Batch_readByProperties
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
  /crm/v3/objects/products/{productId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readProductById
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: >-
        Read an Object identified by `{productId}`. `{productId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveProduct
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: Move an Object identified by `{productId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateProduct
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: >-
        Perform a partial update of an Object identified by `{productId}`.
        `{productId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/products/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two products with same type
      operationId: PublicObject_mergeProductsSameType
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
  /crm/v3/objects/products/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of products by ID
      operationId: Batch_archiveProductsByIds
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
  /crm/v3/objects/products/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of products
      operationId: Batch_createProductsBatch
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
  /crm/v3/objects/products/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of products
      operationId: Batch_updateProductsBatch
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
  /crm/v3/objects/products/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_deleteContact
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/products:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listProductsPage
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: >-
        Read a page of products. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createProductObject
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      description: >-
        Create a product with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard products is provided.
  /crm/v3/objects/products/search:
    post:
      tags:
        - Search
      operationId: Search_productsByCriteria
      security:
        - oauth2_legacy:
            - e-commerce
        - oauth2: []
        - private_apps_legacy:
            - e-commerce
        - private_apps: []
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit:
    get:
      tags:
        - Pipeline Stage Audits
      summary: Return an audit of all changes to the pipeline stage
      operationId: PipelineStageAudits_getStageAudit
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Return a reverse chronological list of all mutations that have occurred
        on the pipeline stage identified by `{stageId}`.
  /crm/v3/pipelines/{objectType}/{pipelineId}:
    get:
      tags:
        - Pipelines
      summary: Return a pipeline by ID
      operationId: Pipelines_getById
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Return a single pipeline object identified by its unique `{pipelineId}`.
    put:
      tags:
        - Pipelines
      summary: Replace a pipeline
      operationId: Pipelines_replacePipelineObject
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Replace all the properties of an existing pipeline with the values
        provided. This will overwrite any existing pipeline stages. The updated
        pipeline will be returned in the response.
    delete:
      tags:
        - Pipelines
      summary: Delete a pipeline
      operationId: Pipelines_removeById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: Delete the pipeline identified by `{pipelineId}`.
    patch:
      tags:
        - Pipelines
      summary: Update a pipeline
      operationId: Pipelines_updatePipelineById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Perform a partial update of the pipeline identified by `{pipelineId}`.
        The updated pipeline will be returned in the response.
  /crm/v3/pipelines/{objectType}/{pipelineId}/audit:
    get:
      tags:
        - Pipeline Audits
      summary: Return an audit of all changes to the pipeline
      operationId: PipelineAudits_getByPipelineId
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Return a reverse chronological list of all mutations that have occurred
        on the pipeline identified by `{pipelineId}`.
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
    get:
      tags:
        - Pipeline Stages
      summary: Return all stages of a pipeline
      operationId: PipelineStages_getAll
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Return all the stages associated with the pipeline identified by
        `{pipelineId}`.
    post:
      tags:
        - Pipeline Stages
      summary: Create a pipeline stage
      operationId: PipelineStages_createStageObject
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Create a new stage associated with the pipeline identified by
        `{pipelineId}`. The entire stage object, including its unique ID, will
        be returned in the response.
  /crm/v3/pipelines/{objectType}:
    get:
      tags:
        - Pipelines
      summary: Retrieve all pipelines
      operationId: Pipelines_getAll
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Return all pipelines for the object type specified by `{objectType}`.
    post:
      tags:
        - Pipelines
      summary: Create a pipeline
      operationId: Pipelines_createNewPipelineObject
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Create a new pipeline with the provided property values. The entire
        pipeline object, including its unique ID, will be returned in the
        response.
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
    get:
      tags:
        - Pipeline Stages
      summary: Return a pipeline stage by ID
      operationId: PipelineStages_getById
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.contacts.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Return the stage identified by `{stageId}` associated with the pipeline
        identified by `{pipelineId}`.
    put:
      tags:
        - Pipeline Stages
      summary: Replace a pipeline stage
      operationId: PipelineStages_replaceStageObject
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Replace all the properties of an existing pipeline stage with the values
        provided. The updated stage will be returned in the response.
    delete:
      tags:
        - Pipeline Stages
      summary: Delete a pipeline stage
      operationId: PipelineStages_deleteStage
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Delete the pipeline stage identified by `{stageId}` associated with the
        pipeline identified by `{pipelineId}`.
    patch:
      tags:
        - Pipeline Stages
      summary: Update a pipeline stage
      operationId: PipelineStages_updateStageById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Perform a partial update of the pipeline stage identified by `{stageId}`
        associated with the pipeline identified by `{pipelineId}`. Any
        properties not included in this update will keep their existing values.
        The updated stage will be returned in the response.
  /crm/v3/objects/companies/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of companies by internal ID, or unique property values
      operationId: Batch_readCompaniesByProperties
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
  /crm/v3/objects/companies/{companyId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readCompanyObject
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
      description: >-
        Read an Object identified by `{companyId}`. `{companyId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveCompany
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
      description: Move an Object identified by `{companyId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateCompanyObject
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
      description: >-
        Perform a partial update of an Object identified by `{companyId}`.
        `{companyId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/companies/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two companies with same type
      operationId: PublicObject_mergeCompaniesSameType
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of companies by ID
      operationId: Batch_archiveCompaniesByIdBatch
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of companies
      operationId: Batch_createCompaniesBatch
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of companies
      operationId: Batch_updateCompaniesBatch
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteContact
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/companies:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listCompaniesPage
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
      description: >-
        Read a page of companies. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createCompanyObject
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
      description: >-
        Create a company with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard companies is provided.
  /crm/v3/objects/companies/search:
    post:
      tags:
        - Search
      operationId: Search_companyObjects
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/extensions/calling/{appId}/settings:
    get:
      tags:
        - Settings
      summary: Get calling settings
      operationId: Settings_getCallingConfig
      security:
        - developer_hapikey: []
      description: Returns the calling extension settings configured for your app.
    post:
      tags:
        - Settings
      summary: Configure a calling extension
      operationId: Settings_configureCallingExtension
      security:
        - developer_hapikey: []
      description: >-
        Used to set the menu label, target iframe URL, and dimensions for your
        calling extension.
    delete:
      tags:
        - Settings
      summary: Delete calling settings
      operationId: Settings_deleteCallingExtension
      security:
        - developer_hapikey: []
      description: >-
        Deletes this calling extension. This will remove your service as an
        option for all connected accounts.
    patch:
      tags:
        - Settings
      summary: Update settings
      operationId: Settings_updateCallingExtension
      security:
        - developer_hapikey: []
      description: Updates existing calling extension settings.
  /crm/v3/extensions/calling/{appId}/settings/recording:
    get:
      tags:
        - Recording_Settings
      operationId: RecordingSettings_getByAppId
      security:
        - developer_hapikey: []
    post:
      tags:
        - Recording_Settings
      operationId: RecordingSettings_setCallRecording
      security:
        - developer_hapikey: []
    patch:
      tags:
        - Recording_Settings
      operationId: RecordingSettings_updateCallingSettings
      security:
        - developer_hapikey: []
  /crm/v3/objects/quotes/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of quotes by internal ID, or unique property values
      operationId: Batch_readQuotesByPropertyValues
      security:
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/quotes/{quoteId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readQuoteById
      security:
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read an Object identified by `{quoteId}`. `{quoteId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveQuoteObject
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
      description: Move an Object identified by `{quoteId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateQuoteObject
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
      description: >-
        Perform a partial update of an Object identified by `{quoteId}`.
        `{quoteId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/quotes/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two quotes with same type
      operationId: PublicObject_mergeTwoQuotesSameType
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
  /crm/v3/objects/quotes/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of quotes by ID
      operationId: Batch_archiveQuotesByIdBatch
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
  /crm/v3/objects/quotes/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of quotes
      operationId: Batch_createQuotesBatch
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
  /crm/v3/objects/quotes/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of quotes
      operationId: Batch_updateQuotesBatch
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
  /crm/v3/objects/quotes/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteContact
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/quotes:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listQuotesPage
      security:
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read a page of quotes. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createQuoteObject
      security:
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
      description: >-
        Create a quote with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard quotes is provided.
  /crm/v3/objects/quotes/search:
    post:
      tags:
        - Search
      operationId: Search_quotesByCriteria
      security:
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/deals/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of deals by internal ID, or unique property values
      operationId: Batch_readDealsByInternalIdOrPropertyValues
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
  /crm/v3/objects/deals/{dealId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readDealById
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
      description: >-
        Read an Object identified by `{dealId}`. `{dealId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveDealObject
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
      description: Move an Object identified by `{dealId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateDealObject
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
      description: >-
        Perform a partial update of an Object identified by `{dealId}`.
        `{dealId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/deals/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two deals with same type
      operationId: PublicObject_mergeDealsSameType
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of deals by ID
      operationId: Batch_archiveDealsByIds
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of deals
      operationId: Batch_createDealsObject
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of deals
      operationId: Batch_updateDealsObjects
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteDeal
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/deals:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_getDealsPage
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
      description: >-
        Read a page of deals. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createDealObject
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
      description: >-
        Create a deal with the given properties and return a copy of the object,
        including the ID. Documentation and examples for creating standard deals
        is provided.
  /crm/v3/objects/deals/search:
    post:
      tags:
        - Search
      operationId: Search_dealsByCriteria
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/imports/{importId}/cancel:
    post:
      tags:
        - Core
      summary: Cancel an active import
      operationId: Core_cancelImport
      security:
        - oauth2_legacy:
            - crm.import
        - private_apps_legacy:
            - crm.import
      description: This allows a developer to cancel an active import.
  /crm/v3/imports/{importId}:
    get:
      tags:
        - Core
      summary: Get the information on any import
      operationId: Core_getImportRecord
      security:
        - oauth2_legacy:
            - crm.import
        - private_apps_legacy:
            - crm.import
      description: A complete summary of an import record, including any updates.
  /crm/v3/imports/{importId}/errors:
    get:
      tags:
        - Public_Imports
      operationId: PublicImports_getErrorDetails
      security:
        - oauth2_legacy:
            - crm.import
        - private_apps_legacy:
            - crm.import
  /crm/v3/schemas/{objectType}:
    get:
      tags:
        - Core
      summary: Get an existing schema
      operationId: Core_getExistingSchema
      security:
        - private_apps_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2_legacy:
            - crm.schemas.custom.read
      description: Returns an existing object schema.
    delete:
      tags:
        - Core
      summary: Delete a schema
      operationId: Core_deleteSchema
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      description: >-
        Deletes a schema. Any existing records of this schema must be deleted
        **first**. Otherwise this call will fail.
    patch:
      tags:
        - Core
      summary: Update a schema
      operationId: Core_updateSchemaObject
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      description: Update the details for an existing object schema.
  /crm/v3/schemas/{objectType}/associations:
    post:
      tags:
        - Core
      summary: Create an association
      operationId: Core_createAssociation
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      description: >-
        Defines a new association between the primary schema's object type and
        other object types.
  /crm/v3/schemas/{objectType}/purge:
    delete:
      tags:
        - Public_Object_Schemas
      operationId: PublicObjectSchemas_purgeObjectSchema
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      deprecated: true
  /crm/v3/schemas/{objectType}/associations/{associationIdentifier}:
    delete:
      tags:
        - Core
      summary: Remove an association
      operationId: Core_removeAssociation
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      description: Removes an existing association from a schema.
  /crm/v3/schemas:
    get:
      tags:
        - Core
      summary: Get all schemas
      operationId: Core_getAllSchemas
      security:
        - private_apps_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2_legacy:
            - crm.schemas.custom.read
      description: Returns all object schemas that have been defined for your account.
    post:
      tags:
        - Core
      summary: Create a new schema
      operationId: Core_defineObjectSchema
      security:
        - private_apps_legacy:
            - crm.schemas.custom.write
      description: >-
        Define a new object schema, along with custom properties and
        associations. The entire object schema, including its object type ID,
        properties, and associations will be returned in the response.
  /crm/v3/properties/{objectType}/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of properties
      operationId: Batch_archiveProperties
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Archive a provided list of properties. This method will return a 204 No
        Content response on success regardless of the initial state of the
        property (e.g. active, already archived, non-existent).
  /crm/v3/properties/{objectType}/groups/{groupName}:
    get:
      tags:
        - Groups
      summary: Read a property group
      operationId: Groups_readPropertyGroup
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.objects.quotes.write
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps:
            - crm.schemas.invoices.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Read a property group identified by {groupName}.
    delete:
      tags:
        - Groups
      summary: Archive a property group
      operationId: Groups_archivePropertyGroup
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: Move a property group identified by {groupName} to the recycling bin.
    patch:
      tags:
        - Groups
      summary: Update a property group
      operationId: Groups_updatePropertyGroup
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Perform a partial update of a property group identified by {groupName}.
        Provided fields will be overwritten.
  /crm/v3/properties/{objectType}/{propertyName}:
    get:
      tags:
        - Core
      summary: Read a property
      operationId: Core_readProperty
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.objects.quotes.write
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps:
            - crm.schemas.invoices.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Read a property identified by {propertyName}.
    delete:
      tags:
        - Core
      summary: Archive a property
      operationId: Core_archiveProperty
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: Move a property identified by {propertyName} to the recycling bin.
    patch:
      tags:
        - Core
      summary: Update a property
      operationId: Core_updatePropertyById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Perform a partial update of a property identified by {propertyName}.
        Provided fields will be overwritten.
  /crm/v3/properties/{objectType}/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of properties
      operationId: Batch_readProperties
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.objects.quotes.write
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps:
            - crm.schemas.invoices.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Read a provided list of properties.
  /crm/v3/properties/{objectType}/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of properties
      operationId: Batch_propertiesCreateBatch
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Create a batch of properties using the same rules as when creating an
        individual property.
  /crm/v3/properties/{objectType}:
    get:
      tags:
        - Core
      summary: Read all properties
      operationId: Core_getAllProperties
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.objects.quotes.write
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps:
            - crm.schemas.invoices.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read all existing properties for the specified object type and HubSpot
        account.
    post:
      tags:
        - Core
      summary: Create a property
      operationId: Core_createProperty
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: >-
        Create and return a copy of a new property for the specified object
        type.
  /crm/v3/properties/{objectType}/groups:
    get:
      tags:
        - Groups
      summary: Read all property groups
      operationId: Groups_readAllProperty
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - private_apps:
            - crm.objects.subscriptions.read
        - private_apps_legacy:
            - crm.objects.marketing_events.read
        - oauth2_legacy:
            - crm.objects.marketing_events.write
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
        - oauth2_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.schemas.quotes.read
        - private_apps:
            - crm.schemas.quotes.read
        - oauth2:
            - crm.objects.companies.read
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps_legacy:
            - crm.objects.marketing_events.write
        - private_apps_legacy:
            - crm.schemas.custom.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - timeline
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.subscriptions.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - crm.objects.feedback_submissions.read
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.schemas.line_items.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.schemas.line_items.read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.schemas.deals.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2:
            - crm.objects.quotes.write
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - private_apps:
            - crm.schemas.commercepayments.read
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.schemas.commercepayments.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - oauth2:
            - crm.schemas.invoices.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps:
            - crm.schemas.invoices.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read all existing property groups for the specified object type and
        HubSpot account.
    post:
      tags:
        - Groups
      summary: Create a property group
      operationId: Groups_createCopy
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets.sensitive
        - oauth2:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - crm.schemas.custom.write
        - private_apps:
            - crm.schemas.deals.write
      description: Create and return a copy of a new property group.
  /crm/v3/owners/{ownerId}:
    get:
      tags:
        - Owners
      summary: Read an owner by given `id` or `userId`
      operationId: Owners_getById
      security:
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
  /crm/v3/timeline/events/batch/create:
    post:
      tags:
        - Events
      summary: Creates multiple events
      operationId: Events_createMultipleBatch
      security:
        - oauth2_legacy:
            - tickets
        - oauth2:
            - crm.schemas.deals.write
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps_legacy:
            - timeline
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - timeline
        - private_apps:
            - crm.objects.companies.write
        - private_apps:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.companies.write
      description: >-
        Creates multiple instances of timeline events based on an event
        template. Once created, these event are immutable on the object timeline
        and cannot be modified. If the event template was configured to update
        object properties via `objectPropertyName`, this call will also attempt
        to updates those properties, or add them if they don't exist.
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}:
    get:
      tags:
        - Templates
      summary: Gets a specific event template for your app
      operationId: Templates_getSpecificEventTemplate
      security:
        - developer_hapikey: []
      description: View the current state of a specific template and its tokens.
    put:
      tags:
        - Templates
      summary: Update an existing event template
      operationId: Templates_updateEventTemplate
      security:
        - developer_hapikey: []
      description: >-
        Updates an existing template and its tokens. This is primarily used to
        update the headerTemplate/detailTemplate, and those changes will take
        effect for existing events.


        You can also update or replace all the tokens in the template here
        instead of doing individual API calls on the `/tokens` endpoint.
    delete:
      tags:
        - Templates
      summary: Deletes an event template for the app
      operationId: Templates_deleteEventTemplate
      security:
        - developer_hapikey: []
      description: >-
        This will delete the event template. All associated events will be
        removed from search results and the timeline UI.


        This action can't be undone, so it's highly recommended that you stop
        using any associated events before deleting a template.
  /crm/v3/timeline/events:
    post:
      tags:
        - Events
      summary: Create a single event
      operationId: Events_createSingleEvent
      security:
        - oauth2_legacy:
            - tickets
        - oauth2:
            - crm.schemas.deals.write
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps_legacy:
            - timeline
        - oauth2:
            - crm.schemas.contacts.write
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.schemas.companies.write
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.schemas.contacts.write
        - private_apps:
            - crm.schemas.companies.write
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - timeline
        - private_apps:
            - crm.objects.companies.write
        - private_apps:
            - crm.schemas.deals.write
        - oauth2:
            - crm.objects.companies.write
      description: >-
        Creates an instance of a timeline event based on an event template. Once
        created, this event is immutable on the object timeline and cannot be
        modified. If the event template was configured to update object
        properties via `objectPropertyName`, this call will also attempt to
        updates those properties, or add them if they don't exist.
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens:
    post:
      tags:
        - Tokens
      summary: Adds a token to an existing event template
      operationId: Tokens_addToEventTemplate
      security:
        - developer_hapikey: []
      description: >-
        Once you've defined an event template, it's likely that you'll want to
        define tokens for it as well. You can do this on the event template
        itself or update individual tokens here.


        Event type tokens allow you to attach custom data to events displayed in
        a timeline or used for list segmentation.


        You can also use `objectPropertyName` to associate any CRM object
        properties. This will allow you to fully build out CRM objects.


        Token names should be unique across the template.
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}:
    put:
      tags:
        - Tokens
      summary: Updates an existing token on an event template
      operationId: Tokens_updateExistingTokenOnEventTemplate
      security:
        - developer_hapikey: []
      description: >-
        This will update the existing token on an event template. Name and type
        can't be changed on existing tokens.
    delete:
      tags:
        - Tokens
      summary: Removes a token from the event template
      operationId: Tokens_removeFromTemplate
      security:
        - developer_hapikey: []
      description: >-
        This will remove the token from an existing template. Existing events
        and CRM objects will still retain the token and its mapped object
        properties, but new ones will not.


        The timeline will still display this property for older CRM objects if
        it's still referenced in the template `Markdown`. New events will not.


        Any lists or reports referencing deleted tokens will no longer return
        new contacts, but old ones will still exist in the lists.
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}/detail:
    get:
      tags:
        - Events
      summary: Gets the detailTemplate as rendered
      operationId: Events_renderDetailTemplate
      security:
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.schemas.contacts.read
        - oauth2_legacy:
            - tickets
        - oauth2:
            - crm.objects.contacts.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - oauth2:
            - crm.objects.deals.read
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2_legacy:
            - timeline
      description: >-
        This will take the `detailTemplate` from the event template and return
        an object rendering the specified event. If the template references
        `extraData` that isn't found in the event, it will be ignored and we'll
        render without it.
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}:
    get:
      tags:
        - Events
      summary: Gets the event
      operationId: Events_getEventById
      security:
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.schemas.contacts.read
        - oauth2_legacy:
            - tickets
        - oauth2:
            - crm.objects.contacts.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - oauth2:
            - crm.objects.deals.read
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2_legacy:
            - timeline
      description: >-
        This returns the previously created event. It contains all existing info
        for the event, but not necessarily the CRM object.
  /crm/v3/timeline/{appId}/event-templates:
    get:
      tags:
        - Templates
      summary: List all event templates for your app
      operationId: Templates_listEventTemplates
      security:
        - developer_hapikey: []
      description: Use this to list all event templates owned by your app.
    post:
      tags:
        - Templates
      summary: Create an event template for your app
      operationId: Templates_createEventTemplateForApp
      security:
        - developer_hapikey: []
      description: >-
        Event templates define the general structure for a custom timeline
        event. This includes formatted copy for its heading and details, as well
        as any custom property definitions. The event could be something like
        viewing a video, registering for a webinar, or filling out a survey. A
        single app can define multiple event templates.


        Event templates will be created for contacts by default, but they can be
        created for companies, tickets, and deals as well.


        Each event template contains its own set of tokens and `Markdown`
        templates. These tokens can be associated with any CRM object properties
        via the `objectPropertyName` field to fully build out CRM objects.


        You must create an event template before you can create events.
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}/render:
    get:
      tags:
        - Events
      summary: Renders the header or detail as HTML
      operationId: Events_renderingHtml
      security:
        - oauth2:
            - crm.schemas.contacts.read
        - private_apps:
            - crm.schemas.contacts.read
        - oauth2_legacy:
            - tickets
        - oauth2:
            - crm.objects.contacts.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps_legacy:
            - timeline
        - oauth2:
            - crm.objects.deals.read
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.schemas.companies.read
        - oauth2:
            - crm.schemas.companies.read
        - private_apps:
            - crm.objects.deals.sensitive.read
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - private_apps_legacy:
            - tickets
        - private_apps:
            - crm.schemas.deals.read
        - oauth2:
            - crm.schemas.deals.read
        - oauth2_legacy:
            - timeline
      description: >-
        This will take either the `headerTemplate` or `detailTemplate` from the
        event template and render for the specified event as HTML. If the
        template references `extraData` that isn't found in the event, it will
        be ignored and we'll render without it.
  /crm/v3/objects/contacts/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of contacts by internal ID, or unique property values
      operationId: Batch_readContactsByProperties
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
  /crm/v3/objects/contacts/{contactId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readContactById
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      description: >-
        Read an Object identified by `{contactId}`. `{contactId}` refers to the
        internal object ID.  Control what is returned via the `properties` query
        param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveContact
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
      description: Move an Object identified by `{contactId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateContactObject
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
      description: >-
        Perform a partial update of an Object identified by `{contactId}`.
        `{contactId}` refers to the internal object ID. Provided property values
        will be overwritten. Read-only and non-existent properties will be
        ignored. Properties values can be cleared by passing an empty string.
  /crm/v3/objects/contacts/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two contacts with same type
      operationId: PublicObject_mergeContactsSameType
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of contacts by ID
      operationId: Batch_archiveContactsByIdBatch
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of contacts
      operationId: Batch_createContacts
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of contacts
      operationId: Batch_updateContactsBatch
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteContact
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/contacts:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listContactsPage
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      description: >-
        Read a page of contacts. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createContactObject
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
      description: >-
        Create a contact with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard contacts is provided.
  /crm/v3/objects/contacts/search:
    post:
      tags:
        - Search
      operationId: Search_contactsByCriteria
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/feedback_submissions/batch/read:
    post:
      tags:
        - Batch
      summary: >-
        Read a batch of feedback submissions by internal ID, or unique property
        values
      operationId: Batch_readFeedbackSubmissions
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
  /crm/v3/objects/feedback_submissions/{feedbackSubmissionId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readFeedbackSubmission
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Read an Object identified by `{feedbackSubmissionId}`.
        `{feedbackSubmissionId}` refers to the internal object ID by default, or
        optionally any unique property value as specified by the `idProperty`
        query param.  Control what is returned via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveFeedbackSubmission
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Move an Object identified by `{feedbackSubmissionId}` to the recycling
        bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateFeedbackSubmission
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Perform a partial update of an Object identified by
        `{feedbackSubmissionId}`. `{feedbackSubmissionId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param. Provided property values
        will be overwritten. Read-only and non-existent properties will be
        ignored. Properties values can be cleared by passing an empty string.
  /crm/v3/objects/feedback_submissions/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two feedback submissions with same type
      operationId: PublicObject_mergeFeedbackSubmissions
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
  /crm/v3/objects/feedback_submissions/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of feedback submissions by ID
      operationId: Batch_archiveFeedbackSubmissionsById
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
  /crm/v3/objects/feedback_submissions/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of feedback submissions
      operationId: Batch_createFeedbackSubmissions
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
  /crm/v3/objects/feedback_submissions/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of feedback submissions
      operationId: Batch_updateFeedbackSubmissions
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
  /crm/v3/objects/feedback_submissions/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteContact
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/feedback_submissions:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listFeedbackSubmissionsPage
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Read a page of feedback submissions. Control what is returned via the
        `properties` query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createFeedbackSubmission
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      description: >-
        Create a feedback submission with the given properties and return a copy
        of the object, including the ID. Documentation and examples for creating
        standard feedback submissions is provided.
  /crm/v3/objects/feedback_submissions/search:
    post:
      tags:
        - Search
      operationId: Search_feedbackSubmissions
      security:
        - oauth2_legacy: []
        - private_apps_legacy: []
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/{objectType}/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of objects by internal ID, or unique property values
      operationId: Batch_readObjectsByInternalIdOrPropertyValues
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/{objectType}/{objectId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readObjectById
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read an Object identified by `{objectId}`. `{objectId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveObject
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: Move an Object identified by `{objectId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateObject
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Perform a partial update of an Object identified by `{objectId}`.
        `{objectId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/{objectType}/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two objects with same type
      operationId: PublicObject_mergeObjectsWithType
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/{objectType}/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of objects by ID
      operationId: Batch_archiveObjectsById
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/{objectType}/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of objects
      operationId: Batch_createObjects
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/{objectType}/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of objects by internal ID, or unique property values
      operationId: Batch_updateObjectsByInternalIdOrPropertyValues
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
  /crm/v3/objects/{objectType}:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listObjectsPage
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Read a page of objects. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createCRMObject
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      description: >-
        Create a CRM object with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard objects is provided.
  /crm/v3/objects/{objectType}/search:
    post:
      tags:
        - Search
      operationId: Search_objectsByCriteria
      security:
        - oauth2_legacy:
            - media_bridge.read
        - private_apps_legacy:
            - tickets.sensitive
        - private_apps:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.subscriptions.read
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.contacts.sensitive.write
        - private_apps_legacy:
            - contacts
        - oauth2:
            - crm.objects.subscriptions.read
        - private_apps:
            - crm.objects.companies.read
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.sensitive.read
        - private_apps:
            - crm.objects.deals.sensitive.write
        - private_apps_legacy:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.users.write
        - private_apps_legacy:
            - media_bridge.read
        - private_apps:
            - crm.objects.companies.write
        - oauth2:
            - crm.objects.companies.write
        - oauth2_legacy:
            - tickets
        - private_apps:
            - crm.objects.users.read
        - private_apps_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.users.read
        - oauth2:
            - crm.objects.users.write
        - private_apps_legacy:
            - e-commerce
        - private_apps:
            - crm.objects.deals.sensitive.read
        - oauth2_legacy:
            - e-commerce
        - private_apps_legacy:
            - tickets
        - oauth2_legacy:
            - crm.objects.goals.read
        - oauth2_legacy:
            - crm.objects.custom.write
        - oauth2:
            - crm.objects.contacts.read
        - oauth2:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.commercepayments.read
        - private_apps:
            - crm.objects.companies.sensitive.write
        - private_apps:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.deals.write
        - oauth2:
            - crm.objects.invoices.read
        - private_apps:
            - crm.objects.invoices.read
        - oauth2:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.quotes.write
        - private_apps:
            - crm.objects.line_items.read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.custom.sensitive.read
        - oauth2_legacy:
            - crm.objects.custom.read
        - private_apps_legacy:
            - crm.objects.custom.read
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.custom.sensitive.write
        - private_apps:
            - crm.objects.contacts.sensitive.read
        - oauth2:
            - crm.objects.quotes.read
        - private_apps:
            - crm.objects.quotes.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/extensions/videoconferencing/settings/{appId}:
    get:
      tags:
        - Settings
      summary: Get settings
      operationId: Settings_getById
      security:
        - developer_hapikey: []
      description: >-
        Return the settings for a video conference application with the
        specified ID.
    put:
      tags:
        - Settings
      summary: Update settings
      operationId: Settings_updateVideoConferencingAppSettings
      security:
        - developer_hapikey: []
      description: >-
        Updates the settings for a video conference application with the
        specified ID.
    delete:
      tags:
        - Settings
      summary: Delete settings
      operationId: Settings_deleteVideoConferencingAppSettings
      security:
        - developer_hapikey: []
      description: >-
        Deletes the settings for a video conference application with the
        specified ID.
  /crm/v3/objects/tickets/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of tickets by internal ID, or unique property values
      operationId: Batch_readTicketsByProperties
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
  /crm/v3/objects/tickets/{ticketId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readTicketById
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: >-
        Read an Object identified by `{ticketId}`. `{ticketId}` refers to the
        internal object ID by default, or optionally any unique property value
        as specified by the `idProperty` query param.  Control what is returned
        via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveTicket
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: Move an Object identified by `{ticketId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateTicketObject
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: >-
        Perform a partial update of an Object identified by `{ticketId}`.
        `{ticketId}` refers to the internal object ID by default, or optionally
        any unique property value as specified by the `idProperty` query param.
        Provided property values will be overwritten. Read-only and non-existent
        properties will be ignored. Properties values can be cleared by passing
        an empty string.
  /crm/v3/objects/tickets/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two tickets with same type
      operationId: PublicObject_mergeTicketsSameType
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
  /crm/v3/objects/tickets/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of tickets by ID
      operationId: Batch_archiveTicketsById
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
  /crm/v3/objects/tickets/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of tickets
      operationId: Batch_ticketCreationBatch
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
  /crm/v3/objects/tickets/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of tickets
      operationId: Batch_updateTicketsBatch
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
  /crm/v3/objects/tickets/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_permanentlyDeleteContact
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/tickets:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listTicketsPage
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: >-
        Read a page of tickets. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createTicketObject
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      description: >-
        Create a ticket with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard tickets is provided.
  /crm/v3/objects/tickets/search:
    post:
      tags:
        - Search
      operationId: Search_ticketsByCriteria
      security:
        - oauth2_legacy:
            - tickets
        - oauth2: []
        - private_apps_legacy:
            - tickets
        - private_apps: []
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/line_items/batch/read:
    post:
      tags:
        - Batch
      summary: Read a batch of line items by internal ID, or unique property values
      operationId: Batch_readLineItems
      security:
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.line_items.read
  /crm/v3/objects/line_items/{lineItemId}:
    get:
      tags:
        - Basic
      summary: Read
      operationId: Basic_readLineItemById
      security:
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.line_items.read
      description: >-
        Read an Object identified by `{lineItemId}`. `{lineItemId}` refers to
        the internal object ID by default, or optionally any unique property
        value as specified by the `idProperty` query param.  Control what is
        returned via the `properties` query param.
    delete:
      tags:
        - Basic
      summary: Archive
      operationId: Basic_archiveLineItem
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
      description: Move an Object identified by `{lineItemId}` to the recycling bin.
    patch:
      tags:
        - Basic
      summary: Update
      operationId: Basic_updateLineItemObject
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
      description: >-
        Perform a partial update of an Object identified by `{lineItemId}`.
        `{lineItemId}` refers to the internal object ID by default, or
        optionally any unique property value as specified by the `idProperty`
        query param. Provided property values will be overwritten. Read-only and
        non-existent properties will be ignored. Properties values can be
        cleared by passing an empty string.
  /crm/v3/objects/line_items/merge:
    post:
      tags:
        - Public_Object
      summary: Merge two line items with same type
      operationId: PublicObject_mergeLineItemsSameType
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
  /crm/v3/objects/line_items/batch/archive:
    post:
      tags:
        - Batch
      summary: Archive a batch of line items by ID
      operationId: Batch_archiveLineItemsByIds
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
  /crm/v3/objects/line_items/batch/create:
    post:
      tags:
        - Batch
      summary: Create a batch of line items
      operationId: Batch_lineItemsCreateBatch
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
  /crm/v3/objects/line_items/batch/update:
    post:
      tags:
        - Batch
      summary: Update a batch of line items
      operationId: Batch_updateLineItems
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
  /crm/v3/objects/line_items/gdpr-delete:
    post:
      tags:
        - GDPR
      summary: GDPR DELETE
      operationId: Gdpr_deleteContactContent
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
      description: >-
        Permanently delete a contact and all associated content to follow GDPR.
        Use optional property 'idProperty' set to 'email' to identify contact by
        email address. If email address is not found, the email address will be
        added to a blocklist and prevent it from being used in the future.
  /crm/v3/objects/line_items:
    get:
      tags:
        - Basic
      summary: List
      operationId: Basic_listLineItemsPage
      security:
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.line_items.read
      description: >-
        Read a page of line items. Control what is returned via the `properties`
        query param.
    post:
      tags:
        - Basic
      summary: Create
      operationId: Basic_createLineItemObject
      security:
        - oauth2:
            - crm.objects.line_items.write
        - private_apps:
            - crm.objects.line_items.write
      description: >-
        Create a line item with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating
        standard line items is provided.
  /crm/v3/objects/line_items/search:
    post:
      tags:
        - Search
      operationId: Search_lineItemsByCriteria
      security:
        - oauth2:
            - crm.objects.line_items.read
        - private_apps:
            - crm.objects.line_items.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/imports:
    get:
      tags:
        - Core
      summary: Get active imports
      operationId: Core_getActiveImportsPage
      security:
        - oauth2_legacy:
            - crm.import
        - private_apps_legacy:
            - crm.import
      description: Returns a paged list of active imports for this account.
    post:
      tags:
        - Core
      summary: Start a new import
      operationId: Core_startImport
      security:
        - oauth2_legacy:
            - crm.import
        - private_apps_legacy:
            - crm.import
      description: >-
        Begins importing data from the specified file resources. This uploads
        the corresponding file and uses the import request object to convert
        rows in the files to objects.
  /crm/v3/owners:
    get:
      tags:
        - Owners
      summary: Get a page of owners
      operationId: Owners_getPage
      security:
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
components:
  securitySchemes:
    oauth2_legacy:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            media_bridge.read: Read media and media events
            crm.objects.goals.read: Read goals
            tickets: Read and write tickets
            crm.objects.custom.read: View custom object records
            e-commerce: e-commerce
            crm.objects.custom.write: Change custom object records
            crm.objects.feedback_submissions.read: View feedback survey submissions
            crm.objects.marketing_events.write: Write marketing events
            timeline: Create timeline events
            crm.schemas.custom.read: View custom object definitions
            crm.objects.marketing_events.read: Read marketing events
            crm.import: Create or modify all your CRM data through bulk imports
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.quotes.write: Quotes
            crm.objects.deals.read: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.deals.write: ' '
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.write: Line Items
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
            crm.objects.contacts.read: ' '
            crm.schemas.quotes.read: Quotes schemas
            crm.schemas.subscriptions.read: Read subscriptions schema
            crm.objects.users.read: Read User CRM objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.schemas.deals.read: ' '
            crm.schemas.contacts.read: ' '
            crm.schemas.commercepayments.read: Read the COMMERCE_PAYMENT properties.
            crm.objects.invoices.read: Read invoices objects
            crm.schemas.invoices.read: Read invoices schema
            crm.schemas.companies.read: ' '
            crm.schemas.line_items.read: Line Items schemas
            crm.objects.owners.read: ' '
            crm.schemas.deals.write: ' '
            crm.schemas.companies.write: ' '
            crm.schemas.contacts.write: ' '
            crm.objects.users.write: Write User CRM objects
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
    private_apps_legacy:
      type: apiKey
      name: private-app-legacy
      in: header
    private_apps:
      type: apiKey
      name: private-app
      in: header
    developer_hapikey:
      type: apiKey
      name: hapikey
      in: query
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Ruby
  - Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
