openapi: 3.0.0
info:
  title: Autonomous API
  description: Building the next evolution of actionable AI.
  version: 1.0.0
servers:
  - url: https://api.induced.ai/api/v1
tags:
  - name: Autonomous
  - name: Extraction
  - name: Task
  - name: Feedback
paths:
  /autonomous:
    post:
      tags:
        - Task
      summary: Execute an Autonomous Task
      operationId: Task_execute
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskExecuteRequest'
      responses:
        '200':
          description: Task executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskExecuteResponse'
  /autonomous/{id}:
    get:
      tags:
        - Autonomous
      summary: Get Autonomous Task Result
      operationId: Autonomous_getResult
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task result retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutonomousGetResultResponse'
  /autonomous/{id}/stop:
    post:
      tags:
        - Autonomous
      summary: Stop an Autonomous Task
      operationId: Autonomous_terminateTask
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task stopped successfully
  /autonomous/{id}/feedback:
    post:
      tags:
        - Feedback
      summary: Provide Feedback for an Autonomous Task
      operationId: Feedback_submission
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackSubmissionRequest'
      responses:
        '200':
          description: Feedback received successfully
  /extract:
    post:
      tags:
        - Extraction
      summary: Extract data from a URL
      operationId: Extraction_fromUrl
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractionFromUrlRequest'
      responses:
        '200':
          description: Data extracted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionFromUrlResponse'
  /extract/{id}:
    get:
      tags:
        - Extraction
      summary: Get extraction result
      operationId: Extraction_getResult
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Extraction result retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionGetResultResponse'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    TaskExecuteRequest:
      type: object
      properties:
        task:
          type: string
          example: Go to google and search for Elon Musk
    FeedbackSubmissionRequest:
      type: object
      properties:
        feedback:
          type: boolean
    ExtractionFromUrlRequest:
      type: object
      properties:
        url:
          type: string
        query:
          type: string
        columns:
          type: string
        limit:
          type: integer
        format:
          type: string
          enum:
            - json
            - csv
            - markdown
    TaskExecuteResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            id:
              type: string
            streamingUrl:
              type: string
            watchUrl:
              type: string
        requestId:
          type: string
        timeTaken:
          type: integer
    AutonomousGetResultResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            run:
              type: object
              properties:
                id:
                  type: string
                status:
                  type: string
                objective:
                  type: string
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      step:
                        type: string
                      status:
                        type: string
                      thought:
                        type: string
                result:
                  type: string
        requestId:
          type: string
        timeTaken:
          type: integer
    ExtractionFromUrlResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            id:
              type: string
            status:
              type: string
            objective:
              type: string
        requestId:
          type: string
        timeTaken:
          type: integer
    ExtractionGetResultResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            run:
              type: object
              properties:
                id:
                  type: string
                status:
                  type: string
                objective:
                  type: string
                url:
                  type: string
                screenshot:
                  type: string
                output:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    format:
                      type: string
                time:
                  type: number
        requestId:
          type: string
        timeTaken:
          type: integer
