openapi: 3.0.1
info:
  title: Layer2 API Specification
  description: |
    Welcome to the Layer2 Financial Developer Guide!
  version: 1.0.5
servers:
  - description: Early Adopter / Beta Instance
    url: https://alpha.layer2financial.dev/api
  - description: Sandbox - Stable API Instance
    url: https://sandbox.layer2financial.com/api
  - description: Production - Stable API Instance
    url: https://platform.layer2financial.com/api
tags:
  - description: Customer application (onboarding) management
    name: Applications
  - description: >-
      Customer management and servicing functions to allow clients to onboard,
      manage and maintain customers
    name: Customers
  - description: Deposit accounts creation and management functions
    name: Accounts/Deposits
  - description: Payment accounts creation and management functions
    name: Accounts/Payments
  - description: Counterparty creation and management functions, including remote linking
    name: Counterparty
  - description: >-
      Exchanges are used to convert funds from one currency to another. This is
      achieved by moving money between 2 platform accounts that are denominated
      in different currencies. We have eliminated the complexity of traditional
      currency trading.
    name: Exchanges
  - description: Deposits are used to move external funds into platform managed accounts
    name: Deposits
  - description: >-
      Transfer are used to move funds between two platform managed accounts that
      are denominated in the same currency. Where possible, these are always
      performed *offchain*. 
    name: Transfers
  - description: Move funds from a platform managed account to an external counter party
    name: Withdrawals
  - description: Manage your callback (webhook) subscriptions
    name: Subscriptions
  - description: Document uploading and management functions
    name: Documents
  - description: Settlement services for funds confirmation and reconciliation
    name: Settlements
paths:
  /v1/withdrawals:
    post:
      tags:
        - Withdrawals
      summary: Create Withdrawal
      operationId: Withdrawals_requestNewWithdrawal
      security:
        - OAuth2Flow:
            - withdrawals:write
      description: >-
        Request a new withdrawal. On successful request, the withdrawal must be
        accepted before it is queued for execution. Withdrawals accepted before 
  /v1/withdrawals/{id}/accept:
    post:
      tags:
        - Withdrawals
      summary: Accept Withdrawal
      operationId: Withdrawals_acceptanceOperation
      security:
        - OAuth2Flow:
            - withdrawals:write
      description: >-
        Accept a withdrawal. This will execute the withdrawal and may not be
        reversible
  /v1/transfers:
    post:
      tags:
        - Transfers
      summary: Create Transfer
      operationId: Transfers_requestNewTransfer
      security:
        - OAuth2Flow:
            - transfers:write
      description: Request a new transfer. The transfer must be accepted prior to executing
  /v1/transfers/{id}/accept:
    post:
      tags:
        - Transfers
      summary: Accept Transfer
      operationId: Transfers_acceptTransfer
      security:
        - OAuth2Flow:
            - transfers:write
      description: >-
        Accept a requested transfer. This will execute the transfer and may not
        be reversible depending on the owner of the destination account
  /v1/subscriptions:
    get:
      tags:
        - Subscriptions
      summary: Get Subscriptions
      operationId: Subscriptions_listAll
      security:
        - OAuth2Flow:
            - subscriptions:read
      description: Return all subscriptions
    post:
      tags:
        - Subscriptions
      summary: Create Subscription
      operationId: Subscriptions_createEventCallback
      security:
        - OAuth2Flow:
            - subscriptions:write
      description: Creates a new event call back subscription
  /v1/exchanges/{id}/accept:
    post:
      tags:
        - Exchanges
      summary: Accept Exchange
      operationId: Exchanges_acceptQuote
      security:
        - OAuth2Flow:
            - exchanges:write
      description: >-
        Accept an exchange quote. This will execute the exchange and is not
        reversible
  /v1/exchanges/quote:
    post:
      tags:
        - Exchanges
      summary: Create Exchange (Quote)
      operationId: Exchanges_requestQuote
      security:
        - OAuth2Flow:
            - exchanges:write
      description: >-
        Requesting an exchange is non binding, you can request as many exchanges
        as needed. Typically within your user experience tier, you are expected
        to poll this endpoint periodically when showing users quotes (e.g. every
        3 seconds). When you are ready to accept a quote, see the [accept
        exchange](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/)
        endpoint. 


        Note: Not all custodians support all order types. Where the order type
        is not possible (Quote/Market/Fix Destination/ Fix Source) an error will
        be returned. 
  /v1/exchanges/market:
    post:
      tags:
        - Exchanges
      summary: Create Exchange (Market)
      operationId: Exchanges_createMarketExchange
      security:
        - OAuth2Flow:
            - exchanges:write
      description: >-
        When requesting a market exchange, the quote received is indicative
        ONLY. This represents an approximate  rate from our liquidity providers.
        On accepting a market exchange the trade is performed at the current
        market rate which will be different to the quote presented to you.


        Note: Not all custodians support all order types. Where the order type
        is not possible (Quote/Market/Fix Destination/ Fix Source) an error will
        be returned.
  /v1/documents/{id}:
    post:
      tags:
        - Documents
      summary: Upload Document
      operationId: Documents_uploadDocument
      security:
        - OAuth2Flow:
            - applications:write
            - customers:write
      description: >-
        Uploads a document to the system. Subsequent uploads to the same id will
        overwrite previous documents.ß
  /v1/deposits:
    post:
      tags:
        - Deposits
      summary: Create Deposit
      operationId: Deposits_createRequest
      security:
        - OAuth2Flow:
            - deposits:write
      description: >-
        Create a deposit request for a platform account in order to send funds
        into the account.
  /v1/deposits/{id}/accept:
    post:
      tags:
        - Deposits
      summary: Accept Deposit
      operationId: Deposits_acceptance
      security:
        - OAuth2Flow:
            - deposits:write
      description: >-
        Accept a Deposit. This is only needed for `PULL` deposits, `PUSH`
        deposits do not need to be accepted. On acceptance, this will initiate
        the funds pull from the source counterparty. It is not reversible
  /v1/customers:
    get:
      tags:
        - Customers
      summary: Retrieve Customers
      operationId: Customers_getMatchingQuery
      security:
        - OAuth2Flow:
            - customers:read
      description: 'Retrieve customers matching the provided query parameters '
    post:
      tags:
        - Customers
      summary: Create Customer
      operationId: Customers_createNew
      security:
        - OAuth2Flow:
            - customers:write
      description: >-
        Create a new customer (individual or corporation). This operation will
        not perform KYC/KYB on your behalf, and is only available to regulated
        clients. For non regulated clients you must onboard via the application
        process
  /v1/customers/{id}/payor:
    post:
      tags:
        - Customers
      summary: Create Payor
      operationId: Customers_createPayor
      security:
        - OAuth2Flow:
            - customers:write
      description: >-
        Onboard a payor and assign them to a customer. All details are optional
        barring the ID and First/Last name
  /v1/customers/{id}/individuals:
    post:
      tags:
        - Customers
      summary: Create Individual
      operationId: Customers_addNewIndividual
      security:
        - OAuth2Flow:
            - customers:write
      description: Add a new individual/officer on a corporate customer
  /v1/counterparties:
    get:
      tags:
        - Counterparty
      summary: Retrieve Counterparties
      operationId: Counterparty_getList
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves a list of counterparties given the filter parameters provided
    post:
      tags:
        - Counterparty
      summary: Create Counterparty
      operationId: Counterparty_createNewCounterparty
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Create a new counterparty for the purpose of pulling funds into the
        platform or pushing out
  /v1/counterparties/{id}/link/details:
    post:
      tags:
        - Counterparty
      summary: Retrieve Linking Details
      operationId: Counterparty_getLinkingDetails
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Retrieve the linking instructions for embedding in a UI to launch
        account linking from providers such as MX or Plaid.
  /v1/counterparties/{id}/link/connect:
    post:
      tags:
        - Counterparty
      summary: Connect Linked Account
      operationId: Counterparty_establishConnection
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Established the connection between a counterparty and external linked
        account. 
  /v1/counterparties/{id}/link/accounts:
    post:
      tags:
        - Counterparty
      summary: Retrieve Linkable Accounts
      operationId: Counterparty_getLinkableAccounts
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Retrieve the accounts that are available for linking for a `LINKED`
        counterparty via a provider such as MX or Plaid. 
  /v1/applications:
    post:
      tags:
        - Applications
      summary: Create Application
      operationId: Applications_startNewApplication
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Start a new application to onboard a person or corporation. Once the
        application is created, proceed to add individuals and update as needed,
        and then submit once the status allows for it. 
  /v1/applications/{id}/submit:
    post:
      tags:
        - Applications
      summary: Submit Application
      operationId: Applications_submitForProcessing
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Submit the application for processing, can only be performed once the
        application status is  "READY_FOR_SUBMISSION".
  /v1/applications/{id}/individual:
    post:
      tags:
        - Applications
      summary: Add Individual
      operationId: Applications_addIndividual
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Adds an individual to the corporate application. Not applicable for
        individual applications
  /v1/applications/{id}/accesscode:
    post:
      tags:
        - Applications
      summary: Request Access Code
      operationId: Applications_generateAccessCode
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Generate an access code for use with the Layer2 Customer Onboarding
        SDK. 
  /v1/accounts/payments:
    get:
      tags:
        - Accounts/Payments
      summary: Retrieve Accounts
      operationId: AccountsPayments_getList
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves a list of accounts given the filter parameters provided
    post:
      tags:
        - Accounts/Payments
      summary: Open Payment Account
      operationId: AccountsPayments_createPaymentAccount
      security:
        - OAuth2Flow:
            - accounts:write
      description: 'Opens a new payment account for a customer. '
  /v1/accounts/payments/{id}/address:
    post:
      tags:
        - Accounts/Payments
      summary: Request Payment Address
      operationId: AccountsPayments_requestPaymentAddress
      security:
        - OAuth2Flow:
            - accounts:write
      description: >
        Returns an address that can be used to send deposits to this account. If
        payor details are provided in the request, the address is also
        associated to the payor and payment reference ID. 


        The
        [transactions](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/)
        listing provides reconciliation details per deposit, including payor
        information if provided. When auto exchange is enabled, the
        [settlements](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/)
        listing provides a fully breakdown of deposit to exchange and
        settlement. 


        The product configuration of the account will determine if the address
        being returned is fixed or temporary (rotating). This can be modified
        via the [Management Interface](https://management.layer2financial.com).
        You can read more about the address leasing model under [Leasing
        Concepts]().  

        > If no payor details are provided whn requesting an address, the
        behaviour defaults to that of a [deposit
        account](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/). 
  /v1/accounts/deposits:
    get:
      tags:
        - Accounts/Deposits
      summary: Retrieve Accounts
      operationId: AccountsDeposits_getList
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves a list of accounts given the filter parameters provided
    post:
      tags:
        - Accounts/Deposits
      summary: Open Account
      operationId: AccountsDeposits_openNewAccount
      security:
        - OAuth2Flow:
            - accounts:write
      description: Opens a new account for a customer of a given product type
  /v1/accounts/deposits/{id}/address:
    post:
      tags:
        - Accounts/Deposits
      summary: Request Address
      operationId: AccountsDeposits_requestAddress
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Generates and retrieves a usable deposit address for the Asset Type that
        is assigned to this account
  /v1/customers/{id}:
    get:
      tags:
        - Customers
      summary: Retrieve Customer
      operationId: Customers_getDetails
      security:
        - OAuth2Flow:
            - customers:read
      description: Retrieve customer details
    patch:
      tags:
        - Customers
      summary: 'Update Customer '
      operationId: Customers_updateDetails
      security:
        - OAuth2Flow:
            - customers:write
      description: >-
        Update customer details. For individuals (officers) linked to a
        corporate customer, modify the individual resource directly using
        [Update
        Individual](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/).
  /v1/customers/{id}/individuals/{individual_id}:
    get:
      tags:
        - Customers
      summary: Retrieve Individual
      operationId: Customers_getIndividualDetails
      security:
        - OAuth2Flow:
            - customers:read
      description: >-
        Retrieve individual details. This operation is only for corporate
        customers that have individual officers with access to the account
    patch:
      tags:
        - Customers
      summary: Update Individual
      operationId: Customers_updateIndividualDetails
      security:
        - OAuth2Flow:
            - customers:write
      description: >-
        Update individual details. This operation is only for corporate
        customers that have individual officers with access to the account
  /v1/counterparties/{id}:
    get:
      tags:
        - Counterparty
      summary: Retrieve Counterparty
      operationId: Counterparty_getList
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves a list of counterparties given the filter parameters provided
    patch:
      tags:
        - Counterparty
      summary: 'Update Counterparty '
      operationId: Counterparty_updateDetails
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Update Counterparty details. There are limits to what can be updated
        once the counterparty has been approved for use. 
  /v1/applications/{id}:
    get:
      tags:
        - Applications
      summary: Retrieve Application
      operationId: Applications_getDetails
      security:
        - OAuth2Flow:
            - applications:read
      description: Retrieve full details of the  application
    patch:
      tags:
        - Applications
      summary: 'Update Application '
      operationId: Applications_updateProperties
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Update applicant properties. For Individuals attached to a corporation,
        you much patch the individuals directly using [Update
        Individual](https://docs.layer2financial.com/api-docs/openapi/layer2/overview/).
  /v1/applications/{id}/individual/{individual_id}:
    delete:
      tags:
        - Applications
      summary: Delete Individual
      operationId: Applications_deleteIndividual
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Deletes an individual from a corporate application. This action is
        permanent and cannot be reversed. All related details of the individual
        (including uploaded documents) will also be deleted.
    patch:
      tags:
        - Applications
      summary: Update Individual
      operationId: Applications_updateIndividualProperties
      security:
        - OAuth2Flow:
            - applications:write
      description: >-
        Update individual properties. This applies only for corporate
        applications where individuals associated to the company need to be
        updated.
  /v1/accounts/payments/{id}:
    get:
      tags:
        - Accounts/Payments
      summary: Retrieve Payment Account
      operationId: AccountsPayments_getDetails
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves the base set of account details for a given account ID
    patch:
      tags:
        - Accounts/Payments
      summary: 'Update Account '
      operationId: AccountsPayments_updateStatus
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Update an account details. Currently only the account status can be
        updated.
  /v1/accounts/deposits/{id}:
    get:
      tags:
        - Accounts/Deposits
      summary: Retrieve Account
      operationId: AccountsDeposits_getDetails
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves the base set of account details for a given account ID
    patch:
      tags:
        - Accounts/Deposits
      summary: 'Update Account '
      operationId: AccountsDeposits_updateStatus
      security:
        - OAuth2Flow:
            - accounts:write
      description: >-
        Update an account details. Currently only the account status can be
        updated.
  /v1/withdrawals/{id}:
    get:
      tags:
        - Withdrawals
      summary: Retrieve Withdrawal
      operationId: Withdrawals_getDetails
      security:
        - OAuth2Flow:
            - transfers:read
      description: Retrieves details of a previously requested withdrawal
  /v1/transfers/{id}:
    get:
      tags:
        - Transfers
      summary: Retrieve Transfer
      operationId: Transfers_getDetails
      security:
        - OAuth2Flow:
            - transfers:read
      description: Retrieves details of a previously requested transfer
  /v1/settlements/{id}:
    get:
      tags:
        - Settlements
      summary: Retrieve Settlement
      operationId: Settlements_getDetailsByAccount
      security:
        - OAuth2Flow:
            - settlements:read
      description: >-
        Returns a detailed breakdown of an outbound settlement by account and
        customer. Filterable by source and destination accounts.
  /v1/exchanges/{id}:
    get:
      tags:
        - Exchanges
      summary: Retrieve Exchange
      operationId: Exchanges_getDetails
      security:
        - OAuth2Flow:
            - exchanges:read
      description: Retrieves details of a previously requested exchange
  /v1/documents/{id}/download:
    get:
      tags:
        - Documents
      summary: Download Document
      operationId: Documents_getDocument
      security:
        - OAuth2Flow:
            - applications:read
            - customers:read
      description: Downloads a previously upload document
  /v1/deposits/{id}:
    get:
      tags:
        - Deposits
      summary: Retrieve Deposit
      operationId: Deposits_getDetails
      security:
        - OAuth2Flow:
            - deposits:read
      description: Retrieves details of a previously requested deposit
  /v1/applications/{id}/status:
    get:
      tags:
        - Applications
      summary: Retrieve Application Status
      operationId: Applications_getStatus
      security:
        - OAuth2Flow:
            - applications:read
      description: 'Retrieve the detailed status of an application '
  /v1/accounts/payments/{id}/transactions:
    get:
      tags:
        - Accounts/Payments
      summary: Retrieve Transactions
      operationId: AccountsPayments_getTransactions
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves all transactions under the given account
  /v1/accounts/payments/{id}/transactions/{id}:
    get:
      tags:
        - Accounts/Payments
      summary: Retrieve Transaction
      operationId: AccountsPayments_getTransaction
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves details of a single transaction under the given account
  /v1/accounts/deposits/{id}/transactions:
    get:
      tags:
        - Accounts/Deposits
      summary: Retrieve Transactions
      operationId: AccountsDeposits_getTransactions
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves all transactions under the given account
  /v1/accounts/deposits/{id}/transactions/{id}:
    get:
      tags:
        - Accounts/Deposits
      summary: Retrieve Transaction
      operationId: AccountsDeposits_getTransaction
      security:
        - OAuth2Flow:
            - accounts:read
      description: Retrieves details of a single transaction under the given account
  /v1/subscriptions/{id}:
    delete:
      tags:
        - Subscriptions
      summary: Delete Subscription
      operationId: Subscriptions_deleteExistingSubscription
      security:
        - OAuth2Flow:
            - subscriptions:write
      description: Delete an existing subscription
components:
  securitySchemes:
    OAuth2Flow:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://auth.layer2financial.com/oauth2/ausbdqlx69rH6OjWd696/v1/token
          scopes:
            customers:read: View Customer Data
            customers:write: Create and Modify Customer Related Data
            accounts:read: View Account Data
            accounts:write: Create and Modify Account Related Data
            settlements:read: View Settlements Data
            applications:read: View Application Data
            applications:write: Create and Modify Application Related Data
            transfers:read: View Transfers Data
            transfers:write: Create and Modify Transfers Related Data
            withdrawals:read: View Withdrawals Data
            withdrawals:write: Create and Modify Withdrawals Related Data
            exchanges:read: View Exchanges Data
            exchanges:write: Create and Modify Exchange Related Data
            deposits:read: View Deposit Related data
            deposits:write: Create and Modify Deposit Related Data
            subscriptions:read: View Subscription Related data
            subscriptions:write: Create and Modify Subscription Related Data
