openapi: 3.0.0
info:
  title: Partner API
  description: A Semi-Private API to let third parties communicate with PayFit
  version: 1.0.0
  x-konfig-ignore:
    object-with-no-properties: true
servers:
  - description: The PayFit API production server
    url: https://partner-api.payfit.com
tags:
  - name: Company
  - name: Contract
  - name: Collaborator
paths:
  /companies/{companyId}:
    get:
      tags:
        - Company
      summary: Get Company
      operationId: GET_company
      security:
        - partner-api-oauth: []
      description: Returns the basic information of the company.
  /companies/{companyId}/accounting:
    get:
      tags:
        - Company
      summary: Get accounting data
      operationId: GET_companyAccounting
      security:
        - partner-api-oauth:
            - accounting:read
      description: >-
        Returns accounting of the company for a given month. The data is
        structured as CSV.
  /companies/{companyId}/accounting-v2:
    get:
      tags:
        - Company
      summary: Get accounting v2 data
      operationId: GET_companyAccountingV2
      security:
        - partner-api-oauth:
            - accounting:read
      description: >
        WARNING: this endpoint is in beta and is subject to changes. We
        discourage its usage in production for now.  Only available for FR and
        UK. Returns accounting data of the company for a given month. For French
        companies, the data returned is the same than the one in the automatic
        accounting exports, so the company accounting exports have to be
        configured properly in order to get details by analytical code, and by
        employee. For UK companies, the data returned is the same than the one
        in the automatic payroll journals, so the company payroll journals have
        to be configured properly in order to get details by employee or by cost
        center.
  /companies/{companyId}/payroll-status:
    get:
      tags:
        - Company
      summary: Get Payroll Status
      operationId: GET_companyPayrollStatus
      security:
        - partner-api-oauth: []
      description: Returns the payroll status on a given pay period.
  /companies/{companyId}/health-insurance-contracts:
    get:
      tags:
        - Company
      summary: List all Health Insurance contracts
      operationId: GET_healthInsuranceContracts
      security:
        - partner-api-oauth:
            - health-insurance:affiliation:read
      description: Returns all Health Insurance contracts.
  /companies/{companyId}/provident-fund-contracts:
    get:
      tags:
        - Company
      summary: List all Provident Fund contracts
      operationId: GET_providentFundContracts
      security:
        - partner-api-oauth:
            - health-insurance:affiliation:read
      description: Returns all Provident Fund contracts.
  /companies-fr/{companyId}:
    get:
      tags:
        - Company
      summary: Get Company (FR)
      operationId: Company_getBasicInfoFr
      security:
        - partner-api-oauth: []
      description: Returns the basic information of the company with french specific data.
  /companies/{companyId}/contracts:
    get:
      tags:
        - Contract
      summary: List all Contracts
      operationId: GET_contracts
      security:
        - partner-api-oauth:
            - contracts:read
      description: Returns all Contracts. This list is paginated.
  /companies/{companyId}/contracts/time:
    get:
      tags:
        - Contract
      summary: List all Worked Time by contract
      operationId: Contract_listWorkedTimeByPayPeriod
      security:
        - partner-api-oauth:
            - time:read
      description: >-
        Returns the worked time for every contract for the given pay period.
        This list is paginated.
  /companies/{companyId}/contracts/{contractId}:
    get:
      tags:
        - Contract
      summary: Get a contract
      operationId: GET_contract
      security:
        - partner-api-oauth:
            - contracts:read
      description: Returns a contract information by ID.
  /companies/{companyId}/contracts-fr:
    get:
      tags:
        - Contract
      summary: List all Contracts (FR)
      operationId: Contract_listFrenchContracts
      security:
        - partner-api-oauth:
            - contracts:read
      description: Returns all Contracts with french specific data. This list is paginated.
  /companies/{companyId}/contracts-fr/{contractId}:
    get:
      tags:
        - Contract
      summary: Get a contract (FR)
      operationId: Contract_getFrenchInfo
      security:
        - partner-api-oauth:
            - contracts:read
      description: Returns a contract information by ID with french specific data.
  /companies/{companyId}/contracts-fr/{contractId}/health-insurance:
    put:
      tags:
        - Contract
      summary: Update a Health Insurance of an employee's contract
      operationId: Contract_updateHealthInsuranceAffiliation
      security:
        - partner-api-oauth:
            - health-insurance:affiliation:write
      description: Allows the affiliation of an health insurance to an employee contract.
  /companies/{companyId}/contracts-fr/{contractId}/provident-fund:
    put:
      tags:
        - Contract
      summary: Update a Provident Fund of an employee's contract
      operationId: Contract_updateProvidentFundAffiliation
      security:
        - partner-api-oauth:
            - health-insurance:affiliation:write
      description: Allows the affiliation of a provident fund to an employee contract.
  /companies/{companyId}/collaborators:
    get:
      tags:
        - Collaborator
      summary: List all Collaborators
      operationId: GET_collaborators
      security:
        - partner-api-oauth:
            - collaborators:read
      description: Returns all Collaborators. This list is paginated.
  /companies/{companyId}/collaborators/meal-vouchers:
    get:
      tags:
        - Collaborator
      summary: List all Collaborators Meal Vouchers
      operationId: Collaborator_listMealVouchers
      security:
        - partner-api-oauth:
            - collaborators:meal-vouchers:read
      description: Returns all Collaborators Meal Vouchers for a given month.
  /companies/{companyId}/collaborators/{collaboratorId}:
    get:
      tags:
        - Collaborator
      summary: Get a collaborator
      operationId: Collaborator_getById
      security:
        - partner-api-oauth:
            - collaborators:read
      description: Returns the collaborator by ID.
  /companies/{companyId}/collaborators/{collaboratorId}/contracts/{contractId}/payslips/{payslipId}:
    get:
      tags:
        - Collaborator
      summary: Get a collaborator's payslip
      operationId: Collaborator_viewPayslip
      security:
        - partner-api-oauth:
            - contracts:payslips:read
      description: Returns a collaborator's payslip.
  /companies/{companyId}/collaborators/{collaboratorId}/payslips:
    get:
      tags:
        - Collaborator
      summary: List all collaborator's payslips
      operationId: Collaborator_listPayslips
      security:
        - partner-api-oauth:
            - contracts:payslips:read
      description: Returns all the payslips of a collaborator by ID.
components:
  securitySchemes:
    partner-api-oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.payfit.com/authorize
          tokenUrl: https://oauth.payfit.com/token
          scopes:
            contracts:read: Allow to read contracts information
            contracts:payslips:read: Allow to read payslips
            contracts:time-information:read: Allow to read time related information of contracts
            collaborators:securite-sociale:read: Deprecated. Use `collaborators:social-security:read` instead.
            collaborators:read: Read general information of collaborators.
            collaborators:contracts:read: Read contract information of collaborators.
            collaborators:management:read: Read information about organisation and management.
            collaborators:meal-vouchers:read: Read meal vouchers information of collaborators.
            collaborators:personal:read: Read personal data of collaborators.
            collaborators:social-security:read: Read the social security identifiers of collaborators.
            collaborators:legal-identity:read: Read the legal identity information of collaborators.
            collaborators:bank-info:read: Allow to read the bank info of collaborators.
            accounting:read: Allow to read company accounting information
            time:read: Allow to read time data
            time:write: Allow to write time data
            health-insurance:affiliation:read: Allow to read health insurance affiliations
            health-insurance:affiliation:write: Allow to write health insurance affiliations