openapi: 3.0.0
info:
  title: Qualtrics Survey API
  description: >-
    The Qualtrics Survey endpoints give you access to the structure of the
    surveys you create. 


    Surveys have a complex structure, and you are encouraged to become familiar
    with the structure using your brand's Qualtrics page to build surveys at
    first. Then you can query those surveys using these endpoints. 


    Once you are familiar, you can use this API to create surveys on the fly, or
    modify existing surveys in your library. 
  version: 3.0.0
  contact:
    name: Support
    url: https://www.qualtrics.com/support/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-konfig-ignore:
    object-with-no-properties: true
servers:
  - description: Canadian Data Center
    url: https://yul1.qualtrics.com/API/v3
  - description: Washington, DC Area Data Center (previously CO1)
    url: https://iad1.qualtrics.com/API/v3
  - description: San Jose, California Data Center (previously AZ)
    url: https://sjc1.qualtrics.com/API/v3
  - description: European Union Data Center (previously EU2 or EU)
    url: https://fra1.qualtrics.com/API/v3
  - description: London, United Kingdom Data Center
    url: https://lhr1.qualtrics.com/API/v3
  - description: Sydney, Australia Data Center (previously AU1)
    url: https://syd1.qualtrics.com/API/v3
  - description: Singapore Data Center
    url: https://sin1.qualtrics.com/API/v3
  - description: Tokyo, Japan Data Center
    url: https://hnd1.qualtrics.com/API/v3
  - description: US Government Data Center
    url: https://gov1.qualtrics.com/API/v3
tags:
  - description: ''
    name: Survey Quotas
  - description: ''
    name: Surveys
  - description: ''
    name: Survey Questions
  - description: ''
    name: Survey Blocks
  - description: ''
    name: Survey Flows
  - description: ''
    name: Survey Versions
  - description: ''
    name: Survey Options
  - description: ''
    name: Survey Languages
  - description: ''
    name: Survey Translations
  - description: ''
    name: Schemas
paths:
  /survey-definitions:
    post:
      tags:
        - Surveys
      summary: Create Survey
      operationId: Surveys_createDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new
        [survey](https://api.qualtrics.com/ZG9jOjg3NzY4Mg-survey-api-introduction).
  /survey-definitions/{surveyId}:
    get:
      tags:
        - Surveys
      summary: Get Survey
      operationId: Surveys_getDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve the
        [survey](https://api.qualtrics.com/ZG9jOjg3NzY4Mg-survey-api-introduction#survey-definition-api-tenets)
        definition or a specified survey format.
    delete:
      tags:
        - Surveys
      summary: Delete Survey
      operationId: Surveys_removeDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Delete a
        [survey](https://api.qualtrics.com/ZG9jOjg3NzY4Mg-survey-api-introduction).
  /survey-definitions/{surveyId}/metadata:
    get:
      tags:
        - Surveys
      summary: Get Survey Metadata
      operationId: Surveys_getMetadata
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve
        [survey](https://api.qualtrics.com/ZG9jOjg3NzY4Mg-survey-api-introduction)
        metadata.
    put:
      tags:
        - Surveys
      summary: Update Metadata
      operationId: Surveys_updateMetadata
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update
        [survey](https://api.qualtrics.com/ZG9jOjg3NzY4Mg-survey-api-introduction)
        metadata.


        <!-- theme: warning -->

        >### Date fields in this API use MySQL DateTime instead of ISO-8601.
  /survey-definitions/{surveyId}/blocks:
    post:
      tags:
        - Survey Blocks
      summary: Create Block
      operationId: SurveyBlocks_createNewBlock
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new
        [block](https://www.qualtrics.com/support/survey-platform/survey-module/block-options/block-options-overview/).
  /survey-definitions/{surveyId}/blocks/{blockId}:
    get:
      tags:
        - Survey Blocks
      summary: Get Block
      operationId: SurveyBlocks_getDefinitionBlock
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a
        [block](https://www.qualtrics.com/support/survey-platform/survey-module/block-options/block-options-overview/)
        definition.
    put:
      tags:
        - Survey Blocks
      summary: Update Block
      operationId: SurveyBlocks_updateDefinitionBlock
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update a
        [block](https://www.qualtrics.com/support/survey-platform/survey-module/block-options/block-options-overview/)
        definition.
    delete:
      tags:
        - Survey Blocks
      summary: Delete Block
      operationId: SurveyBlocks_removeBlock
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Delete a
        [block](https://www.qualtrics.com/support/survey-platform/survey-module/block-options/block-options-overview/)
        from the survey.
  /survey-definitions/{surveyId}/questions:
    get:
      tags:
        - Survey Questions
      summary: Get Questions
      operationId: SurveyQuestions_getList
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Return a list of a [survey
        questions](https://api.qualtrics.com/ZG9jOjg3NzY4Mw-example-use-cases-walkthrough#add-question-to-survey).
    post:
      tags:
        - Survey Questions
      summary: Create Question
      operationId: SurveyQuestions_createNewQuestion
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new question in the specified
        [block](https://www.qualtrics.com/support/survey-platform/survey-module/block-options/block-options-overview/)
        or the default block if not specified.
  /survey-definitions/{surveyId}/questions/{questionId}:
    get:
      tags:
        - Survey Questions
      summary: Get Question
      operationId: SurveyQuestions_getDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a
        [question](https://api.qualtrics.com/ZG9jOjg3NzY4Mw-example-use-cases-walkthrough#add-question-to-survey)
        definition.
    put:
      tags:
        - Survey Questions
      summary: Update Question
      operationId: SurveyQuestions_updateDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update a
        [question](https://api.qualtrics.com/ZG9jOjg3NzY4Mw-example-use-cases-walkthrough#add-question-to-survey)
        definition.
    delete:
      tags:
        - Survey Questions
      summary: Delete Question
      operationId: SurveyQuestions_removeQuestion
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Delete a
        [question](https://api.qualtrics.com/ZG9jOjg3NzY4Mw-example-use-cases-walkthrough#add-question-to-survey)
        from a survey.
  /survey-definitions/{surveyId}/flow:
    get:
      tags:
        - Survey Flows
      summary: Get Flow
      operationId: SurveyFlows_getFlowDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a
        [flow](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/survey-flow-overview/)
        definition.
    put:
      tags:
        - Survey Flows
      summary: Update Flow
      operationId: SurveyFlows_updateDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update a
        [flow](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/survey-flow-overview/)
        definition.
  /survey-definitions/{surveyId}/flow/{flowId}:
    put:
      tags:
        - Survey Flows
      summary: Updates Flow Element Definition
      operationId: SurveyFlows_updateFlowElementDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >
        Update
        [flow](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/survey-flow-overview/)
        by ID.


        If you're having trouble capturing single sign-on (SSO) information,
        make sure you've included all fields within the `Options` object. See
        this example:


        ```JSON

        "Options": {
         "maxAttempts": 3,
         "authenticationError": {
         "SystemMessage": {
         "Section": "Message example",
         "Message": "Test System Message"
         }
         } 
         "failedAuthenticationError": {
         "SystemMessage": {
         "Section": "Message example",
         "Message": "Test System Message"
         }
         } 
         "questionText": "{
         "SystemMessage": {
         "Section": "Question Text section example",
         "Message": "Question Text message example"
         }
         } 
         "allowRetake": "true",
         "loadExistingSession": "false"
        }
  /survey-definitions/{surveyId}/options:
    get:
      tags:
        - Survey Options
      summary: Get Options
      operationId: SurveyOptions_getOptions
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve [survey
        options](https://www.qualtrics.com/support/survey-platform/survey-module/survey-options/survey-options-overview/)
        for a survey with the `surveyId`.
    put:
      tags:
        - Survey Options
      summary: Update Options
      operationId: SurveyOptions_updateOptions
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update [survey
        options](https://www.qualtrics.com/support/survey-platform/survey-module/survey-options/survey-options-overview/)
        for a survey with the `surveyId`.
  /survey-definitions/{surveyId}/versions:
    get:
      tags:
        - Survey Versions
      summary: List Survey Versions
      operationId: SurveyVersions_list
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Return a list of all [versions of a
        survey](https://www.qualtrics.com/support/survey-platform/survey-module/survey-publishing-versions/),
        including survey metadata.
    post:
      tags:
        - Survey Versions
      summary: Create Survey Version
      operationId: SurveyVersions_createNewVersion
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new [survey
        version](https://www.qualtrics.com/support/survey-platform/survey-module/survey-publishing-versions/).
  /survey-definitions/{surveyId}/versions/{versionId}:
    get:
      tags:
        - Survey Versions
      summary: Get Survey Version
      operationId: SurveyVersions_getDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a [survey
        version](https://www.qualtrics.com/support/survey-platform/survey-module/survey-publishing-versions/)
        definition.
  /survey-definitions/{surveyId}/quotas:
    get:
      tags:
        - Survey Quotas
      summary: Get Quotas for Survey
      operationId: SurveyQuotas_getAll
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Retrieve all
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        definitions for a survey.
    post:
      tags:
        - Survey Quotas
      summary: Create Quota
      operationId: SurveyQuotas_createNewQuota
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/).
  /survey-definitions/{surveyId}/quotas/{quotaId}:
    get:
      tags:
        - Survey Quotas
      summary: Get Quota for Survey
      operationId: SurveyQuotas_getDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a specific
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        definition.
    put:
      tags:
        - Survey Quotas
      summary: Update Quota in the Given Survey
      operationId: SurveyQuotas_updateDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update a
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        definition.
    delete:
      tags:
        - Survey Quotas
      summary: Delete Quota
      operationId: SurveyQuotas_deleteQuota
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Delete a
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        from a survey.
  /survey-definitions/{surveyId}/quotagroups:
    get:
      tags:
        - Survey Quotas
      summary: Get Quota Groups for Survey
      operationId: SurveyQuotas_listQuotaGroups
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Return a list of
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        group definitions for a survey.
    post:
      tags:
        - Survey Quotas
      summary: Create Quota Group
      operationId: SurveyQuotas_createQuotaGroup
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Create a new
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        group.
  /survey-definitions/{surveyId}/quotagroups/{quotaGroupId}:
    get:
      tags:
        - Survey Quotas
      summary: Get Quota Group for Survey
      operationId: SurveyQuotas_getQuotaGroupDefinition
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Retrieve a specific
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        group definition.
    put:
      tags:
        - Survey Quotas
      summary: Update Quota Group
      operationId: SurveyQuotas_updateQuotaGroupDefinition
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Update a
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        group definition.
    delete:
      tags:
        - Survey Quotas
      summary: Delete Quota Group
      operationId: SurveyQuotas_removeQuotaGroup
      security:
        - public_oauth2:
            - write:surveys
      description: >-
        Delete a
        [quota](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/quotas/)
        group and all its quotas from a survey.
  /surveys/{surveyId}/languages:
    get:
      tags:
        - Survey Languages
      summary: Get Languages
      operationId: SurveyLanguages_getAvailableLanguages
      security:
        - public_oauth2:
            - read:surveys
      description: >-
        Returns a list of available
        [languages](https://www.qualtrics.com/support/survey-platform/getting-started/languages-in-qualtrics/)
        for a survey given the `surveyId`.
    put:
      tags:
        - Survey Languages
      summary: Update Languages
      operationId: SurveyLanguages_updateEnabledLanguages
      security:
        - public_oauth2:
            - write:surveys
      description: >+
        Updates enabled
        [languages](https://www.qualtrics.com/support/survey-platform/getting-started/languages-in-qualtrics/)
        given the `surveyId`.

        <!--From Readme-->

        For more information about using the survey APIs, see [Managing
        Surveys](../../../../docs/Guides/Common%20Tasks/managing-surveys.md).

        <!-- theme: info -->


        >### Permissions

        >**Set Survey Options** permission must be enabled for the user to
        update survey languages.

  /surveys/{surveyId}/translations/{languageCode}:
    get:
      tags:
        - Survey Translations
      summary: Get Survey Translations JSON
      operationId: SurveyTranslations_getBySurveyIdAndLanguageCode
      security:
        - public_oauth2:
            - read:surveys
      description: >
        Return a list of all fields in a survey that can be
        [translated](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/translate-survey/)
        and their existing translations given a `surveyId` and `languageCode`.

        <!--From Readme-->

        For more information about using the survey APIs, see [Managing
        Surveys](../../../../docs/Guides/Common%20Tasks/managing-surveys.md).
    put:
      tags:
        - Survey Translations
      summary: Update Survey Translations
      operationId: SurveyTranslations_updateTranslations
      security:
        - public_oauth2:
            - write:surveys
      description: >+
        Update a [survey
        translations](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/translate-survey/)
        for a given `surveyId` and `language code`. Must include existing
        translations.

        <!--From Readme-->

        For more information about using the survey APIs, see [Managing
        Surveys](../../../../docs/Guides/Common%20Tasks/managing-surveys.md).

        <!-- theme: info -->


        >### Permissions

        >**Translate Surveys** permission must be enabled for the user to update
        survey languages.

components:
  securitySchemes:
    api_token:
      description: This is a schema for x-api-token header authentication.
      type: apiKey
      name: X-API-TOKEN
      in: header
    public_oauth2:
      description: Public oauth2 schema.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{env}.qualtrics.com/api/oauth/token
          scopes:
            read:surveys: Access your surveys and survey definitions.
            write:surveys: >-
              Create or import new surveys on your behalf, or modify or delete
              your existing surveys.
        authorizationCode:
          tokenUrl: https://{env}.qualtrics.com/api/oauth/token
          scopes:
            read:surveys: Access your surveys and survey definitions.
            write:surveys: >-
              Create or import new surveys on your behalf, or modify or delete
              your existing surveys.
security:
  - api_token: []
  - public_oauth2: []
x-sap-api-type: REST
x-sap-shortText: >-
  The Survey Definition API is an advanced API that allows you to modify your
  surveys. 
x-sap-stateInfo:
  state: Active
