openapi: 3.0.2
info:
  title: Vimeo API
  description: >-
    Build something great. Vimeo's API supports flexible, high-quality video
    integration with your custom apps.
  version: '3.4'
  contact:
    url: https://developer.vimeo.com/help
  x-konfig-ignore:
    potential-incorrect-type: true
servers:
  - description: Vimeo.com
    url: https://api.vimeo.com
tags:
  - description: These are the most common methods for working with live events.
    name: Live\Essentials
  - description: Use these methods to work with live event destinations.
    name: Live\Event destinations
  - description: Use these methods to manage showcase videos.
    name: Showcases\Showcase videos
  - description: Use these methods to work with the thumbnail images of live events.
    name: Live\Event thumbnails
  - description: Use these methods to work with live event videos.
    name: Live\Event videos
  - description: Use these methods to work with user followers.
    name: Users\Followers
  - description: Use these methods to work with video chapters.
    name: Videos\Chapters
  - description: These are the most common methods for working with videos.
    name: Videos\Essentials
  - description: These are the most common methods for working with folders.
    name: Folders\Essentials
  - description: These are the most common methods for working with likes.
    name: Likes\Essentials
  - description: These are the most common methods for working with showcases.
    name: Showcases\Essentials
  - description: Use these methods to manage videos in folders.
    name: Folders\Videos
  - description: Use these methods to work with user pictures.
    name: Users\Pictures
  - description: Use these methods to work with video comments.
    name: Videos\Video comments
  - description: Use these methods to manage user interactions with a category.
    name: Categories\Users
  - description: >-
      Vimeo members with access to embed presets can include their own logo
      images in the embedded player. These custom logos can be part of an embed
      preset.

                  Use these methods to work with custom logos.
    name: Embed Presets\Custom logos
  - description: These are the most common methods for working with embed presets.
    name: Embed Presets\Essentials
  - description: Use these methods to work with On Demand genres.
    name: On Demand\Genres
  - description: Use these methods to work with regions on On Demand pages.
    name: On Demand\Regions
  - description: Use these methods to manage portfolio videos.
    name: Portfolios\Videos
  - description: Use these methods to work with credited users in videos.
    name: Videos\Credits
  - description: >-
      These are the most common methods for working with a user's Watch Later
      queue.
    name: Watch Later Queue\Essentials
  - description: >-
      Use these methods to work with webinar registrations, including signup and
      login.
    name: Webinar\Registrations
  - description: These are the most common methods for working with channels.
    name: Channels\Essentials
  - description: Use these methods to work with channel moderators.
    name: Channels\Moderators
  - description: Use these methods to work with channel subscriptions.
    name: Channels\Subscriptions and subscribers
  - description: Use these methods to work with videos in channels.
    name: Channels\Videos
  - description: These are the most common methods for working with On Demand pages.
    name: On Demand\Essentials
  - description: Use these methods to work with video text tracks.
    name: Videos\Text tracks
  - description: Use these methods to work with video thumbnails.
    name: Videos\Thumbnails
  - description: These are the most common methods for working with webinars.
    name: Webinar\Essentials
  - description: Use these methods to work with embed privacy for live events.
    name: Live\Embed privacy
  - description: Use these methods to work with associated tags.
    name: Videos\Tags
  - description: Use these methods to work with unlisted videos.
    name: Videos\Unlisted videos
  - description: Use these methods to work with video versioning.
    name: Videos\Versions
  - description: Use these methods to work with tags in channels.
    name: Channels\Tags
  - description: Use these methods to work with videos that have embed presets.
    name: Embed Presets\Videos
  - description: Use these methods to manage group members.
    name: Groups\Users
  - description: Use these methods to work with background images on an On Demand page.
    name: On Demand\Backgrounds
  - description: Use these methods to work with promotions on On Demand pages.
    name: On Demand\Promotions
  - description: >-
      Use these methods to manage custom showcase logos, or the supplementary
      images, usually logos, that appear on a showcase's page. These images
      aren't the same as showcase thumbnails, or the images that represent the
      showcase across Vimeo.
    name: Showcases\Custom showcase logos
  - description: >-
      Use these methods to manage custom thumbnail images for showcases. These
      thumbnails come from uploaded image files that aren't necessarily stills
      from a video.
    name: Showcases\Custom showcase thumbnails
  - description: Use these methods to work with animated thumbnails for videos.
    name: Videos\Animated thumbnails
  - description: Use these methods to work with videos in a category.
    name: Categories\Videos
  - description: Use these methods to work with channel categories.
    name: Channels\Categories
  - description: Use these methods to work with private channel members.
    name: Channels\Private channel members
  - description: These are the most common methods for working with groups.
    name: Groups\Essentials
  - description: Use these methods to manage group membership.
    name: Groups\Subscriptions
  - description: Use these methods to manage group videos.
    name: Groups\Videos
  - description: Use these methods to work with poster images on On Demand pages.
    name: On Demand\Posters
  - description: Use these methods to work with videos on On Demand pages.
    name: On Demand\Videos
  - description: These are the most common methods for working with portfolios.
    name: Portfolios\Essentials
  - description: These are the most common methods for working with users.
    name: Users\Essentials
  - description: Use these methods to work with video uploads.
    name: Videos\Uploads
  - description: Use these methods to work with webinar email customizations.
    name: Webinar\Emails
  - description: Use these methods to manage items in folders.
    name: Folders\Items
  - description: Use these methods to work with the activation of live events.
    name: Live\Event activation
  - description: >-
      Use these methods to work with the automated closed captions preferences
      of live events.
    name: Live\Event automated closed captions
  - description: Use these methods to work with the ending of live events.
    name: Live\Event end
  - description: Use these methods to manage a live event's low-latency option.
    name: Live\Event low latency
  - description: Use these methods to work with purchases and rentals on On Demand pages.
    name: On Demand\Purchases and rentals
  - description: Use these methods to work with On Demand seasons.
    name: On Demand\Seasons
  - description: Use these methods to work with team members.
    name: Teams\Members
  - description: Use these methods to work with a user's watch history.
    name: Users\Watch history
  - description: Use these methods to manage the whitelist of embeddable videos.
    name: Videos\Embed privacy
  - description: >-
      Use these methods to work with the video fragments for branched or
      segmented scrubbers.
    name: Videos\Fragments
  - description: These are the most common methods for working with authentication.
    name: Authentication Extras\Essentials
  - description: These are the most common methods for working with categories.
    name: Categories\Essentials
  - description: Use these methods to work with timeline events.
    name: Embed Presets\Timeline events
  - description: Use these methods to work with M3U8 playback URLs for live event streams.
    name: Live\Event M3U8 playback
  - description: These are the most common methods for making product purchases.
    name: Payments\Essentials
  - description: Use these methods to work with user analytics.
    name: Users\Analytics
  - description: Use these methods to work with user feeds.
    name: Users\Feeds
  - description: Use these methods to work with M3U8 playback URLs for live event streams.
    name: Videos\Live M3U8 playback
  - description: Use these methods to work with nondestructive trimming.
    name: Videos\Nondestructive trimming
  - description: Use these methods to work with showcase videos.
    name: Videos\Showcases
  - description: >-
      These are the most common methods for retrieving information about the
      Vimeo API.
    name: API Information\Essentials
  - description: Use these methods to perform authentication.
    name: Authentication Extras\Authenticate
  - description: Use these methods to convert authentication resources.
    name: Authentication Extras\Convert
  - description: Use these methods to exchange authentication resources.
    name: Authentication Extras\Exchange
  - description: Use these methods to work with channels in a category.
    name: Categories\Channels
  - description: Use these methods to work with groups in a category.
    name: Categories\Groups
  - description: Use these methods to work with live event sessions.
    name: Live\Event sessions
  - description: These are the most common methods for working with subscription plans.
    name: Subscription Plans\Essentials
  - description: These are the most common methods for working with tags.
    name: Tags\Essentials
  - description: These are the most common methods for working with the API tutorial.
    name: Tutorial\Essentials
  - description: Use these methods to search for users.
    name: Users\Search
  - description: Use these methods to work with video content ratings.
    name: Videos\Content ratings
  - description: Use these methods to work with Creative Commons licenses.
    name: Videos\Creative Commons
  - description: Use these methods to work with video languages.
    name: Videos\Languages
  - description: Use these methods to work with recommended videos.
    name: Videos\Recommendations
  - description: Use these methods to work with video transcripts.
    name: Videos\Transcripts
paths:
  /:
    get:
      tags:
        - API Information\Essentials
      summary: Get the API specification
      operationId: get_endpoints
      description: This method returns the full OpenAPI specification for the Vimeo API.
  /albums/{album_id}/available_videos:
    get:
      tags:
        - Showcases\Showcase videos
      summary: >-
        Get all the user's videos that can be added to or removed from a
        showcase
      operationId: ShowcasesShowcaseVideos_listInShowcase
      description: >-
        This endpoint returns every video belonging to the authenticated user
        that can be added to or removed from the specified showcase. The user
        must be the owner of the showcase.
  /categories:
    get:
      tags:
        - Categories\Essentials
      summary: Get all categories
      operationId: get_categories
      description: This method returns every available category.
  /categories/{category}:
    get:
      tags:
        - Categories\Essentials
      summary: Get a specific category
      operationId: get_category
      description: This method returns the specified category.
  /categories/{category}/channels:
    get:
      tags:
        - Categories\Channels
      summary: Get all the channels in a category
      operationId: CategoriesChannels_listInCategory
      description: >-
        This method returns every channel that belongs to the specified
        category.
  /categories/{category}/groups:
    get:
      tags:
        - Categories\Groups
      summary: Get all the groups in a category
      operationId: CategoriesGroups_getAllGroups
      description: This method returns every group that belongs to the specified category.
  /categories/{category}/videos:
    get:
      tags:
        - Categories\Videos
      summary: Get all the videos in a category
      operationId: CategoriesVideos_listVideosInCategory
      description: This method returns every video that belongs to the specified category.
  /categories/{category}/videos/{video_id}:
    get:
      tags:
        - Categories\Videos
      summary: Get a specific video in a category
      operationId: CategoriesVideos_getVideoInCategory
      description: >-
        This method returns a single video in the specified category. You can
        use this method to determine whether the video belongs to the category.
  /channels:
    get:
      tags:
        - Channels\Essentials
      summary: Get all channels
      operationId: get_channels
      description: This method returns all available channels.
    post:
      tags:
        - Channels\Essentials
      summary: Create a channel
      operationId: create_channel
      security:
        - oauth2:
            - create
      description: This method creates a new channel.
  /channels/{channel_id}:
    delete:
      tags:
        - Channels\Essentials
      summary: Delete a channel
      operationId: delete_channel
      security:
        - oauth2:
            - delete
      description: This method deletes the specified channel.
    get:
      tags:
        - Channels\Essentials
      summary: Get a specific channel
      operationId: get_channel
      description: This method returns a single channel.
    patch:
      tags:
        - Channels\Essentials
      summary: Edit a channel
      operationId: edit_channel
      security:
        - oauth2:
            - edit
      description: This method edits the specified channel.
  /channels/{channel_id}/categories:
    get:
      tags:
        - Channels\Categories
      summary: Get all the categories to which a channel belongs
      operationId: ChannelsCategories_getBelongingCategories
      description: >-
        This method returns every category to which the specified channel
        belongs.
    put:
      tags:
        - Channels\Categories
      summary: Add a channel to a list of categories
      operationId: ChannelsCategories_addChannelToMultipleCategories
      description: This method adds the specified channel to multiple categories.
  /channels/{channel_id}/categories/{category}:
    delete:
      tags:
        - Channels\Categories
      summary: Remove a channel from a category
      operationId: ChannelsCategories_removeChannelFromCategory
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a channel from the specified category. The
        authenticated user must be the owner of the channel.
    put:
      tags:
        - Channels\Categories
      summary: Add a channel to a specific category
      operationId: categorize_channel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds the specified channel to a single category. The
        authenticated user must be the owner of the channel.
  /channels/{channel_id}/moderators:
    delete:
      tags:
        - Channels\Moderators
      summary: Remove a list of moderators from a channel
      operationId: ChannelsModerators_removeMultipleFromChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method removes multiple moderators from the specified channel. The
        authenticated user must be the owner of the channel.
    get:
      tags:
        - Channels\Moderators
      summary: Get all the moderators of a channel
      operationId: ChannelsModerators_listByChannel
      description: This method returns every moderator of the specified channel.
    patch:
      tags:
        - Channels\Moderators
      summary: Replace the moderators of a channel
      operationId: ChannelsModerators_replaceModerators
      security:
        - oauth2:
            - edit
      description: >-
        This method replaces the current list of channel moderators with a new
        list. The authenticated user must be the owner of the channel and a
        follower of each requested user to add them as a channel moderator.
    put:
      tags:
        - Channels\Moderators
      summary: Add a list of moderators to a channel
      operationId: ChannelsModerators_bulkAddModerators
      security:
        - oauth2:
            - edit
      description: >-
        This method adds multiple users as moderators to the specified channel.
        Include the users by their URI as a JSON array in the body of the
        request using the **user_uri** field, like this: `[{ "user_uri":
        "/users/1234" }, { "user_uri": "/users/1235" }]`. The authenticated user
        must be a follower of a requested user to add this person as a
        moderator. For more information on batch requests like this one, see
        [Using Common Formats and
        Parameters](https://developer.vimeo.com/api/common-formats#working-with-batch-requests).
  /channels/{channel_id}/moderators/{user_id}:
    get:
      tags:
        - Channels\Moderators
      summary: Get a specific moderator of a channel
      operationId: ChannelsModerators_getSpecificModerator
      description: This method returns a single moderator of the specified channel.
    delete:
      tags:
        - Channels\Moderators
      summary: Remove a specific moderator from a channel
      operationId: ChannelsModerators_removeModerator
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a single moderator from the specified channel. The
        authenticated user must be the owner of the channel.
    put:
      tags:
        - Channels\Moderators
      summary: Add a specific moderator to a channel
      operationId: ChannelsModerators_addModeratorToChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single user as a moderator to the specified channel.
        The authenticated user must be a follower of the requested user to add
        them as a channel moderator.
  /channels/{channel_id}/privacy/users:
    get:
      tags:
        - Channels\Private channel members
      summary: Get all the users who can access a private channel
      operationId: ChannelsPrivateChannelMembers_getAccessibleUsers
      description: >-
        This method returns all the users who have access to the specified
        private channel. The authenticated user must be the owner of the
        channel.
    put:
      tags:
        - Channels\Private channel members
      summary: Permit a list of users to access a private channel
      operationId: ChannelsPrivateChannelMembers_permitUserAccess
      security:
        - oauth2:
            - edit
      description: >-
        This method gives multiple users access to the specified private
        channel. The authenticated user must be the owner of the channel.
  /channels/{channel_id}/privacy/users/{user_id}:
    delete:
      tags:
        - Channels\Private channel members
      summary: Restrict a user from accessing a private channel
      operationId: ChannelsPrivateChannelMembers_restrictUserAccess
      security:
        - oauth2:
            - edit
      description: >-
        This method prevents a single user from being able to access the
        specified private channel. The authenticated user must be the owner of
        the channel.
    put:
      tags:
        - Channels\Private channel members
      summary: Permit a specific user to access a private channel
      operationId: ChannelsPrivateChannelMembers_permitUserAccess
      security:
        - oauth2:
            - edit
      description: >-
        This method gives a single user access to the specified private channel.
        The authenticated user must be the owner of the channel.
  /channels/{channel_id}/tags:
    get:
      tags:
        - Channels\Tags
      summary: Get all the tags that have been added to a channel
      operationId: ChannelsTags_getAllChannelTags
      description: >-
        This method returns every tag that has been added to the specified
        channel.
    put:
      tags:
        - Channels\Tags
      summary: Add a list of tags to a channel
      operationId: ChannelsTags_addMultipleTagsToChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds multiple tags to the specified channel. Include the
        tags as a JSON array in the body of the request using the **tag** field,
        like this: `[{ "tag": "funny" }, { "tag": "concert" }]`. The
        authenticated user must be the owner of the channel. For more
        information on batch requests like this one, see [Using Common Formats
        and
        Parameters](https://developer.vimeo.com/api/common-formats#working-with-batch-requests).
  /channels/{channel_id}/tags/{word}:
    delete:
      tags:
        - Channels\Tags
      summary: Remove a tag from a channel
      operationId: ChannelsTags_removeTagFromChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a single tag from the specified channel. The
        authenticated user must be the owner of the channel.
    get:
      tags:
        - Channels\Tags
      summary: Check if a tag has been added to a channel
      operationId: ChannelsTags_checkIfTagAddedToChannel
      description: >-
        This method determines whether a tag has been added to the specified
        channel.
    put:
      tags:
        - Channels\Tags
      summary: Add a specific tag to a channel
      operationId: ChannelsTags_addTagToChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single tag to the specified channel. The
        authenticated user must be the owner of the channel.
  /channels/{channel_id}/users:
    get:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Get all the followers of a channel
      operationId: ChannelsSubscriptionsAndSubscribers_listChannelFollowers
      description: This method returns every follower of the specified channel.
  /channels/{channel_id}/videos:
    delete:
      tags:
        - Channels\Videos
      summary: Remove a list of videos from a channel
      operationId: ChannelsVideos_removeMultipleFromChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method removes multiple videos from the specified channel. Include
        the videos by their URI as a JSON block in the body of the request using
        the **video_uri** field, like this: `[{ "video_uri": "/videos/1234" }, {
        "video_uri": "/videos/1235" }]`. The authenticated user must be a
        moderator of the channel. For more information on batch requests like
        this one, see [Using Common Formats and
        Parameters](https://developer.vimeo.com/api/common-formats#working-with-batch-requests).
    get:
      tags:
        - Channels\Videos
      summary: Get all the videos in a channel
      operationId: ChannelsVideos_listInChannel
      description: This method returns every video in the specified channel.
    put:
      tags:
        - Channels\Videos
      summary: Add a list of videos to a channel
      operationId: ChannelsVideos_addMultipleToChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds multiple videos to the specified channel. The
        authenticated user must be a moderator of the channel.
  /channels/{channel_id}/videos/{video_id}:
    delete:
      tags:
        - Channels\Videos
      summary: Remove a specific video from a channel
      operationId: ChannelsVideos_removeSpecificVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a single video from the specified channel. The
        authenticated user must be a moderator of the channel.
    get:
      tags:
        - Channels\Videos
      summary: Get a specific video in a channel
      operationId: ChannelsVideos_getSpecificVideoInChannel
      description: >-
        This method returns a single video in the specified channel. You can use
        it to determine whether the video is in the channel.
    put:
      tags:
        - Channels\Videos
      summary: Add a specific video to a channel
      operationId: ChannelsVideos_addVideoToChannel
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single video to the specified channel. The
        authenticated user must be a moderator of the channel.
  /channels/{channel_id}/videos/{video_id}/comments:
    get:
      tags:
        - Videos\Video comments
      summary: Get all the video comments on a video
      operationId: VideosVideoComments_getAllReplies
      description: This method returns every video comment on the specified video.
    post:
      tags:
        - Videos\Video comments
      summary: Add a video comment to a video
      operationId: VideosVideoComments_addNewComment
      security:
        - oauth2:
            - interact
      description: This method adds a video comment to the specified video.
  /channels/{channel_id}/videos/{video_id}/credits:
    get:
      tags:
        - Videos\Credits
      summary: Get all the credited users in a video
      operationId: VideosCredits_getAllCreditedUsersInVideo
      description: This method returns every credited user in a video.
    post:
      tags:
        - Videos\Credits
      summary: Credit a user in a video
      operationId: VideosCredits_addUserCreditInVideo
      description: This method adds a user credit to the specified video.
  /channels/{channel_id}/videos/{video_id}/likes:
    get:
      tags:
        - Likes\Essentials
      summary: Get all the users who have liked a video
      operationId: LikesEssentials_getUsersWhoLikedVideo
      description: This method returns every user who has liked the specified video.
  /channels/{channel_id}/videos/{video_id}/pictures:
    get:
      tags:
        - Videos\Thumbnails
      summary: Get all the thumbnails of a video
      operationId: VideosThumbnails_getAllByVideoId
      description: >-
        This method returns all thumbnail images of the specified video. The
        authenticated user must have team permissions for the video.
    post:
      tags:
        - Videos\Thumbnails
      summary: Add a video thumbnail
      operationId: VideosThumbnails_addThumbnailToVideo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a thumbnail image to the specified video. The
        authenticated user must have team permissions for the video.
  /channels/{channel_id}/videos/{video_id}/privacy/users:
    get:
      tags:
        - Videos\Unlisted videos
      summary: Get the users who can access an unlisted video
      operationId: VideosUnlistedVideos_listAccessibleUsers
      description: >-
        This method returns every user who has access to the specified unlisted
        video.
    put:
      tags:
        - Videos\Unlisted videos
      summary: Permit a list of users to access an unlisted video
      operationId: VideosUnlistedVideos_grantAccessToUsers
      security:
        - oauth2:
            - edit
      description: >-
        This method gives multiple users permission to access the specified
        unlisted video. The authenticated user must be the owner of the video.
        The body of the request should follow our [batch request
        format](https://developer.vimeo.com/api/common-formats#working-with-batch-requests):
        each object must contain a single **uri** field whose value is the URI
        of the user who can access the video.
  /channels/{channel_id}/videos/{video_id}/texttracks:
    get:
      tags:
        - Videos\Text tracks
      summary: Get all the text tracks of a video
      operationId: VideosTextTracks_getAllTracks
      description: >-
        This method returns every text track of the specified video. The
        authenticated user must be the owner of the video.
    post:
      tags:
        - Videos\Text tracks
      summary: Add a text track to a video
      operationId: VideosTextTracks_addTextTrackToVideo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a text track to the specified video. For more
        information, see [Working with Text Track
        Uploads](https://developer.vimeo.com/api/upload/texttracks).
  /channels/{channel_id}/videos/{video_id}/versions:
    get:
      tags:
        - Videos\Versions
      summary: Get all the versions of a video
      operationId: VideosVersions_getAllVideoVersions
      description: >-
        This method returns every version of the specified video. The
        authenticated user must be the owner of the video.
  /contentratings:
    get:
      tags:
        - Videos\Content ratings
      summary: Get all content ratings
      operationId: VideosContentRatings_getAllContentRatings
      description: This method returns all available content ratings.
  /creativecommons:
    get:
      tags:
        - Videos\Creative Commons
      summary: Get all Creative Commons licenses
      operationId: VideosCreativeCommons_getAllCCLicenses
      description: This method returns all available Creative Commons licenses.
  /destination/{destination_id}:
    delete:
      tags:
        - Live\Event destinations
      summary: Delete a live event destination
      operationId: LiveEventDestinations_deleteDestination
      security:
        - oauth2:
            - public
      description: >-
        This method deletes the specified event destination belonging to the
        authenticated user.
    get:
      tags:
        - Live\Event destinations
      summary: Get a live event destination
      operationId: LiveEventDestinations_getDestination
      security:
        - oauth2:
            - public
      description: >-
        This method returns the specified event destination belonging to the
        authenticated user.
    patch:
      tags:
        - Live\Event destinations
      summary: Update a live event destination
      operationId: LiveEventDestinations_updateDestination
      security:
        - oauth2:
            - public
      description: >-
        This method updates the specified event destination belonging to the
        authenticated user.
  /groups:
    get:
      tags:
        - Groups\Essentials
      summary: Get all groups
      operationId: get_groups
      description: This method returns every available group.
    post:
      tags:
        - Groups\Essentials
      summary: Create a group
      operationId: create_group
      security:
        - oauth2:
            - create
      description: This method creates a new group.
  /groups/{group_id}:
    delete:
      tags:
        - Groups\Essentials
      summary: Delete a group
      operationId: delete_group
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified group. The authenticated user must be
        the owner of the group.
    get:
      tags:
        - Groups\Essentials
      summary: Get a specific group
      operationId: get_group
      description: This method returns the specified group.
  /groups/{group_id}/users:
    get:
      tags:
        - Groups\Users
      summary: Get all the members of a group
      operationId: GroupsUsers_getGroupUsers
      description: This method returns every user who belongs to the specified group.
  /groups/{group_id}/videos:
    get:
      tags:
        - Groups\Videos
      summary: Get all the videos in a group
      operationId: GroupsVideos_getAllGroupVideos
      description: This method returns every video from the specified group.
  /groups/{group_id}/videos/{video_id}:
    delete:
      tags:
        - Groups\Videos
      summary: Remove a video from a group
      operationId: GroupsVideos_removeFromGroup
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a video from the specified group. The authenticated
        user must be the owner of the group.
    get:
      tags:
        - Groups\Videos
      summary: Get a specific video in a group
      operationId: GroupsVideos_getSingleVideo
      description: >-
        This method returns a single video from the specified group. You can use
        this method to determine whether the video belongs to the group.
    put:
      tags:
        - Groups\Videos
      summary: Add a video to a group
      operationId: GroupsVideos_addToGroup
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a video to the specified group. The authenticated user
        must be the owner of the group.
  /languages:
    get:
      tags:
        - Videos\Languages
      summary: Get all languages
      operationId: get_languages
      description: This method returns all available video languages.
  /live_events:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a list of live events
      operationId: LiveEssentials_deleteMultipleEvents
      security:
        - oauth2:
            - delete
      description: This method deletes multiple events belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get all the live events that belong to the user
      operationId: LiveEssentials_getUserLiveEvents
      description: The method returns every event belonging to the authenticated user.
    post:
      tags:
        - Live\Essentials
      summary: Create a live event
      operationId: LiveEssentials_createEvent
      security:
        - oauth2:
            - create
      description: This method creates a new event for the authenticated user.
  /live_events/{live_event_id}:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a specific live event
      operationId: LiveEssentials_deleteSpecificLiveEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a single event belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get a specific live event
      operationId: LiveEssentials_getEventById
      security:
        - oauth2:
            - private
      description: This method returns a single event belonging to the authenticated user.
    patch:
      tags:
        - Live\Essentials
      summary: Update a live event
      operationId: LiveEssentials_updateEventBelongingToAuthenticatedUser
      security:
        - oauth2:
            - edit
            - private
      description: This method updates an event belonging to the authenticated user.
  /live_events/{live_event_id}/activate:
    post:
      tags:
        - Live\Event activation
      summary: Activate a live event
      operationId: LiveEventActivation_createRtmpLinks
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method creates the necessary RTMP links for the specified event.
        Begin streaming to these links to trigger the event on Vimeo. The
        authenticated user must be the owner of the event.
  /live_events/{live_event_id}/auto_cc:
    patch:
      tags:
        - Live\Event automated closed captions
      summary: Edit the automated closed captions preference of a live event
      operationId: LiveEventAutomatedClosedCaptions_editPreference
      security:
        - oauth2:
            - private
      description: >-
        This method edits the automated closed captions preference for the
        specified event.
  /live_events/{live_event_id}/end:
    post:
      tags:
        - Live\Event end
      summary: End a live event
      operationId: LiveEventEnd_eventTermination
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method ends the specified event. The authenticated user must be the
        owner of the event.
  /live_events/{live_event_id}/low_latency:
    patch:
      tags:
        - Live\Event low latency
      summary: Toggle the low-latency option of a live event
      operationId: LiveEventLowLatency_toggleOption
      security:
        - oauth2:
            - private
      description: This method toggles the low-latency option of the specified event.
  /live_events/{live_event_id}/pictures:
    get:
      tags:
        - Live\Event thumbnails
      summary: Get all the thumbnails of a live event
      operationId: LiveEventThumbnails_getAllThumbnails
      security:
        - oauth2:
            - private
      description: This method returns every thumbnail image of the specified event.
    post:
      tags:
        - Live\Event thumbnails
      summary: Create a live event thumbnail
      operationId: LiveEventThumbnails_createThumbnailForEvent
      security:
        - oauth2:
            - upload
            - private
      description: This method creates a thumbnail image for the specified event.
  /live_events/{live_event_id}/pictures/{thumbnail_id}:
    delete:
      tags:
        - Live\Event thumbnails
      summary: Delete a live event thumbnail
      operationId: LiveEventThumbnails_deleteThumbnailForEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a thumbnail image for the specified event.
    get:
      tags:
        - Live\Event thumbnails
      summary: Get a specific live event thumbnail
      operationId: LiveEventThumbnails_getSpecificThumbnail
      security:
        - oauth2:
            - private
      description: This method returns a single thumbnail image of the specified event.
    patch:
      tags:
        - Live\Event thumbnails
      summary: Edit a live event thumbnail
      operationId: LiveEventThumbnails_editLiveEventThumbnail
      security:
        - oauth2:
            - edit
            - private
      description: This method edits a thumbnail image for the specified event.
  /live_events/{live_event_id}/privacy/domains:
    get:
      tags:
        - Live\Embed privacy
      summary: Get all the domains on which a live event can be embedded
      operationId: LiveEmbedPrivacy_getWhitelistDomains
      security:
        - oauth2:
            - private
      description: >-
        This method returns every whitelisted domain for an event. The embed
        privacy setting must be `whitelist`.
    put:
      tags:
        - Live\Embed privacy
      summary: Embed a live event on one or more domains
      operationId: LiveEmbedPrivacy_embedEventOnDomains
      security:
        - oauth2:
            - edit
            - private
      description: >-
        This method embeds an event on the specified domains. The embed privacy
        setting must be `whitelist`.
  /live_events/{live_event_id}/videos:
    delete:
      tags:
        - Live\Event videos
      summary: Remove a list of videos from a live event
      operationId: LiveEventVideos_removeMultipleVideos
      security:
        - oauth2:
            - edit
            - private
      description: This method removes multiple videos from the specified event.
    get:
      tags:
        - Live\Event videos
      summary: Get all the videos in a live event
      operationId: LiveEventVideos_listLiveEventVideos
      security:
        - oauth2:
            - private
      description: This method returns every video in the specified event.
    post:
      tags:
        - Live\Event videos
      summary: Add a list of videos to a live event
      operationId: LiveEventVideos_addMultiple
      security:
        - oauth2:
            - edit
            - private
      description: This method adds multiple videos to the specified event.
  /live_events/{live_event_id}/videos/{video_id}:
    get:
      tags:
        - Live\Event videos
      summary: Get a specific video in a live event
      operationId: LiveEventVideos_specificEventVideo
      security:
        - oauth2:
            - private
      description: This method returns a single video in the specified event.
  /me:
    get:
      tags:
        - Users\Essentials
      summary: Get the user
      operationId: UsersEssentials_getUser
      description: This method returns the authenticated user.
    patch:
      tags:
        - Users\Essentials
      summary: Edit the user
      operationId: UsersEssentials_editVimeoAccount
      description: This method edits the Vimeo account of the authenticated user.
  /me/albums:
    get:
      tags:
        - Showcases\Essentials
      summary: Get all the showcases that belong to the user
      operationId: ShowcasesEssentials_getAllUserShowcases
      description: This method returns every showcase belonging to the authenticated user.
    post:
      tags:
        - Showcases\Essentials
      summary: Create a showcase
      operationId: ShowcasesEssentials_createUserShowcase
      security:
        - oauth2:
            - create
      description: This method creates a new showcase for the specified user.
  /me/albums/{album_id}:
    delete:
      tags:
        - Showcases\Essentials
      summary: Delete a showcase
      operationId: ShowcasesEssentials_deleteShowcase
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified showcase. The authenticated user must
        be the owner of the showcase.
    get:
      tags:
        - Showcases\Essentials
      summary: Get a specific showcase
      operationId: ShowcasesEssentials_getSpecificShowcase
      description: >-
        This method returns the specified showcase. The authenticated user must
        be the owner of the showcase.
    patch:
      tags:
        - Showcases\Essentials
      summary: Edit a showcase
      operationId: ShowcasesEssentials_editShowcase
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified showcase. The authenticated user must be
        the owner of the showcase.
  /me/albums/{album_id}/videos:
    get:
      tags:
        - Showcases\Showcase videos
      summary: Get all the videos in a showcase
      operationId: ShowcasesShowcaseVideos_listInShowcase
      description: >-
        This method returns every video in the specified showcase. The
        authenticated user must be the owner of the showcase.
    put:
      tags:
        - Showcases\Showcase videos
      summary: Replace all the videos in a showcase
      operationId: ShowcasesShowcaseVideos_replaceVideos
      security:
        - oauth2:
            - edit
      description: >-
        This method replaces all the videos in the specified showcase with a new
        set of one or more videos. The authenticated user must be the owner of
        the showcase.
  /me/albums/{album_id}/videos/{video_id}:
    delete:
      tags:
        - Showcases\Showcase videos
      summary: Remove a video from a showcase
      operationId: ShowcasesShowcaseVideos_removeFromShowcase
      security:
        - oauth2:
            - edit
      description: >-
        This method removes the specified video from its showcase. The
        authenticated user must be the owner of the showcase.
    get:
      tags:
        - Showcases\Showcase videos
      summary: Get a specific video in a showcase
      operationId: ShowcasesShowcaseVideos_getSpecificVideoInShowcase
      description: >-
        This method returns a single video belonging to the specified showcase.
        The authenticated user must be the owner of the showcase.
    put:
      tags:
        - Showcases\Showcase videos
      summary: Add a specific video to a showcase
      operationId: ShowcasesShowcaseVideos_addToShowcase
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single video to the specified showcase. The
        authenticated user must be the owner of the showcase.
  /me/albums/{album_id}/videos/{video_id}/set_album_thumbnail:
    post:
      tags:
        - Showcases\Showcase videos
      summary: Create a thumbnail for a showcase from a showcase video
      operationId: ShowcasesShowcaseVideos_createShowcaseThumbnail
      security:
        - oauth2:
            - edit
      description: >-
        This method creates a thumbnail image for a showcase from the specified
        frame of a showcase video. The authenticated user must be the owner of
        the showcase.
  /me/albums/{album_id}/videos/{video_id}/set_featured_video:
    patch:
      tags:
        - Showcases\Showcase videos
      summary: Set the featured video of a showcase
      operationId: ShowcasesShowcaseVideos_setFeaturedVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method sets the featured video of the specified showcase. The
        authenticated user must be the owner of the showcase, and the featured
        video must belong to it.
  /me/analytics:
    get:
      tags:
        - Users\Analytics
      summary: Get analytics for the user
      operationId: UsersAnalytics_getUserMetrics
      security:
        - oauth2:
            - stats
      description: This method returns analytic metrics for the authenticated user.
  /me/appearances:
    get:
      tags:
        - Videos\Essentials
      summary: Get all the videos in which the user appears
      operationId: VideosEssentials_getUserAppearances
      description: >-
        This method returns all the videos in which the authenticated user has a
        credited appearance.
  /me/categories:
    get:
      tags:
        - Categories\Users
      summary: Get all the categories that the user follows
      operationId: CategoriesUsers_listFollowedCategories
      security:
        - oauth2:
            - private
      description: This method returns every category that the authenticated user follows.
  /me/categories/{category}:
    delete:
      tags:
        - Categories\Users
      summary: Cause the user to stop following a category
      operationId: CategoriesUsers_stopFollowingCategory
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to stop following the
        specified category.
    get:
      tags:
        - Categories\Users
      summary: Check if the user follows a category
      operationId: CategoriesUsers_checkFollowedCategory
      security:
        - oauth2:
            - private
      description: >-
        This method determines whether the authenticated user follows the
        specified category.
    put:
      tags:
        - Categories\Users
      summary: Cause the user to follow a specific category
      operationId: CategoriesUsers_followCategory
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to follow the specified
        category.
  /me/channels:
    get:
      tags:
        - Channels\Essentials
      summary: Get all the channels to which a user subscribes
      operationId: ChannelsEssentials_getUserSubscriptions
      description: >-
        This method returns all the channels to which the specified user
        subscribes.
  /me/channels/{channel_id}:
    delete:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Unsubscribe the user from a specific channel
      operationId: ChannelsSubscriptionsAndSubscribers_unsubscribeUserFromChannel
      security:
        - oauth2:
            - interact
      description: >-
        This method unsubscribes the authenticated user from the specified
        channel.
    get:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Check if a user follows a channel
      operationId: ChannelsSubscriptionsAndSubscribers_checkIfUserFollowsChannel
      description: >-
        This method determines whether the specified user is a follower of a
        particular channel.
    put:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Subscribe the user to a specific channel
      operationId: ChannelsSubscriptionsAndSubscribers_subscribeUserToChannel
      security:
        - oauth2:
            - interact
      description: This method subscribes the authenticated user to the specified channel.
  /me/customlogos:
    get:
      tags:
        - Embed Presets\Custom logos
      summary: Get all the custom logos that belong to the user
      operationId: EmbedPresetsCustomLogos_list
      description: >-
        This method returns every custom logo that belongs to the authenticated
        user or team owner.
    post:
      tags:
        - Embed Presets\Custom logos
      summary: Add a custom user logo
      operationId: EmbedPresetsCustomLogos_addUserLogo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a custom logo representing the authenticated user for
        display in the embedded player. Be sure to use this method in the
        context of the multi-step upload procedure described in our [Working
        with Thumbnail
        Uploads](https://developer.vimeo.com/api/upload/thumbnails#uploading-a-thumbnail)
        guide. This method represents Step 2 of the procedure.
  /me/customlogos/{logo_id}:
    delete:
      tags:
        - Embed Presets\Custom logos
      summary: Delete a custom user logo
      operationId: EmbedPresetsCustomLogos_deleteUserLogo
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified custom logo belonging to the
        authenticated user.
    get:
      tags:
        - Embed Presets\Custom logos
      summary: Get a specific custom user logo
      operationId: EmbedPresetsCustomLogos_getSpecificUserLogo
      description: >-
        This method returns a single custom logo belonging to the authenticated
        user.
  /me/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all available live event destinations for the user to stream to
      operationId: LiveEventDestinations_getAllAvailableDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every available event destination for the
        authenticated user to stream to.
  /me/feed:
    get:
      tags:
        - Users\Feeds
      summary: Get all the videos in the user's feed
      operationId: UsersFeeds_getUserFeedVideos
      security:
        - oauth2:
            - private
      description: This method returns every video in the authenticated user's feed.
  /me/followers:
    get:
      tags:
        - Users\Followers
      summary: Get all the followers of the user
      operationId: UsersFollowers_listAll
      description: This method returns every follower of the authenticated user.
  /me/following:
    get:
      tags:
        - Users\Followers
      summary: Get all the users that the user is following
      operationId: UsersFollowers_listOfFollowingUsers
      description: This method returns every user that the authenticated user is following.
    post:
      tags:
        - Users\Followers
      summary: Follow a list of users
      operationId: UsersFollowers_followMultipleUsers
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to become a follower of
        multiple users. In the body of the request, specify the list of users to
        follow as

        an array of URIs, where `user01_id`, `user02_id`, `user03_id`, and so
        on, are the user IDs of the users in question:


        ```

        {
         [
             {"uri" : "/users/{user01_id}"},
             {"uri" : "/users/{user02_id}"},
             {"uri" : "/users/{user03_id}"}
         ]
        }

        ```
  /me/following/{follow_user_id}:
    delete:
      tags:
        - Users\Followers
      summary: Unfollow a user
      operationId: UsersFollowers_stopFollowingUser
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to stop following another
        user.
    get:
      tags:
        - Users\Followers
      summary: Check if the user is following another user
      operationId: UsersFollowers_checkFollowingUser
      description: >-
        This method determines whether the authenticated user is a follower of
        the specified user.
    put:
      tags:
        - Users\Followers
      summary: Follow a specific user
      operationId: UsersFollowers_followSpecificUser
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to become the follower of the
        specified user.
  /me/groups:
    get:
      tags:
        - Groups\Users
      summary: Get all the groups that the user has joined
      operationId: GroupsUsers_getUserGroups
      description: This method returns every group to which the authenticated user belongs.
  /me/groups/{group_id}:
    delete:
      tags:
        - Groups\Subscriptions
      summary: Remove the user from a group
      operationId: GroupsSubscriptions_removeUserFromGroup
      security:
        - oauth2:
            - interact
      description: >-
        This method removes the authenticated user from the specified group. The
        authenticated user can't be the owner of the group; assign a new owner
        through a PATCH request first.
    put:
      tags:
        - Groups\Subscriptions
      summary: Add the user to a group
      operationId: GroupsSubscriptions_addUserToGroup
      security:
        - oauth2:
            - interact
      description: This method adds the authenticated user to the specified group.
    get:
      tags:
        - Groups\Users
      summary: Check if a user has joined a group
      operationId: GroupsUsers_checkUserJoinedGroup
      description: >-
        This method determines whether the authenticated user belongs to the
        specified group.
  /me/likes:
    get:
      tags:
        - Likes\Essentials
      summary: Get all the videos that a user has liked
      operationId: LikesEssentials_getUserLikedVideos
      description: This method returns every video that the authenticated user has liked.
  /me/likes/{video_id}:
    delete:
      tags:
        - Likes\Essentials
      summary: Cause a user to unlike a video
      operationId: LikesEssentials_unlikeVideo
      security:
        - oauth2:
            - interact
      description: This method causes the authenticated user to unlike the specified video.
    get:
      tags:
        - Likes\Essentials
      summary: Check if the user has liked a video
      operationId: LikesEssentials_checkUserLikedVideo
      description: >-
        This method checks if the authenticated user has liked the specified
        video.
    put:
      tags:
        - Likes\Essentials
      summary: Cause the user to like a video
      operationId: LikesEssentials_likeVideo
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to like the specified video.
        The user can't like their own video.
  /me/live_events:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a list of live events
      operationId: LiveEssentials_deleteMultipleEvents
      security:
        - oauth2:
            - delete
      description: This method deletes multiple events belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get all the live events that belong to the user
      operationId: LiveEssentials_getAllUserLiveEvents
      description: The method returns every event belonging to the authenticated user.
    post:
      tags:
        - Live\Essentials
      summary: Create a live event
      operationId: LiveEssentials_createLiveEvent
      security:
        - oauth2:
            - create
      description: This method creates a new event for the authenticated user.
  /me/live_events/{live_event_id}:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a specific live event
      operationId: LiveEssentials_deleteSingleEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a single event belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get a specific live event
      operationId: LiveEssentials_getSpecificLiveEvent
      security:
        - oauth2:
            - private
      description: This method returns a single event belonging to the authenticated user.
    patch:
      tags:
        - Live\Essentials
      summary: Update a live event
      operationId: LiveEssentials_updateEventBelongingToAuthenticatedUser
      security:
        - oauth2:
            - edit
            - private
      description: This method updates an event belonging to the authenticated user.
  /me/live_events/{live_event_id}/activate:
    post:
      tags:
        - Live\Event activation
      summary: Activate a live event
      operationId: LiveEventActivation_createRtmpLinks
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method creates the necessary RTMP links for the specified event.
        Begin streaming to these links to trigger the event on Vimeo. The
        authenticated user must be the owner of the event.
  /me/live_events/{live_event_id}/auto_cc:
    patch:
      tags:
        - Live\Event automated closed captions
      summary: Edit the automated closed captions preference of a live event
      operationId: LiveEventAutomatedClosedCaptions_editPreferenceForEvent
      security:
        - oauth2:
            - private
      description: >-
        This method edits the automated closed captions preference for the
        specified event.
  /me/live_events/{live_event_id}/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all the destinations of a recurring live event
      operationId: LiveEventDestinations_listAllAvailableDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every destination of the specified event. The
        authenticated user must be the owner of the event.
    post:
      tags:
        - Live\Event destinations
      summary: Create a live event destination
      operationId: LiveEventDestinations_createDestination
      security:
        - oauth2:
            - public
      description: >-
        This method creates a destination for the specified event. The
        authenticated user must be the owner of the event.
  /me/live_events/{live_event_id}/end:
    post:
      tags:
        - Live\Event end
      summary: End a live event
      operationId: LiveEventEnd_eventTerminationAlt1
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method ends the specified event. The authenticated user must be the
        owner of the event.
  /me/live_events/{live_event_id}/low_latency:
    patch:
      tags:
        - Live\Event low latency
      summary: Toggle the low-latency option of a live event
      operationId: LiveEventLowLatency_toggleOption
      security:
        - oauth2:
            - private
      description: This method toggles the low-latency option of the specified event.
  /me/live_events/{live_event_id}/m3u8_playback:
    get:
      tags:
        - Live\Event M3U8 playback
      summary: Get an M3U8 playback URL for a live event
      operationId: LiveEventM3U8Playback_getUrl
      security:
        - oauth2:
            - private
      description: >-
        This method returns an M3U8 playback URL for the specified event stream.
        You should use this endpoint only in conjunction with our recommended
        procedure for playing events via HLS. For more information, see our [HLS
        guide](https://developer.vimeo.com/api/live/playback).
  /me/live_events/{live_event_id}/pictures:
    get:
      tags:
        - Live\Event thumbnails
      summary: Get all the thumbnails of a live event
      operationId: LiveEventThumbnails_getAll
      security:
        - oauth2:
            - private
      description: This method returns every thumbnail image of the specified event.
    post:
      tags:
        - Live\Event thumbnails
      summary: Create a live event thumbnail
      operationId: LiveEventThumbnails_addThumbnail
      security:
        - oauth2:
            - upload
            - private
      description: This method creates a thumbnail image for the specified event.
  /me/live_events/{live_event_id}/pictures/{thumbnail_id}:
    delete:
      tags:
        - Live\Event thumbnails
      summary: Delete a live event thumbnail
      operationId: LiveEventThumbnails_deleteForEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a thumbnail image for the specified event.
    get:
      tags:
        - Live\Event thumbnails
      summary: Get a specific live event thumbnail
      operationId: LiveEventThumbnails_getSpecificThumbnail
      security:
        - oauth2:
            - private
      description: This method returns a single thumbnail image of the specified event.
    patch:
      tags:
        - Live\Event thumbnails
      summary: Edit a live event thumbnail
      operationId: LiveEventThumbnails_updateEventThumbnail
      security:
        - oauth2:
            - edit
            - private
      description: This method edits a thumbnail image for the specified event.
  /me/live_events/{live_event_id}/privacy/domains:
    get:
      tags:
        - Live\Embed privacy
      summary: Get all the domains on which a live event can be embedded
      operationId: LiveEmbedPrivacy_getWhitelistDomains
      security:
        - oauth2:
            - private
      description: >-
        This method returns every whitelisted domain for an event. The embed
        privacy setting must be `whitelist`.
    put:
      tags:
        - Live\Embed privacy
      summary: Embed a live event on one or more domains
      operationId: LiveEmbedPrivacy_embedEventOnDomains
      security:
        - oauth2:
            - edit
            - private
      description: >-
        This method embeds an event on the specified domains. The embed privacy
        setting must be `whitelist`.
  /me/live_events/{live_event_id}/videos:
    delete:
      tags:
        - Live\Event videos
      summary: Remove a list of videos from a live event
      operationId: LiveEventVideos_removeMultiple
      security:
        - oauth2:
            - edit
            - private
      description: This method removes multiple videos from the specified event.
    get:
      tags:
        - Live\Event videos
      summary: Get all the videos in a live event
      operationId: LiveEventVideos_getAll
      security:
        - oauth2:
            - private
      description: This method returns every video in the specified event.
    post:
      tags:
        - Live\Event videos
      summary: Add a list of videos to a live event
      operationId: LiveEventVideos_uploadMultiple
      security:
        - oauth2:
            - edit
            - private
      description: This method adds multiple videos to the specified event.
  /me/live_events/{live_event_id}/videos/{video_id}:
    get:
      tags:
        - Live\Event videos
      summary: Get a specific video in a live event
      operationId: LiveEventVideos_specificVideo
      security:
        - oauth2:
            - private
      description: This method returns a single video in the specified event.
  /me/ondemand/pages:
    get:
      tags:
        - On Demand\Essentials
      summary: Get all the On Demand pages of the user
      operationId: OnDemandEssentials_getAllUserPages
      description: >-
        This method returns every On Demand page belonging to the authenticated
        user.
    post:
      tags:
        - On Demand\Essentials
      summary: Create an On Demand page
      operationId: OnDemandEssentials_createPage
      description: >-
        This method creates a new On Demand page for the specified user. To
        publish the page, use the
        [edit](https://developer.vimeo.com/api/reference/on-demand#edit_vod)
        method.
  /me/ondemand/purchases:
    get:
      tags:
        - On Demand\Purchases and rentals
      summary: Get all of the user's On Demand purchases and rentals
      operationId: OnDemandPurchasesAndRentals_getAllUserPurchasesAndRentals
      security:
        - oauth2:
            - purchased
      description: >-
        This method returns every purchase and rental that the authenticated
        user has made across all On Demand pages.
  /me/ondemand/purchases/{ondemand_id}:
    get:
      tags:
        - On Demand\Purchases and rentals
      summary: Check if a user has made a purchase or rental from an On Demand page
      operationId: OnDemandPurchasesAndRentals_checkUserPurchasesAndRentals
      security:
        - oauth2:
            - purchased
      description: >-
        This method determines whether the authenticated user has made a
        purchase or rental from the specified On Demand page.
  /me/payment_methods:
    get:
      tags:
        - Payments\Essentials
      summary: Get a list of all payments service payment methods
      operationId: PaymentsEssentials_listPaymentMethods
      description: >-
        This method returns a list of all Vimeo payments service payment methods
        that are available to the authenticated user.
  /me/payment_methods/{payment_method_id}:
    get:
      tags:
        - Payments\Essentials
      summary: Get information about a payments service payment method
      operationId: PaymentsEssentials_getPaymentMethodInfo
      security:
        - oauth2:
            - public
      description: >-
        This method returns information about the specified Vimeo payments
        service payment method.
  /me/pictures:
    get:
      tags:
        - Users\Pictures
      summary: Get all the pictures that belong to the user
      operationId: UsersPictures_list
      description: >-
        This method returns every portrait image belonging to the authenticated
        user.
    post:
      tags:
        - Users\Pictures
      summary: Add a picture to the user's account
      operationId: UsersPictures_addPortraitImage
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a portrait image to the authenticated user's Vimeo
        account. Send the binary data of the image file to the location that you
        receive

        from the **link** field in the response. For step-by-step instructions,
        see

        [Working with Thumbnail
        Uploads](https://developer.vimeo.com/api/upload/thumbnails#uploading-a-thumbnail-step-3).
  /me/pictures/{portraitset_id}:
    delete:
      tags:
        - Users\Pictures
      summary: Delete a picture from the user's account
      operationId: UsersPictures_removePortraitImage
      security:
        - oauth2:
            - delete
      description: >-
        This method removes the specified portrait image from the authenticated
        user's Vimeo account.
    get:
      tags:
        - Users\Pictures
      summary: Get a specific picture that belongs to the user
      operationId: UsersPictures_getSpecificPictureBelongingToUser
      description: >-
        This method returns a single portrait image belonging to the
        authenticated user.
    patch:
      tags:
        - Users\Pictures
      summary: Edit a picture in the user's account
      operationId: UsersPictures_editPortraitImage
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified portrait image belonging to the
        authenticated user.
  /me/portfolios:
    get:
      tags:
        - Portfolios\Essentials
      summary: Get all the portfolios that belong to the user
      operationId: PortfoliosEssentials_getAllUserPortfolios
      description: This method returns every portfolio belonging to the authenticated user.
  /me/portfolios/{portfolio_id}:
    get:
      tags:
        - Portfolios\Essentials
      summary: Get a specific portfolio
      operationId: PortfoliosEssentials_getUserPortfolio
      description: >-
        This method returns a single portfolio belonging to the authenticated
        user.
  /me/portfolios/{portfolio_id}/videos:
    get:
      tags:
        - Portfolios\Videos
      summary: Get all the videos in a portfolio
      operationId: PortfoliosVideos_getAllPortfolioVideos
      description: >-
        This method returns every video from the specified portfolio belonging
        to the authenticated user.
  /me/portfolios/{portfolio_id}/videos/{video_id}:
    delete:
      tags:
        - Portfolios\Videos
      summary: Remove a video from a portfolio
      operationId: PortfoliosVideos_removeFromPortfolio
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a video from the specified portfolio belonging to
        the authenticated user.
    get:
      tags:
        - Portfolios\Videos
      summary: Get a specific video in a portfolio
      operationId: PortfoliosVideos_getSpecificVideo
      description: >-
        This method returns a single video from the specified portfolio
        belonging to the authenticated user.
    put:
      tags:
        - Portfolios\Videos
      summary: Add a video to a portfolio
      operationId: PortfoliosVideos_putVideoToPortfolio
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a video to the specified portfolio belonging to the
        authenticated user.
  /me/presets:
    get:
      tags:
        - Embed Presets\Essentials
      summary: Get all the embed presets that a user has created
      operationId: EmbedPresetsEssentials_getAllUserCreatedEmbedPresets
      description: >-
        This method returns every embed preset that belongs to the authenticated
        user.
    post:
      tags:
        - Embed Presets\Essentials
      summary: Create an embed preset
      operationId: EmbedPresetsEssentials_createPreset
      description: This method creates an embed preset.
  /me/presets/{preset_id}:
    get:
      tags:
        - Embed Presets\Essentials
      summary: Get a specific embed preset
      operationId: EmbedPresetsEssentials_getSpecificPreset
      description: >-
        This method returns a single embed preset. The authenticated user must
        be the owner of the preset.
    patch:
      tags:
        - Embed Presets\Essentials
      summary: Edit an embed preset
      operationId: EmbedPresetsEssentials_editPreset
      description: >-
        This method edits the specified embed preset. The authenticated user
        must be the owner of the preset.
  /me/presets/{preset_id}/videos:
    get:
      tags:
        - Embed Presets\Videos
      summary: Get all the videos that have a specific embed preset
      operationId: EmbedPresetsVideos_getSpecificPresetVideos
      description: >-
        This method returns every video to which the specified embed preset has
        been added. The authenticated user must be the owner of videos.
  /me/projects:
    get:
      tags:
        - Folders\Essentials
      summary: Get all the folders that belong to the user
      operationId: FoldersEssentials_getAllUserFolders
      security:
        - oauth2:
            - private
      description: This method returns all the folders belonging to the authenticated user.
    post:
      tags:
        - Folders\Essentials
      summary: Create a folder
      operationId: FoldersEssentials_createFolder
      security:
        - oauth2:
            - create
      description: >-
        This method creates a new folder for the authenticated user. By default,
        this method creates a top-level folder. To create a subfolder — that is,
        to place the new folder inside an existing folder — specify the parent
        folder by URI with the **parent_folder_uri** parameter in the body of
        the request.
  /me/projects/{project_id}:
    delete:
      tags:
        - Folders\Essentials
      summary: Delete a folder
      operationId: FoldersEssentials_deleteFolder
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified folder and optionally also the videos
        that it contains. The authenticated user must be the owner of the
        folder.
    get:
      tags:
        - Folders\Essentials
      summary: Get a specific folder
      operationId: FoldersEssentials_getSpecificFolder
      description: This method returns a single folder belonging to the authenticated user.
    patch:
      tags:
        - Folders\Essentials
      summary: Edit a folder
      operationId: FoldersEssentials_editFolder
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified folder. The authenticated user must be
        the owner of the folder.
  /me/projects/{project_id}/items:
    delete:
      tags:
        - Folders\Items
      summary: Remove items from a folder
      operationId: FoldersItems_removeFromFolder
      security:
        - oauth2:
            - interact
      description: This method removes all items from the specified folder.
    get:
      tags:
        - Folders\Items
      summary: Get all the items in a folder
      operationId: FoldersItems_getFolderItems
      description: This method returns every item that belongs to the specified folder.
  /me/projects/{project_id}/videos:
    delete:
      tags:
        - Folders\Videos
      summary: Remove a list of videos from a folder
      operationId: FoldersVideos_removeMultipleFromFolder
      security:
        - oauth2:
            - interact
      description: >-
        This method removes multiple videos from the specified folder. The
        authenticated user must be the owner of the folder.
    get:
      tags:
        - Folders\Videos
      summary: Get all the videos in a folder
      operationId: FoldersVideos_getVideosInFolder
      description: This method returns all the videos that belong to the specified folder.
    put:
      tags:
        - Folders\Videos
      summary: Add a list of videos to a folder
      operationId: FoldersVideos_addMultipleToFolder
      security:
        - oauth2:
            - interact
      description: >-
        This method adds multiple videos to the specified folder. The
        authenticated user must be the owner of the folder.
  /me/projects/{project_id}/videos/{video_id}:
    delete:
      tags:
        - Folders\Videos
      summary: Remove a video from a folder
      operationId: FoldersVideos_removeSingleVideo
      security:
        - oauth2:
            - delete
      description: >-
        This method removes a single video from the specified folder. Please
        note that this doesn't delete the video itself.
    put:
      tags:
        - Folders\Videos
      summary: Add a video to a folder
      operationId: FoldersVideos_addToFolder
      security:
        - oauth2:
            - interact
      description: >-
        This method adds a single video to the specified folder. The
        authenticated user must be the owner of the folder.
  /me/videos:
    delete:
      tags:
        - Videos\Essentials
      summary: Delete a user's videos
      operationId: VideosEssentials_deleteUserVideos
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes one or more videos belonging to the specified user.
        The authenticated user must have permission to delete the videos.


        Specify the videos to delete in a comma-separated list by URI using the
        **uris** query parameter.
    get:
      tags:
        - Videos\Essentials
      summary: Get all the videos that the user has uploaded
      operationId: VideosEssentials_getAllUserVideos
      description: >-
        This method returns all the videos that the authenticated user has
        uploaded.
    post:
      tags:
        - Videos\Uploads
      summary: Upload a video
      operationId: VideosUploads_beginVideoUploadProcess
      security:
        - oauth2:
            - upload
      description: >-
        This method begins the video upload process for the authenticated user.
        For more information, see our [upload
        documentation](https://developer.vimeo.com/api/upload/videos).
  /me/videos/{video_id}:
    get:
      tags:
        - Videos\Essentials
      summary: Check if the user owns a video
      operationId: VideosEssentials_checkUserOwnsVideo
      description: >-
        This method determines whether the authenticated user is the owner of
        the specified video.
  /me/videos/{video_id}/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all the destinations of a one-time live event
      operationId: LiveEventDestinations_getAllDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every destination of the specified event. The
        authenticated user must be the owner of the event.
    post:
      tags:
        - Live\Event destinations
      summary: Create a one-time live event destination
      operationId: LiveEventDestinations_createOneTimeLiveEventDestination
      security:
        - oauth2:
            - public
      description: >-
        This method creates a destination for the specified event. The
        authenticated user must be the owner of the event.
  /me/videos/{video_id}/m3u8_playback:
    get:
      tags:
        - Videos\Live M3U8 playback
      summary: Get an M3U8 playback URL for a one-time live event
      operationId: VideosLiveM3U8Playback_getPlaybackUrl
      security:
        - oauth2:
            - private
      description: >-
        This method returns an M3U8 playback URL for the specified event stream.
        You should use this endpoint only in conjunction with our recommended
        procedure for playing events via HLS. For more information, see our [HLS
        guide](https://developer.vimeo.com/api/live/playback).
  /me/watched/videos:
    delete:
      tags:
        - Users\Watch history
      summary: Delete the user's watch history
      operationId: UsersWatchHistory_deleteEntireWatchHistory
      security:
        - oauth2:
            - delete
      description: This method deletes the entire watch history of the authenticated user.
    get:
      tags:
        - Users\Watch history
      summary: Get all the videos that a user has watched
      operationId: UsersWatchHistory_getWatchedVideos
      security:
        - oauth2:
            - private
      description: >-
        This method returns every video on the authenticated user's watch
        history. _This endpoint is deprecated. Any request to it returns empty
        data with HTTP status code 200._
  /me/watched/videos/{video_id}:
    delete:
      tags:
        - Users\Watch history
      summary: Delete a specific video from the user's watch history
      operationId: UsersWatchHistory_deleteSpecificVideo
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified video from the authenticated user's
        watch history.
  /me/watchlater:
    get:
      tags:
        - Watch Later Queue\Essentials
      summary: Get all the videos in the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_getVideosInQueue
      security:
        - oauth2:
            - private
      description: >-
        This method returns every video from the authenticated user's Watch
        Later queue.
  /me/watchlater/{video_id}:
    delete:
      tags:
        - Watch Later Queue\Essentials
      summary: Remove a video from the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_removeVideoFromQueue
      security:
        - oauth2:
            - interact
      description: >-
        This method removes the specified video from the authenticated user's
        Watch Later queue.
    get:
      tags:
        - Watch Later Queue\Essentials
      summary: Check if the user has added a video to their Watch Later queue
      operationId: WatchLaterQueueEssentials_checkVideoInQueue
      security:
        - oauth2:
            - private
      description: >-
        This method checks the authenticated user's Watch Later queue for the
        specified video.
    put:
      tags:
        - Watch Later Queue\Essentials
      summary: Add a video to the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_addVideoToQueue
      security:
        - oauth2:
            - interact
      description: >-
        This method adds the specified video to the authenticated user's Watch
        Later queue.
  /me/webinars:
    post:
      tags:
        - Webinar\Essentials
      summary: Create a webinar
      operationId: WebinarEssentials_createWebinar
      security:
        - oauth2:
            - create
      description: This method creates a new webinar for the authenticated user.
  /me/webinars/{webinar_id}:
    get:
      tags:
        - Webinar\Essentials
      summary: Get a specific webinar
      operationId: WebinarEssentials_getSpecificWebinar
      description: >-
        This method returns a single webinar belonging to the authenticated
        user.
      deprecated: true
    patch:
      tags:
        - Webinar\Essentials
      summary: Update a webinar
      operationId: WebinarEssentials_updateWebinarBelongingToAuthenticatedUser
      security:
        - oauth2:
            - edit
      description: This method updates a webinar belonging to the authenticated user.
      deprecated: true
  /me/webinars/{webinar_id}/email_settings:
    get:
      tags:
        - Webinar\Emails
      summary: Get customization email data for a webinar
      operationId: WebinarEmails_getCustomizationData
      description: >-
        This method returns customized email data for the specified webinar. The
        authenticated user must have administrative access to the webinar.
      deprecated: true
    patch:
      tags:
        - Webinar\Emails
      summary: Customize the email preferences of a webinar
      operationId: WebinarEmails_customizePreferences
      security:
        - oauth2:
            - edit
      description: >-
        This method causes the authenticated user to customize the email
        preferences of the specified webinar. The user must have administrative
        access to the webinar.
      deprecated: true
  /me/webinars/{webinar_id}/registrants:
    get:
      tags:
        - Webinar\Registrations
      summary: Get user registration data associated with a webinar
      operationId: WebinarRegistrations_getUserRegistrationsByWebinarId
      security:
        - oauth2:
            - stats
            - private
      description: >-
        This method returns the list of user registrations that is associated
        with the specified webinar and was originally submitted through a
        webinar form.
      deprecated: true
    put:
      tags:
        - Webinar\Registrations
      summary: Capture the user registration list associated with a webinar
      operationId: WebinarRegistrations_captureUserRegistrationList
      description: >-
        This method captures the user registration list associated with the
        specified webinar. A maximum of 50 registrants are permitted as part of
        the request.
      deprecated: true
  /me/webinars/{webinar_id}/registrants/{registrant_id}:
    delete:
      tags:
        - Webinar\Registrations
      summary: Delete a registrant record associated with a webinar
      operationId: WebinarRegistrations_deleteRegistrantRecord
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified registrant associated with a webinar
        and originally submitted through a webinar form.
      deprecated: true
    patch:
      tags:
        - Webinar\Registrations
      summary: Update user registration data associated with a webinar
      operationId: WebinarRegistrations_updateUserRegistrationData
      security:
        - oauth2:
            - edit
      description: >-
        This method updates the specified user registration data associated with
        a webinar and originally submitted through a webinar form.
      deprecated: true
  /oauth/access_token:
    post:
      tags:
        - Authentication Extras\Exchange
      summary: Exchange an authorization code for an access token
      operationId: AuthenticationExtrasExchange_oAuthCodeExchange
      description: >-
        This method exchanges an OAuth authorization code for an OAuth access
        token.
  /oauth/authorize/client:
    post:
      tags:
        - Authentication Extras\Authenticate
      summary: Authorize a client with OAuth
      operationId: client_auth
      description: >-
        This method uses the OAuth protocol to authorize a client. For details
        on OAuth client authorization, see our [Working with
        Authentication](/api/authentication) guide or the [OAuth
        spec](https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.4).
  /oauth/authorize/vimeo_oauth1:
    post:
      tags:
        - Authentication Extras\Convert
      summary: Convert an OAuth 1 access token to an OAuth 2 access token
      operationId: AuthenticationExtrasConvert_oAuth1ToOAuth2
      description: >-
        This method exchanges a legacy Advanced API OAuth 1 token for an API v3
        OAuth 2 token.
  /oauth/verify:
    get:
      tags:
        - Authentication Extras\Essentials
      summary: Verify an OAuth 2 access token
      operationId: verify_token
      description: This method verifies that an OAuth 2 access token exists.
  /ondemand/genres:
    get:
      tags:
        - On Demand\Genres
      summary: Get all On Demand genres
      operationId: OnDemandGenres_getAllGenres
      description: This method returns every existing On Demand genre.
  /ondemand/genres/{genre_id}:
    get:
      tags:
        - On Demand\Genres
      summary: Get a specific On Demand genre
      operationId: OnDemandGenres_specificGenreGet
      description: This method returns a single On Demand genre.
  /ondemand/genres/{genre_id}/pages:
    get:
      tags:
        - On Demand\Genres
      summary: Get all the On Demand pages in a genre
      operationId: OnDemandGenres_getAllPagesInGenre
      description: >-
        This method returns every On Demand page that belongs to the specified
        genre.
  /ondemand/genres/{genre_id}/pages/{ondemand_id}:
    get:
      tags:
        - On Demand\Genres
      summary: Get a specific On Demand page in a genre
      operationId: OnDemandGenres_getSpecificPageInGenre
      description: >-
        This method returns a single On Demand page that belongs to the
        specified genre.
  /ondemand/pages/{ondemand_id}:
    delete:
      tags:
        - On Demand\Essentials
      summary: Delete an On Demand page
      operationId: OnDemandEssentials_deleteOnDemandPage
      security:
        - oauth2:
            - delete
      description: This method deletes the specified On Demand page.
    get:
      tags:
        - On Demand\Essentials
      summary: Get a specific On Demand page
      operationId: get_vod
      description: This method returns the specified On Demand page.
    patch:
      tags:
        - On Demand\Essentials
      summary: Edit an On Demand page
      operationId: edit_vod
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified On Demand page. Use this method to
        enable preorders on the page or to publish the page.
  /ondemand/pages/{ondemand_id}/backgrounds:
    get:
      tags:
        - On Demand\Backgrounds
      summary: Get all the backgrounds on an On Demand page
      operationId: OnDemandBackgrounds_getAllBackgroundsOnPage
      description: >-
        This method returns every background image on the specified On Demand
        page. The authenticated user must be the owner of the page.
    post:
      tags:
        - On Demand\Backgrounds
      summary: Add a background to an On Demand page
      operationId: OnDemandBackgrounds_addBackgroundToPage
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a background image to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/backgrounds/{background_id}:
    delete:
      tags:
        - On Demand\Backgrounds
      summary: Delete a background on an On Demand page
      operationId: OnDemandBackgrounds_deleteBackgroundFromPage
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified background image on an On Demand page.
        The authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Backgrounds
      summary: Get a specific background on an On Demand page
      operationId: OnDemandBackgrounds_getSpecificBackground
      description: >-
        This method returns a single background image on the specified On Demand
        page. The authenticated user must be the owner of the page.
    patch:
      tags:
        - On Demand\Backgrounds
      summary: Edit a background on an On Demand page
      operationId: OnDemandBackgrounds_editBackgroundOnPage
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified background image on an On Demand page.
        The authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/genres:
    get:
      tags:
        - On Demand\Genres
      summary: Get all the genres of an On Demand page
      operationId: OnDemandGenres_getGenres
      description: >-
        This method returns every genre associated with the specified On Demand
        page.
  /ondemand/pages/{ondemand_id}/genres/{genre_id}:
    delete:
      tags:
        - On Demand\Genres
      summary: Remove a genre from an On Demand page
      operationId: OnDemandGenres_removeGenreFromPage
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a genre association from the specified On Demand
        page. The authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Genres
      summary: Check whether an On Demand page belongs to a specific genre
      operationId: OnDemandGenres_checkGenreAssociation
      description: >-
        This method determines whether an On Demand page is associated with the
        specified genre.
    put:
      tags:
        - On Demand\Genres
      summary: Add a genre to an On Demand page
      operationId: OnDemandGenres_addGenreToPage
      security:
        - oauth2:
            - edit
      description: >-
        This method adds the specified genre designation to an On Demand page. A
        page can be associated with a maximum of two genres. The authenticated
        user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/likes:
    get:
      tags:
        - Likes\Essentials
      summary: Get all the users who have liked a video on an On Demand page
      operationId: LikesEssentials_getAllUserLikes
      description: >-
        This method returns every user who has liked the specified video on an
        On Demand page.
  /ondemand/pages/{ondemand_id}/pictures:
    get:
      tags:
        - On Demand\Posters
      summary: Get all the posters on an On Demand page
      operationId: OnDemandPosters_getOnDemandPagePosters
      description: This method returns every poster on the specified On Demand page.
    post:
      tags:
        - On Demand\Posters
      summary: Add a poster to an On Demand page
      operationId: OnDemandPosters_addPosterToPage
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a poster image to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/pictures/{poster_id}:
    get:
      tags:
        - On Demand\Posters
      summary: Get a specific poster on an On Demand page
      operationId: OnDemandPosters_getSpecificPoster
      description: This method returns a single poster on the specified On Demand page.
    patch:
      tags:
        - On Demand\Posters
      summary: Edit a poster on an On Demand page
      operationId: OnDemandPosters_updatePoster
      security:
        - oauth2:
            - edit
      description: >-
        This method edits a poster image on the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/promotions:
    get:
      tags:
        - On Demand\Promotions
      summary: Get all the promotions on an On Demand page
      operationId: OnDemandPromotions_getAllPagePromotions
      security:
        - oauth2:
            - promo_codes
      description: >-
        This method returns every promotion on the specified On Demand page. The
        authenticated user must be the owner of the page.
    post:
      tags:
        - On Demand\Promotions
      summary: Add a promotion to an On Demand page
      operationId: OnDemandPromotions_addPromotionToPage
      security:
        - oauth2:
            - promo_codes
            - create
      description: >-
        This method adds a promotion to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/promotions/{promotion_id}:
    delete:
      tags:
        - On Demand\Promotions
      summary: Delete a promotion on an On Demand page
      operationId: OnDemandPromotions_deletePromotionOnPage
      security:
        - oauth2:
            - promo_codes
            - delete
      description: >-
        This method deletes a promotion on the specified On Demand page. The
        authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Promotions
      summary: Get a specific promotion on an On Demand page
      operationId: OnDemandPromotions_specificPromotionGet
      security:
        - oauth2:
            - promo_codes
      description: >-
        This method returns a single promotion on the specified On Demand page.
        The authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/promotions/{promotion_id}/codes:
    get:
      tags:
        - On Demand\Promotions
      summary: Get all the codes of a promotion on an On Demand page
      operationId: OnDemandPromotions_getAllPromotionCodes
      security:
        - oauth2:
            - promo_codes
      description: >-
        This method returns every code of the specified promotion on an On
        Demand page. The authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/regions:
    delete:
      tags:
        - On Demand\Regions
      summary: Remove a list of regions from an On Demand page
      operationId: OnDemandRegions_removeMultiple
      security:
        - oauth2:
            - edit
      description: >-
        This method removes multiple regions from the specified On Demand page.
        The authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Regions
      summary: Get all the regions on an On Demand page
      operationId: OnDemandRegions_getAll
      description: >-
        This method returns every region on the specified On Demand page. The
        authenticated user must be the owner of the page.
    put:
      tags:
        - On Demand\Regions
      summary: Add a list of regions to an On Demand page
      operationId: OnDemandRegions_addMultiple
      security:
        - oauth2:
            - edit
      description: >-
        This method adds multiple regions to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/regions/{country}:
    delete:
      tags:
        - On Demand\Regions
      summary: Remove a specific region from an On Demand page
      operationId: OnDemandRegions_removeSpecificRegion
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a single region from the specified On Demand page.
        The authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Regions
      summary: Get a specific region on an On Demand page
      operationId: OnDemandRegions_getSpecificRegion
      description: >-
        This method returns a single region on the specified On Demand page. The
        authenticated user must be the owner of the page.
    put:
      tags:
        - On Demand\Regions
      summary: Add a specific region to an On Demand page
      operationId: OnDemandRegions_addRegionToPage
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single region to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/pages/{ondemand_id}/seasons:
    get:
      tags:
        - On Demand\Seasons
      summary: Get all the seasons on an On Demand page
      operationId: OnDemandSeasons_listAll
      description: This method returns every season on the specified On Demand page.
  /ondemand/pages/{ondemand_id}/seasons/{season_id}:
    get:
      tags:
        - On Demand\Seasons
      summary: Get a specific season on an On Demand page
      operationId: OnDemandSeasons_specificGet
      description: This method returns a single season on the specified On Demand page.
  /ondemand/pages/{ondemand_id}/seasons/{season_id}/videos:
    get:
      tags:
        - On Demand\Seasons
      summary: Get all the videos in a season on an On Demand page
      operationId: OnDemandSeasons_getAllVideosInSeason
      description: >-
        This method returns every video in the specified season on an On Demand
        page.
  /ondemand/pages/{ondemand_id}/videos:
    get:
      tags:
        - On Demand\Videos
      summary: Get all the videos on an On Demand page
      operationId: OnDemandVideos_getAllVideos
      description: This method returns every video on the specified On Demand page.
  /ondemand/pages/{ondemand_id}/videos/{video_id}:
    delete:
      tags:
        - On Demand\Videos
      summary: Remove a video from an On Demand page
      operationId: OnDemandVideos_removeFromPage
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a video from the specified On Demand page. The
        authenticated user must be the owner of the page.
    get:
      tags:
        - On Demand\Videos
      summary: Get a specific video on an On Demand page
      operationId: OnDemandVideos_specificVideoGet
      description: >-
        This method returns a single video on the specified On Demand page. Use
        this method to determine whether the video is on the page.
    put:
      tags:
        - On Demand\Videos
      summary: Add a video to an On Demand page
      operationId: OnDemandVideos_addVideoToPage
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a video to the specified On Demand page. The
        authenticated user must be the owner of the page.
  /ondemand/regions:
    get:
      tags:
        - On Demand\Regions
      summary: Get all the On Demand regions
      operationId: get_regions
      description: This method returns every existing On Demand region.
  /ondemand/regions/{country}:
    get:
      tags:
        - On Demand\Regions
      summary: Get a specific On Demand region
      operationId: get_region
      description: This method returns a single On Demand region.
  /subscription_plans/{tier}:
    get:
      tags:
        - Subscription Plans\Essentials
      summary: Get a single subscription plan
      operationId: get_plan
      description: This method returns the specified subscription plan.
  /tags/{word}:
    get:
      tags:
        - Tags\Essentials
      summary: Get a tag
      operationId: get_tag
      description: This method returns the specified tag.
  /tags/{word}/videos:
    get:
      tags:
        - Videos\Tags
      summary: Get all the videos with a specific tag
      operationId: VideosTags_getAllByTag
      description: >-
        This method returns all the public videos associated with the specified
        tag.
  /teammembers/{code}:
    get:
      tags:
        - Teams\Members
      summary: Get membership information about a team
      operationId: TeamsMembers_getMembershipInformation
      description: >-
        This method returns information about the membership of the specified
        team. Usage is currently limited to the team join forms.
  /tokens:
    delete:
      tags:
        - Authentication Extras\Essentials
      summary: Revoke the current access token
      operationId: delete_token
      description: >-
        This method revokes the access token that the requesting app is
        currently using. The token must be of the OAuth 2 type.
  /tutorial:
    get:
      tags:
        - Tutorial\Essentials
      summary: Get started with the Vimeo API
      operationId: developer_tutorial
      description: >-
        This method tests whether users who are working through the [Getting
        Started](https://developer.vimeo.com/api/guides/start) guides have set
        up their configurations correctly.
  /users:
    get:
      tags:
        - Users\Search
      summary: Search for users
      operationId: search_users
      description: This method returns user search results.
  /users/{owner_id}/folders/private_to_me:
    get:
      tags:
        - Folders\Essentials
      summary: Get a user's private-to-me folder
      operationId: FoldersEssentials_getUserPrivateToMeFolder
      description: This method returns the specified private-to-me folder.
  /users/{user_id}:
    get:
      tags:
        - Users\Essentials
      summary: Get the user
      operationId: get_user
      description: This method returns the authenticated user.
    patch:
      tags:
        - Users\Essentials
      summary: Edit the user
      operationId: edit_user
      description: This method edits the Vimeo account of the authenticated user.
  /users/{user_id}/albums:
    get:
      tags:
        - Showcases\Essentials
      summary: Get all the showcases that belong to the user
      operationId: get_showcases
      description: This method returns every showcase belonging to the authenticated user.
    patch:
      tags:
        - Showcases\Essentials
      summary: Add videos and live events to showcases
      operationId: update_showcases
      security:
        - oauth2:
            - edit
      description: >-
        This method adds videos and events to the specified showcases. The
        authenticated user must either be the owner of the showcase or have team
        permissions.


        The present setup permits only one event per showcase.
    post:
      tags:
        - Showcases\Essentials
      summary: Create a showcase
      operationId: create_showcase
      security:
        - oauth2:
            - create
      description: This method creates a new showcase for the specified user.
  /users/{user_id}/albums/{album_id}:
    delete:
      tags:
        - Showcases\Essentials
      summary: Delete a showcase
      operationId: delete_showcase
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified showcase. The authenticated user must
        be the owner of the showcase.
    get:
      tags:
        - Showcases\Essentials
      summary: Get a specific showcase
      operationId: get_showcase
      description: >-
        This method returns the specified showcase. The authenticated user must
        be the owner of the showcase.
    patch:
      tags:
        - Showcases\Essentials
      summary: Edit a showcase
      operationId: edit_showcase
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified showcase. The authenticated user must be
        the owner of the showcase.
  /users/{user_id}/albums/{album_id}/custom_thumbnails:
    get:
      tags:
        - Showcases\Custom showcase thumbnails
      summary: Get all the custom thumbnails of a showcase
      operationId: ShowcasesCustomShowcaseThumbnails_list
      description: >-
        This method returns every custom thumbnail of the specified showcase.
        The authenticated user must be the owner of the showcase.
    post:
      tags:
        - Showcases\Custom showcase thumbnails
      summary: Add a custom thumbnail to a showcase
      operationId: ShowcasesCustomShowcaseThumbnails_addCustomThumbnail
      security:
        - oauth2:
            - upload
      description: >-
        This method adds an uploaded image file as a custom thumbnail for the
        specified showcase. The image doesn't need to be a still from a showcase
        video, unlike with the [standard thumbnail
        method](https://developer.vimeo.com/api/reference/albums#set_video_as_album_thumbnail).
        The authenticated user must be the owner of the showcase.


        For information on how to upload the thumbnail, see our [Working with
        Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails)
        guide, and follow the same steps.
  /users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}:
    delete:
      tags:
        - Showcases\Custom showcase thumbnails
      summary: Delete a custom showcase thumbnail
      operationId: ShowcasesCustomShowcaseThumbnails_deleteCustomThumbnail
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified custom thumbnail from its showcase.
        The authenticated user must be the owner of the showcase.
    get:
      tags:
        - Showcases\Custom showcase thumbnails
      summary: Get a specific custom showcase thumbnail
      operationId: ShowcasesCustomShowcaseThumbnails_getSpecificThumbnail
      description: >-
        This method returns a single custom thumbnail of the specified showcase.
        The authenticated user must be the owner of the showcase.
    patch:
      tags:
        - Showcases\Custom showcase thumbnails
      summary: Replace a custom showcase thumbnail
      operationId: ShowcasesCustomShowcaseThumbnails_replaceCustomThumbnail
      security:
        - oauth2:
            - edit
      description: >-
        This method replaces the specified custom showcase thumbnail with a new
        image file. The authenticated user must be the owner of the showcase.


        For information on how to upload the thumbnail, see our [Working with
        Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails)
        guide.
  /users/{user_id}/albums/{album_id}/logos:
    get:
      tags:
        - Showcases\Custom showcase logos
      summary: Get all the custom logos of a showcase
      operationId: ShowcasesCustomShowcaseLogos_listAllCustomLogos
      description: >-
        This method returns every custom logo of the specified showcase. The
        authenticated user must be the owner of the showcase.
    post:
      tags:
        - Showcases\Custom showcase logos
      summary: Add a custom logo to a showcase
      operationId: ShowcasesCustomShowcaseLogos_addCustomLogo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds an image file as a custom logo to the specified
        showcase. The authenticated user must be the owner of the showcase.


        For information on how to upload the logo, see our [Working with
        Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails)
        guide.
  /users/{user_id}/albums/{album_id}/logos/{logo_id}:
    delete:
      tags:
        - Showcases\Custom showcase logos
      summary: Delete a custom showcase logo
      operationId: ShowcasesCustomShowcaseLogos_deleteCustomLogo
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified custom logo from its showcase. The
        authenticated user must be the owner of the showcase.
    get:
      tags:
        - Showcases\Custom showcase logos
      summary: Get a specific custom showcase logo
      operationId: ShowcasesCustomShowcaseLogos_getSpecificLogo
      description: >-
        This method returns a single custom logo of the specified showcase. The
        authenticated user must be the owner of the showcase.
    patch:
      tags:
        - Showcases\Custom showcase logos
      summary: Replace a custom showcase logo
      operationId: ShowcasesCustomShowcaseLogos_replaceLogo
      security:
        - oauth2:
            - edit
      description: >-
        This method replaces the specified custom showcase logo with a new image
        file. The authenticated user must be the owner of the showcase.


        For information on how to upload the logo, see our [Working with
        Thumbnail Uploads](https://developer.vimeo.com/api/upload/thumbnails)
        guide.
  /users/{user_id}/albums/{album_id}/videos:
    get:
      tags:
        - Showcases\Showcase videos
      summary: Get all the videos in a showcase
      operationId: ShowcasesShowcaseVideos_getShowcaseVideos
      description: >-
        This method returns every video in the specified showcase. The
        authenticated user must be the owner of the showcase.
    put:
      tags:
        - Showcases\Showcase videos
      summary: Replace all the videos in a showcase
      operationId: ShowcasesShowcaseVideos_replaceShowcaseVideos
      security:
        - oauth2:
            - edit
      description: >-
        This method replaces all the videos in the specified showcase with a new
        set of one or more videos. The authenticated user must be the owner of
        the showcase.
  /users/{user_id}/albums/{album_id}/videos/{video_id}:
    delete:
      tags:
        - Showcases\Showcase videos
      summary: Remove a video from a showcase
      operationId: ShowcasesShowcaseVideos_removeVideoFromShowcase
      security:
        - oauth2:
            - edit
      description: >-
        This method removes the specified video from its showcase. The
        authenticated user must be the owner of the showcase.
    get:
      tags:
        - Showcases\Showcase videos
      summary: Get a specific video in a showcase
      operationId: ShowcasesShowcaseVideos_getSpecificVideoInShowcase
      description: >-
        This method returns a single video belonging to the specified showcase.
        The authenticated user must be the owner of the showcase.
    put:
      tags:
        - Showcases\Showcase videos
      summary: Add a specific video to a showcase
      operationId: ShowcasesShowcaseVideos_addToShowcase
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single video to the specified showcase. The
        authenticated user must be the owner of the showcase.
  /users/{user_id}/albums/{album_id}/videos/{video_id}/set_album_thumbnail:
    post:
      tags:
        - Showcases\Showcase videos
      summary: Create a thumbnail for a showcase from a showcase video
      operationId: ShowcasesShowcaseVideos_createShowcaseThumbnail
      security:
        - oauth2:
            - edit
      description: >-
        This method creates a thumbnail image for a showcase from the specified
        frame of a showcase video. The authenticated user must be the owner of
        the showcase.
  /users/{user_id}/albums/{album_id}/videos/{video_id}/set_featured_video:
    patch:
      tags:
        - Showcases\Showcase videos
      summary: Set the featured video of a showcase
      operationId: ShowcasesShowcaseVideos_setFeaturedVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method sets the featured video of the specified showcase. The
        authenticated user must be the owner of the showcase, and the featured
        video must belong to it.
  /users/{user_id}/analytics:
    get:
      tags:
        - Users\Analytics
      summary: Get analytics for the user
      operationId: UsersAnalytics_getMetrics
      security:
        - oauth2:
            - stats
      description: This method returns analytic metrics for the authenticated user.
  /users/{user_id}/appearances:
    get:
      tags:
        - Videos\Essentials
      summary: Get all the videos in which the user appears
      operationId: get_appearances
      description: >-
        This method returns all the videos in which the authenticated user has a
        credited appearance.
  /users/{user_id}/categories:
    get:
      tags:
        - Categories\Users
      summary: Get all the categories that the user follows
      operationId: CategoriesUsers_listFollowedCategories
      security:
        - oauth2:
            - private
      description: This method returns every category that the authenticated user follows.
  /users/{user_id}/categories/{category}:
    delete:
      tags:
        - Categories\Users
      summary: Cause the user to stop following a category
      operationId: CategoriesUsers_stopFollowingCategory
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to stop following the
        specified category.
    get:
      tags:
        - Categories\Users
      summary: Check if the user follows a category
      operationId: CategoriesUsers_checkFollowedCategory
      security:
        - oauth2:
            - private
      description: >-
        This method determines whether the authenticated user follows the
        specified category.
    put:
      tags:
        - Categories\Users
      summary: Cause the user to follow a specific category
      operationId: CategoriesUsers_followSpecificCategory
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to follow the specified
        category.
  /users/{user_id}/channels:
    get:
      tags:
        - Channels\Essentials
      summary: Get all the channels to which a user subscribes
      operationId: ChannelsEssentials_getUserSubscriptions
      description: >-
        This method returns all the channels to which the specified user
        subscribes.
  /users/{user_id}/channels/{channel_id}:
    delete:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Unsubscribe the user from a specific channel
      operationId: ChannelsSubscriptionsAndSubscribers_unsubscribeUserFromChannel
      security:
        - oauth2:
            - interact
      description: >-
        This method unsubscribes the authenticated user from the specified
        channel.
    get:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Check if a user follows a channel
      operationId: ChannelsSubscriptionsAndSubscribers_checkUserFollowsChannel
      description: >-
        This method determines whether the specified user is a follower of a
        particular channel.
    put:
      tags:
        - Channels\Subscriptions and subscribers
      summary: Subscribe the user to a specific channel
      operationId: ChannelsSubscriptionsAndSubscribers_subscribeToChannel
      security:
        - oauth2:
            - interact
      description: This method subscribes the authenticated user to the specified channel.
  /users/{user_id}/customlogos:
    get:
      tags:
        - Embed Presets\Custom logos
      summary: Get all the custom logos that belong to the user
      operationId: EmbedPresetsCustomLogos_listUserLogos
      description: >-
        This method returns every custom logo that belongs to the authenticated
        user or team owner.
    post:
      tags:
        - Embed Presets\Custom logos
      summary: Add a custom user logo
      operationId: EmbedPresetsCustomLogos_addUserLogo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a custom logo representing the authenticated user for
        display in the embedded player. Be sure to use this method in the
        context of the multi-step upload procedure described in our [Working
        with Thumbnail
        Uploads](https://developer.vimeo.com/api/upload/thumbnails#uploading-a-thumbnail)
        guide. This method represents Step 2 of the procedure.
  /users/{user_id}/customlogos/{logo_id}:
    delete:
      tags:
        - Embed Presets\Custom logos
      summary: Delete a custom user logo
      operationId: EmbedPresetsCustomLogos_deleteUserLogo
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified custom logo belonging to the
        authenticated user.
    get:
      tags:
        - Embed Presets\Custom logos
      summary: Get a specific custom user logo
      operationId: EmbedPresetsCustomLogos_getSpecificUserLogo
      description: >-
        This method returns a single custom logo belonging to the authenticated
        user.
  /users/{user_id}/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all available live event destinations for the user to stream to
      operationId: LiveEventDestinations_listAvailableDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every available event destination for the
        authenticated user to stream to.
  /users/{user_id}/feed:
    get:
      tags:
        - Users\Feeds
      summary: Get all the videos in the user's feed
      operationId: get_feed
      security:
        - oauth2:
            - private
      description: This method returns every video in the authenticated user's feed.
  /users/{user_id}/followers:
    get:
      tags:
        - Users\Followers
      summary: Get all the followers of the user
      operationId: get_followers
      description: This method returns every follower of the authenticated user.
  /users/{user_id}/following:
    get:
      tags:
        - Users\Followers
      summary: Get all the users that the user is following
      operationId: UsersFollowers_listOfFollowedUsers
      description: This method returns every user that the authenticated user is following.
    post:
      tags:
        - Users\Followers
      summary: Follow a list of users
      operationId: follow_users
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to become a follower of
        multiple users. In the body of the request, specify the list of users to
        follow as

        an array of URIs, where `user01_id`, `user02_id`, `user03_id`, and so
        on, are the user IDs of the users in question:


        ```

        {
         [
             {"uri" : "/users/{user01_id}"},
             {"uri" : "/users/{user02_id}"},
             {"uri" : "/users/{user03_id}"}
         ]
        }

        ```
  /users/{user_id}/following/{follow_user_id}:
    delete:
      tags:
        - Users\Followers
      summary: Unfollow a user
      operationId: unfollow_user
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to stop following another
        user.
    get:
      tags:
        - Users\Followers
      summary: Check if the user is following another user
      operationId: UsersFollowers_checkFollowingStatus
      description: >-
        This method determines whether the authenticated user is a follower of
        the specified user.
    put:
      tags:
        - Users\Followers
      summary: Follow a specific user
      operationId: follow_user
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to become the follower of the
        specified user.
  /users/{user_id}/groups:
    get:
      tags:
        - Groups\Users
      summary: Get all the groups that the user has joined
      operationId: GroupsUsers_getUserGroupsList
      description: This method returns every group to which the authenticated user belongs.
  /users/{user_id}/groups/{group_id}:
    delete:
      tags:
        - Groups\Subscriptions
      summary: Remove the user from a group
      operationId: leave_group
      security:
        - oauth2:
            - interact
      description: >-
        This method removes the authenticated user from the specified group. The
        authenticated user can't be the owner of the group; assign a new owner
        through a PATCH request first.
    put:
      tags:
        - Groups\Subscriptions
      summary: Add the user to a group
      operationId: join_group
      security:
        - oauth2:
            - interact
      description: This method adds the authenticated user to the specified group.
    get:
      tags:
        - Groups\Users
      summary: Check if a user has joined a group
      operationId: GroupsUsers_checkBelongGroup
      description: >-
        This method determines whether the authenticated user belongs to the
        specified group.
  /users/{user_id}/likes:
    get:
      tags:
        - Likes\Essentials
      summary: Get all the videos that a user has liked
      operationId: get_likes
      description: This method returns every video that the authenticated user has liked.
  /users/{user_id}/likes/{video_id}:
    delete:
      tags:
        - Likes\Essentials
      summary: Cause a user to unlike a video
      operationId: unlike_video
      security:
        - oauth2:
            - interact
      description: This method causes the authenticated user to unlike the specified video.
    get:
      tags:
        - Likes\Essentials
      summary: Check if the user has liked a video
      operationId: LikesEssentials_checkVideoLikedByUser
      description: >-
        This method checks if the authenticated user has liked the specified
        video.
    put:
      tags:
        - Likes\Essentials
      summary: Cause the user to like a video
      operationId: like_video
      security:
        - oauth2:
            - interact
      description: >-
        This method causes the authenticated user to like the specified video.
        The user can't like their own video.
  /users/{user_id}/live_events:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a list of live events
      operationId: LiveEssentials_deleteMultipleEvents
      security:
        - oauth2:
            - delete
      description: This method deletes multiple events belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get all the live events that belong to the user
      operationId: LiveEssentials_getUserLiveEvents
      description: The method returns every event belonging to the authenticated user.
    post:
      tags:
        - Live\Essentials
      summary: Create a live event
      operationId: LiveEssentials_createEventForUser
      security:
        - oauth2:
            - create
      description: This method creates a new event for the authenticated user.
  /users/{user_id}/live_events/{live_event_id}:
    delete:
      tags:
        - Live\Essentials
      summary: Delete a specific live event
      operationId: LiveEssentials_deleteSpecificEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a single event belonging to the authenticated user.
    get:
      tags:
        - Live\Essentials
      summary: Get a specific live event
      operationId: LiveEssentials_getEventById
      security:
        - oauth2:
            - private
      description: This method returns a single event belonging to the authenticated user.
    patch:
      tags:
        - Live\Essentials
      summary: Update a live event
      operationId: LiveEssentials_updateEventBelongingToAuthenticatedUser
      security:
        - oauth2:
            - edit
            - private
      description: This method updates an event belonging to the authenticated user.
  /users/{user_id}/live_events/{live_event_id}/activate:
    post:
      tags:
        - Live\Event activation
      summary: Activate a live event
      operationId: LiveEventActivation_createRtmpLinks
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method creates the necessary RTMP links for the specified event.
        Begin streaming to these links to trigger the event on Vimeo. The
        authenticated user must be the owner of the event.
  /users/{user_id}/live_events/{live_event_id}/auto_cc:
    patch:
      tags:
        - Live\Event automated closed captions
      summary: Edit the automated closed captions preference of a live event
      operationId: LiveEventAutomatedClosedCaptions_editPreferenceForEvent
      security:
        - oauth2:
            - private
      description: >-
        This method edits the automated closed captions preference for the
        specified event.
  /users/{user_id}/live_events/{live_event_id}/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all the destinations of a recurring live event
      operationId: LiveEventDestinations_getAllAvailableDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every destination of the specified event. The
        authenticated user must be the owner of the event.
    post:
      tags:
        - Live\Event destinations
      summary: Create a live event destination
      operationId: LiveEventDestinations_createEventDestination
      security:
        - oauth2:
            - public
      description: >-
        This method creates a destination for the specified event. The
        authenticated user must be the owner of the event.
  /users/{user_id}/live_events/{live_event_id}/end:
    post:
      tags:
        - Live\Event end
      summary: End a live event
      operationId: LiveEventEnd_eventTerminationAlt2
      security:
        - oauth2:
            - create
            - private
      description: >-
        This method ends the specified event. The authenticated user must be the
        owner of the event.
  /users/{user_id}/live_events/{live_event_id}/low_latency:
    patch:
      tags:
        - Live\Event low latency
      summary: Toggle the low-latency option of a live event
      operationId: LiveEventLowLatency_toggleOption
      security:
        - oauth2:
            - private
      description: This method toggles the low-latency option of the specified event.
  /users/{user_id}/live_events/{live_event_id}/m3u8_playback:
    get:
      tags:
        - Live\Event M3U8 playback
      summary: Get an M3U8 playback URL for a live event
      operationId: LiveEventM3U8Playback_getUrlForEventStream
      security:
        - oauth2:
            - private
      description: >-
        This method returns an M3U8 playback URL for the specified event stream.
        You should use this endpoint only in conjunction with our recommended
        procedure for playing events via HLS. For more information, see our [HLS
        guide](https://developer.vimeo.com/api/live/playback).
  /users/{user_id}/live_events/{live_event_id}/ott_destination/{destination_id}:
    delete:
      tags:
        - Live\Event destinations
      summary: Delete a live event OTT destination
      operationId: LiveEventDestinations_deleteOttDestination
      security:
        - oauth2:
            - private
      description: >-
        This method deletes an OTT channel as the destination of the specified
        event. The authenticated user must be the owner of the event.
  /users/{user_id}/live_events/{live_event_id}/ott_destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all the OTT destinations of a recurring live event
      operationId: LiveEventDestinations_getAllOttDestinations
      security:
        - oauth2:
            - private
      description: >-
        This method returns every OTT destination of the specified event. The
        authenticated user must be the owner of the event.
    post:
      tags:
        - Live\Event destinations
      summary: Create a live event OTT destination
      operationId: LiveEventDestinations_createOttDestination
      security:
        - oauth2:
            - private
      description: >-
        This method creates an OTT channel as the destination of the specified
        event. The authenticated user must be the owner of the event.
  /users/{user_id}/live_events/{live_event_id}/pictures:
    get:
      tags:
        - Live\Event thumbnails
      summary: Get all the thumbnails of a live event
      operationId: LiveEventThumbnails_getAllThumbs
      security:
        - oauth2:
            - private
      description: This method returns every thumbnail image of the specified event.
    post:
      tags:
        - Live\Event thumbnails
      summary: Create a live event thumbnail
      operationId: LiveEventThumbnails_createThumbnailForEvent
      security:
        - oauth2:
            - upload
            - private
      description: This method creates a thumbnail image for the specified event.
  /users/{user_id}/live_events/{live_event_id}/pictures/{thumbnail_id}:
    delete:
      tags:
        - Live\Event thumbnails
      summary: Delete a live event thumbnail
      operationId: LiveEventThumbnails_deleteThumbnailForEvent
      security:
        - oauth2:
            - delete
            - private
      description: This method deletes a thumbnail image for the specified event.
    get:
      tags:
        - Live\Event thumbnails
      summary: Get a specific live event thumbnail
      operationId: LiveEventThumbnails_getSpecificThumbnail
      security:
        - oauth2:
            - private
      description: This method returns a single thumbnail image of the specified event.
    patch:
      tags:
        - Live\Event thumbnails
      summary: Edit a live event thumbnail
      operationId: LiveEventThumbnails_editEventThumbnail
      security:
        - oauth2:
            - edit
            - private
      description: This method edits a thumbnail image for the specified event.
  /users/{user_id}/live_events/{live_event_id}/privacy/domains:
    get:
      tags:
        - Live\Embed privacy
      summary: Get all the domains on which a live event can be embedded
      operationId: LiveEmbedPrivacy_getWhitelistDomains
      security:
        - oauth2:
            - private
      description: >-
        This method returns every whitelisted domain for an event. The embed
        privacy setting must be `whitelist`.
    put:
      tags:
        - Live\Embed privacy
      summary: Embed a live event on one or more domains
      operationId: LiveEmbedPrivacy_embedEventOnDomains
      security:
        - oauth2:
            - edit
            - private
      description: >-
        This method embeds an event on the specified domains. The embed privacy
        setting must be `whitelist`.
  /users/{user_id}/live_events/{live_event_id}/videos:
    delete:
      tags:
        - Live\Event videos
      summary: Remove a list of videos from a live event
      operationId: LiveEventVideos_removeMultiple
      security:
        - oauth2:
            - edit
            - private
      description: This method removes multiple videos from the specified event.
    get:
      tags:
        - Live\Event videos
      summary: Get all the videos in a live event
      operationId: LiveEventVideos_listAllVideosInEvent
      security:
        - oauth2:
            - private
      description: This method returns every video in the specified event.
    post:
      tags:
        - Live\Event videos
      summary: Add a list of videos to a live event
      operationId: LiveEventVideos_addMultipleVideos
      security:
        - oauth2:
            - edit
            - private
      description: This method adds multiple videos to the specified event.
  /users/{user_id}/live_events/{live_event_id}/videos/{video_id}:
    get:
      tags:
        - Live\Event videos
      summary: Get a specific video in a live event
      operationId: LiveEventVideos_getSpecificVideo
      security:
        - oauth2:
            - private
      description: This method returns a single video in the specified event.
  /users/{user_id}/ondemand/pages:
    get:
      tags:
        - On Demand\Essentials
      summary: Get all the On Demand pages of the user
      operationId: OnDemandEssentials_getAllUserPages
      description: >-
        This method returns every On Demand page belonging to the authenticated
        user.
    post:
      tags:
        - On Demand\Essentials
      summary: Create an On Demand page
      operationId: create_vod
      description: >-
        This method creates a new On Demand page for the specified user. To
        publish the page, use the
        [edit](https://developer.vimeo.com/api/reference/on-demand#edit_vod)
        method.
  /users/{user_id}/ondemand/purchases:
    get:
      tags:
        - On Demand\Purchases and rentals
      summary: Get all of the user's On Demand purchases and rentals
      operationId: OnDemandPurchasesAndRentals_listUserPurchasesAndRentals
      security:
        - oauth2:
            - purchased
      description: >-
        This method returns every purchase and rental that the authenticated
        user has made across all On Demand pages.
  /users/{user_id}/pictures:
    get:
      tags:
        - Users\Pictures
      summary: Get all the pictures that belong to the user
      operationId: get_pictures
      description: >-
        This method returns every portrait image belonging to the authenticated
        user.
    post:
      tags:
        - Users\Pictures
      summary: Add a picture to the user's account
      operationId: create_picture
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a portrait image to the authenticated user's Vimeo
        account. Send the binary data of the image file to the location that you
        receive

        from the **link** field in the response. For step-by-step instructions,
        see

        [Working with Thumbnail
        Uploads](https://developer.vimeo.com/api/upload/thumbnails#uploading-a-thumbnail-step-3).
  /users/{user_id}/pictures/{portraitset_id}:
    delete:
      tags:
        - Users\Pictures
      summary: Delete a picture from the user's account
      operationId: delete_picture
      security:
        - oauth2:
            - delete
      description: >-
        This method removes the specified portrait image from the authenticated
        user's Vimeo account.
    get:
      tags:
        - Users\Pictures
      summary: Get a specific picture that belongs to the user
      operationId: get_picture
      description: >-
        This method returns a single portrait image belonging to the
        authenticated user.
    patch:
      tags:
        - Users\Pictures
      summary: Edit a picture in the user's account
      operationId: edit_picture
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified portrait image belonging to the
        authenticated user.
  /users/{user_id}/portfolios:
    get:
      tags:
        - Portfolios\Essentials
      summary: Get all the portfolios that belong to the user
      operationId: get_portfolios
      description: This method returns every portfolio belonging to the authenticated user.
  /users/{user_id}/portfolios/{portfolio_id}:
    get:
      tags:
        - Portfolios\Essentials
      summary: Get a specific portfolio
      operationId: get_portfolio
      description: >-
        This method returns a single portfolio belonging to the authenticated
        user.
  /users/{user_id}/portfolios/{portfolio_id}/videos:
    get:
      tags:
        - Portfolios\Videos
      summary: Get all the videos in a portfolio
      operationId: PortfoliosVideos_getAllPortfolioVideos
      description: >-
        This method returns every video from the specified portfolio belonging
        to the authenticated user.
  /users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}:
    delete:
      tags:
        - Portfolios\Videos
      summary: Remove a video from a portfolio
      operationId: PortfoliosVideos_removeFromPortfolioVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method removes a video from the specified portfolio belonging to
        the authenticated user.
    get:
      tags:
        - Portfolios\Videos
      summary: Get a specific video in a portfolio
      operationId: PortfoliosVideos_getSpecificVideo
      description: >-
        This method returns a single video from the specified portfolio
        belonging to the authenticated user.
    put:
      tags:
        - Portfolios\Videos
      summary: Add a video to a portfolio
      operationId: PortfoliosVideos_addVideoToPortfolio
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a video to the specified portfolio belonging to the
        authenticated user.
  /users/{user_id}/presets:
    get:
      tags:
        - Embed Presets\Essentials
      summary: Get all the embed presets that a user has created
      operationId: EmbedPresetsEssentials_getUserEmbedPresets
      description: >-
        This method returns every embed preset that belongs to the authenticated
        user.
    post:
      tags:
        - Embed Presets\Essentials
      summary: Create an embed preset
      operationId: EmbedPresetsEssentials_createEmbedPreset
      description: This method creates an embed preset.
  /users/{user_id}/presets/{preset_id}:
    get:
      tags:
        - Embed Presets\Essentials
      summary: Get a specific embed preset
      operationId: EmbedPresetsEssentials_getSpecificEmbedPreset
      description: >-
        This method returns a single embed preset. The authenticated user must
        be the owner of the preset.
    patch:
      tags:
        - Embed Presets\Essentials
      summary: Edit an embed preset
      operationId: EmbedPresetsEssentials_editPreset
      description: >-
        This method edits the specified embed preset. The authenticated user
        must be the owner of the preset.
  /users/{user_id}/presets/{preset_id}/videos:
    get:
      tags:
        - Embed Presets\Videos
      summary: Get all the videos that have a specific embed preset
      operationId: EmbedPresetsVideos_getPresetVideos
      description: >-
        This method returns every video to which the specified embed preset has
        been added. The authenticated user must be the owner of videos.
  /users/{user_id}/projects:
    get:
      tags:
        - Folders\Essentials
      summary: Get all the folders that belong to the user
      operationId: get_projects
      security:
        - oauth2:
            - private
      description: This method returns all the folders belonging to the authenticated user.
    post:
      tags:
        - Folders\Essentials
      summary: Create a folder
      operationId: create_project
      security:
        - oauth2:
            - create
      description: >-
        This method creates a new folder for the authenticated user. By default,
        this method creates a top-level folder. To create a subfolder — that is,
        to place the new folder inside an existing folder — specify the parent
        folder by URI with the **parent_folder_uri** parameter in the body of
        the request.
  /users/{user_id}/projects/{project_id}:
    delete:
      tags:
        - Folders\Essentials
      summary: Delete a folder
      operationId: delete_project
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified folder and optionally also the videos
        that it contains. The authenticated user must be the owner of the
        folder.
    get:
      tags:
        - Folders\Essentials
      summary: Get a specific folder
      operationId: get_project
      description: This method returns a single folder belonging to the authenticated user.
    patch:
      tags:
        - Folders\Essentials
      summary: Edit a folder
      operationId: edit_project
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified folder. The authenticated user must be
        the owner of the folder.
  /users/{user_id}/projects/{project_id}/items:
    get:
      tags:
        - Folders\Items
      summary: Get all the items in a folder
      operationId: FoldersItems_getFolderContents
      description: This method returns every item that belongs to the specified folder.
  /users/{user_id}/projects/{project_id}/videos:
    delete:
      tags:
        - Folders\Videos
      summary: Remove a list of videos from a folder
      operationId: FoldersVideos_removeMultipleVideosFromFolder
      security:
        - oauth2:
            - interact
      description: >-
        This method removes multiple videos from the specified folder. The
        authenticated user must be the owner of the folder.
    get:
      tags:
        - Folders\Videos
      summary: Get all the videos in a folder
      operationId: FoldersVideos_getAllFolderVideos
      description: This method returns all the videos that belong to the specified folder.
    put:
      tags:
        - Folders\Videos
      summary: Add a list of videos to a folder
      operationId: FoldersVideos_addToFolderVideos
      security:
        - oauth2:
            - interact
      description: >-
        This method adds multiple videos to the specified folder. The
        authenticated user must be the owner of the folder.
  /users/{user_id}/projects/{project_id}/videos/{video_id}:
    delete:
      tags:
        - Folders\Videos
      summary: Remove a video from a folder
      operationId: FoldersVideos_removeFromFolderVideo
      security:
        - oauth2:
            - delete
      description: >-
        This method removes a single video from the specified folder. Please
        note that this doesn't delete the video itself.
    put:
      tags:
        - Folders\Videos
      summary: Add a video to a folder
      operationId: FoldersVideos_addSingleFolderVideo
      security:
        - oauth2:
            - interact
      description: >-
        This method adds a single video to the specified folder. The
        authenticated user must be the owner of the folder.
  /users/{user_id}/team/role:
    get:
      tags:
        - Teams\Members
      summary: Get information about the user's role on a team
      operationId: TeamsMembers_getUserTeamRole
      description: >-
        This method returns information about the authenticated user's role on
        the specified team owner's team.
  /users/{user_id}/team_users/{team_user_id}:
    get:
      tags:
        - Teams\Members
      summary: Get membership information about a team
      operationId: TeamsMembers_getTeamMembershipInformation
      description: >-
        This method returns information about the membership of the specified
        team. Usage is currently limited to the team join forms.
  /users/{user_id}/uploads/{upload_id}:
    delete:
      tags:
        - Videos\Uploads
      summary: Complete a streaming upload
      operationId: VideosUploads_completeStreamingUpload
      security:
        - oauth2:
            - upload
      description: >-
        This method completes the specified streaming upload of the
        authenticated user.
    get:
      tags:
        - Videos\Uploads
      summary: Get an upload attempt
      operationId: VideosUploads_getUploadAttempt
      security:
        - oauth2:
            - upload
      description: >-
        This method returns the specified upload attempt of the authenticated
        user. _This method has been deprecated. For information on our currently
        supported upload approaches, see our [Working with Video
        Uploads](https://developer.vimeo.com/api/upload/videos) guide._
  /users/{user_id}/videos:
    delete:
      tags:
        - Videos\Essentials
      summary: Delete a user's videos
      operationId: delete_videos
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes one or more videos belonging to the specified user.
        The authenticated user must have permission to delete the videos.


        Specify the videos to delete in a comma-separated list by URI using the
        **uris** query parameter.
    get:
      tags:
        - Videos\Essentials
      summary: Get all the videos that the user has uploaded
      operationId: get_videos
      description: >-
        This method returns all the videos that the authenticated user has
        uploaded.
    post:
      tags:
        - Videos\Uploads
      summary: Upload a video
      operationId: upload_video
      security:
        - oauth2:
            - upload
      description: >-
        This method begins the video upload process for the authenticated user.
        For more information, see our [upload
        documentation](https://developer.vimeo.com/api/upload/videos).
  /users/{user_id}/videos/{video_id}:
    get:
      tags:
        - Videos\Essentials
      summary: Check if the user owns a video
      operationId: VideosEssentials_checkUserOwnership
      description: >-
        This method determines whether the authenticated user is the owner of
        the specified video.
  /users/{user_id}/videos/{video_id}/destinations:
    get:
      tags:
        - Live\Event destinations
      summary: Get all the destinations of a one-time live event
      operationId: LiveEventDestinations_getAllAvailableDestinations
      security:
        - oauth2:
            - public
      description: >-
        This method returns every destination of the specified event. The
        authenticated user must be the owner of the event.
    post:
      tags:
        - Live\Event destinations
      summary: Create a one-time live event destination
      operationId: LiveEventDestinations_createOneTimeLiveEventDestination
      security:
        - oauth2:
            - public
      description: >-
        This method creates a destination for the specified event. The
        authenticated user must be the owner of the event.
  /users/{user_id}/videos/{video_id}/m3u8_playback:
    get:
      tags:
        - Videos\Live M3U8 playback
      summary: Get an M3U8 playback URL for a one-time live event
      operationId: VideosLiveM3U8Playback_getPlaybackUrlForEventStream
      security:
        - oauth2:
            - private
      description: >-
        This method returns an M3U8 playback URL for the specified event stream.
        You should use this endpoint only in conjunction with our recommended
        procedure for playing events via HLS. For more information, see our [HLS
        guide](https://developer.vimeo.com/api/live/playback).
  /users/{user_id}/watchlater:
    get:
      tags:
        - Watch Later Queue\Essentials
      summary: Get all the videos in the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_listUserQueueVideos
      security:
        - oauth2:
            - private
      description: >-
        This method returns every video from the authenticated user's Watch
        Later queue.
  /users/{user_id}/watchlater/{video_id}:
    delete:
      tags:
        - Watch Later Queue\Essentials
      summary: Remove a video from the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_removeVideoFromQueue
      security:
        - oauth2:
            - interact
      description: >-
        This method removes the specified video from the authenticated user's
        Watch Later queue.
    get:
      tags:
        - Watch Later Queue\Essentials
      summary: Check if the user has added a video to their Watch Later queue
      operationId: WatchLaterQueueEssentials_checkVideoInQueue
      security:
        - oauth2:
            - private
      description: >-
        This method checks the authenticated user's Watch Later queue for the
        specified video.
    put:
      tags:
        - Watch Later Queue\Essentials
      summary: Add a video to the user's Watch Later queue
      operationId: WatchLaterQueueEssentials_addVideoToQueue
      security:
        - oauth2:
            - interact
      description: >-
        This method adds the specified video to the authenticated user's Watch
        Later queue.
  /users/{user_id}/webinars:
    post:
      tags:
        - Webinar\Essentials
      summary: Create a webinar
      operationId: create_webinar
      security:
        - oauth2:
            - create
      description: This method creates a new webinar for the authenticated user.
  /users/{user_id}/webinars/{webinar_id}:
    get:
      tags:
        - Webinar\Essentials
      summary: Get a specific webinar
      operationId: get_webinar
      description: >-
        This method returns a single webinar belonging to the authenticated
        user.
      deprecated: true
    patch:
      tags:
        - Webinar\Essentials
      summary: Update a webinar
      operationId: update_webinar
      security:
        - oauth2:
            - edit
      description: This method updates a webinar belonging to the authenticated user.
      deprecated: true
  /users/{user_id}/webinars/{webinar_id}/email_settings:
    get:
      tags:
        - Webinar\Emails
      summary: Get customization email data for a webinar
      operationId: WebinarEmails_getCustomizationData
      description: >-
        This method returns customized email data for the specified webinar. The
        authenticated user must have administrative access to the webinar.
      deprecated: true
    patch:
      tags:
        - Webinar\Emails
      summary: Customize the email preferences of a webinar
      operationId: WebinarEmails_customizePreferences
      security:
        - oauth2:
            - edit
      description: >-
        This method causes the authenticated user to customize the email
        preferences of the specified webinar. The user must have administrative
        access to the webinar.
      deprecated: true
  /users/{user_id}/webinars/{webinar_id}/registrants:
    get:
      tags:
        - Webinar\Registrations
      summary: Get user registration data associated with a webinar
      operationId: WebinarRegistrations_getUserRegistrationsByWebinarId
      security:
        - oauth2:
            - stats
            - private
      description: >-
        This method returns the list of user registrations that is associated
        with the specified webinar and was originally submitted through a
        webinar form.
      deprecated: true
    put:
      tags:
        - Webinar\Registrations
      summary: Capture the user registration list associated with a webinar
      operationId: WebinarRegistrations_captureUserRegistrationList
      description: >-
        This method captures the user registration list associated with the
        specified webinar. A maximum of 50 registrants are permitted as part of
        the request.
      deprecated: true
  /users/{user_id}/webinars/{webinar_id}/registrants/{registrant_id}:
    delete:
      tags:
        - Webinar\Registrations
      summary: Delete a registrant record associated with a webinar
      operationId: WebinarRegistrations_deleteRegistrantRecord
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified registrant associated with a webinar
        and originally submitted through a webinar form.
      deprecated: true
    patch:
      tags:
        - Webinar\Registrations
      summary: Update user registration data associated with a webinar
      operationId: WebinarRegistrations_updateUserRegistrationData
      security:
        - oauth2:
            - edit
      description: >-
        This method updates the specified user registration data associated with
        a webinar and originally submitted through a webinar form.
      deprecated: true
  /videos:
    get:
      tags:
        - Videos\Essentials
      summary: Search for videos
      operationId: search_videos
      description: This method returns all the videos that match custom search criteria.
  /videos/{video_id}:
    delete:
      tags:
        - Videos\Essentials
      summary: Delete a video
      operationId: delete_video
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified video. The authenticated user must be
        the owner of the video.
    get:
      tags:
        - Videos\Essentials
      summary: Get a specific video
      operationId: get_video
      description: This method returns a single video.
    patch:
      tags:
        - Videos\Essentials
      summary: Edit a video
      operationId: edit_video
      security:
        - oauth2:
            - edit
      description: This method edits the specified video.
  /videos/{video_id}/albums:
    get:
      tags:
        - Videos\Showcases
      summary: Get all the showcases that contain a video
      operationId: VideosShowcases_getAllContShowcases
      description: This method returns all the showcases that contain the specified video.
    patch:
      tags:
        - Videos\Showcases
      summary: Add or remove a video from a list of showcases
      operationId: VideosShowcases_addToMultipleShowcases
      description: >-
        This method adds or removes the specified video to or from multiple
        showcases.
  /videos/{video_id}/animated_thumbsets:
    get:
      tags:
        - Videos\Animated thumbnails
      summary: Get all the animated thumbnails of a video
      operationId: VideosAnimatedThumbnails_getAllSets
      description: >-
        This method returns all the sets of animated thumbnails associated with
        the specified video. The authenticated user must be the owner of the
        video.
    post:
      tags:
        - Videos\Animated thumbnails
      summary: Create a set of animated thumbnails for a video
      operationId: VideosAnimatedThumbnails_createSet
      security:
        - oauth2:
            - create
      description: >-
        This method creates a set of animated thumbnails for the specified
        video. Please note that you can't create more than four sets of animated
        thumbnails for the same video.
  /videos/{video_id}/animated_thumbsets/{picture_id}:
    delete:
      tags:
        - Videos\Animated thumbnails
      summary: Delete a set of animated thumbnails for a video
      operationId: VideosAnimatedThumbnails_deleteSet
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes a set of animated thumbnails for the specified
        video.
    get:
      tags:
        - Videos\Animated thumbnails
      summary: Get a specific set of animated thumbnails
      operationId: VideosAnimatedThumbnails_specificSetGet
      description: >-
        This method returns a particular set of animated thumbnails associated
        with the specified video. The authenticated user must be the owner of
        the video.
  /videos/{video_id}/animated_thumbsets/{picture_id}/status:
    get:
      tags:
        - Videos\Animated thumbnails
      summary: Get the status of a set of animated thumbnails
      operationId: VideosAnimatedThumbnails_getStatusOfSet
      description: >-
        This method returns the status of a particular set of animated
        thumbnails associated with the specified video. The status indicates
        whether the thumbnails are ready to use. The authenticated user must be
        the owner of the video.
  /videos/{video_id}/available_albums:
    get:
      tags:
        - Showcases\Showcase videos
      summary: >-
        Get all the showcases to which the user can add or remove a specific
        video
      operationId: ShowcasesShowcaseVideos_listAvailableShowcases
      description: >-
        This endpoint returns every showcase to which the authenticated user can
        add or remove the specified video. The user must be the owner of the
        showcase.
  /videos/{video_id}/available_channels:
    get:
      tags:
        - Channels\Videos
      summary: >-
        Get all the channels to which the user can add or remove a specific
        video
      operationId: ChannelsVideos_getAccessibleChannels
      description: >-
        This method returns every channel to which the authenticated user can
        add or remove the specified video. The authenticated user must be a
        moderator of the channel.
  /videos/{video_id}/categories:
    get:
      tags:
        - Categories\Videos
      summary: Get all the categories to which a video belongs
      operationId: CategoriesVideos_getAllVideoCategories
      description: This method returns every category that contains the specified video.
    put:
      tags:
        - Categories\Videos
      summary: Suggest categories for a video
      operationId: CategoriesVideos_setVideoCategories
      security:
        - oauth2:
            - edit
      description: >-
        This method sets multiple categories and subcategories for the specified
        video. Include the categories as a JSON block in the body of the request
        using the **category** field, like this: `[{ "category": "Tech" }, {
        "category": "Music" }]`. The authenticated user must have edit access to
        the video. For more information on batch requests like this one, see
        [Using Common Formats and
        Parameters](https://developer.vimeo.com/api/common-formats#working-with-batch-requests).
  /videos/{video_id}/chapters:
    get:
      tags:
        - Videos\Chapters
      summary: Get all the chapters of a video
      operationId: get_chapters
      description: This method returns every chapter of the specified video.
    post:
      tags:
        - Videos\Chapters
      summary: Add a chapter to a video
      operationId: create_chapter
      security:
        - oauth2:
            - upload
      description: This method adds a chapter to the specified video.
  /videos/{video_id}/chapters/temporary/pictures:
    post:
      tags:
        - Videos\Chapters
      summary: >-
        Generate an upload link or timecode-based thumbnail for an unsaved video
        chapter
      operationId: VideosChapters_generateChapterThumbnail
      security:
        - oauth2:
            - public
      description: >-
        This method generates either an upload link or a timecode-based
        thumbnail for an unsaved video chapter. To generate the upload link,
        which enables the authenticated user to upload a chapter thumbnail image
        manually, leave the body of the request empty. To generate an automatic
        timecode-based thumbnail, specify the **timecode** parameter in the body
        of the request.
  /videos/{video_id}/chapters/temporary/pictures/{uid}:
    get:
      tags:
        - Videos\Chapters
      summary: Get a single chapter thumbnail associated with an unsaved video chapter
      operationId: VideosChapters_getSingleChapterThumbnail
      description: >-
        This method returns the specified thumbnail associated with an unsaved
        video chapter.
  /videos/{video_id}/chapters/{chapter_id}:
    delete:
      tags:
        - Videos\Chapters
      summary: Delete a chapter
      operationId: delete_chapter
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified chapter from a video. The
        authenticated user must be the owner of the video.
    get:
      tags:
        - Videos\Chapters
      summary: Get a specific chapter
      operationId: get_chapter
      description: This method returns a single chapter of the specified video.
    patch:
      tags:
        - Videos\Chapters
      summary: Edit a chapter
      operationId: edit_chapter
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified chapter of a video. The authenticated
        user must be the owner of the video.
  /videos/{video_id}/chapters/{chapter_id}/pictures:
    get:
      tags:
        - Videos\Chapters
      summary: Get all the thumbnails associated with a saved video chapter
      operationId: VideosChapters_getChapterThumbnails
      security:
        - oauth2:
            - public
      description: >-
        This method returns every thumbnail associated with the specified saved
        video chapter.
    post:
      tags:
        - Videos\Chapters
      summary: >-
        Generate an upload link or timecode-based thumbnail for a saved video
        chapter
      operationId: VideosChapters_generateChapterThumbnailOrUploadLink
      security:
        - oauth2:
            - create
      description: >-
        This method generates either an upload link or a timecode-based
        thumbnail for the specified saved video chapter. To generate the upload
        link, which enables the authenticated user to upload a chapter thumbnail
        image manually, leave the body of the request empty. To generate an
        automatic timecode-based thumbnail, include the **timecode** parameter
        in the body of the request.
  /videos/{video_id}/chapters/{chapter_id}/pictures/{uid}:
    delete:
      tags:
        - Videos\Chapters
      summary: Delete a chapter thumbnail
      operationId: VideosChapters_deleteChapterThumbnail
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified chapter thumbnail from a video.


        The authenticated user must be the owner of the video that the chapter
        belongs to.

        This method deletes both timecode-generated and custom-uploaded
        thumbnails.
    get:
      tags:
        - Videos\Chapters
      summary: Get a single chapter thumbnail associated with a saved video chapter
      operationId: VideosChapters_getSingleChapterThumbnail
      description: >-
        This method returns the specified thumbnail associated with a saved
        video chapter.
    patch:
      tags:
        - Videos\Chapters
      summary: Set a chapter thumbnail as active
      operationId: VideosChapters_setChapterThumbnailActive
      security:
        - oauth2:
            - edit
      description: This method sets the specified chapter thumbnail for a video as active.
  /videos/{video_id}/comments:
    get:
      tags:
        - Videos\Video comments
      summary: Get all the video comments on a video
      operationId: get_comments
      description: This method returns every video comment on the specified video.
    post:
      tags:
        - Videos\Video comments
      summary: Add a video comment to a video
      operationId: create_comment
      security:
        - oauth2:
            - interact
      description: This method adds a video comment to the specified video.
  /videos/{video_id}/comments/{comment_id}:
    delete:
      tags:
        - Videos\Video comments
      summary: Delete a video comment
      operationId: delete_comment
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified video comment. The authenticated user
        must be the owner of the comment.
    get:
      tags:
        - Videos\Video comments
      summary: Get a specific video comment
      operationId: get_comment
      description: This method returns the specified video comment.
    patch:
      tags:
        - Videos\Video comments
      summary: Edit a video comment
      operationId: edit_comment
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified video comment. The authenticated user
        must be the owner of the comment.
  /videos/{video_id}/comments/{comment_id}/replies:
    get:
      tags:
        - Videos\Video comments
      summary: Get all the replies to a video comment
      operationId: VideosVideoComments_getAllReplies
      description: This method returns every reply to the specified video comment.
    post:
      tags:
        - Videos\Video comments
      summary: Add a reply to a video comment
      operationId: VideosVideoComments_createReply
      security:
        - oauth2:
            - interact
      description: This method adds a reply to the specified video comment.
  /videos/{video_id}/credits:
    get:
      tags:
        - Videos\Credits
      summary: Get all the credited users in a video
      operationId: VideosCredits_getAllCreditedUsersInVideo
      description: This method returns every credited user in a video.
    post:
      tags:
        - Videos\Credits
      summary: Credit a user in a video
      operationId: VideosCredits_addUserCredit
      description: This method adds a user credit to the specified video.
  /videos/{video_id}/credits/available_users:
    get:
      tags:
        - Videos\Credits
      summary: Get users who can be credited on a video
      operationId: available_users
      description: >-
        This method returns the users who can be credited on the specified
        video.
  /videos/{video_id}/credits/{credit_id}:
    delete:
      tags:
        - Videos\Credits
      summary: Delete the credit for a user in a video
      operationId: VideosCredits_deleteUserCredit
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified user credit from a video. The
        authenticated user must be the creator of the credit or the credited
        user.
    get:
      tags:
        - Videos\Credits
      summary: Get a specific credited user in a video
      operationId: VideosCredits_getSpecificCreditedUser
      description: This method returns a single credited user in a video.
    patch:
      tags:
        - Videos\Credits
      summary: Edit the credit for a user in a video
      operationId: VideosCredits_editUserCreditInVideo
      security:
        - oauth2:
            - edit
      description: This method edits the specified user credit in a video.
  /videos/{video_id}/fragments:
    delete:
      tags:
        - Videos\Fragments
      summary: Delete a video's fragments
      operationId: delete_fragments
      description: This method deletes all fragments for the specified video.
    get:
      tags:
        - Videos\Fragments
      summary: Get all the fragments for a video
      operationId: get_fragments
      description: >-
        This method returns all of the fragments associated with the specified
        video.
    put:
      tags:
        - Videos\Fragments
      summary: Update a video's fragments
      operationId: put_fragments
      description: This method updates the specified video with new fragments.
  /videos/{video_id}/likes:
    get:
      tags:
        - Likes\Essentials
      summary: Get all the users who have liked a video
      operationId: LikesEssentials_getUserLikes
      description: This method returns every user who has liked the specified video.
  /videos/{video_id}/pictures:
    get:
      tags:
        - Videos\Thumbnails
      summary: Get all the thumbnails of a video
      operationId: VideosThumbnails_getAllByVideoId
      description: >-
        This method returns all thumbnail images of the specified video. The
        authenticated user must have team permissions for the video.
    post:
      tags:
        - Videos\Thumbnails
      summary: Add a video thumbnail
      operationId: VideosThumbnails_addThumbnailToVideo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a thumbnail image to the specified video. The
        authenticated user must have team permissions for the video.
  /videos/{video_id}/pictures/{picture_id}:
    delete:
      tags:
        - Videos\Thumbnails
      summary: Delete a video thumbnail
      operationId: VideosThumbnails_deleteThumbnailFromVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified thumbnail image from a video. The
        authenticated user must have team permissions for the video.
    get:
      tags:
        - Videos\Thumbnails
      summary: Get a specific video thumbnail
      operationId: VideosThumbnails_getThumbnailFromVideo
      description: >-
        This method returns a single thumbnail image from the specified video.
        The authenticated user must have team permissions for the video.
    patch:
      tags:
        - Videos\Thumbnails
      summary: Edit a video thumbnail
      operationId: VideosThumbnails_editThumbnailImage
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified video thumbnail image. The authenticated
        user must be the owner of the thumbnail.
  /videos/{video_id}/presets/{preset_id}:
    delete:
      tags:
        - Embed Presets\Videos
      summary: Remove an embed preset from a video
      operationId: EmbedPresetsVideos_removePresetFromVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method removes the specified embed preset from a video. The
        authenticated user must either be the owner of the video or a team user
        with the contributor or admin role.
    get:
      tags:
        - Embed Presets\Videos
      summary: Check if an embed preset has been added to a video
      operationId: EmbedPresetsVideos_checkIfPresetAddedToVideo
      description: This method determines whether a video has the specified embed preset.
    put:
      tags:
        - Embed Presets\Videos
      summary: Add an embed preset to a video
      operationId: EmbedPresetsVideos_addPresetToVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method adds an embed preset to the specified video. The
        authenticated user must either be the owner of the video or a team user
        with the contributor or admin role.
  /videos/{video_id}/privacy/domains:
    get:
      tags:
        - Videos\Embed privacy
      summary: Get all the domains on a video's whitelist
      operationId: VideosEmbedPrivacy_listWhitelistDomains
      description: This method returns every domain on the specified video's whitelist.
  /videos/{video_id}/privacy/domains/{domain}:
    delete:
      tags:
        - Videos\Embed privacy
      summary: Remove a domain from a video's whitelist
      operationId: VideosEmbedPrivacy_removeDomainFromWhitelist
      security:
        - oauth2:
            - edit
      description: This method removes the specified domain from a video's whitelist.
    put:
      tags:
        - Videos\Embed privacy
      summary: Add a domain to a video's whitelist
      operationId: VideosEmbedPrivacy_addDomainToWhitelist
      security:
        - oauth2:
            - edit
      description: This method adds the specified domain to a video's whitelist.
  /videos/{video_id}/privacy/users:
    get:
      tags:
        - Videos\Unlisted videos
      summary: Get the users who can access an unlisted video
      operationId: VideosUnlistedVideos_listAccessibleUsers
      description: >-
        This method returns every user who has access to the specified unlisted
        video.
    put:
      tags:
        - Videos\Unlisted videos
      summary: Permit a list of users to access an unlisted video
      operationId: VideosUnlistedVideos_grantAccessToUsers
      security:
        - oauth2:
            - edit
      description: >-
        This method gives multiple users permission to access the specified
        unlisted video. The authenticated user must be the owner of the video.
        The body of the request should follow our [batch request
        format](https://developer.vimeo.com/api/common-formats#working-with-batch-requests):
        each object must contain a single **uri** field whose value is the URI
        of the user who can access the video.
  /videos/{video_id}/privacy/users/{user_id}:
    delete:
      tags:
        - Videos\Unlisted videos
      summary: Restrict a user from viewing an unlisted video
      operationId: VideosUnlistedVideos_restrictUserAccess
      security:
        - oauth2:
            - edit
      description: >-
        This method prevents a user from being able to view the specified
        unlisted video. The authenticated user must be the owner of the video.
    put:
      tags:
        - Videos\Unlisted videos
      summary: Permit a single user to access an unlisted video
      operationId: VideosUnlistedVideos_grantUserAccess
      security:
        - oauth2:
            - edit
      description: >-
        This method gives a single user permission to access the specified
        unlisted video. The authenticated user must be the owner of the video.
  /videos/{video_id}/sessions/status:
    get:
      tags:
        - Live\Event sessions
      summary: Get the ingest status of a one-time live event
      operationId: LiveEventSessions_getIngestStatus
      description: This method returns the ingest status of the specified event.
  /videos/{video_id}/tags:
    get:
      tags:
        - Videos\Tags
      summary: Get all the tags of a video
      operationId: VideosTags_getVideoTags
      description: >-
        This method returns all the tags associated with the specified video.
        The authenticated user must be the owner of the video.
    put:
      tags:
        - Videos\Tags
      summary: Add a list of tags to a video
      operationId: VideosTags_addMultiple
      security:
        - oauth2:
            - edit
      description: >-
        This method adds multiple tags to the specified video. Include the tags
        as a JSON array  as the body of the request with the  **name** field,
        like this: `[{ "name": "funny"}, {"name": "concert" }]`. The
        authenticated user must have edit access to the video. For more
        information on batch requests like this one, see [Using Common Formats
        and
        Parameters](https://developer.vimeo.com/api/common-formats#working-with-batch-requests).
  /videos/{video_id}/tags/{word}:
    delete:
      tags:
        - Videos\Tags
      summary: Remove a tag from a video
      operationId: VideosTags_removeTag
      security:
        - oauth2:
            - edit
      description: >-
        This method removes the specified tag from a video. The authenticated
        user must have edit access to the video.
    get:
      tags:
        - Videos\Tags
      summary: Check if a tag has been added to a video
      operationId: VideosTags_checkTagVideo
      description: >-
        This method determines whether the specified tag has been added to a
        video. The authenticated user must be the owner of the video.
    put:
      tags:
        - Videos\Tags
      summary: Add a specific tag to a video
      operationId: VideosTags_addTagToVideo
      security:
        - oauth2:
            - edit
      description: >-
        This method adds a single tag to the specified video. The authenticated
        user must be the owner of the video.
  /videos/{video_id}/texttracks:
    get:
      tags:
        - Videos\Text tracks
      summary: Get all the text tracks of a video
      operationId: VideosTextTracks_getAllVideoTracks
      description: >-
        This method returns every text track of the specified video. The
        authenticated user must be the owner of the video.
    post:
      tags:
        - Videos\Text tracks
      summary: Add a text track to a video
      operationId: VideosTextTracks_addTextTrack
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a text track to the specified video. For more
        information, see [Working with Text Track
        Uploads](https://developer.vimeo.com/api/upload/texttracks).
  /videos/{video_id}/texttracks/{texttrack_id}:
    delete:
      tags:
        - Videos\Text tracks
      summary: Delete a text track
      operationId: VideosTextTracks_deleteTextTrack
      security:
        - oauth2:
            - delete
      description: >-
        This method deletes the specified text track from a video. The
        authenticated user must be the owner of the video.
    get:
      tags:
        - Videos\Text tracks
      summary: Get a specific text track
      operationId: VideosTextTracks_getSpecificTextTrack
      description: >-
        This method returns a single text track of the specified video. The
        authenticated user must be the owner of the video.
    patch:
      tags:
        - Videos\Text tracks
      summary: Edit a text track
      operationId: VideosTextTracks_editTextTrack
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified text track of a video. The authenticated
        user must be the owner of the video.
  /videos/{video_id}/timelinethumbnails:
    post:
      tags:
        - Embed Presets\Timeline events
      summary: Add a timeline event thumbnail to a video
      operationId: EmbedPresetsTimelineEvents_addThumbnailToVideo
      security:
        - oauth2:
            - upload
      description: >-
        This method adds a timeline event thumbnail to the specified video. The
        authenticated user must be the owner of the video.
  /videos/{video_id}/timelinethumbnails/{thumbnail_id}:
    get:
      tags:
        - Embed Presets\Timeline events
      summary: Get a timeline event thumbnail
      operationId: EmbedPresetsTimelineEvents_getSingleThumbnail
      description: >-
        This method returns a single timeline event thumbnail that belongs to
        the specified video.
  /videos/{video_id}/transcripts/{texttrack_id}:
    get:
      tags:
        - Videos\Transcripts
      summary: Get transcript segments
      operationId: get_transcript
      description: This method returns the transcript segments of the specified text track.
  /videos/{video_id}/trim:
    get:
      tags:
        - Videos\Nondestructive trimming
      summary: Get the status of a video's trim operation
      operationId: clip_trim
      description: >-
        This method returns the status of the trim operation for the specified
        video.
    post:
      tags:
        - Videos\Nondestructive trimming
      summary: Start a trim operation for a video
      operationId: clip_trim
      description: This method starts a trim operation for the specified video.
  /videos/{video_id}/versions:
    get:
      tags:
        - Videos\Versions
      summary: Get all the versions of a video
      operationId: VideosVersions_getAllVideoVersions
      description: >-
        This method returns every version of the specified video. The
        authenticated user must be the owner of the video.
    post:
      tags:
        - Videos\Versions
      summary: Add a version to a video
      operationId: VideosVersions_addVideoVersion
      description: >-
        This method adds a version to the specified video. The authenticated
        user must be the owner of the video.
  /videos/{video_id}/versions/{version_id}:
    delete:
      tags:
        - Videos\Versions
      summary: Delete a video version
      operationId: VideosVersions_deleteVideoVersion
      security:
        - oauth2:
            - edit
      description: >-
        This method deletes the specified version from a video. The
        authenticated user must be the owner of the video.
    get:
      tags:
        - Videos\Versions
      summary: Get a specific video version
      operationId: VideosVersions_getSpecificVersion
      description: >-
        This method returns a single version of the specified video. The
        authenticated user must be the owner of the video.
    patch:
      tags:
        - Videos\Versions
      summary: Edit a video version
      operationId: VideosVersions_editVideoVersion
      security:
        - oauth2:
            - edit
      description: >-
        This method edits the specified version of a video. The authenticated
        user must be the owner of the video.
  /videos/{video_id}/videos:
    get:
      tags:
        - Videos\Recommendations
      summary: Get all the related videos of a video
      operationId: VideosRecommendations_getRelatedVideos
      description: This method returns every related video of the specified video.
  /webinars/{webinar_id}:
    get:
      tags:
        - Webinar\Essentials
      summary: Get a specific webinar
      operationId: WebinarEssentials_getSpecificWebinar
      description: >-
        This method returns a single webinar belonging to the authenticated
        user.
      deprecated: true
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/access_token
          scopes:
            create: Create new albums, channels, and so on
            delete: Delete videos, albums, channels, and so on
            edit: Edit existing videos, albums, channels, and so on
            email: Access to email addresses
            interact: >-
              Interact with Vimeo resources on a member's behalf, such as liking
              a video or following another member
            private: Access private member data
            promo_codes: Add, remove, and review Vimeo On Demand promotions
            public: Access public member data
            purchase: Purchase content
            purchased: Access a member's Vimeo On Demand purchase history
            scim: Manage users and team groups via the SCIM protocol
            stats: Access video stats
            upload: Upload videos
            video_files: >-
              Access video files belonging to members with a PRO subscription or
              higher
        clientCredentials:
          tokenUrl: /oauth/authorize/client
          scopes:
            create: Create new albums, channels, and so on
            delete: Delete videos, albums, channels, and so on
            edit: Edit existing videos, albums, channels, and so on
            email: Access to email addresses
            interact: >-
              Interact with Vimeo resources on a member's behalf, such as liking
              a video or following another member
            private: Access private member data
            promo_codes: Add, remove, and review Vimeo On Demand promotions
            public: Access public member data
            purchase: Purchase content
            purchased: Access a member's Vimeo On Demand purchase history
            scim: Manage users and team groups via the SCIM protocol
            stats: Access video stats
            upload: Upload videos
            video_files: >-
              Access video files belonging to members with a PRO subscription or
              higher
security:
  - oauth2:
      - create
      - delete
      - edit
      - email
      - interact
      - private
      - promo_codes
      - public
      - purchase
      - purchased
      - scim
      - stats
      - upload
      - video_files
