openapi: 3.0.3
info:
  title: Visier Consolidated Analytics APIs
  description: Visier APIs for managing consolidated analytics (CA) tenants.
  version: 22222222.99201.1256
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  x-api-status-urls: false
servers:
  - url: https://{vanity-name}.api.visier.io
    variables:
      vanity-name:
        default: vanity
tags:
  - name: ConsolidatedAnalyticsV1Alpha
paths:
  /v1alpha/admin/consolidated-analytics/tenants:
    get:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Retrieve a list of all consolidated analytics tenants
      operationId: ConsolidatedAnalyticsV1Alpha_ListTenants
      description: >-
        This API allows you to retrieve the full list of consolidated analytics
        tenants in your administrating tenant.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The maximum number of tenants to return. The maximum value is 1000.
            Default is 400.
          name: limit
          in: query
          schema:
            type: integer
            format: int32
        - description: The starting index of the first tenant to return. Default is 0.
          name: start
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPITenantListResponseDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    post:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Create a consolidated analytics tenant
      operationId: ConsolidatedAnalyticsV1Alpha_CreateTenant
      description: |-
        This API allows you to create a consolidated analytics tenant.

         A new CA tenant has no source tenants and no excluded sources.

         **Note:** CA tenant codes must have a prefix of CA. For example, WFF_{XXX}~CA{YYY} where {XXX} is the administrating tenant code and {YYY}
         is the consolidated analytic tenant code.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/ConsolidatedAnalyticsAPITenantCreateRequestDTO
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPITenantCreateRequestDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /v1alpha/admin/consolidated-analytics/tenants/:tenantId/excluded-sources:
    get:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Retrieve a consolidated analytics tenant's excluded sources
      operationId: ConsolidatedAnalyticsV1Alpha_ListExcludedSources
      description: |-
        This API allows you to retrieve a CA tenant's excluded sources.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPIExcludedSourcesListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    put:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Set a consolidated analytics tenant's excluded sources
      operationId: ConsolidatedAnalyticsV1Alpha_SetExcludedSources
      description: >-
        This API defines the excluded sources for a consolidated analytics
        tenant.

         After you create a CA tenant, you may optionally define a list of excluded sources. The excluded sources are the sources whose data is excluded from the CA tenant.
         You can also use this API to replace the list of excluded sources for an existing CA tenant.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedSourcesBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPIExcludedSourcesListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    delete:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Remove excluded sources from a consolidated analytics tenants
      operationId: ConsolidatedAnalyticsV1Alpha_RemoveExcludedSources
      description: >-
        This API removes excluded sources from the list of excluded sources for
        a consolidated analytics tenant.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedSourcesBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPIExcludedSourcesListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    patch:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Add excluded sources to a consolidated analytics tenant
      operationId: ConsolidatedAnalyticsV1Alpha_AddExcludedSources
      description: >-
        This API adds excluded sources to the list of excluded sources for a
        consolidated analytics tenant.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedSourcesBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPIExcludedSourcesListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /v1alpha/admin/consolidated-analytics/tenants/:tenantId/source-tenants:
    get:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Retrieve a consolidated analytics tenant's source tenants
      operationId: ConsolidatedAnalyticsV1Alpha_ListSourceTenants
      description: |-
        This API allows you to retrieve a CA tenant's source tenants.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
        - description: >-
            The maximum number of source tenants to return. The maximum value is
            1000. Default is 400.
          name: limit
          in: query
          schema:
            type: integer
            format: int32
        - description: >-
            The starting index of the first source tenant to return. Default is
            0.
          name: start
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPISourceTenantListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    put:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Set a consolidated analytics tenant's source tenants
      operationId: ConsolidatedAnalyticsV1Alpha_SetSourceTenants
      description: |-
        This API defines the source tenants for a consolidated analytics tenant.

         After you create a CA tenant, you must define a list of its source tenants. The source tenants are the tenants whose data is aggregated in the CA tenant.
         You can also use this API to replace the list of source tenants for an existing CA tenant.

         If successful, the response returns an updated list of source tenants.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
        - description: >-
            The maximum number of source tenants to return. The maximum value is
            1000. Default is 400.
          name: limit
          in: query
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantCodeBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPISourceTenantListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    delete:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Remove source tenants from a consolidated analytics tenants
      operationId: ConsolidatedAnalyticsV1Alpha_RemoveSourceTenants
      description: >-
        This API removes source tenants from the list of source tenants for a
        consolidated analytics tenant.

         If successful, the response returns an updated list of source tenants.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
        - description: >-
            The maximum number of source tenants to return. The maximum value is
            1000. Default is 400.
          name: limit
          in: query
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantCodeBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPISourceTenantListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    patch:
      tags:
        - ConsolidatedAnalyticsV1Alpha
      summary: Add source tenants to a consolidated analytics tenant
      operationId: ConsolidatedAnalyticsV1Alpha_AddSourceTenants
      description: >-
        This API adds source tenants to the list of source tenants for a
        consolidated analytics tenant.

         If successful, the response returns an updated list of source tenants.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      parameters:
        - description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          name: tenantId
          in: query
          schema:
            type: string
        - description: >-
            The maximum number of source tenants to return. The maximum value is
            1000. Default is 400.
          name: limit
          in: query
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantCodeBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ConsolidatedAnalyticsAPISourceTenantListDTO
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    ConsolidatedAnalyticsAPIExcludedSourcesListDTO:
      type: object
      properties:
        excludedSources:
          description: A list of a CA tenant's excluded sources.
          type: array
          items:
            type: string
    ConsolidatedAnalyticsAPISourceTenantListDTO:
      type: object
      properties:
        tenantCodes:
          description: A list of a CA tenant's source tenants codes
          type: array
          items:
            type: string
    ConsolidatedAnalyticsAPITenantCreateRequestDTO:
      type: object
      properties:
        tenantCode:
          description: >-
            The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is
            the administrating tenant code and {YYY}
             is the consolidated analytic tenant code.
          type: string
    ConsolidatedAnalyticsAPITenantListResponseDTO:
      type: object
      properties:
        tenantCodes:
          description: A list of CA tenants codes.
          type: array
          items:
            type: string
    ExcludedSourcesBody:
      type: object
      properties:
        excludedSources:
          description: A list of a CA tenant's excluded sources.
          type: array
          items:
            type: string
    GoogleProtobufAny:
      description: >-
        Contains an arbitrary serialized message along with a @type that
        describes the type of the serialized message.
      type: object
      properties:
        '@type':
          description: The type of the serialized message.
          type: string
      additionalProperties: true
    TenantCodeBody:
      type: object
      properties:
        tenantCodes:
          description: >-
            A list of a CA tenant's source tenants codes. The maximum length is
            1000.
          type: array
          items:
            type: string
    Status:
      description: The response structure for errors.
      type: object
      properties:
        errorCode:
          description: Error classification.
          type: string
        message:
          description: Error message describing the root cause of the error.
          type: string
        rci:
          description: Optional root cause identifier.
          type: string
