/*
 * csharp-body-with-object-field API
 *
 * A simple API based for testing csharp-body-with-object-field.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://konfigthis.com
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CsharpBodyWithObjectField.Net.Client;

namespace CsharpBodyWithObjectField.Net.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITestApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Fetches a JSON value based on input parameter
        /// </summary>
        /// <remarks>
        /// Provide an input parameter to receive a JSON value with properties.
        /// </remarks>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object Fetch(int operationIndex = 0);

        /// <summary>
        /// Fetches a JSON value based on input parameter
        /// </summary>
        /// <remarks>
        /// Provide an input parameter to receive a JSON value with properties.
        /// </remarks>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> FetchWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITestApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Fetches a JSON value based on input parameter
        /// </summary>
        /// <remarks>
        /// Provide an input parameter to receive a JSON value with properties.
        /// </remarks>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> FetchAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fetches a JSON value based on input parameter
        /// </summary>
        /// <remarks>
        /// Provide an input parameter to receive a JSON value with properties.
        /// </remarks>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> FetchWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITestApi : ITestApiSync, ITestApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TestApi : ITestApi
    {
        private CsharpBodyWithObjectField.Net.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TestApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TestApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TestApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TestApi(string basePath)
        {
            this.Configuration = CsharpBodyWithObjectField.Net.Client.Configuration.MergeConfigurations(
                CsharpBodyWithObjectField.Net.Client.GlobalConfiguration.Instance,
                new CsharpBodyWithObjectField.Net.Client.Configuration { BasePath = basePath }
            );
            this.Client = new CsharpBodyWithObjectField.Net.Client.ApiClient(this.Configuration);
            this.AsynchronousClient = new CsharpBodyWithObjectField.Net.Client.ApiClient(this.Configuration);
            this.ExceptionFactory = CsharpBodyWithObjectField.Net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TestApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TestApi(CsharpBodyWithObjectField.Net.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CsharpBodyWithObjectField.Net.Client.Configuration.MergeConfigurations(
                CsharpBodyWithObjectField.Net.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new CsharpBodyWithObjectField.Net.Client.ApiClient(this.Configuration);
            this.AsynchronousClient = new CsharpBodyWithObjectField.Net.Client.ApiClient(this.Configuration);
            this.ExceptionFactory = CsharpBodyWithObjectField.Net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TestApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TestApi(CsharpBodyWithObjectField.Net.Client.ISynchronousClient client, CsharpBodyWithObjectField.Net.Client.IAsynchronousClient asyncClient, CsharpBodyWithObjectField.Net.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CsharpBodyWithObjectField.Net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CsharpBodyWithObjectField.Net.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CsharpBodyWithObjectField.Net.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CsharpBodyWithObjectField.Net.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CsharpBodyWithObjectField.Net.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Fetches a JSON value based on input parameter Provide an input parameter to receive a JSON value with properties.
        /// </summary>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object Fetch(int operationIndex = 0)
        {
            CsharpBodyWithObjectField.Net.Client.ApiResponse<Object> localVarResponse = FetchWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches a JSON value based on input parameter Provide an input parameter to receive a JSON value with properties.
        /// </summary>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public CsharpBodyWithObjectField.Net.Client.ApiResponse<Object> FetchWithHttpInfo(int operationIndex = 0)
        {
            CsharpBodyWithObjectField.Net.Client.RequestOptions localVarRequestOptions = new CsharpBodyWithObjectField.Net.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CsharpBodyWithObjectField.Net.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CsharpBodyWithObjectField.Net.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "TestApi.Fetch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/simple-endpoint", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Fetch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetches a JSON value based on input parameter Provide an input parameter to receive a JSON value with properties.
        /// </summary>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> FetchAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CsharpBodyWithObjectField.Net.Client.ApiResponse<Object> localVarResponse = await FetchWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches a JSON value based on input parameter Provide an input parameter to receive a JSON value with properties.
        /// </summary>
        /// <exception cref="CsharpBodyWithObjectField.Net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<CsharpBodyWithObjectField.Net.Client.ApiResponse<Object>> FetchWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            CsharpBodyWithObjectField.Net.Client.RequestOptions localVarRequestOptions = new CsharpBodyWithObjectField.Net.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CsharpBodyWithObjectField.Net.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CsharpBodyWithObjectField.Net.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "TestApi.Fetch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-KEY")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-KEY", this.Configuration.GetApiKeyWithPrefix("X-API-KEY"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/simple-endpoint", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Fetch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
