openapi: 3.0.0
info:
  title: General API
  description: >-
    >

    This is a description of the API.  

    # Authentication

    ## Token-based Authentication

    One method of connecting to the API is to use a persistent access token that
    is associated with a specific user account. This access token should be
    passed using the Authorization header with each API request. For example, if
    your Authentication Token was VnJexj4MzMhLilaLz7MdYFEKFRBmuBUAJMkDjOdTp, the
    correct header would be:  


    ```X-AUTH-TOKEN: VnJexj4MzMhLilaLz7MdYFEKFRBmuBUAJMkDjOdTp```
  version: 0.3.0
servers:
  - url: https://api.interviewstream.com/
paths:
  /incoming-assessment:
    get:
      tags:
        - Incoming Assessment
      operationId: IncomingAssessment
      parameters:
        - name: ats
          in: query
          description: ATS integration name
          required: true
          style: form
          schema:
            type: string
        - name: companyId
          in: query
          description: ID of the company
          required: true
          style: form
          schema:
            type: integer
            format: int64
        - name: assessmentOrderId
          in: query
          description: ID of the Assessment Order
          required: true
          style: form
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: >-
            Perform an Incoming Assessment from the ATS SuccessFactors to IVS
            application. This General API changes the status of an interview.
        '400':
          description: >-
            Bad request: ATS, companyId, and assessmentOrderId are required. If
            ATS is present, greenhouse is not supported yet
        '404':
          description: 'Not found: ATS was not found'
  /candidates:
    get:
      tags:
        - Candidates
      summary: Returns a list of candidates that the API token has access to.
      description: |2-
         >
         *       Returns a list of candidates that the API token has access to.
      operationId: Candidates
      responses:
        '200':
          description: Returns a list of candidates that the API token has access to.
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /candidates/{iCandidate}:
    get:
      tags:
        - Candidates
      summary: Gets a candidate by ID.
      description: |2-
         >
         *       Returns detailed information about the specified Candidate.
      operationId: ACandidate
      parameters:
        - name: iCandidate
          in: path
          description: Candidate ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: Returns detailed information about the specified Candidate.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /requisitions:
    get:
      tags:
        - Requisitions
      summary: Gets a list of Requisitions.
      description: |2-
         >
         *     Returns a list of requisitions that the API token has access to.
      operationId: Requisitions
      responses:
        '200':
          description: Returns a list of requisitions that the API token has access to.
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
      security:
        - HasApiKey: []
  /requisitions/{iRequisition}:
    get:
      tags:
        - Requisitions
      summary: Gets a Requisition Candidate by ID.
      description: |2-
         >
         *     Returns detailed information about the specified Requisition.
      operationId: A Requisition
      parameters:
        - name: iRequisition
          in: path
          description: Requisition ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: Returns detailed information about the specified Requisition.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - HasApiKey: []
  /requisitions/{iRequisition}/candidates:
    get:
      tags:
        - Requisitions
      summary: >-
        Returns a list of RequisitionCandidates belonging to the specified
        Requisition.
      description: |2-
         >
         *     Returns a list of RequisitionCandidates belonging to the specified Requisition.
      operationId: B Requisition
      parameters:
        - name: iRequisition
          in: path
          description: Requisition ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: >-
            Returns a list of RequisitionCandidates belonging to the specified
            Requisition.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /requisitionCandidates:
    get:
      tags:
        - RequisitionCandidate
      summary: >-
        Returns a list of requisition candidates that the API token has access
        to.
      description: |2-
         >
         *       Returns a list of requisition candidates that the API token has access to.
      operationId: RequisitionCandidates
      responses:
        '200':
          description: >-
            Returns a list of requisitions-candidates that the API token has
            access to.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /requisitionCandidates/{iRequisitionCandidates}:
    get:
      tags:
        - RequisitionCandidate
      summary: Returns detailed information about the specified requisition candidates.
      description: |2-
         >
         *       Returns detailed information about the specified requisition candidates.
      operationId: A RequisitionCandidate
      parameters:
        - name: iRequisitionCandidates
          in: path
          description: Requisition Candidate ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: >-
            Returns a list of requisitions-candidates that the API token has
            access to.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /requisitionCandidates/{iRequisitionCandidates}/shareLinks:
    get:
      tags:
        - RequisitionCandidate
      summary: >-
        Returns a list of RequisitionCandidateShareLinks belonging to this
        RequisitionCandidate.
      description: |2-
         >
         *       Returns a list of RequisitionCandidateShareLinks belonging to this RequisitionCandidate.
      operationId: B RequisitionCandidate
      parameters:
        - name: iRequisitionCandidates
          in: path
          description: Requisition Candidate ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: >-
            Returns a list of requisitions-candidates that the API token has
            access to.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
  /requisitionCandidates/{iRequisitionCandidates}/requests:
    get:
      tags:
        - RequisitionCandidate
      summary: >-
        Returns a list of RequisitionCandidateRequests belonging to this
        RequisitionCandidate.
      description: |2-
         >
         *       Returns a list of RequisitionCandidateRequests belonging to this RequisitionCandidate.
      operationId: C RequisitionCandidate
      parameters:
        - name: iRequisitionCandidates
          in: path
          description: Requisition Candidate ID
          required: true
          style: form
          schema:
            type: integer
      responses:
        '200':
          description: >-
            Returns a list of requisitions-candidates that the API token has
            access to.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - HasApiKey: []
components:
  securitySchemes:
    HasApiKey:
      type: apiKey
      name: X-AUTH-TOKEN
      in: header
