openapi: 3.1.0
info:
  title: Zapier AI Actions API
  version: 1.0.0
  description: ''
servers:
  - url: https://actions.zapier.com
paths:
  /api/v1/check/:
    get:
      operationId: check
      summary: Check
      parameters: []
      responses:
        '200':
          description: OK
      description: Test that the API and auth are working.
      security:
        - AccessPointApiKeyHeader: []
        - AccessPointApiKeyQuery: []
        - AccessPointOAuth: []
        - SessionAuth: []
  /api/v1/configuration-link/:
    get:
      operationId: get_configuration_link
      summary: Get Configuration Link
      parameters: []
      responses:
        '200':
          description: OK
      description: >-
        Provides a link to configure more actions. Alternatively, searching
        through apps and actions will provide more specific configuration links.
      security:
        - AccessPointApiKeyHeader: []
        - AccessPointApiKeyQuery: []
        - AccessPointOAuth: []
        - SessionAuth: []
  /api/v1/exposed/:
    get:
      operationId: list_exposed_actions
      summary: List Exposed Actions
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExposedActionResponseSchema'
      description: List all the currently exposed actions for the given account.
      security:
        - AccessPointApiKeyHeader: []
        - AccessPointApiKeyQuery: []
        - AccessPointOAuth: []
        - SessionAuth: []
  /api/v1/exposed/{exposed_app_action_id}/execute/:
    post:
      operationId: execute_app_action_endpoint
      summary: Execute App Action Endpoint
      parameters:
        - in: path
          name: exposed_app_action_id
          schema:
            format: uuid
            title: Exposed App Action Id
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: >-
        Give us a plain english description of exact action you want to do.
        There should be dynamically generated documentation for this endpoint
        for each action that is exposed.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteRequest'
        required: true
      security:
        - AccessPointApiKeyHeader: []
        - AccessPointApiKeyQuery: []
        - AccessPointOAuth: []
        - SessionAuth: []
  /api/v1/execution-log/{execution_log_id}/:
    get:
      operationId: get_execution_log_endpoint
      summary: Get Execution Log Endpoint
      parameters:
        - in: path
          name: execution_log_id
          schema:
            format: uuid
            title: Execution Log Id
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: Get the execution log for a given execution log id.
      security:
        - AccessPointApiKeyHeader: []
        - AccessPointApiKeyQuery: []
        - AccessPointOAuth: []
        - SessionAuth: []
components:
  schemas:
    ExposedActionResponseSchema:
      properties:
        results:
          items:
            $ref: '#/components/schemas/ExposedActionSchema'
          title: Results
          type: array
        configuration_link:
          description: URL to configure and expose more actions.
          title: Configuration Link
          type: string
      required:
        - results
        - configuration_link
      title: ExposedActionResponseSchema
      type: object
    ExposedActionSchema:
      properties:
        id:
          description: The unique ID of the exposed action.
          title: Id
          type: string
        operation_id:
          description: The operation ID of the exposed action.
          title: Operation Id
          type: string
        description:
          description: Description of the action.
          title: Description
          type: string
        params:
          description: Available hint fields for the action.
          title: Params
          type: object
      required:
        - id
        - operation_id
        - description
        - params
      title: ExposedActionSchema
      type: object
    ExecuteResponse:
      description: This is a summary of the results given the action that was executed.
      properties:
        id:
          description: The id of the execution log.
          title: Id
          type: string
        action_used:
          description: The name of the action that was executed.
          title: Action Used
          type: string
        input_params:
          description: The params we used / will use to execute the action.
          title: Input Params
          type: object
        review_url:
          description: >-
            The URL to run the action or review the AI choices the AI made for
            input_params given instructions.
          title: Review Url
          type: string
        result:
          anyOf:
            - type: object
            - type: 'null'
          description: >-
            A trimmed down result of the first item of the full results. Ideal
            for humans and language models!
          title: Result
        additional_results:
          description: The rest of the full results. Always returns an array of objects
          items:
            type: object
          title: Additional Results
          type: array
        result_field_labels:
          anyOf:
            - type: object
            - type: 'null'
          description: Human readable labels for some of the keys in the result.
          title: Result Field Labels
        status:
          default: success
          description: The status of the execution.
          enum:
            - success
            - error
            - empty
            - preview
          title: Status
          type: string
        error:
          anyOf:
            - type: string
            - type: 'null'
          description: The error message if the execution failed.
          title: Error
        assistant_hint:
          anyOf:
            - type: string
            - type: 'null'
          description: A hint for the assistant on what to do next.
          title: Assistant Hint
      required:
        - id
        - action_used
        - input_params
        - review_url
        - additional_results
      title: ExecuteResponse
      type: object
    ErrorResponse:
      additionalProperties: true
      properties:
        error:
          description: Error message.
          title: Error
          type: string
      required:
        - error
      title: ErrorResponse
      type: object
    ExecuteRequest:
      additionalProperties: true
      description: >-
        This extends from ExecuteRequestBase to add the preview_only option.


        (1) Providers who allow side effects or (2) actions that do not have a
        side effect should use this class.
      properties:
        instructions:
          description: >-
            Plain english instructions. Provide as much detail as possible, even
            if other fields are present.
          title: Instructions
          type: string
        preview_only:
          default: false
          description: >-
            If true, we will not execute the action, but will return the params
            of the preview.
          title: Preview Only
          type: boolean
      required:
        - instructions
      title: ExecuteRequest
      type: object
  securitySchemes:
    AccessPointApiKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key
    AccessPointApiKeyQuery:
      type: apiKey
      in: query
      name: api_key
    AccessPointOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize/
          tokenUrl: /oauth/token/
          scopes:
            nla:exposed_actions:execute: Run AI Actions
            openid: OpenID Connect scope
    SessionAuth:
      type: apiKey
      in: cookie
      name: nlasession
