name: SnapTrade
targets:
  SnapTrade:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [SnapTrade]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable