# coding: utf-8

"""
    python-pydantic-list-or-str API

    A simple API based for testing python-pydantic-list-or-str.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from python_pydantic_list_or_str.paths.simple_endpoint.get import FetchRaw


class TestApiRaw(
    FetchRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
