/*
 * csharp-body-with-object-field API
 *
 * A simple API based for testing csharp-body-with-object-field.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://konfigthis.com
 */


using System;
using Xunit;
using CsharpBodyWithObjectField.Net.Client;
using CsharpBodyWithObjectField.Net.Model;

namespace CsharpBodyWithObjectField.Net.Test
{
    /// <remarks>
    /// Boilerplate for writing some simple tests
    /// </remarks>
    public class SimpleTests : IDisposable
    {
        public SimpleTests()
        {
            // Setup
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test Client Initialization
        /// </summary>
        [Fact]
        public void ClientTest()
        {
            CsharpBodyWithObjectFieldClient client = new CsharpBodyWithObjectFieldClient();
            // Configure API key authorization: ApiKeyAuth
            client.SetApiKey("YOUR_API_KEY");

            Assert.NotNull(client);
        }
    }
}
