name: Update Submodules

on:
  schedule:
    # Run every day at 2am
    - cron:  '0 2 * * *'
  # Run manually
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubicloud

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.SUBMODULES_ACCESS_TOKEN }}
      continue-on-error: true

    - name: Update submodules
      run: ./scripts/update-submodules.sh
